### ISSUE TITLE
Invisible wall in Room 312

### ISSUE THREAD

**Issue by silentdream21** [elishacloud/Silent-Hill-2-Enhancements#101]
I hope this isn't annoying but..
In the well-known room 312 there is an invisible wall in pass between a bed and a case. Pass rather wide that James could come into it. I do not know for what reason developers did not give such chance. It's a shame at such important point of a game a little. Whether it is possible to correct it? Yes, I do not understand modding of games, so I apologize if my question seems too naive.
Sorry for my bad English.

**Comment by Polymega** [comment]
Hi @silentdream21 , 

No worries, you're not annoying anyone. :) 

As far as I know, I don't believe any one on the team knows how to make new collision boundaries for certain objects.

![image](https://user-images.githubusercontent.com/27395260/54496134-4f221600-48c2-11e9-972d-e602601a1678.png)

**Comment by silentdream21** [comment]
Thanks for fast reply:)

**Comment by Bigmanjapan** [comment]
It's possible to find addresses that control collisions of a location by extensive memory scanning (and changing values on the found addresses) and using a hidden minimap as an indicator of change since it draws collisions.

**Comment by Bigmanjapan** [comment]
It's possible to find addresses that control collisions of a location by extensive memory scanning (and changing values on the found addresses) and using a hidden minimap as an indicator of change since it draws collisions. Nekorun says he knows how to activate minimap on PC version.

**Comment by Bigmanjapan** [comment]
Collision data is stored in .cld files. Room 312 data is in `rr91.cld` file. 
From what I understand collision data file contains infromation on point pairs that get connected by a line automatically. 

This would be a portion (all float values apart from the first several single bytes) that describes one point pair, it has X and Z coordinates for each point and that is needed to move points around:

`01 01 00 00 04 00 00 00 05 00 00 00 00 00 00 00 00 9E 63 47 00 80 F7 C3 00 74 9F 46 00 00 80 3F 00 25 64 47 00 80 F7 C3 00 74 9F 46 00 00 80 3F 00 25 64 47 00 80 F7 C3 00 0C 9E 46 00 00 80 3F 00 9E 63 47 00 80 F7 C3 00 0C 9E 46 00 00 80 3F`

I don't know how to add new data to a .cld file (to create new collision points) that has all the data already stacked together, I can only change existing points position.

Since hidden minimap draws collisions it can be used to track changes made in the file.

![Безимени-2](https://user-images.githubusercontent.com/31383389/54879396-22926f00-4e6b-11e9-90b6-3c3678f3bd73.jpg)

I guess some of the room's outer borders or other lines inside the room could be used to create new portion of the area in question.

![Безимени-3](https://user-images.githubusercontent.com/31383389/54879441-92085e80-4e6b-11e9-939b-61d06005c783.jpg)

**Comment by Bigmanjapan** [comment]
https://youtu.be/4LJg80Bs-ww

I used three outer borders that a player doesn't connect with during regular gameplay and one piece of single point geometry that is also unreachable and therefore safe to use without breaking existing room design.

If you like it, I will make a new `rr91.cld` file.

**Comment by Polymega** [comment]
Wow! You keep on impressing! 

> If you like it, I will make a new rr91.cld file.

You put a lot of work into this and the results look great. We should definitely include it then!

**Comment by Bigmanjapan** [comment]
[rr91.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3000501/rr91.zip)

I would advice on using original .cld file for any visual effects research in this room since it's unknown if any effects are tied to the room's collisions (if any of those unreachable borders / single point collisions are needed for something else).

**Comment by Polymega** [comment]
Thanks for your work here, Bigmanjapan. 

We'll add this to the next update release coming soon. If I turns out we need to revert collision data for other visual effects in this room, we can add the original `rr91.cld` file to a future update to replace the file. 

@silentdream21 you can download Bigmanjapan's edited file above and place it in `KONAMI\Silent Hill 2\sh2e\bg\rr\`

**Comment by silentdream21** [comment]
Wow, Bigmanjapan, it is really impressive, thank you👍

**Comment by PhoenixCyanFire** [comment]
How did you activate the minimap in this?
