### ISSUE TITLE
Error: Files unavailable after final update 

### ISSUE THREAD

**Issue by kingphil006** [elishacloud/Silent-Hill-2-Enhancements#1018]
I had SH2 installed in my computer with the last EE version working, today I got the pop up asking me if I wanted to update, I got this error and then decided to do a clean installation, I unistalled the Enhanced Edition first and then the game, but after installing the game again I got the same error, now I don't have the previous version of EE and can't install the final update. :( 
![image](https://github.com/user-attachments/assets/2b31d0c4-2221-46f4-8d3e-c30c3a547887)

**Comment by Polymega** [comment]
Please see here: https://x.com/WhereAllBegins/status/1829643993917112408

**Comment by kingphil006** [comment]
> Please see here: https://x.com/WhereAllBegins/status/1829643993917112408

sorry, but X/Twitter is not avalaible in my country, can you send a screenshot?

**Comment by AmyRoxwell** [comment]
> > Please see here: https://x.com/WhereAllBegins/status/1829643993917112408
> 
> sorry, but X/Twitter is not avalaible in my country, can you send a screenshot?

![image](https://github.com/user-attachments/assets/de5e1948-9f63-43d9-8ad4-80d022521be9)

**Comment by kingphil006** [comment]
> > > Please see here: https://x.com/WhereAllBegins/status/1829643993917112408
> > 
> > 
> > sorry, but X/Twitter is not avalaible in my country, can you send a screenshot?
> 
> ![image](https://private-user-images.githubusercontent.com/89411895/363434419-de5e1948-9f63-43d9-8ad4-80d022521be9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMzIxNDIsIm5iZiI6MTcyNTEzMTg0MiwicGF0aCI6Ii84OTQxMTg5NS8zNjM0MzQ0MTktZGU1ZTE5NDgtOWY2My00M2Q5LThhZDQtODBkMDIyNTIxYmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDE5MTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5Yzc3YWY1ODVlN2IyYWVjMjU4NWQyMjE5YWU3YjFjZmJkNzcyZjQyMGZkYzRhNjM3Y2EyMjcxYTYwMmYwMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ilGHdcN7DhQ0g_FaBErBm3XRSf8EaCl5ZbQ6LZKINLw)

Thanks! so I getting this error because the servers are packed? I just have to wait? this is it?

**Comment by Mero2403** [comment]
Still have the same error? I try to update and the same error appears.

**Comment by lecosilva** [comment]
If you're getting this message, try a VPN and do not let it choose the fastest available by itself, pick an uncommon location.
It appears that the fastest locations available are being used to a sum where they still remain as congested ones, so you won't be able to download the packages. I've manually selected Andorra (while actually in Brazil) and the setup worked, even though slowly.

**Comment by Polymega** [comment]
Thanks for the tip, @lecosilva! Sorry for the troubles here, everyone.

**Comment by Polymega** [comment]
We're still trying to resolve this issue. Can you please try this test file for me? Here's what you do:

1. Go to your `SILENT HILL 2` game folder and make a _backup_ of your `SH2EEsetup.exe` file in there.
2. Once backed up to another location, download this new version of `SH2EEsetup.exe` here: [SH2EEsetup_Download_Fix_Test.zip](https://github.com/user-attachments/files/17652785/SH2EEsetup_Download_Fix_Test.zip)
3. Unzip this package and place the new `SH2EEsetup.exe` within your `SILENT HILL 2` game folder (where the previous `SH2EEsetup.exe` existed).
4. Run the new `SH2EEsetup.exe` and let us know if you can now successfully download the package files or not.

Because this is a new test file, you might get a [false positive](https://allaboutcookies.org/antivirus-false-positive) warning about it from your antivirus vendor. The file is safe but, if you're still unsure, you can submit the file for review to Windows Defender, BitDefender, or your other favorite vendor of choice.

Thanks
