### ISSUE TITLE
Action button stuck being held down + more

### ISSUE THREAD

**Issue by Polish18** [elishacloud/Silent-Hill-2-Enhancements#1043]
Basically whenever i hold the aim button it acts as if the action button that you use to shoot is already being held do so it shoots automatically

My inventory button also just switches to the pause so i have two pause buttons

I found a way to fix this but its really tedious, you have to open the setup and repair the controller support option every single time

I believe it started happening the recent updates, it used to happen sometimes a few days ago but now it happens no matter what unless I repair the controller support in setup

**Comment by Polymega** [comment]
We believe this was caused due to a memory overflow issue that happens when playing in very large resolutions while also utilizing our new render resolution feature.

We pushed out a hotfix for this a couple days back. Ensure you're using the latest version of our "Enhanced Executable" to address this. You can open `SH2EEsetup.exe` and select "Update Packages" and select "Enhanced Executable" from there.

**Comment by Polymega** [comment]
We've since pushed out a fix for the 'memory overflow' issue talked about here. Please make sure you update our project files. If you're still experiencing this issue, please re-open this ticket and let us know.
