### ISSUE TITLE
Can't install - Files unavailable

### ISSUE THREAD

**Issue by magnusvinicius** [elishacloud/Silent-Hill-2-Enhancements#1048]
![image](https://github.com/user-attachments/assets/1b4702d7-c5cc-4492-801b-c12671c4ed2a)
Can't pass through this, any solutions?

**Comment by AlexSSantana** [comment]
I have the same same problem. Other people said they were able to download the files separately and manually, but I don't want to go through all that work.

**Comment by vanfanel** [comment]
I am also seeing this.
Where are the files so I can manually download them and overwrite the ones from the original release, please?

**Comment by oozaru2020** [comment]
[_sh2ee.csv](https://github.com/user-attachments/files/16923751/_sh2ee.csv)
Use this file to download manually just open it with notepad++ and copy the link and paste it into a page there are direct links, if you want to find it by yourself just start the normal update with the exe but pause it and go to your temp folder which is in users appdata local temp

**Comment by Polymega** [comment]
We've had reports it's not wanting to connect based on location/region. I'm unsure at the moment why that is but it's something we of course want to look into.

**Comment by magnusvinicius** [comment]
So I just tried to install the EE while using a VPN connected to Australia (I'm from Brazil) and it worked ad started downloading the files like a breezy...

**Comment by magnusvinicius** [comment]
So I just tried to install the EE while using a VPN connected to Australia (I'm in Brazil) and it worked and started downloading the files like a breezy...

**Comment by Polymega** [comment]
We're still trying to resolve this issue. Can you please try this test file for me? Here's what you do:

1. Go to your `SILENT HILL 2` game folder and make a _backup_ of your `SH2EEsetup.exe` file in there.
2. Once backed up to another location, download this new version of `SH2EEsetup.exe` here: [SH2EEsetup_Download_Fix_Test.zip](https://github.com/user-attachments/files/17652785/SH2EEsetup_Download_Fix_Test.zip)
3. Unzip this package and place the new `SH2EEsetup.exe` within your `SILENT HILL 2` game folder (where the previous `SH2EEsetup.exe` existed).
4. Run the new `SH2EEsetup.exe` and let us know if you can now successfully download the package files or not.

Because this is a new test file, you might get a [false positive](https://allaboutcookies.org/antivirus-false-positive) warning about it from your antivirus vendor. The file is safe but, if you're still unsure, you can submit the file for review to Windows Defender, BitDefender, or your other favorite vendor of choice.

Thanks
