### ISSUE TITLE
The flashlight doesn't cast shadows in every area of the game

### ISSUE THREAD

**Issue by Tasosgemah** [elishacloud/Silent-Hill-2-Enhancements#1056]
It seems like in some areas the casting of shadows from the flashlight is disabled. One of those areas is the big bowling room where you find Eddie the second time. When you use the flashlight there it won't cast any shadows, which looks uneven compared to the rest of the game.

I'm not sure if this is normal in the non-modded PC version or the PS2. I'm also not sure if there are other areas that are also affected. Either way i think it would be great for the enhanced version's flashlight to be able to cast shadows everywhere for consistency's sake.

**Comment by Polymega** [comment]
Hi there,

Shadow behavior is far, far, far from perfect in this game. And that's true for all versions of it. I believe our shadow behaviors are 1:1 or extremely close to it as you'd see them in the console releases. Because shadow behavior is so 'inconsistent' throughout the game, we didn't feel like doing a total overhaul of the shadow system.

And since we're now wrapped up with the project, we won't be revisiting aspects such as this, sorry.
