### ISSUE TITLE
Requesting file names for specific modified files

### ISSUE THREAD

**Issue by yabadabaclappa** [elishacloud/Silent-Hill-2-Enhancements#1067]
Hello. 

I just finished replaying the game for the umpteenth time now that this project has gotten its final update. However, while I agree with most changes there are also some changes that I do not agree with that I would like to remove as I know this project is modular, but I have no way of knowing which file corresponds to which specific change in the game. 

I would like to know what individual files correspond to the following changes:
- The ladder seen down below when James jumps from the fire escape door from Woodside Apartments into Blue Creek Apartments (is this tied to the same file rendering the room inside the window as the cutscene plays out or is it separate?)
- Darkening the door in the bar in the hotel basement where James has to affix a light bulb into the lamp on the desk
- Said lamp's cord (I'm sorry if the business with the cords annoy any of you but I just don't like them, it's nothing personal)
- The jukebox itself
- Refrigerator cord for one of the apartments
- The bars in the sewers (I saw all of your update vid and know you did everything you could but I actually preferred the original solution where you added a platform at the end past the bars where the water ended as shown in one of your Twitter pics so I'd rather just remove it entirely)
- The red squares

That's about it. I think a changelog for every change would be neat. I hope someone will be able to provide it someday but these will do for me personally for now. I'll just say that I do appreciate all of the hard work that's gone into these changes and fixes so it's nothing personal when I say that I don't like all of them! We all love this masterpiece of a game!

**Comment by TommvinHuwaltzky** [comment]
I second this.
A few years ago I knew at least the file-name for the cord on the fridge in the hospital (that has the ring inside), but since then I forgot. Documentation is key... -.-

And it _is_ a weird business. I agree when you guys added the lamp-base to the one on the stand in the Mary-scene, because that seems to have been an oversight from the devs. But that electrical appliances work in Silent is is I'd say on purpose. Since the town's spiritual power, and we don't know what is real and so on.

So it's a bit hard and kinda subjective to differentiate what was an oversight and what is "magic" in the game-world's logic.

But for ppl like yaba and me, it would be awesome to just make it openly-modular (:

**Comment by Polymega** [comment]
I do not have an itemized list of every edit done. I'd recommend downloading the SH2 Level Viewer/Editor to help determine which `.map` files you want to hone in on: https://github.com/pmttavara/ph2
