### ISSUE TITLE
Game won't save on 446GB SSD

### ISSUE THREAD

**Issue by KorewaSmug** [elishacloud/Silent-Hill-2-Enhancements#107]
whenever i try to save the game it says "Unable to save game. Press return to continue" 
![help](https://user-images.githubusercontent.com/49621603/56098298-095e6a80-5ecd-11e9-8a04-2458d8759c26.png)
![help2](https://user-images.githubusercontent.com/49621603/56098309-285cfc80-5ecd-11e9-91c5-c7e1d6ab9f60.png)
![help3](https://user-images.githubusercontent.com/49621603/56098316-40348080-5ecd-11e9-8fab-47bc066b8f5f.png)

**Comment by Polymega** [comment]
Hi @KorewaSmug,

Let's go down a list of possible culprits?

- Do you have the game installed to an admin-protected directory such as `Program Files`?
   - If so, you will need to set the folder permissions for the parent installation folder (typically `\KONAMI\`) to **Modify** so the game can has write permissions to create the save file(s). [More info on this can be found here.](http://enhanced.townofsilenthill.com/SH2/#installGame)
- Have you tried **deleting** the `Folder 01` folder found in `\KONAMI\Silent Hill 2\data\save\` and creating a new, blank `Folder 01` folder with the same name? 
   - If so, re-launch the game and make a new save file. It will probably say the folder/file is damaged in the game, like in your screenshot above, so delete that file with Backspace then attempt a new save. 
- Is your anti-virus software preventing the game from writing/creating new files (such as a save file in this case)?

**Comment by KorewaSmug** [comment]
my data folder didn't have a save folder so i added one but now when the game launches I'm met with a black screen with white Japanese text on it. i tried removing the save folder but it still takes me to that screen

**Comment by Polymega** [comment]
May I ask where you got your copy of SH2 PC from?

Here's what the folder structure should look like for these areas. The last photo will look different for you, of course, as these are the actual save files: 

![image](https://user-images.githubusercontent.com/27395260/56098598-e7b2b280-5ecf-11e9-8c96-757632f174ab.png)
![image](https://user-images.githubusercontent.com/27395260/56098599-f0a38400-5ecf-11e9-8da2-d368655e0306.png)
![image](https://user-images.githubusercontent.com/27395260/56098600-f600ce80-5ecf-11e9-8ef4-fec9637865fc.png)

**Comment by KorewaSmug** [comment]
everything there looks the same except for the fact that mine doesn't have a save folder. also I'm using the directors cut version that I (unfortunately) pirated from a website called nitroblog

**Comment by Polymega** [comment]
No worries, no one here is here to judge how you got the game. I only ask because I know certain pirated versions have had problems in the past and I'm led to believe whoever packaged it either didn't include all the files are messed around with stuff. 

The version you got: Did you actually have to install it or were all the files already "there"? 

I'm led to believe this may be part of the reason why you're having issues. But try this: Place the attached file in your `\KONAMI\Silent Hill 2\data\save\Folder 01\` folder. I'm not sure if this will fix anything, but it won't hurt either: [sh2pc.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3077846/sh2pc.zip)

Beyond that, at the moment, I'm currently stumped on what to do besides recommending find a more reliable source for the game.

**Comment by KorewaSmug** [comment]
on the version I got i actually had to install it and the game won't even launch now. also yes i have changed
permissions for my KONAMI folder
![asasasas](https://user-images.githubusercontent.com/49621603/56098776-2a758a00-5ed2-11e9-9def-1f0ce01f746e.png)

**Comment by KorewaSmug** [comment]
also i tried your fix but i can't see if it will work because the game won't launch

**Comment by Polymega** [comment]
Okay, let's get you back to having the game launch. None of the files I sent should cause any harm; they're just save file data. 

So if you delete the `\save\` folder then game will relaunch?

**Comment by KorewaSmug** [comment]
I followed one of the trouble shooting steps on the download page and was able to get it to this screen again. I'll try deleting the save folder again too see if that works. this is the best screenshot i could get of the black screen
![asdasdasdas](https://user-images.githubusercontent.com/49621603/56098876-8d1b5580-5ed3-11e9-9bdf-3c8c6f020c61.png)

**Comment by KorewaSmug** [comment]
deleting save didn't fix it

**Comment by Polymega** [comment]
Odd. Try ensuring `SET DX_CONFIG_LANGUAGE 1` is the line found inside the `language.ini` file (on the game's main directory. Maybe it was set to `0` (which I believe is the selection for the Japanese language choice).

**Comment by Polymega** [comment]
Oh, I don't see that file in your game's main directory. Open up Notepad, write the following: 

`SET DX_CONFIG_LANGUAGE 1`

And save it as `language.ini` to the game's main directory.

**Comment by KorewaSmug** [comment]
I don't see a language.ini file 
![asasasas](https://user-images.githubusercontent.com/49621603/56098943-70cbe880-5ed4-11e9-9f61-9b5888fc33a9.png)

**Comment by Polymega** [comment]
Yeah, that pirated copy is missing files. Try the suggestion I posted above.

**Comment by KorewaSmug** [comment]
oh
didn't see your comment lol

**Comment by KorewaSmug** [comment]
SHIT

**Comment by KorewaSmug** [comment]
I DIDN'T MEAN TO DO THAT

**Comment by KorewaSmug** [comment]
there we go

**Comment by Polymega** [comment]
It;s been many years since I've last installed this game, but thinking about it, I'm starting to think the game doesn't create files such as the save folder and language file until you launch the game and create/set these while playing. This leads me to believe that your PC isn't allowing the game to write files in the directory. 

Because when you first opened the ticket you were able to at least play the game, yes? 

Now, does that explain the weird Japanese characters and hang-ups on launch? I don't know. But I'm starting to think there's a read/write permissions thing going on. Have you tried running the game as administrator?

**Comment by KorewaSmug** [comment]
I re-installed the game and it worked thank you
