### ISSUE TITLE
Error of "Couldn't download 'webcsv.url'" when installing SH2EE.exe

### ISSUE THREAD

**Issue by Abderraoufbkrr** [elishacloud/Silent-Hill-2-Enhancements#1087]
I'am using the last system version of wine (9.19)
![Screenshot_2024-10-13-21-21-12_1366x768](https://github.com/user-attachments/assets/4a3e4e37-7b34-41e9-bc2e-aacecd2f0814)
and when the install script reaches the setup of the EE it tell me this
![Screenshot_2024-10-13-21-56-17_1366x768](https://github.com/user-attachments/assets/4e76137d-2fa7-4fc1-8138-ecafa7c4c420)

**Comment by Polymega** [comment]
Sorry you're having issues. If you have access to a VPN, can you see if that resolves the problem? Alternatively, you can directly download the packages through the CSV file here: https://files.townofsilenthill.com/SH2EE/_sh2ee.csv

**Comment by Polymega** [comment]
You can reference the file tree on the site. But to make things simple: Simply extract the files in each ZIP as-is within the root directory of the game's folder.

**Comment by Polymega** [comment]
Did you install the base, vanilla game first? Can I see a snapshot of the game's directory?

**Comment by Polymega** [comment]
We're still trying to resolve this issue. Can you please try this test file for me? Here's what you do:

1. Go to your `SILENT HILL 2` game folder and make a _backup_ of your `SH2EEsetup.exe` file in there.
2. Once backed up to another location, download this new version of `SH2EEsetup.exe` here: [SH2EEsetup_Download_Fix_Test.zip](https://github.com/user-attachments/files/17652785/SH2EEsetup_Download_Fix_Test.zip)
3. Unzip this package and place the new `SH2EEsetup.exe` within your `SILENT HILL 2` game folder (where the previous `SH2EEsetup.exe` existed).
4. Run the new `SH2EEsetup.exe` and let us know if you can now successfully download the package files or not.

Because this is a new test file, you might get a [false positive](https://allaboutcookies.org/antivirus-false-positive) warning about it from your antivirus vendor. The file is safe but, if you're still unsure, you can submit the file for review to Windows Defender, BitDefender, or your other favorite vendor of choice.

Thanks

**Comment by SilentHeII** [comment]
![image](https://github.com/user-attachments/assets/3b0844a1-9d57-4c99-b716-8d8415ec5724)
This is the error I get when using the setup tool from your newest version.

**Comment by mah84** [comment]
Can you help me please with: Couldn't download 'webcsv.url' error:((

**Comment by Polymega** [comment]
> Can you help me please with: Couldn't download 'webcsv.url' error:((

Sorry for the issues you're having. If you have the ability to use a VPN, please enable it and see if it then allows you to run the Setup Tool. Otherwise, you can manually download the package files by downloading and opening this file, and grabbing the URLs found within: 

[_sh2ee.csv](https://github.com/user-attachments/files/18679414/_sh2ee.csv)
