### ISSUE TITLE
sh2ee.csv when trying to launch the setup inside of the game directory

### ISSUE THREAD

**Issue by Tominelis** [elishacloud/Silent-Hill-2-Enhancements#1096]
Although I downloaded the game files from myabandonware.com and installed it successfully, the enhanced edition setup shows this error alongside two message popups before hand: 
I get these popups two times after clicking yes, and then the other attached popup appears.
![image](https://github.com/user-attachments/assets/baeeb035-3dfa-4715-bcfe-89c8e2e20b98)

This is the error I get after submitting the certificate two times or just pressing No when submitting the certificate one time: 
![image](https://github.com/user-attachments/assets/8a6207cd-dc38-415f-a92c-c7ad451405db)

Can anyone help me out?

**Comment by Polymega** [comment]
I am trying to get to the bottom of this issue. Can you try again and let me know if it still happens?

**Comment by Tominelis** [comment]
Hi, the issue is still the same even after redownloading the enhanced edition setup.

**Comment by Polymega** [comment]
We're still trying to resolve this issue. Can you please try this test file for me? Here's what you do:

1. Go to your `SILENT HILL 2` game folder and make a _backup_ of your `SH2EEsetup.exe` file in there.
2. Once backed up to another location, download this new version of `SH2EEsetup.exe` here: [SH2EEsetup_Download_Fix_Test.zip](https://github.com/user-attachments/files/17652785/SH2EEsetup_Download_Fix_Test.zip)
3. Unzip this package and place the new `SH2EEsetup.exe` within your `SILENT HILL 2` game folder (where the previous `SH2EEsetup.exe` existed).
4. Run the new `SH2EEsetup.exe` and let us know if you can now successfully download the package files or not.

Because this is a new test file, you might get a [false positive](https://allaboutcookies.org/antivirus-false-positive) warning about it from your antivirus vendor. The file is safe but, if you're still unsure, you can submit the file for review to Windows Defender, BitDefender, or your other favorite vendor of choice.

Thanks

**Comment by Tominelis** [comment]
Hi, the problem was resolved for me personally. I didn't try any new fix methods except retrying the setup every day until it worked, so I assumed the issue was fixed.
