### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#110]
@elishacloud @AeroWidescreen @Bigmanjapan @FrozenFish24 @Belek666 @Nisto @CookiePLMonster @ThirteenAG @angularGraphics

I'd like to thank you all for everything you've done and continue to do for this beloved game. 

[The next major update for the project](https://www.youtube.com/watch?v=377H3K9jAGA) has released and I couldn't be more proud of everything you all have accomplished and continue to achieve. 

If/when you download the packages for this newest update, I invite you all to launch the game, and, from the game's main menu, click on "Movies" then click on "PC Credits." :) 

Thank you all for a fan-freakin'-tastic job well done!!

**Comment by ThirteenAG** [comment]
Pretty incredible to see you guys show so much love and care for this game. Video game communities are the best.

**Comment by AeroWidescreen** [comment]
We have collectively done a better job at remastering this game than the very company that owns it. Sometimes I don't know if we should be proud or disappointed. All I know is that it's been really fun collaborating with you guys and I hope there's more to come.

**Comment by Nisto** [comment]
Glad to have been a part of this. Keep it up everyone.

**Comment by Bigmanjapan** [comment]
![loyalty](https://user-images.githubusercontent.com/31383389/56453976-3bac1400-6374-11e9-8c6e-673ce4f3fa73.jpg)

**Comment by Bigmanjapan** [comment]
Thank for you work of putting the project together.

**Comment by Polymega** [comment]
The thanks goes to each and every one of you! This project has and will always be a team effort. And I want to say this again: I'm so damn fortunate and grateful to be collaborating with all of you. Putting aside everyone's obvious skills and talent, all of you are just so kind, patient, and willing to help. I feel very lucky to be working along such great people.

**Comment by Storm3000** [comment]
I love your work, guys. Is really awesome what you have made with this game. I thought it was impossible to fix because the original PC release was a mess. I had serious issues trying to play this game, and that directly affects the quality of the game. You cannot perceive what the creator wants to express with his work when everything is different from his original vision. That's what happened with the awful Konami remake. The PC/Xbox ports were "fine", but full of issues.

Now this Enhanced Edition is what I call the ultimate Silent Hill 2. There are still some details missing here and there, but it's almost a perfect game now. Congratulations!

**Comment by Polymega** [comment]
Team, I wanted to share a simple Reddit post I just found. I thought it was really nice, and hope it'll put a smile on your faces, too:
https://www.reddit.com/r/silenthill/comments/c81bbe/first_playthrough_on_the_enhanced_edition_so/

**Comment by Polymega** [comment]
![IMG_20191015_024029~2](https://user-images.githubusercontent.com/27395260/66806385-66c38a80-eef5-11e9-91bd-39592b96323a.jpg)
![IMG_20191015_024019](https://user-images.githubusercontent.com/27395260/66806393-6b883e80-eef5-11e9-8b34-ab100f8618f7.jpg)
