### ISSUE TITLE
Can I have an offline installer?

### ISSUE THREAD

**Issue by ghf50** [elishacloud/Silent-Hill-2-Enhancements#1102]
Hello, Dear devs.

Can I have an offline installer that contain all EE files?
My ISP blocked the server and I can't download EE files through installer.

**Comment by Polymega** [comment]
If you open this file with a text editor, such as NotePad, you can find links to all the project packages: https://files.townofsilenthill.com/SH2EE/_sh2ee.csv

**Comment by ghf50** [comment]
Thank you @Polymega ！
This helped.

**Comment by Polymega** [comment]
We're still trying to resolve this issue. Can you please try this test file for me? Here's what you do:

1. Go to your `SILENT HILL 2` game folder and make a _backup_ of your `SH2EEsetup.exe` file in there.
2. Once backed up to another location, download this new version of `SH2EEsetup.exe` here: [SH2EEsetup_Download_Fix_Test.zip](https://github.com/user-attachments/files/17652785/SH2EEsetup_Download_Fix_Test.zip)
3. Unzip this package and place the new `SH2EEsetup.exe` within your `SILENT HILL 2` game folder (where the previous `SH2EEsetup.exe` existed).
4. Run the new `SH2EEsetup.exe` and let us know if you can now successfully download the package files or not.

Because this is a new test file, you might get a [false positive](https://allaboutcookies.org/antivirus-false-positive) warning about it from your antivirus vendor. The file is safe but, if you're still unsure, you can submit the file for review to Windows Defender, BitDefender, or your other favorite vendor of choice.

Thanks

**Comment by ghf50** [comment]
@Polymega Hello
I've tested the new SH2EEsetup.exe from SH2EEsetup_Download_Fix_Test.zip, still can't download "webcsv.url"
![notitle](https://github.com/user-attachments/assets/c2890858-296c-4ae5-8736-25fd16cc24d5)
