### ISSUE TITLE
Enhanced FMV Pack on SH2:EE website.

### ISSUE THREAD

**Issue by Storm3000** [elishacloud/Silent-Hill-2-Enhancements#112]
Hi!

First of all, congratulations for the new update, guys. I love your work.

Which version of Enhanced FMV Pack should I use? I play on 16:9 aspect ratio, but now the only option to download is 16:10. What happened with the other pack?

Also, I suggest to add in Troubleshooting/The Game Freezes, the option to use the NA .exe. With the english .exe the game won't crash upon launch.

**Comment by Polymega** [comment]
In my quest to simplify the installation guide for users (as people who are less computer savvy have mentioned it's a bit overwhelming) I removed the FMV options and made it to where only the original FMV pack is available (the one originally made by angular graphics). 

If you still have your 16:9 FMV download you're completely fine to use that still. 

I can look into adding such a thing to the Troubleshooting portion of the guide later on, sure. 

We're not going to touch the spread/cone angle of the flashlight, as it's nearly the same as the PS2's spread. The only reason the spread looks smaller on the PS2 build is because it's using per-vertex lighting, which doesn't evenly distribute the lighting effect across the environment. 

> Occasionally, you may notice how the light overpasses James's back when running/walking on streets.

Although, can you clarify what you mean by this?

**Comment by Storm3000** [comment]
I'm sorry, my english is not the best. I'll post a pic:

![Sin título](https://user-images.githubusercontent.com/28787944/56512599-37affb80-6506-11e9-9147-4f99625bf5ac.jpg)

**Comment by Polymega** [comment]
> I'm sorry, my english is not the best. I'll post a pic:

No worries. Ah, okay, I understand now. And...

> I'm seeing a Silent Hill 2 PS2 walkthrough on Youtube right now, and it has the same radiancy on the flashlight with the same "issue", so I can live with it. No problem, then.

You beat me to it. :) This appears to be how the game engine/programming was wrote to handle the glow around the flashlight lens. At least on the PCSX2 version, this glow is substantially bigger and makes that rendering effect even more noticeable: 

![image](https://user-images.githubusercontent.com/27395260/56533759-52926800-6526-11e9-8001-349b0a260959.png)

**Comment by Polymega** [comment]
@Storm3000 I've updated/adjusted the Installation Guide in regards to performance issues (random crashes) that can occur with the modified DC executable. This change updates the Changelog, Step #2: Install Enhanced EXE, and now includes a portion in the Troubleshooting section about this:

- http://enhanced.townofsilenthill.com/SH2/#changelog
- http://enhanced.townofsilenthill.com/SH2/#installEnhancedEXE
- http://enhanced.townofsilenthill.com/SH2/#troubleshooting
