### ISSUE TITLE
Map indications still visible & Controller vibration

### ISSUE THREAD

**Issue by RenoFriends** [elishacloud/Silent-Hill-2-Enhancements#115]
Hi there

I am aware that in 2018 it was a thread about the pilar boxing on the maps menu and that Fix2D stretches the image to "solve" this problem but would be great to have other solution and don't know if someone is working on it...

Also I have a Xbox one wireless controller with official adaptor that works great but I can't manage it to vibrate... Do I need to erase like the guide says the Xinput files? Don't know if my controller is direct input or not... Thanks!

**Comment by Polymega** [comment]
> and that Fix2D stretches the image to "solve" this problem but would be great to have other solution and don't know if someone is working on it...

Yes, this is on our to-do list still. 

> I have a Xbox one wireless controller with official adaptor that works great but I can't manage it to vibrate... 

Refer to the bottom of the Troubleshooting table for vibration troubleshooting: http://enhanced.townofsilenthill.com/SH2/#troubleshooting

**Comment by RenoFriends** [comment]
I already read there but I will try again tomorrow, thanks!
By the way I used to launch the game through a steam shortcut and now doesn't launch don't know why...

**Comment by Polymega** [comment]
Xbox controllers are XInput. Are you also using the Xi Lavendy driver? 

http://lavendy.net/special/driver/xi/index.html

That may possibly cause conflicts. I'm not sure as I don't have that driver installed.

**Comment by RenoFriends** [comment]
I didn't install that driver or almost doesn't sound to me...

**Comment by Polymega** [comment]
Hi @RenoFriends,

Have you had any success with restoring vibration?

**Comment by RenoFriends** [comment]
No 😓 and starting the game from Steam either

**Comment by Polymega** [comment]
Silly question to ask, but does your Xbox One controller vibrate for other games on your PC? If you go the link below, connect your controller, and click "Test Vibration" that works?

https://html5gamepad.com

**Comment by RenoFriends** [comment]
Yes, it works =(

**Comment by Polymega** [comment]
Not including the Xi Lavendy driver, can you double-check and make sure you don't have any additional, unneeded software/drivers installed that relate to controller usage?

For example, another person had an issue with vibration and a driver causing conflict: 
https://www.reddit.com/r/silenthill/comments/bj1zsi/silent_hill_2_enhanced_edition_with_dualshock_3/

While that issue was about the DualShock 3, it can also relate to Xbox controllers, too. 

Here is a tutorial to bring up the add/remove software window for Windows 7:
https://support.microsoft.com/en-us/help/2601726

And Windows 10:
https://www.laptopmag.com/articles/uninstall-programs-windows-10

Here is what it looks like on Windows 7: 
![image](https://user-images.githubusercontent.com/27395260/57058592-c77c4500-6c7e-11e9-927f-cae96f86d0b4.png)

**Comment by w1lddog2** [comment]
I have 360 gamepad and vibrates no issue, i also have a One Gamepad vibrates no problem, plus i also use a DS3 with the SCP driver and all of them have vibration on SH2 using XInput Plus. Tried them on various PC and they do work.

By any chance in steam do you have enable  "Xbox configuration support" if that's the case, shutdown "steam.exe" and try to play the game and see if vibration works.  When you have enable that option steam will inject itself in any program that doesn't need admin rights and sometimes can mess things up, even if you are not running the game using steam.....

**Comment by elishacloud** [comment]
Closing this out.
