### ISSUE TITLE
removal of ultimate asi loader and usage of d3d8 was bad idea and needs to be reverted

### ISSUE THREAD

**Issue by v00d00m4n** [elishacloud/Silent-Hill-2-Enhancements#116]
Ultimate asi loader can be used as dozen of dll wrappers, which allows combine it with other wrappers. Priot this really bad update that moved fix from asi plugin into stand alone d3d8 WIne d3d8 to opengl wrapper cant be used anymore, dgVoodoo wrapper cant be used too, actually non of other d3d8 wrappers can be used, and there are many wrappers that works better than built-in crosire's one and has more options. So, basically with this update you forced people to use just one inferior most basic d3d8 wrapper and whole idea was really bad. I, for example, prefered dgVoodoo handling everything from windowed mode and antialising, to forcing bilinear filtering to some unfiltered textures and even applying built in scanlines to mimic old tv look. I also like dgvoodoo for a fact that it wrapped game to more up to date dx10-11, instead of quite broken (thanks to MS) d3d9, antialising there was also flawless, it also had pretty perfect window handling options, which are all gone now. Another bad thing about whole change - i used to combine dgVoodoo with SpecialK, which has texture dumping and injection for D3D10+ only and not for D3D9, and i used it for my secretly developed neural network enhanced texture mod (had to use SpecialK because existing texture import tools sucks and no one cares to make a new proper texture tool that will allow to change resolution and format of textures). Guess what???  NOW IT DOES NOT WORK NOW, because built in wrapper wraps to d3d9 and SK does not support it well for texture modding and even it did, texture hashes could be different and would require reworking everything. 

Moral of this story: never ever use any gfx, audio, input or any other input\output api dlls because they are often used by generic graphics, audio and input restoration\enhancment wrappers, and you limiting their usage and making it all harder. Also never change the way things work in a middle of the way since it can brake things.

Genius Ultimate ASI architecture allowed to avoid this and load and game specific improvements without collision with any other more generic wrappers, and decision to dump asi architecture and go full solo mode was short sighted and not really smart move. Basically core of this fix is still ASI loader, but instead of using generic one with pluging architecture, you just merged everything and stripped down UASI features and tied it ot just one (judging byt exports it seems like it cant be still used as dinput8 and dsound but its also bad idea, because it will prevent usage of xinput plus in one case and dsound 3d restoration wrappers in other case) dll which prevents using other more advanced wrappers for d3d8.

So, i strongly suggest to get back to ASI architecture and usage of ultimate ASI loader which has all of dll collision problems sorted, constantly updated and and can load game specific fixes asi from scripts folder without collision with any other dll. And yes, this would allow me to continue high resolution mod development, with help of chained dgvoodoo and specialk, which i had to stop since this update ruined this fine chain of tools... this may sound a little bit egoistic but im doing this mod for all SH2 users and i heard in recent video FAQ that you are not planning any texture enhancements except for full screen images, so someone has to do it, but specialk which requires dx10+ is the only proper way to do it.

**Comment by elishacloud** [comment]
@v00d00m4n, thanks for your comments.  This project still fully supports Ultimate ASI Loader.  If you look at the config file [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/7f51d6279c1b745ac461509abab8dbc494fb9bf8/Common/Settings.ini#L39-L41) you will see the `[Plugins]` section where this can be enabled.

To use dgVoodoo2, do the following steps:

1. Disable `d3d8to9` in the d3d8.ini config file.
2. Enable `LoadPlugins` and `LoadFromScriptsOnly` in the d3d8.ini config file.
3. Create a folder under Silent Hill 2 called `scripts`.
4. Download the latest `LoadWineD3D.asi` from the [LoadWineD3D-ASI](https://github.com/elishacloud/LoadWineD3D-ASI) project and copy it to the `scripts` folder.
5. Download the latest `d3d8.dll` file from [dgVoodoo2](http://dege.freeweb.hu/dgVoodoo2/dgVoodoo2.html) and copy it to the `scripts` folder.
6. Start Silent Hill 2 and enjoy!

For your convenience I have already done all these steps and created a package with all the files you need.  Just unzip these into the Silent Hill 2 folder: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3125575/d3d8.zip)

_Note: The reason I did not use dgVoodoo2 is because it is not open source.  I am trying to use open source as much as possible,  Also, I remember that dgVoodoo2 created some issue with Silent Hill 2, though I don't remember what it was at this moment._

**Comment by elishacloud** [comment]
I created a new option for this specific use case so you that don't need to use LoadWineD3D-ASI.  The new option is called [`LoadD3d8FromScriptsFolder`](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/b9cb4625458ecdcb9b60f44a3d229784a534f3b7/Common/Settings.ini#L42).  Just do the following:

1. Disable the `d3d8to9` option
2. Enable the `LoadD3d8FromScriptsFolder` option
3. Copy the dgVoodoo2's d3d8.dll file into the `scripts` folder
 
Here is the latest update with this new feature: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3133197/d3d8.zip)

This update should work fine with specialk.  Just copy the specialk files into the Silent Hill 2 folder as before.  Let me know if you have any issues here.

**Comment by elishacloud** [comment]
Closing issue.  A workaround has been provided.
