### ISSUE TITLE
Closet cutscene noise effect and bars blur

### ISSUE THREAD

**Issue by Bigmanjapan** [elishacloud/Silent-Hill-2-Enhancements#139]
@Polymega 

sh2pc.exe+542694 (00942694) byte 

Freeze this address at 0 value during the cutscene to make noise effect overlay closet bars' blur.

![Безымянный4](https://user-images.githubusercontent.com/31383389/59661477-1a7d6d80-91d5-11e9-99a9-ea5b3e23e0b7.png)

![Безымянный3](https://user-images.githubusercontent.com/31383389/59661484-1f422180-91d5-11e9-84ee-a6008206d51b.png)

**Comment by Polymega** [comment]
_Niiice!_ I was in the same memory region of your address fix but never could pin-point the culprit address. This is another reason why the pros are pros at what they do. Well done with this! 

It looks like some opcodes will need to be modified or nop'ed to fully override that byte value of 5. 

I know Aero_ is working on some other fixes for the project, so I will get his attention on this a little later. Thanks for your help here, Bigmanjapan!

**Comment by Polymega** [comment]
**Nop'ing** this instruction will automatically put the byte for sh2pc.exe+542694 (00942694) at `0`:

`00478343 - A3 94269400 - mov [00942694],eax`

It can be nop'ed whenever [the camera cuts to this angle using code Elisha has already written](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/ClosetCutscene.cpp#L138-L139)? Then it can be un-nop'ed afterwards?

**Comment by elishacloud** [comment]
> It can be nop'ed whenever [the camera cuts to this angle using code Elisha has already written](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/419458097924e1dae9659328fc93c3df39c25c44/Patches/ClosetCutscene.cpp#L138-L139)? Then it can be un-nop'ed afterwards?

No.  We cannot use my existing code for this.  If I nop it there it could crash.  We will need to make asm for this.  I can probably make the code myself though.  Should not be too hard.

**Comment by Polymega** [comment]
If it helps: It's probably safe to either nop it will in the room (Room ID: `0x13`) or at the beginning of the cutscene (Cutscene ID: `0x0E`) instead of during that particular camera cut?

**Comment by elishacloud** [comment]
I believe this implementation should work.  Testing module: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3450055/d3d8.zip)

_Note: I used cutscene ID `0x0E` and camera position `-21376.56445`._

**Comment by Polymega** [comment]
Confirmed working great across all binaries! Thank you Bigmanjapan and Elisha! This is a small but oh-so-sexy visual improvement for such a cool/weird cutscene.

**Comment by Polymega** [comment]
@elishacloud 
On the topic of the `ClosetCutsceneFix`: While testing your module I happened to come across a very simple solution for # 1 [from this list](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/68), which we never addressed.

--------------------

### Part 1:

Ignore the solution for # 1 from that link above and use this approach instead: 

During this cutscene (`0x0E`) on camera position `-22256.61133` set the following (one write, no constant iteration): 

```
Flashlight light R - 00942AB0 float = 0
Flashlight light G - 00942AB4 float = 0
Flashlight light B - 00942AB8 float = 0
Flashlight render - 0089FF82 byte = 0
```

... and that's it for Part 1! These values will restore to their correct numbers upon cutscene ID end (regardless if the cutscene ends on its own or if the player ends it early). 

You recently worked with `0089FF82 byte` for the `LightingTransitionFix`. The float addresses here were probably also used before with previous flashlight work.

What we're doing here is disabling the flashlight completely during a particular camera cut, to simulate James himself turning off the light right before heading into the closet. This not only alleviates the concern of the missing lens flare (because the camera becomes too close to James while he's in the closet when `ReduceCutsceneFOV` is used), but makes the cutscene as a whole more believable because why would you hide in a closet if you also aren't going to turn off your light??

------------------

### Part 2: 

Turning off the flashlight as we're doing for Part 1 here [alters the room visuals for the addresses we changed for this part](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/ClosetCutscene.cpp#L165-L173). 

Please change `-0.2f` here to `-0.7f`, and `1.0f` to `0.3f`.

------------------

### Part 3: 

I was going to wait and bring this up when Aero_ submit's his post processing fix, but we can change it now since you're in these parts. 

[Please remove the "Closet bar intensity" address/fix](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/ClosetCutscene.cpp#L146) from the module. (There are several instances of the address in your code, of course.) Please keep the "Time of Day" address fix in the module; that one is completely fine.

We're removing this because, this approach to blurring the bars [creates a visual issue](https://user-images.githubusercontent.com/27395260/60777023-17074300-a0fe-11e9-85a6-dcdc18e969e5.png) as pointed out to me by a YouTube comment.

I found a better approach to fix this that will be submitted to you when Aero_ submits his post processing fixes. Basically, we're dropping the closet bar blur from the `ClosetCutsceneFix` and it'll be a part of the post processing fix instead now.

---------------

Thank you!

**Comment by elishacloud** [comment]
> Ignore the solution for # 1 from that link above and use this approach instead:

I don't think I implemented this one.  I think it is in WSF, so I did not remove it.  However, all the rest of this should be done.

Test module: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3459397/d3d8.zip)

**Comment by Polymega** [comment]
Thanks Elisha. 

> I don't think I implemented this one. I think it is in WSF, so I did not remove it. 

That's correct. It was never touched with by either your repository or the WSF. 

Instead of trying to deal with FOV adjustments to restore James' flashlight glow, we'll take an entirely different route for this by turning off James' flashlight during a particular camera cut. Sorry for any confusion there. On that note, the fix looks good except [Part 1 from the post above](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/139#issuecomment-516999772) isn't implemented.

**Comment by elishacloud** [comment]
OK, try this one.  It looks like I forgot to put the `f` next to the `-22256.61133` to indicate that it is a float.

Test module: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3459670/d3d8.zip)

**Comment by Polymega** [comment]
Worked like a charm on all binaries! Thanks for including this last-minute addition.
