### ISSUE TITLE
Editing d3d8.ini doesn't apply changes

### ISSUE THREAD

**Issue by samTrent** [elishacloud/Silent-Hill-2-Enhancements#145]
Hey guys,
So I'm having [this issue](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/103) and it looks like the solution is to set the d3d8to9 setting to 0 in the d3d8.ini file. I tried doing this and it didn't work. I am suspicious however, that none of the changes that I make to that file seem to actually get reflected in the game.

For example, I tried setting the UnlockJapLang option to true but I don't get the option in the game. I tried disabling the DPadMovementFix but it still worked in game. The game still runs safemode if it crashes dispite DisableSafeMode being set to true.

I've reinstalling d3d8.ini but to no avail and yes, I've double checked to ensure that I'm actually saving the file. Anyone have any idea as to whats going?

btw, just want to say thanks for all your hardwork putting this thing together. Its amazing!
Thanks.

![directoryPart1](https://user-images.githubusercontent.com/22596215/60740486-c257a280-9f1a-11e9-8a8c-64db443f3ed6.PNG)

![directoryPart2](https://user-images.githubusercontent.com/22596215/60740496-cb487400-9f1a-11e9-86d8-f3f8cfe6dcd0.PNG)

**Comment by Polymega** [comment]
Hi @samTrent,

> The game still runs safemode if it crashes dispite DisableSafeMode being set to true.

That particular fix is part of the Widescreen Fix package (that's integrated into the SH2 Enhancements module). This tells me the Widescreen Fix specific fixes included in the project aren't working for you. 

I was helping a streamer set up her PC to run SH2:EE for the first time the other day and she had the same issue of the Widescreen Fix parts not working. Turns out she was using an older version of the SH2 Enhancements module [that didn't include the latest Windows Update fix we've pushed out.](https://www.youtube.com/watch?v=jAIL37IL2uU) Once she updated to the latest build of that, all `d3d8.ini` file fixes were working for her. 

So to start things off, please ensure you're using the latest version of the SH2 Enhancements module by downloading it here (the `d3d8.zip` package): https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest

Replace files within the game's main directory, if prompted. I'd recommend restarting your PC after replacing those files but before launching the game again. Let me know if that helps any first. If you're still having issues after this, please launch the game, close it, then attach your `d3d8.log` file as a reply here. 

Thanks

**Comment by Polymega** [comment]
PS - If using Notepad++ to edit your INI file before to actually save changes (File > Save or Crtl + S). Notepad++ will allow you to close the program without asking to save changes because it can reload the unsaved file changes at a later time.

I mention this because someone else had this specific problem when we were troubleshooting. :)

**Comment by samTrent** [comment]
THAT DID IT! 
Thank you so much man for the prompt reply! You guys are amazing! I've been looking forward to playing this game for so long now!

So I did three things, I'm not sure which one actually did the fix.
1) Downloaded and installed the new d3d8 zip that you provided
2) Rolled back ReShade from 4.3 to 4.2.1
3) Used ctl-s to ensure that it saved

Hopefully this helps some one
