### ISSUE TITLE
Implimentation of Soft Shadows

### ISSUE THREAD

**Issue by umbrellacorp53** [elishacloud/Silent-Hill-2-Enhancements#147]
Soft Shadows. I can't find any discussion on this topic and I know it's something on the roadmap. Please pardon me if it's not my place to open the discussion or if I missed the topic header somewhere. I'm just curious what ideas you guys are spitballing and what we know so far about how shadows have been implemented in the PC version. 

Random thought... if the shadows are too difficult to reverse engineer would it be possible to inject them? That would probably end up being way more work considering all the effort you've put in so far adjusting the existing shadows and light sources.

Anyone have access to literature on DX8 soft shadows?

**Comment by Polymega** [comment]
I'm not the person to truly talk about this as I'm far from a programmer/modder, but from what research I've done in the past, [soft shadows were first introduced to DirectX in version 8.1, but were solidly used/implemented in DX9 and onwards. ](https://developer.valvesoftware.com/wiki/DirectX_Versions)

Dean Calver, the lead programmer for Creature Labs (who did the SH2 PC port), [commented on implementing soft shadows before](https://www.youtube.com/watch?v=zAPf5fSDGVk): 

> It should be possible to hook into the renderer and pop in a blur shader via the emulator. The blur would be pretty simple, the hard part would be finding where and when to do it.

In addition to that, Silent Hill 2 does a lot of trickery with soft shadows that many people may not notice. 

For example: If you turn your flashlight on/off the new dynamic shadows don't immediately "pop" in. Instead, they slowly _fade in_ over the course of a few seconds. So additional code creates a transparency slider for the shadow render pass. 

In terms of research: Very little has been done/looked into for this. This is mostly due to the scope of such a project, working on other fixes/enhancements currently on the table, and the need for the right people to come along and help us who are very familiar/comfortable with such work.

**Comment by umbrellacorp53** [comment]
Your second link sent me to a Looney Tunes YouTube video lol

**Comment by Polymega** [comment]
lol so it did! That's funny. I sent that link to a friend earlier. Try that link again now, haha.

**Comment by umbrellacorp53** [comment]
I imagine the source code is under lock and key... If not stuffed inside some pachinko machine. :|

I just read that entire thread and I'm amazed at what a team of 4 was able to accomplish in 3-4 months... If they hadn't managed then there would be no HD project! Such talented coders. I really wish I knew where to even begin digging to help. All I have is time.

**Comment by umbrellacorp53** [comment]
I imagine the source code is under lock and key... If not stuffed inside some pachinko machine. :|

I just read that entire thread and I'm amazed at what a team of 4 was able to accomplish in 3-4 months... If they hadn't managed then there would be no HD project! Such talented coders. I really wish I knew where to even begin digging to help. All I have is time.

**Comment by Polymega** [comment]
> I imagine the source code is under lock and key... If not stuffed inside some pachinko machine. :|

The source code is long gone. This is the primary reason why the HD Collection is so terrible: Hijinx Studios received early, incomplete beta code of the game because that's all Konami had left of the source code; they lost (discarded?) the final, gold release code. 

Granted, Hijinx Studios also didn't have the experience/tenure in creating remasters without source code--like what BluePoint Games is known for and excels at--so that's another factor in the HD Collection's demise.

Anyway, it turns out throwing away source code was a common practice, especially for Japanese publishers, in the 80s, 90s, and early 2000s. More info on that here: https://www.youtube.com/watch?v=0EfcatLcrrA&feature=youtu.be&t=278

> I just read that entire thread and I'm amazed at what a team of 4 was able to accomplish in 3-4 months... If they hadn't managed then there would be no HD project! Such talented coders.

I'm very happy to hear you say this. A lot of people dump on the vanilla PC port without being aware of the circumstances. While there are many issues with the port, it's completely mind-blowing to me that a team of 4-5 ported this in such a short amount of time. 

Not only were there hands tied in having to compress audio/video effects by request of Konami, but they had to alter additional code/effects to make it compatible on as many GPUs of the time as possible. (Which, ironically, we're now working on undoing/restoring.) To do all of this in that time frame is crazy to me.

**Comment by umbrellacorp53** [comment]
> Konami had left of the source code; they lost (discarded?) the final, gold release code.

That's so sad but I understand now how it could happen after watching that video, which by the way was brutal to watch. Had to relive my PT-PTSD all over again. I don't think I've ever been that pumped up then disappointed in my adult life.

> A lot of people dump on the vanilla PC port without being aware of the circumstances.

I'm just amazed that it exists in the first place! It's almost an oddity. Since the HD remaster strayed so far away from the original intent (especially when it came to redoing all the voice acting 🤮) I'm grateful there is at least **some** other way of experiencing the game in HD without emulators.

Side note: Could you imagine a proper HD remake of SH 1-4? I won't hold my breath. Lol

**Comment by umbrellacorp53** [comment]
Closing this to clear the clutter. There is an official Issue.
