### ISSUE TITLE
Increase Draw Distance

### ISSUE THREAD

**Issue by AeroWidescreen** [elishacloud/Silent-Hill-2-Enhancements#15]
@elishacloud [A continuation of this discussion](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/2#issuecomment-379328436). I'm creating a new issue so there isn't any confusion. 

The addresses below are for instructions that write 7500 float to 00942958. This allows us to control the draw distance when that particular value is used. We want to increase it because it was found to be too low, especially in the Woodside Apartments where we often see a black wall in the hallways.

@Bigmanjapan recommends a value of 8500 float as default. If I remember correctly, this was tested by @Polymega and no issues were found. 

```
// controls draw distance when 7500 is used
0047C19F 4604D000
0057E7CB 4604D000
00587F7D 4604D000
00587FBD 4604D000
00594FEC 4604D000
0059EC21 4604D000
```

**Comment by elishacloud** [comment]
Thanks @AeroWidescreen!

**Comment by elishacloud** [comment]
I implemented the Increased Draw Distance feature with [ed32d05](https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/ed32d05fb13ddb63835f06a21152aacfcc854346) check-in.

I used 8500 float as default.  But easy enough to change later if needed.

**Comment by elishacloud** [comment]
Fixed.  Closing issue.

**Comment by Keith94** [comment]
Any chance of making it customizable by the user?

**Comment by elishacloud** [comment]
Yes, I thought about that.  It is pretty easy to implement.  It would simply be allowing the user to customize this variable [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/94a7d017c07182550d1f39ce39acfb8540be909c/Patches/DrawDistance.cpp#L27).  That is part of the reason I kept it as an actual variable rather than a byte array, which would have made it slightly easier to implement.  A variable is ease to change in the future, if we ever decide to change it.

However the draw distance is different in different locations in the game.  This fix only changes the draw distance of the locations that use 7500.0f.  So all it would do is customize those locations. I am not sure how valuable it would be to allow them to customize only these locations.

I don't really want to do the work to find all the draw distance locations in the entire game and let them customize each of them uniquely.  I am not even sure how many unique draw distances there are in the game.

**Comment by Polymega** [comment]
You really won't see much more than what you can already see in the game as-is. This is because of the games "fog-of-war" effect (the fog haze it places X distance in front of James at all times). 

@Keith94 are you asking for this for experimentation/research purposes? If so, we could simply provide you a Cheat Engine Table where you can adjust the draw distance to any amount you'd like at any time?

**Comment by Keith94** [comment]
Ah, okay. I was hoping it could allow seeing more of the world i.e. increasing the graphics quality in general. A Cheat Engine could be useful for that, please.

**Comment by Polymega** [comment]
I see. Yeah, there's two factors to achieve that: Increasing the draw distance (how much geometry loads ahead of time in front of James) and removing or increasing the fog distance (how far back the "fog haze" is from James' body). 

For these enhancements it's probably best to keep it as representative to the released version(s) as possible but we can send you a Cheat Table soon to go crazy with those types of things. Stay tuned!

**Comment by Polymega** [comment]
@Bigmanjapan is there a value to change the distance or remove the "fog-of-war" in the PC game?
