### ISSUE TITLE
About Black level with noise filter enabled

### ISSUE THREAD

**Issue by Badore90** [elishacloud/Silent-Hill-2-Enhancements#170]
I think best way to play this game is in a completely (or almost) dark room, using a tv with a black that's black (crt tv/monitor or Oled). 

I've always noticed that the Xbox and PC versions have a grey noise filter. 
i.e. on Xbox (I've it connected to a crt) with noise filter on, I can notice a huge difference in the black when playing a cut-scene, only black bars are real black, the actual scene is grey.
With noise filter off instead, the black in the scene is perfect, as in the horizzontal bars. 
It's simply like playing another game.

On Pc is the same thing. The ps2 is the only version with a black level that match the black bars.

I was wondering if it's possible to add a patch for change the noise filter's color from grey to black. 
When I suggest this game to someone I say that the noise filter is quite important, it matters for the story and add to the atmosphere, so it's better to leave it enabled on the first run.

**Comment by Polymega** [comment]
The `PS2StyleNoiseFilter` and ReShade filters were carefully made to match the PS2 version as close as possible. Time and attention was put into these two fixes to give the closest PS2 representation as possible, in regards to the noise filter and levels. You can see comparison photos here: 
http://enhanced.townofsilenthill.com/SH2/comparisons/noisefilter.htm

> i.e. on Xbox (I've it connected to a crt) with noise filter on

You shouldn't compare a lossy, analogue image (CRT) to a lossless, digital image (PC), as comparing the two is akin to comparing apples to oranges. In order to do proper testing, you must compare on the same source. In this case, SH2 PCSX2 to SH2 PC (both digital output sources) on the same monitor/display.

The reason you can see the noise grain in totally black parts (or, in other words, why the game makes true blacks look grey when using the noise filter) is due to a developer-intended approach. If the noise grain was black, you'd see no grain in the totally black areas of the game. By making the grain varied shades of grey, you'll see the grain filter in all different contrasted parts of the game. 

The reference photos to the PS2 version linked above visually shows this.

**Comment by Badore90** [comment]
Thank you for the answer,

I finished the game multiple times on all 3 Platform, btw it's been a long time since my last playthrough… I'm coming back to this game only ultimately since I heard of your incredible work :D

...So, I made some further tests to be sure and noticed that:
- the Ps2 version seems to adjust the black bars black level, this confused me a little (on Xbox it doesn't happen). Then even on Ps2 the black level raise up a little with noise filter on. It must be how the game was intended to be as you said, no question about it.

My point was just that being the black actually black (you know with a crt monitor you have absolute black) the screen merge with the (completely dark) room. In dark areas you only see what your flashlight is lighting up (you don't see the tv screen at all! It's Amazing with these kind of games). 

However far from me to continue this discussion. I was mistaking about the ps2 version sorry, the grain have some grey on the original version too. Plus Reshade do something to the noise filter too you're right. I kept it disabled since it drops to 18fps (I haven't a proper gaming PC '^^). 

I have to try the enhanced edition with some of my calibrated screens. I could try it only on my laptop panel. 

Another thing I noticed on Ps2 is that the brightness option seems to raise up the contrast. 
i.e. with my tv normal settings, vertical bars appear faint (in a perfect dark room) setting the game option to 2. 
Now I can raise it up (to 4), then lower my tv brightness (until the bar return faint as they was) and see a perfect black even with noise filter on. Now that I think about it, I Always noticed that even raising up the game option to 7, the inventory menu always shows the same (true) black while other elements appear more bright.
I'll check it better to see if I'm losing some near black shades (probable…).

Can you confirm it (game's brightness option actually raise up the contrast)??

**Comment by Polymega** [comment]
> (you know with a crt monitor you have absolute black)

You can play around with the ReShade filter's levels to get a desired contrast you're looking for. After launching the game, press the **Home** key to open ReShade's control panel. 

**Uncheck** the "Performance Mode" checkbox near the bottom.
Under the **Levels** filter, adjust the "BlackPoint" and "WhitePoint" level sliders.

> Can you confirm it (game's brightness option actually raise up the contrast)??

When playing the PC version in windowed mode, it does **not** adjust the game's gamma or contrast. Older PC games were typically played only in fullscreen mode, so developers would often change your _entire monitor's_ gamma whenever you adjust the brightness slider in the game. When you play SH2 PC in windowed mode, it breaks this feature, therefor the brightness doesn't actually adjust. 

The noise filter becomes _slightly_ darker or brighter when you change the brightness in the game's Options menu, regardless if playing in windowed mode or not. It is recommended to play the game at a brightness level of 3 for the most accurate noise grain filter. 

Sadly, this is a limitation of the game due to its age.

**Comment by Badore90** [comment]
Thank you for the ReShade info, interesting. 

Just for clarity: I'm clueless about game development/modding, but I've some experience about video tec. (monitor calibration and general knowledge of how panels of every tec. work).

I know about the windowed mode thing, but I always leave ResY/ResX to 0. This way the game is displayed in full-screen regardless on how "EnableWndMode" and "FullscreenWndMode" are set. 
I mean, I can set EnableWndMode and correctly adjust the Brightness option if ResY/ResX is set to 0 (or 1366x768 in my case). It's normal, right?

To conclude about the noise filter. A precisation: on Ps2 the cut-scene black bars doesn't adjust their black level, simply the noise filter is present on them too (it fills up the entire screen, differently on what happens on Xbox where noise filter doesn't include cut-scene bars).

Definitely on Ps2 the game's brightness option raise up the contrast (not the brightness), so the game doesn't give to the player a clear clue on how to set the tv/monitor levels.
Since they mastered the game on a Sony BVM crt monitor, game's levels should be as rec. 709 reference, at least the Ps2 version... 
Most modern tvs have the brightness correctly set by default, so it shouldn't be a problem as long as the tv/pc rgb range correspond.

Thank you very much for the disposability.

**Comment by Polymega** [comment]
> I can set EnableWndMode and correctly adjust the Brightness option if ResY/ResX is set to 0 (or 1366x768 in my case). It's normal, right?

No, if you want to use the game's built-in Brightness adjuster you have to play in true fullscreen mode (`EnableWndMode = 0`). I wouldn't recommend doing this, personally. 

> on Ps2 the cut-scene black bars doesn't adjust their black level, simply the noise filter is present on them too (it fills up the entire screen, differently on what happens on Xbox where noise filter doesn't include cut-scene bars).

I see. Because you're playing in widescreen I strongly encourage you to disable the cutscene letter boxing (assuming you have `ReduceCutsceneFOV` enabled). The `ReduceCutsceneFOV` mod zooms in on cutscenes to match the horizontal composition of the original 4:3 view. By doing this, the cutscene's imagery becomes cropped vertically. If you enable the cutscene borders as well, you're further reducing the vertical image space to the point where character heads will become "sliced" by the border. 

> I'll check the EE version connecting the pc to a HD CRT to see if the brightess option work as on Ps2.

If you play in true fullscreen mode it may work. Otherwise it probably won't. Best of luck to you on your tests.

**Comment by Badore90** [comment]
> No, if you want to use the game's built-in Brightness adjuster you have to play in true fullscreen mode (EnableWndMode = 0). I wouldn't recommend doing this, personally.
> 
I play in true fullscreen, it was just a thing I noticed.

> I see. Because you're playing in widescreen I strongly encourage you to disable the cutscene letter boxing (assuming you have ReduceCutsceneFOV enabled). The ReduceCutsceneFOV mod zooms in on cutscenes to match the horizontal composition of the original 4:3 view. By doing this, the cutscene's imagery becomes cropped vertically. If you enable the cutscene borders as well, you're further reducing the vertical image space to the point where character heads will become "sliced" by the border.
> 
Don't worry I have it all perfectly set on the EE pc version. I carefully read the instrunctions on your site. It's all very clear and easy to understand, really simple to keep the enhancement up to date. It's pratically impossible to do something wrong :D

> If you play in true fullscreen mode it may work. Otherwise it probably won't. Best of luck to you on your tests.
> 
Thanks

>  It is recommended to play the game at a brightness level of 3 for the most accurate noise grain  filter.
> 
Definitely yes, since this option changes the image Contrast. Therefore best thing is to leave it at default and adjust the tv Brightness command if needed, thank you for pointing this out. Actually playing with that setting busts color levels.

**Comment by Badore90** [comment]
I take this opportunity to ask you about the "Speaker Config" in game options. I using a stereo tv or headset, it's better to just use "speaker" and "headphone"?? Or some other option (like "quadraphonic") do a better job??

I'm asking about that since on the Ps2 version the surround effect is much more noticeable (using the same headset). Sorry for the O.T.

**Comment by Polymega** [comment]
For the PC version, I believe the game must detect specialized drivers in order to change the sound configuration. If the game doesn't detect Dolby drivers, for example, it'll keep defaulting back to "Stereo." Likewise, when I change it to "Headphone" it reverts back to "Stereo" for me. 

I'm not 100% sure why it does that so I can't help you much with troubleshooting there. 

However, I can say that sometime in the distant future Elisha has toyed with the idea of creating a built-in solution to fix the audio clicks/pops in the game. If we can find a built-in solution (that is, so we can remove IndirectSound from the installation process), we can then utilize DSOAL instead. I've used DSOAL with SH2 PC and it sounds incredible, especially with headphones. It practically sounds just like the PS2 version for most sound stage/sound space deliverances.

Integrating DSOAL will likely be something that's done much further down the line. So, for now, I'd just play using IndirectSound and whatever sound configuration the game lets you choose that you like.

**Comment by Badore90** [comment]
> For the PC version, I believe the game must detect specialized drivers in order to change the sound configuration. If the game doesn't detect Dolby drivers, for example, it'll keep defaulting back to "Stereo." Likewise, when I change it to "Headphone" it reverts back to "Stereo" for me.
> I'm not 100% sure why it does that so I can't help you much with troubleshooting there.

Understood. I'll test it out and report back if finding something interesting. I noticed the difference at the beginning of the game, through the forest path that lead to Silent Hill. The monster's rattle is like a central sound on PC, on Ps2 is clearly behind me.

> However, I can say that sometime in the distant future Elisha has toyed with the idea of creating a built-in solution to fix the audio clicks/pops in the game. If we can find a built-in solution (that is, so we can remove IndirectSound from the installation process), we can then utilize DSOAL instead. I've used DSOAL with SH2 PC and it sounds incredible, especially with headphones. It practically sounds just like the PS2 version for most sound stage/sound space deliverances.
> Integrating DSOAL will likely be something that's done much further down the line. So, for now, I'd just play using IndirectSound and whatever sound configuration the game lets you choose that you like.

This is really interesting. 
This EE is better than 90% of official games remasters, the accomplishment is even greater considering how old this game is. Therefore it'd be great to correct these little things, making this amazing work 100% perfect.

I think It is already better than the original in most things. 
I really appreciate the way you made all the patches to be separately enabled/disabled. It's very simple to revert back the game to vanilla, or play on a 4:3 monitor keeping all the improvements (just disabling the 16:9 related ones).

**Comment by Polymega** [comment]
Thank you for the kind words. In particular: 

> (sure is the best way to play on HD 16:9 screens).

That is the main intent of this project. To provide a true, definitive **HD** SH2 experience. We didn't get that with the Silent Hill HD Collection, so the fans (us) must step up. 

Playing the game in 4:3 on original hardware on CRT televisions is still an excellent experience. But if you want to play in HD and/or widescreen we want to provide a version that pays respect to the masterpiece, along with going beyond-scope and improving additional aspects of the game where feasibly possible.

If/when we can use DSOAL the audio will give you goosebumps if you use headphones with SH2:EE. But again, this will be some time out.

**Comment by Badore90** [comment]
> Thank you for the kind words.

It's the least

> That is the main intent of this project. To provide a true, definitive HD SH2 experience. We didn't get that with the Silent Hill HD Collection, so the fans (us) must step up.

You shouldn't even compare your work to that crap.

> Playing the game in 4:3 on original hardware on CRT televisions is still an excellent experience. But if you want to play in HD and/or widescreen we want to provide a version that pays respect to this masterpiece, along with going beyond-scope and improving additional aspects of the game where feasibly possible.

There are some 16:9 CRT monitors capable of very high resolutions, like this: https://www.cnet.com/products/samsung-syncmaster-900-nf-pg19nsbu/specs/
This monitor support a max resolution of 2048x1536p @ 60hzin RGB-limited or 2048x1536i @ 60hz in RGB-Full (on CRT both progressive and interlaced signals are displayed perfectly).
You can't find a similar image quality on modern Tvs/monitors. 

I have a excellent 4:3 CRT monitor capable of pretty high resolution. SH2 render surprisingly well on that monitor, colors are natural, vivid, vibrant. Only Top Plasma tvs can stand a comparison. Even on this monitor the EE is much better than the vanilla, since I can go beyond 1024x760 resolution, and all the other video/audio improvements.
This mod makes the PC version much better to play on any kind of monitor

> If/when we can use DSOAL the audio will give you goosebumps if you use headphones with SH2:EE. But again, this will be some time out.

I'm looking forward to it. Btw I tested more carefully, I think the surround is actually present, just less marked than on Ps2. 
Activating the "spatial audio" for headset on windows doesn't make a noticeable difference. Maybe I'll try the Dolby Atmos for headphone... But I guess these external programs cannot be of help.
