### ISSUE TITLE
Silent Hill 2 EE Random Micro Stutter in Town\FMV

### ISSUE THREAD

**Issue by Kazama84** [elishacloud/Silent-Hill-2-Enhancements#182]
Hello, i've installed the enhancements following your guide; I've got some weird random microstutter here and there throughout the game only when in outside location and FMV. It's some random but annoying hiccups. During internal location they never happen though.

Here is my d3d8 log file
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3770047/d3d8.log)

**Comment by Polymega** [comment]
Hi there, 

If you're experience stutters while only out in the town it's likely that the Fog Fix is slowing down your computer. Reduce the values (intensity) of the Fog Fix settings or set `Nemesis2000FogFix =` to `0` to fully disable the Fog Fix in the `d3d8.ini` file. Disabling the Fog Fix will revert the game to using the vanilla fog effects.

In regards to stuttering during FMVs, it might be due to ReShade. More specifically: The SMAA filter within ReShade. Trying setting `d3d8to9 = 0` in the `d3d8.ini` file to fully disable ReShade and see if the stuttering is resolved for the FMVs. You may want to try this first to see if it helps you with performance during any fog rendering, too. 

You can check out other troubleshooting tips/suggestions here: 
http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm

**Comment by Polymega** [comment]
Hmm... Yeah that's not normal behavior. Your graphics card is beyond up to the task for this game.

ReShade can often be the culprit for any hiccups like this. To be sure: You actually set `d3d8to9 = 0` in the `d3d8.ini` and didn't just press F12 in-game to disable the filters? (Disabling the filters in-game doesn't actually disable ReShade.)

I don't have any other ideas/suggestions off the top of my head, but I'll let you know if any thing else comes to mind for me later on.

**Comment by Kazama84** [comment]
Thanks for the replies, i've managed to alleviate this stutter moving the SH2 installation folder on a primary SSD; Launching the game from SSD this hiccups are far more reasonable. It could be something wrong with my secondary mechanical hard drive? it's a seagate barracuda 7200RPM (crystal disk says condition Good)or maybe swap primary\secondary hard drive?
