### ISSUE TITLE
The enhancements dont seem to take effect.

### ISSUE THREAD

**Issue by arkey123** [elishacloud/Silent-Hill-2-Enhancements#184]
Everything runs fine and launches, but the game itself looks gray and almost like there is a static filter shade. I've tried changing the native resolutions, tried the troubleshooting where you need to set window  mode to 0 and vice versa. Game just looks gray and nothing like the video, I have followed the steps again with all the files and reShade but nothing... help.... (edit: im running directors cut)

**Comment by arkey123** [comment]
![sh2pc 2019-11-04 00-02-43](https://user-images.githubusercontent.com/57319203/68085605-c67ad900-fe96-11e9-825d-a708b56a084e.png)
![sh2pc 2019-11-04 00-02-46](https://user-images.githubusercontent.com/57319203/68085606-c67ad900-fe96-11e9-8813-4ee8be789005.png)
![sh2pc 2019-11-04 00-02-31](https://user-images.githubusercontent.com/57319203/68085607-c67ad900-fe96-11e9-82ec-82df2d87b5be.png)

**Comment by arkey123** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3801586/d3d8.log)

**Comment by Polymega** [comment]
Hi @arkey123 ,

Your visuals are actually completely fine! When you enable the noise filter, blacks are no longer true black because of the gray-ish noise grain that sits on top of it. 

Why is the noise grain gray-ish as opposed to something like black? Because if the noise grain were black you'd never see it on top of the many dark/black areas of the game. 

Here's screen captures from my game:

![sh2pc 2019-11-03 12-11-00](https://user-images.githubusercontent.com/27395260/68089067-3fe0e000-fe33-11e9-9def-af2984deb979.png)
![sh2pc 2019-11-03 12-11-09](https://user-images.githubusercontent.com/27395260/68089068-3fe0e000-fe33-11e9-9080-1091a4a8c2c2.png)

Notice when I disable the noise filter blacks are more, well, black!

**Comment by Polymega** [comment]
Here's an old comparison page I made of the noise filter (against PS2 filter): 
http://enhanced.townofsilenthill.com/SH2/comparisons/noisefilter.htm

**Comment by arkey123** [comment]
Ohhhh.... That's makes sense, thanks for that @Polymega
