### ISSUE TITLE
Resolution won't go to 1080x1920, only 1200x1600?

### ISSUE THREAD

**Issue by blondroid** [elishacloud/Silent-Hill-2-Enhancements#186]
I have no idea what is going on. Things worked perfectly a few months ago, (June) then I installed the new update and it isn't working anymore.  First I was getting crashes on startup. 

Even though I had the Safe Mode Disable turned on, the program still starts in safemode and the graphics got reverted to small resolutions with the larger options gone. 

 I deleted everything and tried a clean install of the entire game and the Enhanced Edition mods, step by step, and now it won't let me go higher than 1200x1600, and the text looks much lower rez than it should. I triple and quadruple checked my monitor's resolution and it is set to 1080p. X and Y rez are set to 0 in the .ini. 

Help please?

[d3d9.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3812230/d3d9.log)
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3812231/d3d8.log)

**Comment by Polymega** [comment]
> First I was getting crashes on startup.

Be sure to update **both** the SH2 Enhancements module (which you've done) and the [Enhanced Edition Essential Files](http://enhanced.townofsilenthill.com/SH2/#installEssentialFiles). 

One of the features of the latest public update of the SH2 Enhancement module requires the `ext_str.txt` file to be found/located in `<path-to-game>\Silent Hill 2\sh2e\text\` in order to launch correct. The `exe_str.txt` file can be found in the Enhanced Edition Essential Files download. 

In the next update, there will be a fail-safe check for this fix. In that, if it can't detect the `exe_str.txt` file, it'll ignore that fix and continue to launch as normal. 

> I deleted everything and tried a clean install of the entire game and the Enhanced Edition mods, step by step, and now it won't let me go higher than 1200x1600, and the text looks much lower rez than it should.

This is because the Widescreen Fix module (integrated into the SH2 Enhancements module) isn't taking effect. This is likely due to the issue I mentioned above. 

Try and do my suggestion above first to see if that alleviates your issue. Also note that the resolution shown/displayed in the game's options menu won't be won't you're using in `ResX` and `ResY`, found within the `d3d8.ini` file. And if you try and change the resolution through the game's options menu, it'll crash the game. 

In the next update, the game's options menu will show the true resolution you are using and also prevent you from changing it in-game: https://twitter.com/WhereAllBegins/status/1142898738597421059

**Comment by blondroid** [comment]
That seems to have fixed it. My issue was that I accidentally installed the old version of the Essential Files that I still had saved.

Thank you so much!!! I am very grateful

Another quick question: does the current version allow for further enhancement via the nVidia control panel with anti-aliasing and anistropic filtering? I know that used to cause glitches, but I don't see anything about needing to disable it anymore.

**Comment by Polymega** [comment]
> My issue was that I accidentally installed the old version of the Essential Files that I still had saved.

Great! We've included a project changelog so you can see at a glance when an enhancement package has been updated: http://enhanced.townofsilenthill.com/SH2/#changelog

Also consider following us on [Twitter](https://twitter.com/WhereAllBegins) and [YouTube](https://www.youtube.com/user/WhereAllBegins) to keep up with updates.
