### ISSUE TITLE
Always play game load/save sound in respective menus.

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#209]
Something maybe for a future update, which mimics SH3 PC's approach to it:

The "game load" sound effect only plays to full completion when starting a new game/loading a game from the main menu. The game load sound does play, but will get cut off short if you load a save from the PC pause menu.

The "save sound" will only play when interacting with a red save square, and will not play at all if you choose to save your game from the PC pause menu. 

It would be a nice touch to restore these sounds, and have them play fully, even when saving/loading from the PC pause menu, as what SH3 PC does.

**Comment by Polymega** [comment]
@elishacloud @bigmanjapan

Setting 0249C8B8 byte to 1 while in-game will provoke the "game load" SFX, but it only loops the first second infinitely while the value is 1. 0249C8BC byte also seems to be linked/associated with 0249C8B8.

If I find other addresses which I think might be relevant I'll edit this post or make a new one.

**Comment by Polymega** [comment]
@TheMachineAmbassador
Thanks for taking an interest here. :)

I hope it'd be a relatively straightforward solution of finding the instructions that call the save sound when interacting with a red square and using these instructions when triggering the save menu through the PC pause menu.

You'll just want to ensure that what you're changing is for when you pull up the save screen via the PC pause menu vs. interacting with a red square.

If it helps, we already have a variable made for [00932178](https://github.com/JokieW/SilentHillDatabase/blob/master/SH2/SH2%20PC%20memory%20addresses#L36) called `EventIndexAddr` that you can see here: 
- https://github.com/JokieW/SilentHillDatabase/blob/master/SH2/SH2%20PC%20memory%20addresses#L36-L50

**Comment by TheMachineAmbassador** [comment]
I guess i found interesting thing in this memory 0x48c1d0. When you trigger red square save thing you trigger this function and this trigger function calls sound manager function 0x48c301.
![sound_id](https://user-images.githubusercontent.com/77938614/155433748-cc18dc90-3a27-4d03-8094-8343954373d0.png)
If you change this push 2743 (2743 is sound id i guess. e.g. 2744 is door open id) it changes sound. Now i'll search for the pause menu sound manager and if i compare menu buton index with save game buttons id i can change sound id with the red square save sound's id or maybe i can find more interesting things in pause menu save function that doesn't need to change any id :)

**Comment by TheMachineAmbassador** [comment]
I've found the puase menu's save sound manager aswell 0040282e but thing is this value affects whole sound in the pause menu. So as i said above i found the pause menu's button index value and compared with value of save game and changed the value of sound id when it's true. Also i did a simple cheat engine script to test it. [simple_script.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8129061/simple_script.zip).

**Comment by Polymega** [comment]
Excellent work, MachineAmbassador! I spammed the hell out of the save screen and the sound played every time without issue. 

Would you like to make a pull request for this change or would you prefer sharing your assembly code here once you have everything finalized? If you'd like to make a PR for this fix, please note that we'll need to make this fix work across all three SH2 PC executables. Elisha can provide more info about this and I can send you these binaries if you need them for testing.

@elishacloud 
I should point out that, in MachineAmbassador's fix here, `009326B4` (Pause menu button index) is a new address that is also needed to be used for an addendum for `GameLoadFix` which you can find here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/118#issuecomment-830336713

**Comment by nipkownix** [comment]
Very nice! Let me know if you need any help implementing the fix.

**Comment by TheMachineAmbassador** [comment]
> Very nice! Let me know if you need any help implementing the fix.

Thank you so much :)

> Would you like to make a pull request for this change or would you prefer sharing your assembly code here once you have everything finalized? If you'd like to make a PR for this fix, please note that we'll need to make this fix work across all three SH2 PC executables. 

When i turn back from job i will look at "game load" issue. I guess i was found the where the issue is but had to go job :)

> Elisha can provide more info about this and I can send you these binaries if you need them for testing.

Yeah I might need binaries. After i solve the issues i will need latest code to share with you aswell or i can pull request the fix if you want to.

**Comment by Polymega** [comment]
> Yeah I might need binaries.

Sure thing. Here you are: http://www.igotaletter.com/temp/sh2pc/_Original_No_CD_Executables.zip

> After i solve the issues i will need latest code to share with you aswell or i can pull request the fix if you want to.

Yeah, whatever you like! For the project, there a two approaches to make fixes work across all binaries. Elisha and/or nipkow can explain how to do that. Or if you'd prefer to provide your changes here in this ticket for the NA v1.0 executable we can then make the code work on all binaries for you.

> When i turn back from job i will look at "game load" issue. I guess i was found the where issue is but had to go job :)

Oh, nice!

Just to warn you: I can't remember where we talked about this, but _I think_ it might be impossible to preserve the "game load" SFX when loading a save file while in-game. I think we determined that, when loading a save file in-game, the game has to terminate all previous audio in order for it to load the new audio at the selected save point. Since the "game start" SFX starts _before_ the game terminates audio, it also gets terminated with it.

When you start a new game or select a save file from the main menu, it does not have to terminate any audio (since no audio plays on the main menu), which is why the "game start" SFX can play to completion from here.

**Comment by AeroWidescreen** [comment]
> When you start a new game or select a save file from the main menu, it does not have to terminate any audio (since no audio plays on the main menu), which is why the "game load" SFX can play to completion from here.

Yup, I remember this. I think we also concluded that the addition of the quick save / quick load feature was poorly done and is often the root of many problems. If I had it my way I would remove those options entirely, but I know the majority of people would be upset about that.

**Comment by Polymega** [comment]
> If I had it my way I would remove those options entirely, but I know the majority of people would be upset about that.

I feel your frustration here, as probably +50% of all our fixes relate to the save/load anywhere feature in some way, but it's too useful to remove. Could you imagine how much harder/slower overall project work would be if we didn't have this feature? And for better or worse, in the modern landscape of gaming, this is an incredible convenience feature to have (so much so that Team Silent mimicked it themselves for SH3 PC).

**Comment by TheMachineAmbassador** [comment]
That will be pretty challenging :). I said i found something but that didn't fix the issue. Currently i'm trying to find where or how the game cuts the sound but i guess there is no function kinda like "cut the music" when loaded. Maybe it's just deletes the memory and loads new sounds. Is there any problem on ps2 version like that?

**Comment by TheMachineAmbassador** [comment]
> Bigmanjapan found an address that may be relevant to what you're looking for [found here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/47#issuecomment-809132880). The issue/concern is that the game very likely _needs_ to kill the audio in order to load the new audio from a loaded save point.

Yeah you're totally right i tried everything and searched everywhere but didn't work. As you said there is no audio control mechanism or something like that. When you load a save the game literally kills every sounds in game i guess. Now i'm working on programming the "Save Game" button and it works for the 1.0 version already. But is there any rules about programming style ? Because i'm on the half way i can change if i made something wrong.

**Comment by Polymega** [comment]
> But is there any rules about programming style ?

I'm not a programmer so I may not be providing all the info (or correct info) needed, but from my understanding, there's two ways to search for addresses across all three binaries. 

1. This module's method. Example: https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/285109b14782254807d61c015ac37fa386175e5b#diff-1523f81c0cccc077e46eb515b90b611134b7715b2968d11cbe8e3790aab1654cR45-R46

2. The Widescreen Fixes Pack method, where you find similar byte patterns for the address(es) across all three binaries and use that to apply the fix across the board. Example: https://github.com/elishacloud/Silent-Hill-2-Enhancements/pull/491/commits/17a69920dfd7fd5b8049e198be055c78206ef832#diff-d4662335816c2d1d395168e8c544e6305098cde7e8661399dc254338f10780f8R60

Elisha, Aero_, and/or nipkow can hopefully provide more details about either of these methods, if needed. 

Or, if you'd prefer, we can take your Cheat Engine script fix for the 1.0 executable and integrate it into the project for you.

**Comment by TheMachineAmbassador** [comment]
Program seems close to ready but there are still some issues. Game doesen't play "Save Game" sound effect at first level (new game) until other sound effect stops if you quickly press the "Save Game" button again.
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8148107/d3d8.zip)

**Comment by TheMachineAmbassador** [comment]
That issue is fixed!!!
[Release.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8148990/Release.zip)

**Comment by Polymega** [comment]
Nice! I did a quick test and noticed a bug where all the other selections through the PC pause menu are now playing the "back" SFX when they're selected:

https://user-images.githubusercontent.com/27395260/155898455-6a0e03a7-7db1-4f31-b1b3-28ba1ad58a67.mp4

**Comment by TheMachineAmbassador** [comment]
Ah sorry :) I accidentally set the push value to 2713 (back sound id). now it's really fixed i guess :))) 
[Release.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8149401/Release.zip)

**Comment by Polymega** [comment]
No worries! I didn't do an extensive/full playthrough to test, but I did test the pause menu for all binaries and everything seems to be working just fine. Beautiful work here, MachineAmbassador! Thank you very much for your time, help, and expertise on this matter!

**Comment by TheMachineAmbassador** [comment]
You're welcome. I was a bit lucky when no functions use "Pause menu button index" for other button menus. Only when you pause game this value starts. If this value used anywhere else it could be more challenging. I will PR the code after my check is done.

**Comment by TheMachineAmbassador** [comment]
I completed the project and send the pull request. Is there anything else i can help ?

**Comment by Polymega** [comment]
You're awesome!

> Is there anything else i can help ?

Thank you for offering to help elsewhere and taking an initiative here. :) I looked over our project's "to-do" list and, while there's not much left on the list, there are some things left which are pretty challenging. If any of these interest you please let us know!

------------------

### Remove the momentary "pause/stutter" during in-game cutscenes that happens when the game loads a dialogue audio file.

This is an issue that also affects the Xbox version of the game. Whenever the game calls dialogue audio for an in-game cutscene, it'll momentarily "freeze" the game. For example: When James exits the beginning bathroom, the game will momentarily freeze as soon as he passes the telephone pole (when Mary begins to speak).

- No ticket has been made for this yet

-------------------

### Have the game run stable on multiple cores. AKA fix the infamous sound looping issue for the game.

A crowning achievement for the game, just like restoring soft shadows or PS2 audio. The ultimate goal here is to have the game run stable on multiple cores **without it using significantly more CPU resources than what the vanilla game would use on multiple cores.** 

   - https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/423
 
-------------------

### Fix the audio bug of the final boss moth attack.

I don't think this relates to the sound loop issue mentioned above. Please see the ticket link below. This is important to try and fix because it otherwise totally ruins the final moments of the game.

- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/424

---------------------

### Game-wide mouse support?

This would be a nice bonus for the project--it's something that's not critical to have. You can already use the mouse when interacting with menus (inventory, main menu, save/load screen) and riddle images (such as combo locks), but you cannot use the mouse during normal gameplay.

It would be cool to do something like what SH3 PC does:

- Mouse left/right: Turn character
- Left click: Action
- Right click: Ready weapon
- Mouse wheel: Cycle weapons

But again, this isn't expected or needed for the project. It would be a cool bonus feature is all.

- No ticket has been made for this yet

**Comment by Polymega** [comment]
### Fix mouse selection for 3-choice Command window.

It's safe to assume most people don't use the mouse for navigating the inventory screen, so this is not important to fix. To be honest, it's something I've always known about but never brought up. I figure I'd mention it since both you and nipkow have been working with the game's menus recently.

Mouse support does not work for any item that has three selections in the "Command" box. It will work for one or two selections, but not three.

![Screenshot 2022-02-27 22-21-42](https://user-images.githubusercontent.com/27395260/155918768-97147448-9ee1-4ee1-b0b5-457959df0b8f.png)

**Comment by TheMachineAmbassador** [comment]
> It's safe to assume most people don't use the mouse for navigating the inventory screen, so this is not important to fix.

I didn't even noticed there is a mouse support in the inventory :) I don't why but i think these 3 issues are related to the game only uses single cpu core. If we can run this game on multiple core maybe too many problem would be solved but of course that is the most hardest one.

> Remove the momentary "pause/stutter" during in-game cutscenes that happens when the game loads a dialogue audio file.

I can start with first or and especially that third one. That sound glitch I don't know if it was related to that problem but that is broke my save file i guess. I was trying to get 10 star for green spray and when i came to the last boss i had that bug too
 after finished the game i got my 10 star save but when i get back to the menu and load 10 star save file game said "Unable to load saved game". That because why i wanted to make a save editor (stupid RNG's but i made Result Changer it does the same job) :))) I hate that problem i want to start with that but i will need a save file for that. I think i can put it in second place because its a rare problem.

**Comment by Polymega** [comment]
> but i think these 3 issues are related to the game only uses single cpu core. If we can run this game on multiple core maybe too many problem would be solved but of course that is the most hardest one.

For a while I thought the momentary stutter when audio first plays during cutscenes was related to this, but it also happens when you play the game on multiple cores. Not only that, but it also happens on the Xbox version. I don't believe the Xbox ran on a single CPU core? I think this is a quirk when Team Silent ported the game over to Xbox (which the PC port is based on).

As for the glitched final boss moth attack SFX: This one is hard for me to tell whether or not it relates to the multicore issue. It doesn't help that I've had a hard time consistently provoking this bug...

> I hate that problem i want to start with that but i will need a save file for that. I think i can put it in second place because its a rare problem. So i will start with the sluttering problem.

Sweet! Thank you. Also, here's a list of save points throughout the entire game. It's useful to have when testing any fix: www.igotaletter.com/temp/sh2pc/General_Saves.zip

> I was trying to get 10 star for green spray

I recently ~~unlocked~~ modded all the sprays for my own testing. You can download the save files for all the Hyper Spray variants below. Read the "ReadMe" inside the save folder: www.igotaletter.com/temp/sh2pc/SH2_PC_All_Hyper_Sprays.zip

![image](https://user-images.githubusercontent.com/27395260/156058924-020fc4b9-5f82-4bca-9fb7-f1145861d6f1.png)

**Comment by TheMachineAmbassador** [comment]
> Sweet! Thank you. Also, here's a list of save points throughout the entire game. It's useful to have when testing any fix: [www.igotaletter.com/temp/sh2pc/General_Saves.zip](http://www.igotaletter.com/temp/sh2pc/General_Saves.zip)

Thanks for the save files that will definetly help me to find issues more quickly.

> For a while I thought the momentary stutter when audio first plays during cutscenes was related to this, but it also happens when you play the game on multiple cores. Not only that, but it also happens on the Xbox version. I don't believe the Xbox ran on a single CPU core? I think this is a quirk when Team Silent ported the game over to Xbox (which the PC port is based on).
> As for the glitched final boss moth attack SFX: This one is hard for me to tell whether or not it relates to the multicore issue. It doesn't help that I've had a hard time consistently provoking this bug...

At first i thought it's a cpu problem because that is general problem but after digging game i found some useful information about the issue. Stuttering problem can be related of the voice.afs files size. Because game starts the "read sound file" function at the point when mary begins speaking and file size is too big for like this process.
![Proc-mon](https://user-images.githubusercontent.com/77938614/156067530-4bb5d576-bdc8-4241-8a45-0dea6b49167f.png)
I don't know is game keeps the sound data in the RAM but if it's not so we have to think a way to load sound data in RAM while at the loading screen. That way can increase loading speed but totally decreases loading sound data but of course that way is pretty hard (impossible actually) and i hope we won't need that way :).

![readSoundData](https://user-images.githubusercontent.com/77938614/156070428-7957bd62-b5c3-4f04-bc05-7bf43ca8bb12.png)
Also i found this thing (0x0056872e). When the game needs to load a sound data calls this function and i think this is related to sound looping and stuttering problem. Because when i right click on the call value and NOP data before Mary speaks it will freeze at that load sound point (if you restore that NOP the game continues kinda like that stuttering problem) and if you NOP this in a random place games sound starts looping. I think the game was trying to be RAM friendly so that it would run on all computers in that years but problem is for that process game still needs a nice cpu :)

![error_Handler](https://user-images.githubusercontent.com/77938614/156071140-cd6b3029-7796-4ed9-a2fe-6d6e3c214814.png)

But of course that things i said is just a theory and i have to prove them :). And i guess i found pretty nice memory address inside that function.  "0x2493300" is used for when there is a problem while reading sound file and game writes the error to this memory and outputs this value to the console (but of course we don't have a console). If the sound loop problem in the game is the cause of the file read error maybe it can help us to find the problem. So I'm going to make a simple program to output the error to a text file and will try to trigger that sound looping issue.

**Comment by Polymega** [comment]
> Stuttering problem can be related of the voice.afs files size. 

Yeah, that's what I figured. Since all dialogue files are stored in that one container, the game has to load _the whole thing_ each time to find/call the audio file it needs. If I recall correctly, I believe SH2 PS2 uses the same voice.afs container that is rougly the same in file size. Not that it matters, but I wonder why there's no momentary stutter on that version... 🤔

> "0x2493300" is used for when there is a problem while reading sound file and game writes the error to this memory and outputs this value to the console (but of course we don't have a console). [...] So I'm going to make a simple program to output the error to a text file...

Wow! Great discovery and great thinking on this! 

> ...and will try to trigger that sound looping issue.

All you have to do is play the game without using the single core affinity fix and the sound loop bug will typically happen within 30-60 seconds. 😅

**Comment by TheMachineAmbassador** [comment]
> Yeah, that's what I figured. Since all dialogue files are stored in that one container, the game has to load _the whole thing_ each time to find/call the audio file it needs. If I recall correctly, I believe SH2 PS2 uses the same voice.afs container that is rougly the same in file size. Not that it matters, but I wonder why there's no momentary stutter on that version... 🤔

I kept asking myself that questing aswell :) i mean even if the problem is game loading sound data from hard drive how ps2 dvd can be fast from my ssd :). ps2 only have 32 mb ram they should read data from dvd already but still works better than pc! Maybe problem is on porting issue ( we trying to fix that issues already :) ) or OS problem. I wonder how sh3 manages sound. Is there a 1.5 gb file to read like sh2. I mean when i play sh3 port it was nearly perfect of course there was some issues but it wasn't like sh2.

> Wow! Great discovery and great thinking on this!

>> ...and will try to trigger that sound looping issue.

> All you have to do is play the game without using the single core affinity fix and the sound loop bug will typically happen within 30-60 seconds. 😅

Unfortunately that didn't work at least i tried :) İlk başta oyunun ses efektini okumadığını sadece hafızada kendini tekrar ediyor diye düşündüm, but game is already completed reading the sound file it just repeats the sound effect. Thanfully i guess i found something that can trigger "sound looping" issue. I guess i found the memory address of 4 sound effects (music, sound effects from monsters, gun sound, and other sound effects like when loading a game or something random things ) in game. we know the sound effect from monsters is problematic one. So i will look at that and of course if its true i will share addresses in here that can help us to fix  "game load" sound effect issue (of course that seems impossible but i still want to fix that :) ).

**Comment by Polymega** [comment]
This request has been added through this PR: https://github.com/elishacloud/Silent-Hill-2-Enhancements/pull/493

Thanks, Machine Ambassador!
