### ISSUE TITLE
2 Issues Im having

### ISSUE THREAD

**Issue by SUCK-my-DUCK** [elishacloud/Silent-Hill-2-Enhancements#213]
Hi there,

I started setting everything up today (note: Im also not an expert when it comes to sth like this :p) and Im having the following issues now: 1. The game doesnt boot up at all/ doesnt load the reshade filters when my controler is plugged in (ds4). 2. james cant turn while running. He can only run forward and thats it. Can u guys help me out? 

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4200043/d3d8.log)

**Comment by Polymega** [comment]
Hi there,
Looking at your `d3d8.log` file, I would recommend **removing** the ReShade files from the game's directory, as ReShade is typically too demanding for integrated graphics cards.

As for your controller: DualShock 4 controllers are treated as DirectInput gamepads on Windows. Remove the XInput Plus file from the game's directory if you are using them. XInput Plus is needed for XInput gamepads, but not for DirectInput gamepads.

If you are using rotational (3D) control types, pressing up will always have James run forward in the direction his body is facing.

**Comment by Polymega** [comment]
Also, if you're using something like DS4Windows for your DualShock 4 while also playing the game, ensure that software isn't creating controller input conflicts.

Try playing the game without something like DS4Windows or Joy2Key to see if that fixes your movement problem.

**Comment by SUCK-my-DUCK** [comment]
I tried the movement problem with the keyboard and the 3D control setting seems to be the issue like u said so that should be no problem. 

I also launch the game with the nvidia graphic card my laptop has and not the integrated graphic card. 

XInput Files are not used. Also it doesnt matter if I use DS4Windows or not, once my controler is connected the game just doesnt work. I cant get to the main menu at all.

**Comment by Polymega** [comment]
> I also launch the game with the nvidia graphic card my laptop has and not the integrated graphic card.
We've had issues before with people who are using laptops that can switch between a dedicated and integrated graphics options. 

In your log file, it says you're using your integrated graphics when launching the game. This is likely the reason why it would hang on launch when also using ReShade. 

If you can get the game to launch using your dedicated Nvidia GPU then it should probably launch with ReShade. Otherwise, you can forgo (remove) ReShade and just play without it.

> Also it doesnt matter if I use DS4Windows or not, once my controler is connected the game just doesnt work. I cant get to the main menu at all.

Try this, copy + pasted from the troubleshooting portion of the website:

Silent Hill 2 PC detects and uses the first gamepad you connect to your computer. Disconnect any other gamepads or similar peripherals that are already connected to your PC. This may include wireless dongles/receivers or non-controller gaming peripherals that are detected as gamepads by your PC. This is the most common reason why the game does not detect the gamepad.

**Comment by SUCK-my-DUCK** [comment]
ok so because Im using a surface book my keyboard is being detected first. well that really sucks :p at least I know what the issue is now :D

**Comment by Polymega** [comment]
Interesting, as my Surface Pro 3 allows the detachable keyboard to stay connected and I can still use a controller. (Granted, I've only tested Xbox controllers on my Surface.)

Perhaps one day we can have the game listen/use any/all input device it detects, so users won't have to fight this arcane, early 2000s requirement. Until that time, I'm glad you got it figured out!

**Comment by SUCK-my-DUCK** [comment]
yup. hope we find a solution for this soon :D thx for your help :)

**Comment by SUCK-my-DUCK** [comment]
I could still play the game if Id use a xbox controler right?

**Comment by Polymega** [comment]
Yes. You can follow the steps for Xbox controllers here: 
http://enhanced.townofsilenthill.com/SH2/#controllerSetup

Xbox controllers work best with Windows because Microsoft makes both Windows and Xbox, so compatibility is best for them.

DualShock 2 & 3 have no inherent driver support on Windows,[ and DualShock 4 isn't as well supported by Sony on Windows](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/168) (likely due to Microsoft being a competitor of their's).

**Comment by Badore90** [comment]
> Looking at your d3d8.log file, I would recommend removing the ReShade files from the game's directory, as ReShade is typically too demanding for integrated graphics cards.

I'd suggest to try using Re-shade, disabling just the two AA filters. Enabling only DPX and Levels (I do so on my PC with the integrated GPU).
This way you can play with correct/Ps2 like color levels that affect all the environment and noise filter.

**Comment by SUCK-my-DUCK** [comment]
> Interesting, as my Surface Pro 3 allows the detachable keyboard to stay connected and I can still use a controller. (Granted, I've only tested Xbox controllers on my Surface.)
> 
> Perhaps one day we can have the game listen/use any/all input device it detects, so users won't have to fight this arcane, early 2000s requirement. Until that time, I'm glad you got it figured out!
> 
> **Edit:** That probably is it. The detachable keyboard is detected as an external HID device, and the other week I learned DualShock 4 controllers are _actually_ detected as external HID devices (and not truly DirectInput gamepads). That makes sense why the removable keyboard is creating conflict with that particular controller.

Hey there again,

I'm playing the game currently and I got another problem: the cutscenes desync. The fmvs cant keep up with the sound. Any idea how this happens and how I can solve this?

**Comment by Polymega** [comment]
You probably have the same issue as me on my Surface Pro 3 [and this user on their Surface Pro 6](https://www.resetera.com/threads/silent-hill-2-enhanced-edition-trailer-fan-mod-feb-13-2020-update-4-now-released.63926/page-3#post-29119582).

Simply put: ReShade is too demanding for your Surface computer, when running the game on integrated graphics.

**To fix this:** Disable ReShade by doing one of the following:
- Press **F12** in-game to disable the ReShade filter.
- **Permanent solution:** Remove the following files/folders from the game's directory:
```
reshade-shaders\
d3d9.dll
d3d9.log
ReShade.ini
ReShade_sh2pc.ini
```

**Comment by SUCK-my-DUCK** [comment]
I actually removed the reshader but its still happening. Ill try the F12 option but that propably wont change it either. Ill let you know.

**Comment by Polymega** [comment]
That ought to be the reason why. Also, to be sure: You haven't adjusted the framerate for the game any, have you?

**Comment by SUCK-my-DUCK** [comment]
Nope I didnt do anything with the framerate. Cutscenes are still somewhat our of sync.

**Comment by Polymega** [comment]
If it's only _slightly_ desynced it may very well be how the videos inherently are. Lip syncing, in both the FMVs and in-game cutscenes, isn't completely perfect in any version of the game. 

Is the desync very bad?

**Comment by SUCK-my-DUCK** [comment]
I actually fixxed ir by setting the SingleCoraAffinity or whatever it was to 2

**Comment by Polymega** [comment]
Great! Glad to hear you have it sorted out.

**Comment by elishacloud** [comment]
> I actually fixxed ir by setting the SingleCoraAffinity or whatever it was to 2

I was thinking about setting this to `2` by default.  The reason is that many programs default to using the first CPU.  This means that the first CPU could already be busy from other applications.  This can cause issues with Silent Hill 2 note getting enough CPU time.  Having Silent Hill2 default to a different CPU reduces the risk of other programs interfering with it.  I also have this set to `2` on my computer.

Next update will default this to using the second CPU core: 4231a694b8542f51c987c139431f475cf36640a3

**Comment by Polymega** [comment]
I often change it to non-1 as well. Good call on this decision.

**Comment by elishacloud** [comment]
Closing this out.  This will be updated in the next release.
