### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by clowncontrol** [elishacloud/Silent-Hill-2-Enhancements#218]
followed installation instructions exactly and now neither exes will launch the game, my directory tree is the exact same as the one you have on the site. There are no error messages, nothing happens after I run either exes even in admin mode

**Comment by Polymega** [comment]
When you tried to launch the game, did it create a `d3d8.log` file in the game's directory? If so, please attach it. 

Can you send a screenshot of your game's installation directory anyways? We need something to try and work off of.

**Comment by clowncontrol** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4208875/d3d8.log)
![Silent Hills](https://user-images.githubusercontent.com/61092137/74593429-d905c200-4ff0-11ea-91b1-728d28b094fb.PNG)
![inside sh2e](https://user-images.githubusercontent.com/61092137/74593431-dd31df80-4ff0-11ea-9133-151944a4f44c.PNG)
Have a look, thanks for your help

**Comment by Polymega** [comment]
Thanks for the screenshots (and showing all file type extensions; it makes things easier). 

I noticed you have no `dsound.log` file, which tells me IndirectSound did not launch along with the game, which might explain the issues you're having. 

If using IndirectSound, ensure you have also downloaded the [Microsoft Visual C++ 2010 Redistributable Package (x86).](https://www.microsoft.com/en-us/download/details.aspx?id=5555)

If that doesn't fix it, try temporarily **removing** `dsound.dll` from the game's directory, just to see if the game will then launch for you.

**Comment by clowncontrol** [comment]
removed dsound and the exes still wouldnt run

**Comment by Polymega** [comment]
Oh, this is probably why. I didn't pay attention to this in your `d3d8.log` file before. Your game is saved in this path:

`C:\Users\pumpk\OneDrive\Desktop\Arcade\Silent.Hill.2.Directors.Cut.PC.Game(djDEVASTATE™)\Silent.Hill.2.Directors.Cut.PC.Game(djDEVASTATE™)\Silent Hill 2\d3d8.ini`

This pirated copy of SH2 PC will cause issue simply because of the "™" in the folder name. [More info on this here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/179#issuecomment-544001266)

Try moving the game to a more clean/simple directory, without the use of specialized characters in the directory path such as "™".

**Comment by elishacloud** [comment]
@clowncontrol, can you try with this update: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4302984/d3d8.zip)
