### ISSUE TITLE
Shadows missing after installing update

### ISSUE THREAD

**Issue by LillyBowling** [elishacloud/Silent-Hill-2-Enhancements#227]
After installing the update, no shadows appear even with shadows enabled in options
![Capture](https://user-images.githubusercontent.com/61334309/75077009-609e7580-54b6-11ea-8150-c34f5519bd42.PNG)
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4238300/d3d8.log)

**Comment by Polymega** [comment]
Thank you for the information. 

Have you tried using our patched executable to see if that alleviates the issue?
http://enhanced.townofsilenthill.com/SH2/install.htm#installEnhancedEXE

You can no longer use the executable that came with the game, because it uses SecuROM DRM, [which is now blocked by Windows 10](https://arstechnica.com/gaming/2015/08/windows-10-wont-run-games-with-securom-drm-says-microsoft-2/).

**Comment by LillyBowling** [comment]
Testing it now, I thought that I was already using it.

**Comment by LillyBowling** [comment]
Using the new executable, there are still no shadows and my save games are now gone.

**Comment by Polymega** [comment]
> and my save games are now gone.

Using a different executable should have no affect at all on your save files. Your save files are located at `Silent Hill 2\data\save\Folder 01\`. Unless you delete `Folder 01` (or the contents within it) they should still be there, and save files are cross-compatible with all executable versions.

Can you please attach a new copy of your `d3d8.log` file after trying to run the new executable?

**Comment by LillyBowling** [comment]
The saves were probably my own error. It appears that James is casting a shadow after his monologue.


[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4238350/d3d8.log)

**Comment by Polymega** [comment]
Okay, your new log file is looking better. More of the features/fixes are now being logged in this one. I think part of the problem was using a non-"No CD" executable at first (since Windows 10 essentially blocks SecuROM executables now).

In regards to your save files:
If you installed SH2 PC to an admin-protected directory, such as `Program Files` (which you did), you must run the game as an administrator in order to save your game progress.

We have a feature in our project which checks this and will ask you to run the game as admin if it needs to. However, since you were using the original executable at first, our project wasn't working fully correct with your game. Now that you are using a patched executable, I'm hoping you got the UAC (run as admin) prompt when launching the game. 

So, where did you save files go? [If we look at the PCGamingWiki article for SH2 PC](https://www.pcgamingwiki.com/wiki/Silent_Hill_2:_Director's_Cut#Notes), if you do **not** run the game as admin in an admin-protected directory, all external files which are custom made/adjusted by the game (such as your `options.ini`, `settings.ini`, and save files) will instead be stored in `%LOCALAPPDATA%\VirtualStore\`.

What this means is, if you didn't have any files within `Silent Hill 2\data\save\Folder 01\` before, you should now hopefully have save files in there once you start saving your game again. This is simply a hurdle of old, early 2000's PC games.

However... looking at your new `d3d8.log` file, things like the Fog Fix are not be written/activated. To confirm, did the game ask if you wanted to run as admin on launch now, after using the patched executable?

**Comment by LillyBowling** [comment]
It didn't ask about if I wanted to run it as an admin or not. However I found another install in programfilesx86 which had a copy of my save files.

**Comment by Polymega** [comment]
Okay, that's good. Try saving your game, ensuring shadows are enabled for you (and the shadows are soft in areas where you use the flashlight), and the Fog Fix is working for you. Your `d3d8.log` file will help tell you if things like the Fog Fix are working upon launching/closing the game and re-checking the log file.

**Comment by LillyBowling** [comment]
It seems to be working!
When I launched the game from the Program Files (x86) [I manually launched as admin] install there were shadows that were working and I was able to save the game here is the log 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4238397/d3d8.log)

Strangely when I tried launching the install from Program Files there were no shadows and I had this strange ghosting effect on James 
![image](https://user-images.githubusercontent.com/61334309/75078852-a01b9080-54bb-11ea-92a1-f9ae177891ea.png)

That strangeness aside, I think the solution is to just use the one that seems to work.

**Comment by Polymega** [comment]
Interesting. That shadow bug is exactly the same issue this user was experiencing: https://www.reddit.com/r/silenthill/comments/f5tdj2/just_installed_enhanced_edition_and_now_i_have/

I'm curious to get @elishacloud 's theory on the matter.

My guess might be this:

> When I launched the game from the Program Files (x86) [...] when I tried launching the install from Program Files 

SH2 PC is a 32 bit application and 32 bit applications should be installed to `Program Files (x86)` and not `Program Files`. I wonder if that would cause such an issue with the shadows and other symptoms you were experiencing.

**Comment by Polymega** [comment]
Oh, and also reading over my own notes/suggestions on that Reddit post. Try this as well:

http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#a-burntin-image-appears-during-screen-fade-transitions

We hope to integrate this particular fix into the project for the next update.

**Comment by LillyBowling** [comment]
Thank you!
T
o produce the bug in the Program Files installed application, i had my flashlight off and had just closed the inventory menu.

**Comment by LillyBowling** [comment]
I just tried launching the game using the antialiasing override settings from nvidia, and it created the same problems with shadows that I was experiencing in the non (x86) install. Disabling the nvidia antialiasing made the shadows come back.

**Comment by Polymega** [comment]
Thanks for testing this! So it looks like AA overriding isn't playing nice with the new shadow work. We hope to integrate our own AA solution for the project at a future date, so you wouldn't need to use your GPU's AA overriding, or ReShade.

**Comment by Polymega** [comment]
I was able to replicate the no-shadow thing:

![image](https://user-images.githubusercontent.com/27395260/75098572-dde4eb80-5585-11ea-9de5-f3a4e939e708.png)
(Notice there's no shadows on the wall from the stair handrails.)

This was achieved by removing the ReShade files from the game's directory and then overriding anti-aliasing, as LillyBowling did:

![image](https://user-images.githubusercontent.com/27395260/75098579-fc4ae700-5585-11ea-88dc-22352b36748f.png)

Then, if you pull up the PC pause menu and exit it, what looks to be the "shadow mask" becomes... inverted? This overlays on everything _but_ James, making things like his flashlight dark (as the shadow mask (I'm guessing) now sits on top of the flashlight pass):

![image](https://user-images.githubusercontent.com/27395260/75098594-36b48400-5586-11ea-8e1c-20a38001a6c1.png)

This is also what creates the inverted "after burn" of James' silhouette cut-out on the shadow mask:

![image](https://user-images.githubusercontent.com/27395260/75098613-6bc0d680-5586-11ea-9575-ba5a928c2205.png)
