### ISSUE TITLE
Dialog Build Batch Script Bugs And Fixes 

### ISSUE THREAD

**Issue by MarioTainaka** [elishacloud/Silent-Hill-2-Enhancements#228]
Hello There i'd like to report a few bugs that the conversion tutorial has:

The Batch Script is very bugged and has several issues:

1:The entire part of the script which takes wav files and converts them to ADX and loops them isn't correct.

after conversion and creating the directory it delete the filelist.lst which is used to compare against the afs. this causes files to get messed up even if your file order is correct.

What I suggest is removing this bit and letting the user convert to ADX and loop the files first. Then converting the rest to ADX and merging them.

Next creating a folder called ADX and copying the files in there and running the batch from outside that folder seems to fix all issues

3:Importing wav files or wav files with the .adx extension results in a black screen of death. Here are my modified files. 

The batch file with alot of stuff removed and a file list to look for ADX files instead of wav since those result in a bsod

[Script Fixes.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4242307/Script.Fixes.zip)

**Comment by Polymega** [comment]
Thanks for checking this out! 

> this causes files to get messed up even if your file order is correct.

Can you elaborate on how they get messed up? Does this carry over to in-game performance/behavior of the audio when playing?

**Comment by MarioTainaka** [comment]
@Polymega in game files will appear out of order so for example the continue sound will be a playing cutscene audio instead, loops don't.. well loop properly even though the loops are set up perfectly. the sound will loop on one second endlessly. Weird stuff like that.

**Comment by elishacloud** [comment]
> 1:The entire part of the script which takes wav files and converts them to ADX and loops them isn't correct.

Can you explain more detail what is not correct here?

> after conversion and creating the directory it delete the filelist.lst which is used to compare against the afs. this causes files to get messed up even if your file order is correct.

This is correct.  I delete the `filelist.lst` in case it was left over from the last run.  When I was working on this I used to run this script from the same folder over and over so cleaning up the last run was important for me.  The very first time you run it there is nothing to delete so the line only takes effect the second time you run it.  In that case you don't want the file left over from your last run.

> 3:Importing wav files or wav files with the .adx extension results in a black screen of death. Here are my modified files.

There may be some misunderstanding here.  This script assumes that you only have the WAV files and you want to build a voice.asf file.
1. First step the script does is converts several WAV files into ADX.  Certain files need to be in ADX format for the game to function correctly.
2. Then it renames the WAV files to ADX.  This is done because the WAV format is much better than ADX and the game can handle either format, but is looking for files with a particular name.
3. Then it creates a `filelist.lst` file with the correct order of all the ADX files.
4. Then it imports these files into the blank voice.asf file.

BTW: this script was really created for my own use.  I posted it here in hopes that others would find it useful to them.  I am glad you were able to modify it and get it working for you!  :-)

**Comment by elishacloud** [comment]
Closing this out.
