### ISSUE TITLE
Speaker Config - Stereo Only

### ISSUE THREAD

**Issue by Adore33** [elishacloud/Silent-Hill-2-Enhancements#233]
In the game options under Speaker Config.  I have 9 audio settings to pick from.  I am using Logitech G430 7.1 surround headphones.  This game has a "Surround" option and "7.1" option.  Not sure which one I should be using but I set it to 7.1.  When I apply the setting and come back into options it is always reverted back to Stereo.  In the game it seems like it is surround, or at least panning audio though.  I have also heard that it will apply the correct setting but always show Stereo.  Thanks for any information.

I also looked at my own d3d8.log and noticed...
"Unknown game binary hash: 0479a86b75cdadbf90fedf521d02b630"

Reference files attached...

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4259485/d3d8.log)

![sh2_audio](https://user-images.githubusercontent.com/61531087/75413007-4dded300-58f2-11ea-8f59-ba643965040d.jpg)

**Comment by Adore33** [comment]
I did some more looking into this and testing.  I read on... http://satsun.org/audio/  that Silent Hill uses...

| DirectSound | NT6 | 7.0 | Use ALchemy to restore hardware sound. Says 7.1 but no LFE |

Then I looked in the dsound.ini file I went to the last setting...

milesCompatibility=false and changed it to true.  Now instead of showing Stereo in the games options it says 5.1 Audio.

So maybe "waiting for SH2E devs response" this is a setting that needs to be changed to get surround working through IndirectSound for Silent Hill 2.

**Comment by Polymega** [comment]
Hi there, 

I actually had a chat about this very thing not too long ago with someone else. So I'll copy + paste my info about it here:

> This is a good question, and one I personally don't have the answer to. Even using the vanilla PC version, it will reset back to stereo on change here. I think this option was created for the PC build back when different hardware accelerated cards were on the market, of which they might not be compatible with modern operating systems anymore. I'm not sure.
> 
> Or, your 7.1 audio software/driver needs to be set as the default audio method for your PC in order for the game to detect and use it? I'm honestly not sure. This feature has always been a mystery to me, and assuredly others.
>[...]
>There is a good chance this feature was designed around a particular way older operating systems and/or audio cards worked. If/when we introduce DSOAL to the project, this should be even less of a concern.

As you've discerned, the real way to change the sound stage/presentation for the PC game is to use an audio wrapper (which is what IndirectSound is doing). I would **not** recommend using ALchemy to do this, only because--and I'm going off very old memory here--this audio wrapper either doesn't work for SH2 PC, no longer works with modern operating systems, or no longer works as intended, period.

We will need to create our own built-in audio "pop/click" remover before we can implement it, but, in the future, we plan to integrate DSOAL into the project. I've done early tests with DSOAL and it sounds wonderful. Using headphones, the binaural audio is restored and really immerses you.

And, even with IndirectSound or DSOAL implemented the game will still say... you're using Stereo. So chances are, in a future update, we will simply lock out the speaker configuration selection, the same as what we've done with the screen position selection, to avoid any confusion on the matter. As it doesn't seem to do anything, anyways. Adding an audio wrapper such as DSOAL or IndirectSound is what actually changes the sound stage/presentation.

**Comment by Adore33** [comment]
So you would recommend keeping the IndirectSound settings for milesCompatibility to False?  I am not using a Alchemy wrapper.  Only changed the milesCompatibility setting for IndirectSound.

**Comment by Polymega** [comment]
I haven't dived too deep into all the settings IndirectSound has to offer, so I'm not sure what effect `milesCompatibility` would have on the game. From the description:

>     Many versions of Miles expect a 5.1 rear speaker configuration
>     and may not work with properly with other speaker configurations
>     (e.g. the side speakers in a 7.1 configuration may not be used
>     or no surround will be output for 5.1 or 7.1 home theater configurations).

You can try it out and, if things sound pretty off, you can disable it again.

**Comment by Adore33** [comment]
Ahh ok...

I would agree probably best to leave as is until your mod team can tailor what is needed for SH2s audio.  Thank you for your detailed info and time.  I learned some new stuff.
