### ISSUE TITLE
Blackscreen when soft shadows are enable

### ISSUE THREAD

**Issue by rlsprite** [elishacloud/Silent-Hill-2-Enhancements#238]
When I reach the apartments I get a blackscreen, at first I thought the game hanged/crashed but if I pause I get this:
![8jHL00H](https://user-images.githubusercontent.com/33965548/75619756-51729400-5b56-11ea-94c7-04d60f536a5a.jpg)
James can't be seen for some reason too.

If a press pause again I get a trippy effect:
![Hcpn3Gm](https://user-images.githubusercontent.com/33965548/75619773-8ed72180-5b56-11ea-9298-c517ffd90149.png)

Disabling soft shadows fixes the problem.

I'm not sure why this is happening... My GPU is quite old (AMD HD6950) but should be more than capable in handling SH2.

**Comment by Polymega** [comment]
Can you check and confirm you don't have anti-aliasing force enabled through your AMD GPU control panel? Maybe perhaps as a global setting for all games you play?

While not identical, your issue [sounds similar to this issue](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/227#issuecomment-589994354), which is caused by force enabling AA through a GPU's control panel.

**Comment by rlsprite** [comment]
I totally forgot I had AA forced for the game (for all SH games to be precise xD). Disabling AA solved the issue. Thanks!

**Comment by Polymega** [comment]
Great! I'm glad we were able to pin-point the cause. In regards to the issue: We can maybe try and look into this in the future, so you can then use your GPU's forced AA once more.
