### ISSUE TITLE
BGM loop issue

### ISSUE THREAD

**Issue by Badore90** [elishacloud/Silent-Hill-2-Enhancements#242]
I experienced a loop in the hotel (very annoying, about 1/4 of a second that repeats itself).

I entered this room:

![sh2pc 2020-03-10 21-24-50](https://user-images.githubusercontent.com/44087144/76357090-559d6f00-6317-11ea-8993-9a7a28e115ec.png)

Started to explore a little and when reached here, the loop started:

![sh2pc 2020-03-10 21-24-35](https://user-images.githubusercontent.com/44087144/76357102-5afab980-6317-11ea-9dcc-4cc278c06c19.png)

the loop continued until I exited the game.

I noticed another thing before, when loading another hotel savegame: the BGM only started after about a minute (btw I'm not sure, it could be normal…)

I was using the **@Polymega** save folder. Here the logs:

[d3dlogs.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4314700/d3dlogs.zip)

**Comment by Polymega** [comment]
This is something I can't easily/readily replicate for testing purposes. I'm not sure what to do about it, as it seems to happen rarely and randomly.

- https://twitter.com/Doom_i/status/1230333671384735746
- https://twitter.com/ljosrokk/status/1230478125735325697

**Comment by Badore90** [comment]
> This is something I can't easily/readily replicate for testing purposes. I'm not sure what to do about it, as it seems to happen rarely and randomly.
> 
> https://twitter.com/Doom_i/status/1230333671384735746
> https://twitter.com/ljosrokk/status/1230478125735325697

I think it could be a PC related issue too.  Indeed on this PC I have the delay problem the second time i play FMVs (like the Angela one, in front of the mirror).
It is not related to the game, since I have this problem just playing the FMV with VLC media player outside the game.

Anyway I now set the single core affinity to CPU 2. Doesn't happened any loop so far.

**Comment by Polymega** [comment]
One of the biggest, most beneficial fixes we can now do for the game--since soft shadows are now restored--is "untangle" the games' processes so it can properly utilize all cores of a computer. This would likely also fix things such as the rogue sound looping bug that still happens, along with many other great benefits.

But this would likely be the final, monumentous fix for the project, after everything else is accomplished. Doing such a task would be an incredible undertaking...

> Anyway I now set the single core affinity to CPU 2. Doesn't happened any loop so far.

In the next update, it'll be set to a user's second core by default in the INI, to hopefully reduce the likelihood of audio/visual skipping.
