### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Raziels-Lament** [elishacloud/Silent-Hill-2-Enhancements#253]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4383188/d3d8.log)
The last couple updates I have not been able to play the game. I've fumbled with various settings but the results are always the same. I launch the game and just sit staring at a black screen forever. No errors or other prompts. I just have to kill the process after whatever time I decide to give up on it. I do have a gsync monitor and have disabled that and lowered refresh to 60hz just to be sure that wasn't the hang up but no dice. I'm not to savy on this, please assist.

**Comment by Polymega** [comment]
Have you also been updated the [Essential Files](http://enhanced.townofsilenthill.com/SH2/install.htm#installEssentialFiles) package whenever you update the [SH2 Enhancements](http://enhanced.townofsilenthill.com/SH2/install.htm#installSH2Enhancements) module? I know a few updates ago you must update them both otherwise the game would not launch correctly or at all.

**Comment by Raziels-Lament** [comment]
All updated. I even tried a fresh install. I own the original game CDs I bought years ago when it released for PC in the US. I even tried the abandoware files. I'm assuming it's something to due with my particular configuration I just don't know how to continue troubleshooting.

**Comment by Polymega** [comment]
One thing to test is to launch the game after each step, from a fresh install. So, [following the guide](http://enhanced.townofsilenthill.com/SH2/install.htm):

1. Install the base game. Does it still run? If so:
2. Install the new executable. Does it still run? If so:
3. etc, etc, etc

This way, we could at least determine what specific package is causing the issue.

But before doing all that, what happens if you remove the ReShade files from the game's directory? IIRC, certain GTX cards didn't play nice with ReShade... I think... I'm going off old memory here.

Remove these files from the game's directory:

```
reshade-shaders\
d3d9.dll
d3d9.log
ReShade.ini
ReShade_sh2pc.ini
```

Also, can you confirm [you have no additional, foreign files in the game's directory](http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree) that aren't a part of our project?

**Comment by Raziels-Lament** [comment]
Good call - Same result across the board:

Base game (original exe and CD) -> BLACK SCREEN
Base game (fixed exe from SH2EE site) -> BLACK SCREEN
Complete SH2EE install (skipped d3d8 update) -> BLACK SCREEN
Complete SH2EE install (d3d8 update and restart) -> BLACK SCREEN

P.S. I've never used reshade for this game.  And never installed anything other then SH2EE files in the game directory.

**Comment by Polymega** [comment]
Do you have any settings in your Nvidia GPU control panel that could be causing this? Perhaps a global (default) setting for all games that's causing any shenanigans?

**Comment by Raziels-Lament** [comment]
I doubt it. I never force anything globally. I've pretty much always had my global settings a certain way. Anything I'd consider a setting of consequence would only be changed/set on a per application basis. I did try it will default global settings - same result. hmm. I don't get it, I've had the enhanced edition working on the system before.

**Comment by Polymega** [comment]
Hmm... Maybe try this? Maybe a recent Windows update affected you in this way?

http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#a-burntin-image-appears-during-screen-fade-transitions

(We'll have this feature included into the project for the next update.)

**Comment by Raziels-Lament** [comment]
Just tried that setting - No go. I am running Windows 10 Pro 1909 (build 18363) 64bit of course. I'd have do some googling to see if anyone has been having related application issues with a recent update.

**Comment by Raziels-Lament** [comment]
Only thing I could find through google searches is the affinity setting. I tried setting to different cores to see if that made any difference. Same result black screen and opening task manager always shows sh2pc.exe as not responding.

**Comment by Polymega** [comment]
If the vanilla game isn't working for you that's likely not the issue, as the single core affinity fix is part of our project (unless you manually changed the process affinity in Task Manager for the vanilla game).

This is a fairly dumb suggestion, but does running the game as admin allow it to properly launch?

**Comment by Raziels-Lament** [comment]
I did try running the executable as admin early on to no avail. And please ask/suggest anything "dumb" just in case I missed something simple. I appreciate your continued assistance.

**Comment by Raziels-Lament** [comment]
WEIRD SOLUTION! I found an old post of someone experiencing the same problem I am now and they said that they had copied the game directory to a thumb drive (I forgot the reason why) and out of curiosity they tried to run it from the thumb drive and it worked! So, I said what the hell. I copied the game folder to a spare thumb drive I had and it does in fact work! I have no idea why this is but I'm so happy I can finally play it again. I am interested if anyone can figure out why this works and what might be the solution to "trick" it into doing the same on my installed SSD.

**Comment by Polymega** [comment]
Very weird! Huh. On both of my PCs, the game is installed on the main (C:\) drive. One in Program Files (x86), the other in My Documents.

Looking at the log file, the next step _after_ setting single core affinity is the [ImproveStorageSupport](http://enhanced.townofsilenthill.com/SH2/config.htm#ImproveStorageSupport). I don't know why that'd affect anything (and it probably shouldn't, since you couldn't get the vanilla version to start), but you could try disabling that to see if it would then run in your E:\ drive.

**Comment by Raziels-Lament** [comment]
Just tried that, still the same issue. Darn. However it works flawlessly on my thumb drive. I even loaded Reshade into it so I could inject SMAA. Looks beautiful in 3440x1440. I'm already loving the UI/text improvements!

**Comment by Polymega** [comment]
Sorry I can't offer any solution for your `E:\` drive issue, but I'm happy you're able to play it through another drive in the meantime!

**Comment by Raziels-Lament** [comment]
Just a quick FYI. I had a bit of free space on my C: drive so I copied the folder there (C:\Silent Hill 2\) and it works great! Guess it hates my E: drive. Registry issue maybe?

**Comment by Polymega** [comment]
I spoke with Elisha (our lead programmer) about this and here's what he has to say:

> I am pretty sure this issue is related to a thread deadlock, which is the something that causes the audio glitches if single core affinity is disabled.  This game has really bad thread handling and they never expected hard drives or CPUs to run at the speed they do.  I am able to replicate this issue it I modify the loading speed of the audio files.
> 
> I have run this on my SSD and it worked for me.  More than likely the issue is the relative speed between the hard drive vs the CPU.  The game does tasks at the same time as it is loading files off the disk.  If either thread gets done too early then it causes a deadlock and a black screen.

One of the final goals for this project would be to "untangle" all the thread-locking issues of the game. This would be a major undertaking, so would likely not be attempted/done until towards the end of the overall project.

**Comment by Raziels-Lament** [comment]
I really appreciate you checking into the matter. Since I'm am able to run it on another drive I am more then happy to do so just to be able to play it again. Thank you so much!
