### ISSUE TITLE
More new enhanced features being optional?

### ISSUE THREAD

**Issue by Dairnon** [elishacloud/Silent-Hill-2-Enhancements#258]
First of all I wanna thank you for the amazing mod project. The enhancement project has done a lot of amazing work remastering and enhancing the original SH2 ps2 port to PC. Some changes have been essential like fog and lighting adjustments as well as fixing stability issues that the original PC version had.

Some of these new updates have fixed things that were considered issues in the ps2 port such as translation/grammar issues for dialog and signs. 

Other changes include adding geometry to surfaces and adjusting the camera position to fix widescreen clipping.

For some fans these _issues_ are considered part of some original charm left over from the developers and feel like unnecessary changes that cover up the original ps2 version.

I was hoping it'd be possible in time to allow these changes (as well as newer ones to come like the texture enhancements) to be configurable for the die hard fans who want the classic version 
 preserved as the way Team Silent had launched it.

This way everyone from the purist to more casual people can enjoy the game without any issue.

**Comment by Polymega** [comment]
Hi Joe,

Thank you for the kind words.

> I was hoping it'd be possible in time to allow these changes (as well as newer ones to come like the texture enhancements) to be configurable

Yes, [this is something I planned to catalog in the future](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/180) , near or at the end of the project's life. 

There are many, many facets to this project we're still working on, and we all do this on our spare time with no expectation of compensation, so time and resources are stretched thin as it is. This means our priorities at this time are to continue and ultimately finish planned tasks for the project.

Note, for the future, that to make these things "configurable" will mean to simply disable them, which would use the vanilla PC version's files, which may not still be to a "PS2 purists'" standards.

> This way everyone from the purist to more casual people can enjoy the game without any issue.

Unfortunately, that is impossible. You can please some of the people some of the time, but you can't please all of the people all of the time. We do our best, but it won't please everyone.

**Comment by elishacloud** [comment]
@Dairnon, This project is open source and, as such, pretty much any part of this project can be disabled.  There are three main ways to disable things in this project:

1. The first way is by modifying settings in the `d3d8.ini` file.

There are many settings in the ini file which allows you to disable pretty much any code change we made to the game.  These options are pretty granular and allow for isolated changes to disable items you don't want.  See the [Configuration Details](http://www.enhanced.townofsilenthill.com/SH2/config.htm) page for a list of the options.

2. The second way is by removing items out of the `sh2e` folder.

One of the core mandates of this project is to not overwrite any file in the Silent Hill 2 folder.  All of the replaced data files are stored in a separate folder called `sh2e`.  By simply deleting files in this folder you can undo many of the changes.  For example, by removing all the `.msg` files you can undo most of the dialog/text changes in the game, by removing the `Silent Hill 2\sh2e\pic\etc\MousePointer.png` file you can undo the mouse cursor change, etc.

3. The third way is by modifying the code.

In some cases more than one change is packaged together.  For example all the sound effects are stored in a single file called `sddata.bin`.  If you want to make a change to only one of sound effect files you will need to repack the `sddata.bin` file.  In these cases, since this is a 100% open source project, [we give you the tools](https://github.com/elishacloud/Silent-Hill-2-Enhancements/tree/5dc7ac3604fd2c86ca3eb101b5d32f4cb6855879/AudioScripts/SFX) as part of this project to make those changes yourself.  But in most cases you won't need to since (1) or (2) above will allow you to undo 90% of the items you would want to undo.
