### ISSUE TITLE
DSR and Ambient occlusion

### ISSUE THREAD

**Issue by fromarcturus** [elishacloud/Silent-Hill-2-Enhancements#259]
Hi am I causing any problems doing a 4k downsample to 1080p? Nvidia AA is a no no also correct? Also is there a way to add ambient occlusion via nvidia driver or reshade? Thanks keep up the great work!

**Comment by TommvinHuwaltzky** [comment]
you can add MXAO to the Silent-Hill-games with no problem, and you won't even notice the performance impact (with exception of part 3), since they're locked at 30fps anyway.
the issue is how injecting AO works. usually, when a game is programmed, in the render-pipeline AO goes before transparency-effects, like fog or dust. since injecting it makes it render at the very end, it bleeds through all those effects, and thus you can see it as thick outlines of objects through the mist.
I usually leave it on in indoor-scenarios, which gives the SH-games even more dephts, but outside, with all the fog, it's just too distracting. 
you would have to have access to the source-code to implement it properly, I guess...
