### ISSUE TITLE
Music Loop issue at the Hospital

### ISSUE THREAD

**Issue by ZimSan** [elishacloud/Silent-Hill-2-Enhancements#270]
When you find Laura at the hospital and the cutscene plays, at a certain point the music loops weirdly and doesn't stop until you arrive at the boss room. It's the only cutscene with this issue I've seen so far.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4568656/d3d8.log)

There is also I believe a mistranslation for the German version of Silent Hill 2.
<img width="1920" alt="sh2pc_VOgkGJbA4Z" src="https://user-images.githubusercontent.com/63849135/80888372-a77ec780-8cbe-11ea-896b-686818ea6500.png">
In here Laura says something like "You pathetic idiot" but in the english version she says "You fartface!" which is a more believable thing to say for a kid. In the german version a more correct translation would be like "Du Pupsgesicht!".

**Comment by Polymega** [comment]
Hi ZimSan,

Thanks for the notes. If you were to close the game and restart it, then load the Laura scene back up, does the issue still happen?

In regards to the German translation of the game: It's been noted by Spanish and Italian players that the translations in their respective languages can be poor in a lot of areas.

The same is likely true for the German and French versions. We ultimately need a German (and French) fan to help with cleaning up the language files in their respective languages.

If this is something you'd be interested in wanting to do please let me know! We can give guidance and set you up to edit and improve the German files.

Thanks

**Comment by Polymega** [comment]
PS - I should mention we have folks in this group who have already helped clean up the English, Italian, and Spanish files. So there would be help/assistance around the corner from several people: http://enhanced.townofsilenthill.com/SH2/config.htm#TextAdjustments

**Comment by ZimSan** [comment]
When I opened up the game again it didn't happen but is there any particular reason for this happening at all like maybe playing the game for a certain amount of time or something? 

Sure. I'd love to help.

**Comment by Polymega** [comment]
> is there any particular reason for this happening

It's very likely due to the game always wanting to thread lock itself. This is what the `SingleCoreAffinity` fix helps prevent but sometimes it'll still happen. It can also happen if too many processes are happening at once on your PC and there's a slight hiccup between when the game expects the music to load and when it actually does load.

One of the big, final things we hope to address with the game is "untangling" the thread locking issues, so it runs smoothly and on all CPU cores.

> Sure. I'd love to help.

Great! And thanks! I'll reply back soon with more details and see if you'd still like to help after all the information. Thanks again!

**Comment by Badore90** [comment]
> PS - I should mention we have folks in this group who have already helped clean up the English, Italian, and Spanish files. So there would be help/assistance around the corner from several people: http://enhanced.townofsilenthill.com/SH2/config.htm#TextAdjustments

I'm here if you need some help. Some guidelines we follow were:

1. This shouldn't be a "fan-made translation" (you could do it, but as a personal separated patch), but the official translation, simply corrected. Never underestimate the official translation and the fact that German gamers know this translation since 20 years.
So even if some phrases are 100% faithful to the english, if they're good, leave it as it is (there could be some even better than the english version).
Make sure to only do objective improvements (not based on personal taste), if in doubt, leave it as it is.

2. Try to follow the english punctuation, removing the exaggerate use of dots (…………), adding space between dots and words and match the lines structure.

3. On notepad++ go to **visualize**, **symbols** and hit **shows all symbols** so you won't make errors (as I firstly done), i.e. when you head to next line, for making the program to know, you have to press Tab.

4. Make sure to make the modifications to match an all files. i.e. if you change an item name, you'll likely have to change it either in the file of the staqe where you find it, in the one where you use it, and in Item_x file (item_msg and memo_msg without the x shouldn't be used, but we make these files too to match for safety).

5. There are some recurrent phrases throughout the game that could sound strange, but they have a precise meaning. For example the phrase that James said if you try to leave the hospital. If you change it, you have to change accordingly in the recovery end file too. Lake file too have a recurrent phrase with a end file and so on.

**Comment by Polymega** [comment]
Hi @ZimSan,

Thanks for being patient with me. Lots going on at the moment. And thanks for being interested in helping clean up any errors for the German language files for the game.

There's several things to go over, to help give you a better idea of what all is involved when working with the text files for the game. So let's jump into it:

---------------------------------

**Getting started/organizing:**

- Make sure you are using the European (Director's Cut) version of the game. This is because the North American version of the game purposefully nulled out data for many `.mes` files that are not English. If you need them, I can provide these files from the European version of the game.

- The German files are located at `SILENT HILL 2\data\etc\message\` and are all the files that end in `_g.mes`. The `.mes` format stands for "message" and the `_g` at the end of the file name stands for "German."

- Make a copy of all the German `.mes` files to a new folder. This will be your working folder for editing purposes.

- Once you make any edits to a `*_g.mes` file, you will then place it in `SILENT HILL 2\sh2e\etc\message\`. This way, you do not overwrite the original `.mes` files (for preservation, and so you can look back on them, if needed).

----------------------------------------

**Important: Special cases for `.mes` files:**

- Whenever you begin, be sure to use the `stage_x_heaven_msg_g.mes`, `m_card_msg_g.mes`, and `m_card_x_msg_g.mes` files from the [Essential Files download package](http://enhanced.townofsilenthill.com/SH2/install.htm#installEssentialFiles), if you edit these particular files. We had to adjust specific data within these files to fix visual bugs/errors

---------------------

**Editing `.mes` files:**

- We use a tool called [sh2msgconvert](https://gitlab.com/sh2msgconvert/sh2msgconvert) to edit the `.mes` files. This tool will convert the `.mes` files into a readable `.txt` file for editing. Once you are finished editing, the tool can then convert your `.txt` files back into `.mes` for the game to use.

   - We recommend you use [Notepad++](https://notepad-plus-plus.org/downloads/) when editing the `.txt` files, to preserve the file's formatting.

- [There is documentation on how to use sh2msgconvert.](https://gitlab.com/sh2msgconvert/sh2msgconvert/-/blob/master/README.md) This documentation will teach you how to use the software. If you are having any problems using it, @Infrid and @IlDucci are its creators and can assist you.

----------------

**Editing the same text found in multiple files:**

- Memo and riddle text is stored and used in multiple `.mes` files. For example, the Walter Sullivan newspaper article found in the apartment trash chute can be found in `stage_apart_out_msg_g.mes`. However, once you read this article, it can then also be called from the `memo_msg_g.mes` and/or `memo_x_msg_g.mes` files (your inventory memo screen).

   - So, if you change any text for a riddle/memo, you will also need to apply these changes for the same riddle/memo within the `memo_msg_g.mes` and/or `memo_x_msg_g.mes` files, as well.

- As you go through all the `*_g.mes` files, be mindful that a text string can be stored and called in different `.mes` files.

----------------------------------------

**Additional tips when beginning:**

- Consider referencing the `*_e.mes` files found in the[ Essential Files download package](http://enhanced.townofsilenthill.com/SH2/install.htm#installEssentialFiles) when comparing/editing the `*_g.mes` files. As Badore90 mentioned, we:
   - Removed excessive and frivolous uses of ellipses (...).
   - Corrected coloring for text (some things that are read from an external source were white when they should have been blue).
   - Corrected descriptors (such as mentioning a piece of paper is correctly on a bed, instead of on the floor).

- Badore90's notes above this post are also good to read and familiarize yourself with. They will help with any editing work.

- And to compliment one of Badore90's bullet points: Be considerate with your edits, in regards to both the original translation and/or how it relates to the English version, in terms of meaning/intent/structure.

--------------------------

**Most importantly:**

### Play test all your changes!!!

It's very important to ensure all your edits are displaying/working correctly in-game. 
- Is any one line too long for the game screen to handle? (Be sure to keep the line length about how it is now, so it will still comfortably fit in the screen for 4:3 players.)
- Does any text adjustments break the formatting of the limited space within the inventory screen?
- Are `<VARIABLES>` (found in `.txt` files after using the sh2msgconvert tool) still intact after any edits? 
   - `<VARIABLES>` are the random numbers/text that will generate for riddles/memos on each playthrough.
- If you changed text, are you sure that same text isn't also used in another `.mes` file?

To see any edits you've made, you must fully close and relaunch the game after placing the updated `.mes` file in the game's directory, to see the edits take effect.

--------------------------

Lastly, if you have any troubles, concerns, issues, or just general questions, let us know! There are quite a few of us here that can help you out!

If you'd still like to help improve the German files for your fellow native speakers, please let me know and thanks again for your consideration!
