### ISSUE TITLE
Improve the outdoors self-shadow 

### ISSUE THREAD

**Issue by 894-572** [elishacloud/Silent-Hill-2-Enhancements#272]
![no7607hm9lf21](https://user-images.githubusercontent.com/44001490/80924753-57653b00-8d7a-11ea-846a-9921efaf3b27.png)

![sh2pc_2020_05_03_22_51_49_720](https://user-images.githubusercontent.com/44001490/80924777-7663cd00-8d7a-11ea-952b-c6196ab4d6d4.png)

As far as I know all versions of the game don't project the self-shadow while outdoors — is it feasible to improve on this area?

I'm really sorry if the terminology isn't right, but I hope that you get the gist.

**Comment by Polymega** [comment]
Hi there,

Self shadows for James are only programmed in the game to be used wherever the flashlight can be used. Because there's no pre-existing code to enable his self shadow elsewhere, we can't change much about it.

If you're meaning soft shadows, those too are only ever used in the game wherever the flashlight can be used: https://youtu.be/uJi0_kJbCoU?t=307

In regards to making James' daytime outdoor shadow soft? I'm not the best person to answer this as I don't know how the game differentiates the render passes for shadows between the current methods of determining when it should be hard or soft.

But rest assured shadow behavior is now correct as seen on the console versions (explained in more detail in the video link above).

**Comment by 894-572** [comment]
>Self shadows for James are only programmed in the game to be used wherever the flashlight can be used (and a few other specialized areas). Because there's no pre-existing code to enable his self shadow elsewhere, we can't change much about it.

>But rest assured shadow behavior is now correct as seen on the console versions (explained in more detail in the video link above).

Sure, I hoped that going beyond the PS2 version would be possible.

**Comment by Polymega** [comment]
For sure. If there's ways we can do such things, we will definitely strive to do so. And thanks for your suggestion on this; while we're not certain if we ever can do it, it's great to hear other fans itching to get even more out of this beloved, old game.

**Comment by 894-572** [comment]
https://www.youtube.com/watch?v=uJi0_kJbCoU&t=307

Is it possible to enable the solid shadow models for all areas where the self-shadow isn't used?

Since this doesn't match the original PS2 behavior the setting should be configurable, even though I vastly prefer the non-layered implementation.

**Comment by Polymega** [comment]
I don't think we're going to fiddle with shadows/shadow behavior much more with our project. While the shadows outdoors during the daytime are "sharp", it's at least accurate to the console versions, so we'll call this good on our end.

**Comment by elishacloud** [comment]
> While the shadows outdoors during the daytime are "sharp", it's at least accurate to the console versions

This is the correct behavior and true to real life.  The closer the light source the more diffusion happens and the softer the shadows.  The further away the light source the sharper the shadows.  The sun is quite far away which is why the shadows are more sharp when outside.

To test this check your shadow with a nearby lamp and then check your shadow outside when the sun is shining bright overhead.  You will see much sharper shadows outside.
