### ISSUE TITLE
Audio stuttering issues

### ISSUE THREAD

**Issue by Hurtdeer** [elishacloud/Silent-Hill-2-Enhancements#273]
Hi,

I can't seem to make it through the initial Angela graveyard cuscene without the bgm looping (most of the time) and the voice files stuttering and desyncing (every time-- sometimes early on, sometimes later). It's a repeatable issue that I've gotten every time on around 11 restarts, including closing all programs, rebooting my computer, and trying every SingleCoreAffinity option from 0 to 3 (it was set to 2 on its initial few goes) in the settings. I thought it might have been my external soundcard, but the issue is repeatable on other outputs also.

I haven't had a single crash either. The problem seems to clear up once the cut scene ends (or I end it), but I haven't run the game much further than that as I don't fancy repeated issues affecting this atmospheric game. Is there something I'm missing?

Huge appreciation for the work done on this by the way. I'm so glad I finally get to try it, even with this issue tripping me up
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4572124/d3d8.log)

**Comment by Polymega** [comment]
Hi Hurtdeer,

Sorry about the troubles you're having, and thanks for attaching a copy of your `d3d8.log` file.

Everything seems to be in order by looking at your log file. Can you try something for me? Set `d3d8to9 = 0` in the `d3d8.ini` file and do a few more tests in the area you were experiencing trouble. Setting `d3d8to9 = 0` will both disable d3d8to9 and ReShade.

I'm thinking there's a possibility that ReShade might be causing the stuttering/desyncing (which may also be causing the audio problems). It's not that your PC isn't capable of handling ReShade, but that there might be some sort of minor incompatibility going on with some driver(s) between it and your computer.

If that doesn't work, next try temporarily removing the `dsound.dll` file and testing again. This will remove IndirectSound for the game. I know IndirectSound can sometimes not play nice when using dedicated audio cards.

Thanks

**Comment by Hurtdeer** [comment]
Hi Polycule. Thanks for the swift reply! 

It appears that disabling direct x9 and ReShade did indeed fix the issue. Tried the cutscene twice with no problems whatsoever. Then turned the setting back on and the problem resurfaced instantly.

I noticed ReShade informs me of a new update when I run the game now-- as I had only just installed everything today, I was wary of updating anything in case it would cause issue. Should I do it? Would it resolve the issue do you think?

If not, I hope I'm not stuck not being able to use those enhancements, but I can live with it

**Comment by Polymega** [comment]
Great! Glad to hear we were able to pin-point the issue.

**About ReShade:**
We currently use ReShade for three purposes:

- It's built-in SMAA (anti-aliasing)
- To _slightly_ recolor the game image to have a cooler/blue tint
- To _slightly_ darken the base black levels

Out of the three things listed, the SMAA is the main reason we include it with our project. However, since you have a really good graphics card, you definitely don't need ReShade for anti-aliasing purposes.

For you, I strongly recommend **removing** the ReShade files from the game's directory and instead use your GPU's AA instead, which will give you much better AA results (and avoid the issues you were having using ReShade): http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#what-antialiasing-should-i-use-for-the-game

So that leaves the other two items that ReShade provides: The slight recoloring and level adjustments. These two things are not critical to have for your overall experience, so you should still have a great time without them.

We plan to integrate our own custom shaders for SMAA (for those with GPUs that can't do their own AA), color adjustment, and level adjustment, so we will no longer have to use ReShade at all. This way, everyone will get the benefits that ReShade provided, but without the actual use of the software, to help avoid any compatibility errors such as what you've experienced.

While we don't have these shaders ready for the project yet, we hope to include them in the next project update.

**Comment by Hurtdeer** [comment]
Hi, thanks very much! And apologies for the late followup- I did post this rather late last night

I've deleted all the reshaders and switched over to my graphics card native anti-aliasing, and, irritatingly, the problem has resurfaced. It'll consistently happen again on any anti-aliasing setting, from 2x to 8x (although I haven't tried lower transparency settings yet, as your website recommends one specific option). Turning my nvidia's anti-aliasing off fixes the issue completely, but, well, it does look noticeably worse. Any idea why it would be doing this?

**Comment by Polymega** [comment]
Hmm... well it might be worth mentioning that the lip syncing was never stellar for the game. So if the lip syncing is only _slightly_ off for you that might actually be correct/normal.

If you're experiencing bad stuttering/desyncing (something that's definitely "not right"), maybe try temporarily removing the `dsound.dll` file and see if that fixes it? Perhaps it's the dedicated sound card not playing nice with IndirectSound?

**Comment by Hurtdeer** [comment]
It is, unfortunately, not just slightly off-- it's completely garbled, playing segments out of order a syllable at a time as if triggering seperate parts of the recording at random. The music often begins looping too. I removed the dsound.dll file and it changed nothing-- the problem persists when I've used my internal card for output too. The only thing that truly stops it is not having anti-aliasing of any kind. Seems bizarre, but I assume it's connected to the threading issue you've mentioned in other threads, loading issues confusing the game.

It's a shame, because it looks noticably worse without anti-aliasing, but between that and losing the wonderful music while the characters say gabbfshfbbglabghabl at me, i guess i may have to live with it for now!

**Comment by Polymega** [comment]
This is peculiar... Do you reckon updating or rollbacking your Nvidia drivers might do some good?

- https://www.reddit.com/r/techsupport/comments/anhoeq/games_stutter_with_rtx_2060/efx46ui/
- https://us.forums.blizzard.com/en/heroes/t/game-stutters-since-upgrading-to-rtx-2060/25659/18
- https://forums.tomshardware.com/threads/rtx-2060-stuttering-in-some-games.3464675/

Do you typically experience lag/stutters with other games, as well?

> I could record a video of what's happening if that helps anything?

I'm not sure if it'd help with troubleshooting but it certainly doesn't hurt to do so!

**Comment by elishacloud** [comment]
The issue here is that the game does very poor thread handling.  Any slight increase in timing on one thread (like enabling AA) causes one of the threads to deadlock and audio looping.  This game needs a lot of work on its thread handling, and that will be a project all to itself!

**Comment by Hurtdeer** [comment]
It's a new computer but every other game I've run recently has been perfect (RE3make on high settings, Doom Eternal on full, no problems whatsoever). Even with SH2 it's just an audio issue- absolutely no graphical ones. I figured it must have been a thread handling issue going by other posts on this forum, and, well, I suppose there's no way around it, so I'll just live with slightly worse graphics until if and when you ever manage to rework it-- ultimately it's still going to be an improvement

I really appreciate the help and effort you put into trying to resolve this issue for me! The amount of time and effort you've all put into this project is staggering and I'm very grateful for it!

**Comment by Polymega** [comment]
I'm sorry the game is giving you trouble whenever any type of AA is seemingly used. And, truly, thank you for being kind and understanding that the game and our project for it is very much a WIP. I wish we could've found a good work-around for the problem you're having at this time. It's our hope, as Elisha alluded to, that we can untangle all these nasty threads and make the game run smoothly on multi cores, sometime down the line.

**Comment by elishacloud** [comment]
@Hurtdeer, one thing you could try is adding the `SingleCoreAffinityTimer` option and setting it to `0`.  You would also need to make sure that the `SingleCoreAffinity` is set to something other than `0`.  So the ini would look like this:

```ini
SingleCoreAffinityTimer = 0
SingleCoreAffinity = 2
```

I am not sure if this will make a difference, but it is worth trying.

Note: I added the timer as a hidden option to help reduce some threading issues with Windows 7.  Disabling it might help in your case.

**Comment by Hurtdeer** [comment]
Hi there, sorry for the delayed reply again, got busy with something

I tried what you suggested @elishacloud and the results were... interesting. It still garbles, and the music did eventually start looping again-- however, it seemed as if it was doing a far better job of trying to stabilise  itself, with initial glitches giving way to to dialogue almost getting back on track again. However- eventually it still fell apart

However with that considered, I tested it with the antialias setting on x8, so I bumped it down to x2 (which I had tried before without it working) and... got through the cutscene without any audio glitching at all! So it seems with the SingleCoreAffinityTimer at 0, i'm allowed to treat myself to a little Antialiasing. Maybe even x4 works?

So that's great news! I'd almost all but given up. However, I'm still apprehensive that the problem could materialise beyond this one cutscene I've now watched about 20 times, so I'll see how it goes on before I continue this completely solved. Meanwhile, amazing, thanks so much for your help!
