### ISSUE TITLE
Lapis Eye Key Doesn't Exist

### ISSUE THREAD

**Issue by nickhollis21** [elishacloud/Silent-Hill-2-Enhancements#283]
Hi all, 

I am playing RE2 on PS+ and I'm trying to crack the Louise Puzzle Box by collecting the Lapis Eye Key. I am in room M2 in the hospital by the dresser and there is no key to collect. I am spamming X all around the dresser, I have collected the shotgun shells that were inside the dresser but the key was never there. I am now stuck and cannot progress because the key does not exist. Please help! What can I do??

**Comment by Polymega** [comment]
You're playing Resident Evil 2 on PlayStation Plus?

This project is for the PC version of Silent Hill 2.

**Comment by Polymega** [comment]
I think maybe there's some coincidental typos going on. 

You can't obtain the shotgun shells on the dresser unless you obtain the lapis eye key first. Check your inventory to be sure you don't already have it (or that you didn't already use it on the puzzle box).

This would be the first time I've ever heard of such a thing happening. Chances are, you've already obtained it or used it on the puzzle box.

**Comment by nickhollis21** [comment]
Hi there, thanks for the comment. Maybe it is different on PS+. I have checked my inventory and the key doesn’t appear to be in my inventory. The box is still locked with no way of opening it. I have tried restarting the game and still no luck. Since this is PC only, maybe I can be pointed in the right direction for the correct forum? Thanks!

**Comment by Polymega** [comment]
I believe the PS+ version is the **Silent Hill HD Collection**? If so, that version of the game is _notoriously_ buggy, so it might be likely a key item didn't spawn.

I'm not sure where to point you for assistance on that version of the game, as chances are anyone will likely tell you to restart from a previous save point (or restart the game).

Be warned Silent Hill HD Collection as a whole is prone to failure, due to it using beta code that wasn't properly cleaned up for gold release.

**Comment by nickhollis21** [comment]
Thanks for the help! Luckily I didn’t spend the $100 on it, I’m streaming it. That probably is the case. Sadly I only have 1 save file so I’d have to restart the game. Ah well.

**Comment by Polymega** [comment]
Sorry that happened to you. Silent Hill HD Collection is a pretty rough way to play SH2 and SH3.

I'm going to close this ticket. But for the HD Collection, I'd recommended saving every chance you get, and saving in new save slots (instead of overwriting old ones), so you can fall back on previous save files in case something happens.

If you ever come across a PC copy of SH2, try out our project! I think you'd have an overall better experience with SH2 that way.
