### ISSUE TITLE
Options menu text invisible. Pause menu doesn't appear.

### ISSUE THREAD

**Issue by JacobFlight** [elishacloud/Silent-Hill-2-Enhancements#299]
I've installed all the enhancement items and the main menu text on the opening home screen is fine. Once I move the options menu, the grey surround for the text appears, along with the dials at the bottom, but there is no text. The software knows that I'm hovering over the options because it makes a sound and arrows appear either side of where the text would be.

Also, if I launch the game and pause then the game pauses but no menu appears at all. It does respond with menu noises when I navigate with the mouse/directional buttons.

See images below. I've never played SH2 and I'm desperate! Any help would be amazing.

![sh2pc 2020-07-19 18-22-28](https://user-images.githubusercontent.com/68511833/87880860-f0f0d000-c9ec-11ea-8840-94734c320875.png)

![sh2pc 2020-07-19 18-22-11](https://user-images.githubusercontent.com/68511833/87880870-141b7f80-c9ed-11ea-93e9-115895a2c0dd.png)

Here's my logfile:

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/4944191/d3d8.log)

**Comment by Polymega** [comment]
This is an issue when using older integrated graphics cards (such as Intel HD Graphics). These older IGPs won't render the HD font, most likely due to this texture file being massive in resolution (4000+ pixels wide). These old IGPs weren't necessarily made with 3D gaming in mind, hence their limitations.

Also see here:
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/264
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/240

Playing with the original, non-HD font should restore the text. Open the `d3d8.ini` file and set `UseCustomFonts = 0`.

Because you're using an old IGP for graphics processing, you will likely also need to disable the Fog Fix [and ReShade](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-runs-slowstutters-in-general) (if you were using ReShade). Otherwise, you'll very likely experience lag/slow down.

To disable the Fog Fix, open the `d3d8.ini` file and set `fog_custom_on = 0`.

**Comment by JacobFlight** [comment]
This worked a treat! Thank you so much for your speedy reply. Awesome. Yeah, this is a bit of an old machine so I'll avoid the ReShade. 

Thanks again!

**Comment by AeroWidescreen** [comment]
Hello, if you're still having trouble with ReShade then please try this new build of SH2E. It includes post-processing effects that are designed to be more efficient than ReShade and resolve any performance issues you may be having.

Verify that ReShade has been _removed_ before attempting to try this. Settings can be adjusted in the **[SHADERS]** section of the INI file.

[d3d8_b1.5.1806.zip](https://mega.nz/file/dP5QCbQK#kOX7UST9b2LeAhWiN4d7zuS9fJ0JmU6ZTljGJktsQiI)
