### ISSUE TITLE
Tutorial video?

### ISSUE THREAD

**Issue by grizzvibezz** [elishacloud/Silent-Hill-2-Enhancements#307]
Hello! i'm new to pc and I was wondering if there is a step by step video explaining how to install and run silent hill 2.

**Comment by Polymega** [comment]
Hi grizzvibezz, 

We don't have a video tutorial at this time. This is due to the files/packages that we use are constantly changing as the project evolves, so we opt instead to update the instructions on the website.

However, installation is relatively easy: Install the game, then download the packages listed on the website. Most of the packages are just putting the files in the correct folders within the game's installation directory.

[You can also refer to this directory tree](http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree) after you install everything to ensure you've placed all the files in the correct spots.
