### ISSUE TITLE
Stuttering / Framepacing issues

### ISSUE THREAD

**Issue by TheGaluMoD** [elishacloud/Silent-Hill-2-Enhancements#325]
Hi guys, great work on this mod, however I'm having issues with stuttering and I'm not sure what to do at this point. I already tried all the steps in the Troubleshooting section and they didn't improve things. I feel like my PC should be more than able to handle the game anyway.
I enabled nVidias FPS Counter and I can see that the framerate is always jumping around between 30 and 31 FPS. So I assume the occasional extra frame is responsible for the stuttery feel. I've already tried using nVidia's vsync options in the control panel to no effect.

Also, CPU utilization for the Core I selected is constantly at 100%. Is that normal?

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5350861/d3d8.log)

**Comment by Polymega** [comment]
Hi there,

I'm thinking the stuttering you're describing only happens every now-and-then, mostly when outdoors. If so, that's "normal" behavior. I put that word in quotation marks because it's something that we might look into at a later time, but something that the PC game has always done since it was first released.

We're been discussing and testing some things with this that you can read on this thread here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/282

> Also, CPU utilization for the Core I selected is constantly at 100%. Is that normal?

Yes, the game has a memory issue that will use 100% of whatever core it's running on. This, too, has always been like that for the PC version since day one. Elisha could discuss this issue in more technical detail, but you can find other tickets on here where he talks about it. This is something we would like to look into at a later time, but will likely be one of the last things we address for this project, given the nature of how involved it would be to address it.

**Comment by TheGaluMoD** [comment]
Yes, I do think it might be more common outdoors. I haven't played the vanilla PC version in a while for obvious reasons, so I'd forgotten about these performance issues. I'm also a lot more sensitive to this stuff now, so I'll stick to emulating the PS2 version for now. But I'll definitely keep an eye on this project. Really amazing stuff, keep up the great work!

**Comment by Polymega** [comment]
Sure. Your results may differ than mine, but I experience same/similar movement hitches on PCSX2 with the game. I discuss that a little in the thread I linked. I'm curious if you experience no movement hitches with the emulator.

**Comment by TheGaluMoD** [comment]
Yeah I was just scrolling through that thread. I haven't emulated it in ages so I'm probably misremembering and my experience is gonna be the same as yours. I'd just assumed that it'd be smooth, at the very least when using the software renderer. I'll check and if I have any interesting findings to report I'll post them in #282 :)

**Comment by Polymega** [comment]
Thanks! A pool of data from others may help us down the line. :)
