### ISSUE TITLE
Trouble launching Silent Hill 2 

### ISSUE THREAD

**Issue by gregitol** [elishacloud/Silent-Hill-2-Enhancements#331]
hey, when i try to launch the game an error pops up, it didn't happen the times i've tried before, but in those cases it would just launch with a black screen and then crash. I'll post pics of the error and the game's directory. It's in spanish, but i think you'll understand. Thanks
![error](https://user-images.githubusercontent.com/73664970/97617559-ab38a000-19fc-11eb-8289-78f2f620edcc.PNG)
![directory](https://user-images.githubusercontent.com/73664970/97617571-aecc2700-19fc-11eb-89ee-1a3b14ef8381.PNG)

**Comment by elishacloud** [comment]
I don't see a log file here.  It looks like it is crashing before our module is able to create a log file.  It could be because the downloaded executable is being blocked by Windows.

See this comment for more details:  https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/326#issuecomment-711102896

**Comment by gregitol** [comment]
i see. How could i prevent that from happening?. Thank you for helping btw

**Comment by elishacloud** [comment]
Try doing the steps from that comment to see if they help.  For example, try with your original executable.

**Comment by gregitol** [comment]
all done!. i was running the .exe file with compatibility mode, as soon as i disabled it, it started working

**Comment by elishacloud** [comment]
Great!  I am glad you got it working!
