### ISSUE TITLE
Main Menu and inventory item images are extremely small and off center.

### ISSUE THREAD

**Issue by Yury23** [elishacloud/Silent-Hill-2-Enhancements#332]
Exactly as said. The Main Menu appears at the top left of the screen in minuscule dimensions, while what I can assume are credits fade in and out a little lower from it (also very small). Upon guessing and pressing an option, I was loaded at Brookhaven Hospital, in the office. I can't tell if it was an old save of mine or a save made by the team to test, and I don't mind it, but when trying to check the inventory, I noticed that it appeared as empty at first. I started rotating among the invisible items and realized the actual thing was that the items were, again, minuscule and off their place. Troubleshooting page didn't have a solution, and nothing I read in Configurations seemed to help. What could I do?

If it's any matter, I started downloading the packs shortly after the update 06 video went live.

**Comment by elishacloud** [comment]
This typically means that the high resolution textures are not in place.

1. Make sure you have downloaded and installed all the required packages.
2. Make sure you have extracted them to the correct location.  Check out this page to see what your folder should look like:  http://www.enhanced.townofsilenthill.com/SH2/install.htm#directoryTree

If you still have issues after installing all required packages please upload your log files.

**Comment by Yury23** [comment]
Everything seems to be in place. What are the log files named so I upload them?

**Comment by elishacloud** [comment]
Log file is "d3d8.log".  Upload it here to GitHub.

**Comment by Yury23** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5461701/d3d8.log)

**Comment by elishacloud** [comment]
There are a few things I noticed:
1. You seem to have extra files and folders that are not normally there.  For example the `Desinstalar.exe`, `Desinstalar.ini` and `Redest` are not normally suppose to be there.
2. You seem to be missing some files that are normally supposed to be there, like `sh2.ico` and `sh2logo.jpg`

These two items make me wonder if there is a problem with the version of Silent Hill 2 that you are using.

Also, I noticed that the path you are using is `C:\Program Files\Silent Hill 2\Silent Hill 2`.  You have a Silent Hill 2 folder inside of a Silent Hill 2 folder.  Is there anything in the `C:\Program Files\Silent Hill 2` folder other than `Silent Hill 2`?

Check the start menu files to make sure they are correct.  For you, they should be located in the `C:\Program Files\Silent Hill 2\Silent Hill 2\sh2e\pic\etc` folder.  The folder should look like this:

![image](https://user-images.githubusercontent.com/25625456/97642526-a4149080-1a02-11eb-8abd-56e0fbab61be.png)

If it does not look like that then redownload the [Image Enhancement Pack](http://www.enhanced.townofsilenthill.com/SH2/install.htm#installImageEnhancementPack) and install it.

**Comment by Yury23** [comment]
Oh, should've clarified, the folder is just as I got it from myabandonware.com. It's just as the installation left it. Going to check the menu textures now.

**Comment by Yury23** [comment]
And yes, the textures are all correcct.

**Comment by elishacloud** [comment]
> The Main Menu appears at the top left of the screen in minuscule dimensions

This means that the game is not picking up the new high resolution textures.  It could be because the game is looking in the wrong location for them, for example the shortcut has a wrong path or the textures are on the wrong folder, etc.  Or, somehow the game and the textures are not mapped correctly, example, the relative path of the game to the textures is wrong, etc.

I would recommend starting over and reinstalling everything, making sure not to create nested "Silent Hill 2" folders.

Also, if you look at this line in the log file:

```log
Environment variable __COMPAT_LAYER = "Installer"
```

You can see that Windows thinks the game is an installer.  Somehow, the way that you have installed Silent Hill 2 caused Windows to think that Silent Hill 2 is an installation program.  That may be interfering with the game.

You may also want to check the compatibility options to make sure that they are correct.

See this thread here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/326#issuecomment-711102896

**Comment by elishacloud** [comment]
You may also want to try disabling `EnableWndMode`.  Like this:

```ini
EnableWndMode = 0
```

**Comment by Yury23** [comment]
Thanks. I'll reinstall it from another source and try.

**Comment by AeroWidescreen** [comment]
This is where a GOG release could be beneficial. A legitimate, standard source to get the game from.
