### ISSUE TITLE
Problem with Resolution In-Game

### ISSUE THREAD

**Issue by CKS417** [elishacloud/Silent-Hill-2-Enhancements#334]
I've never had any problems with upping the resolution in-game from 640x480 to 1920x1080. However with the recent update since I installed the new files that came with it. The d3d8.ini has kept me stuck on 640x480 and hasn't allowed me to up the resolution in the settings. I tried messing with the .ini file and to no avail sadly, so I'm here now after I left a comment on the video about my problem and thankfully I got a response. So as recommended, I'll attach the d3d8.log. Thank you in advance
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5468383/d3d8.log)

**Comment by AeroWidescreen** [comment]
> Environment variable __COMPAT_LAYER = "640X480"

Right click the Silent Hill 2 exe, go to the Compatibility tab and make sure "Run in 640x480 screen resolution" is UNCHECKED.

![compatibility](https://i.imgur.com/jTJGSsa.png)

**Comment by CKS417** [comment]
> Right click the Silent Hill 2 exe, go to the Compatibility tab and make sure "Run in 640x480 screen resolution" is UNCHECKED.

I gave what you said a try and unchecked it, but for some reason. It still runs in 640x480. So I attempted to tweak the d3d8.log to my resolution and it still ends up running in 640x480. Apologies for all this trouble

![image](https://user-images.githubusercontent.com/73727586/97771910-d5719580-1b95-11eb-879a-87015ea88355.png)

**Comment by Polymega** [comment]
That's peculiar. If you set `EnableWndMode = 1` in the `d3d8.ini` file does this still happen?

**Comment by AeroWidescreen** [comment]
@CKS417 
In addition to what **Polymega** said, could you upload a new d3d8.log file so we can see what it says now? Disabling that compatibility option should have fixed it ...

> I gave what you said a try and unchecked it, but for some reason. It still runs in 640x480.

Unless you changed the wrong exe or shortcut? I see you have the enhanced edition exe and a backup of your original exe ... so maybe? Nah, that's probably not the issue here.

**Comment by CKS417** [comment]
> In addition to what Polymega said, could you upload a new d3d8.log file so we can see what it says now? Disabling that compatibility option should have fixed it ...

Sure thing, I've attached it to this post. Plus in edition to what **Polymega** said, I have what they said a try in the d3d8.ini and to no success unfortunately. 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5469458/d3d8.log)

**Comment by Polymega** [comment]
This is still being shown in the log file:
```
217804 03:59:02.543 Environment variable __COMPAT_LAYER = "640X480"
```
I'd double-check Aero_'s suggestion of:

> Unless you changed the wrong exe or shortcut?

Are you launching the game through a **shortcut**? If so, make sure the "Run in 640 x 480 screen resolution" is also unchecked in the properties for the shortcut file.

**Comment by CKS417** [comment]
> Are you launching the game through a shortcut? If so, make sure the "Run in 640 x 480 screen resolution" is unchecked in the properties of both the main exe file and the shortcut file.

Yes correct, I tried what  **Aero_** suggested with the shortcut. I made sure to uncheck them both. Still doesn't work sadly.

**Comment by Polymega** [comment]
I re-read your original post. To clarify: When you set `EnableWndMode = 1` to test, did the game window take up the whole size of your display? Or was it small (640 x 480)?

I may've misread your original post, but I re-read it as you were trying to change the game's resolution through its options menu?

If so, currently, you cannot change the game's resolution through its options menu; it can only be done through the `d3d8.ini` file.

**Comment by CKS417** [comment]
> To clarify: When you set EnableWndMode = 1 to test, did the game window take up the whole size of your display? Or was it small (640 x 480)?

It went full screen, however it was still stuck in 640x480. Especially with both the menu and the Konami logo appearing pixelated.

> If so, currently, you cannot change the game's resolution through its options menu; it can only be done through the d3d8.ini file.

I've tried that, changing the 640x480 to 1920x1080 manually with the d3d8.ini file and saving it. But it automatically goes back to the previous resolution.

**Comment by AeroWidescreen** [comment]
@elishacloud Any ideas here? Could this be a problem with Windows 10 Enterprise? His game appears to be stuck in 640x480 compatibility mode and disabling it has no effect.

**Comment by elishacloud** [comment]
Compatibility settings are not always easy to change in Windows.  Not all options are available via the GUI.

First let's make sure you are editing the compatibility settings on the correct exe file.  You should be editing this file: `C:\Games\SH2\sh2pc.exe`

Secondly, if you are comfortable with changing registry settings you can delete the Silent Hill 2 entries from these two locations:

* HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers
* HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers

_Note: Be careful when editing the registry because you can cause irreparable damage to your operating system or applications from the registry._

There is also a compatibility tool you can download from [here](https://www.nirsoft.net/utils/app_compatibility_view.html) and run.  You should also be able to delete or modify the compatibility settings from this tool.

Thirdly, if the above two options don't work you can just rename the file.  The compatibility settings are based on the file name and path.  Just rename it from:

`C:\Games\SH2\sh2pc.exe`
 To:
`C:\Games\SH2\sh2pc_ee.exe`

Also make sure you update any shortcuts you are using so that it links to the new exe file.

**Comment by CKS417** [comment]
> First let's make sure you are editing the compatibility settings on the correct exe file. You should be editing this file: C:\Games\SH2\sh2pc.exe

Already tried this with **Aero's** advice and didn't work sadly. However with great news though!

> Just rename it from:

C:\Games\SH2\sh2pc.exe
To:
C:\Games\SH2\sh2pc_ee.exe

This worked! Now my games back in working order, thank you all so much for your time and help! I'm gonna continue supporting this project as much as possible <3
