### ISSUE TITLE
Game refuses to read Xbox controller.

### ISSUE THREAD

**Issue by CK252525** [elishacloud/Silent-Hill-2-Enhancements#337]
I've done literally everything I can think of, even applying Xinput and using a directinput controller. It works and runs perfectly otherwise, with the EE. I can't change the bindings ingame, it doesn't detect a controller at all. I know for a fact both of my controllers work perfectly.

**Comment by Polymega** [comment]
Hi there,
Please attach a copy of your `d3d8.log` file.

**Comment by CK252525** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5471787/d3d8.log)

**Comment by Polymega** [comment]
Looking at the log, SH2 PC is detecting and using the following, instead of your Xbox controller:

```
63212 16:10:04.455 |----------- GAMEPADS -----------
1988 11:10:53.634 |- Name: 'Monect Hid Device' GUID: {990A6CF0-108A-11EA-8001-444553540000}
```

SH2 PC detects and uses the first controller connected to your PC. Try removing other devices that Windows might think is a gamepad (in this situation, whatever "Monect Hid Device" might be). 

After you disconnect a device you might think is the culprit, you can relaunch the game and, if it still can't detect your Xbox controller, close the game, re-open the log file (which updates itself after every game launch), and see what device SH2 PC is still picking up first.

More info can be read here: http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#my-gamepad-is-not-being-detected-by-the-game

**Comment by Polymega** [comment]
Some others with similar problems: 
https://www.reddit.com/r/techsupport/comments/8un820/cannot_delete_hid_driver_help/
https://www.reddit.com/r/CrackSupport/comments/b4ve6k/i_think_ive_found_the_reason_my_360_controller/
https://www.reddit.com/r/SteamController/comments/coy6wn/steam_detects_two_controllers_but_i_dont_have_any/

If you follow any advice/tutorials on the internet, be cautious with what you adjust/edit/remove on your PC.

**Comment by CK252525** [comment]
Going into my System32 and deleting Monect entirely did it! Thanks!
