### ISSUE TITLE
Game stops when I try to open the map.

### ISSUE THREAD

**Issue by swatism7** [elishacloud/Silent-Hill-2-Enhancements#340]
This happens within the first 5 minutes of the game after I get the map. I press M, the screen fades into black, and nothing shows up. The music still plays. None of the keys do anything except for Esc, which closes the game. Still happens if I open the map from the inventory menu.
Any ideas?
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5478644/d3d8.log)

**Comment by Polymega** [comment]
Hi there,

I'm thinking it's because you're using an old integrated graphics processor (IGP):

```
1720 15:32:01.923 "Intel(R) HD Graphics"
```

The IGP may not be able to handle the high resolution of the maps. Do the HD fonts work for you by chance? Often times, older IGPs can't handle the HD fonts, either.

You can go to `\Silent Hill 2\sh2e\pic\` and **rename** the `map` folder in here to something else (such as `map_temp`). This will prevent the game from accessing/reading the high resolution map files and instead using the default, vanilla map files. You can do this to test if the vanilla map files load for you.

**Comment by swatism7** [comment]
I thought that was it.
Anyway, I tried it, and now it works. Thanks.
