### ISSUE TITLE
DPadMovementFix = 0 does not prevent me from walking using DPad

### ISSUE THREAD

**Issue by Kramst** [elishacloud/Silent-Hill-2-Enhancements#342]
I am using Xbox 360 Wireless controller. I assigned some actions to DPad (use health, map, inventory, light). They work fine, but since DPad is still accepted as movement input everytime I use them my character moves a bit. This isn't game breaking but it is annoying and I'd rather not have it happening.

**Comment by AeroWidescreen** [comment]
You're right. I think it has something to do with the XInput Plus configuration, which @Polymega might be able to help you with.

**Comment by Polymega** [comment]
Aero_ is correct, also open `XInputPlus.ini` and change `LS=LS|DPAD` to `LS=LS`.

The `DPadMovementFix` in our INI was done to fix it for DirectInput gamepads, but as a side bonus it also fixes it for XInput gamepads. 

I should probably change it to just `LS=LS` in the XInputPlus INI file, since our own `DPadMovementFix` fixes it now. And that way, if someone disables `DPadMovementFix` they won't have to also disable it in the XInput Plus INI.

**Comment by Kramst** [comment]
That did indeed fix the problem. Thanks!
