### ISSUE TITLE
Images in item menu are wrong or outright missing.

### ISSUE THREAD

**Issue by TheLegendOfGroose** [elishacloud/Silent-Hill-2-Enhancements#345]
As title said, they're either missing or warped versions of image files. This is after adding update 6's new image pack.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5489893/d3d8.log)
![Desktop Screenshot 2020 11 04 - 12 40 45 37](https://user-images.githubusercontent.com/73962144/98155091-56cd6e80-1e9b-11eb-8f11-b29d27902f73.png)

**Comment by Polymega** [comment]
Hello,

```
4432 12:40:20.199 Starting Silent Hill 2 Enhancements! v1.5.1750.0
```

You're using an older version of the SH2 Enhancements module. This old version doesn't have correct support for high res images. [Download the latest version here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v1.7.1850.0)

Looking at your log file some more:

```
4432 12:40:20.215 |- 11/04/2020  12:23 PM    <DIR>          d3d8
```

...it looks like you might have downloaded the newest version of the SH2 Enhancement module but placed it in a `d3d8` folder inside the game's main directory, instead of placing the files within the game's main directory?

[Here's a directory tree for reference.](http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree)

**Comment by TheLegendOfGroose** [comment]
Ah yes, that was it, forgot to put those in the main directory. Thank you!

**Comment by Polymega** [comment]
No problem. Glad it was an easy fix!
