### ISSUE TITLE
CameraEditor don't work for me SH2 NA version 1.0 

### ISSUE THREAD

**Issue by Rainnvod** [elishacloud/Silent-Hill-2-Enhancements#351]
Hi, I have SH2 NA Version, I did all the things in instruction but camera do not work. Camera Editor only starts but not working

**Comment by Polymega** [comment]
You also need to have Cheat Engine. At the time, when I made the cam editor, I did not realize you also needed Cheat Engine to make the editor work.

If you decide to download Cheat Engine, be very careful; certain installers for the software on their own site are questionable and dubious in nature. They'll ask you to install other software with it and it's not easy to find where to say "no" to these things. You can try this version of the download for hopefully the safest results:

![image](https://user-images.githubusercontent.com/27395260/99292554-5b851180-280f-11eb-8db6-a84fbb0f3c44.png)

Be sure to scan the download before doing anything with it.

**Comment by Rainnvod** [comment]
I have Cheat Engine 7.2 on my PC..what should i do with it?

**Comment by Rainnvod** [comment]
![image](https://user-images.githubusercontent.com/74556339/99294974-db35cf00-2855-11eb-906f-513b86565a45.png)

**Comment by Polymega** [comment]
If memory serves, you can drag + drop the camera editor tool (.exe) onto the Cheat Engine executable so that it launches through Cheat Engine. Assuming this works, and after you do this, _then_ launch SH2 PC and that should be it. 

If this still doesn't work let me know and I can give you another file to work with.

### Important note:
**Never** have Cheat Engine open when running Steam/Origins/etc. These gaming platforms will detect Cheat Engine as a cheating device and could ban you from any online games on their platforms! You can double-check Cheat Engine is fully closed by opening your Task Manager and ensuring the Cheat Engine process is no longer running.

**Comment by Rainnvod** [comment]
Then I drug and drop Editor I have this window of Cheat Engine
![image](https://user-images.githubusercontent.com/74556339/99295722-d3c2f580-2856-11eb-9d88-9169447e8882.png)

**Comment by Polymega** [comment]
Okay, let's completely ignore `sh2pc_camera_editor.exe` then. It's been so long I can't remember how to make it work that way. I just directly use Cheat Engine to work with the camera editor.

Download this Cheat Table and save it somewhere on your computer: http://www.igotaletter.com/temp/sh2pc/_UNIVERSAL_LIST.zip

- Open Cheat Engine as you've done
- Click the Folder icon at the top left to load a Cheat Table
   - Select the Cheat Table you downloaded
- Launch SH2 PC
- Click the computer monitor icon at the top left to select a process to open
   - Select sh2pc.exe

That should be it. [You can refer to these shortcut keys](http://etc.townofsilenthill.com/sh2pc_camera_editor/#controls) for use.

**Comment by Rainnvod** [comment]
Thx great! It works now !

**Comment by Polymega** [comment]
Great! I'll close this ticket then.

**Comment by selfd3struct1on** [comment]
Got a letter website is shut down, do you guys still have the free camera tool?

**Comment by Polymega** [comment]
The website is still running. Refer to these steps to utilize the camera editor: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/351#issuecomment-728266241
