### ISSUE TITLE
Is There a Standart Version of New Title Screen?

### ISSUE THREAD

**Issue by CHNSK** [elishacloud/Silent-Hill-2-Enhancements#352]
Hi all, not an issue per se, I just wanted to ask if there's an upscaled title screen I can choose without the Enhanced Edition sub title under the logo?

**Comment by AeroWidescreen** [comment]
No, not unless @Polymega has one that he's willing to share. 

You're welcome to make your own start background though. It has to be in the same resolution and aspect ratio if you want it to work.

**Comment by Polymega** [comment]
No, there isn't. After years of hard work I feel we've earned the right to have our project title on the project, and having our project title helps others become aware of the project (through streaming, sharing screenshots, etc).

**Comment by CHNSK** [comment]
Wow, I didn't mean to come as unappreciative for your work which I'm extremely grateful. It's just that since it's made new, I assumed you might have a standard version of the game's official title. While you wanting to advertise the mod is very reasonable, to be honest, it felt a little...intrusive. If we are talking about hard work, albert from Re4hd.com is making maybe the greatest HD texture mod since 2014 and he's just as faithful. So it's not about hard work and earning rights, at least this was not what I meant. But it's your ball, your rules...

**Comment by Polymega** [comment]
I apologize if I came across as overly defensive or you not being appreciative. That was definitely not the desired outcome I had with my response.

Looking back, I can see how that can come across the wrong way.

While the project is thankfully supported by most, I've funneled and taken the brunt of all the awful (I don't mean constructive, but truly hateful) comments over the years. A lot of what we do has pissed these people off and, according to them, have stained/ruined/spit on Team Silent's vision and made the game unfaithful. You'll have to forgive me if I'm straight to the point with such an answer; it's because of this which is no fault of your own.
