### ISSUE TITLE
Text and certain textures either loading incorrectly or not at all?

### ISSUE THREAD

**Issue by donodonodono** [elishacloud/Silent-Hill-2-Enhancements#355]
hey, im not very that good at installing mods for pc games in general (and this is also my first time using github, too. hope im doing this right..), so this could be an incredibly stupid issue im currently having, but i just wanna figure out how to get this game working again. strangely, the game only started doing this when i reached the other world jail. every time i open the game,  it does this, even after a reinstall.

heres some images to show the issue im currently having, and i'll include a log as well.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5611295/d3d8.log)

https://imgur.com/a/mPJ3Mkb

**Comment by Polymega** [comment]
It looks like you're completely missing the `sh2e` folder, which holds the improved audio, FMVs, fonts, etc.

And yet... it looks like you still have HD fonts without the `sh2e` folder?

My guess is that you placed all our custom files in the `data` folder, instead of the `sh2e` folder. This may likely be why you're also experiencing issues. 

- [Here is the purpose of the `sh2e` folder.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#what-is-the-purpose-of-the-sh2e-folder)
- [This is what you want your directory tree to look like after installing everything.](http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree)

My suggestion would be [to uninstall the game](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#how-do-i-fully-uninstallreinstall-silent-hill-2-pc-and-the-enhanced-edition-project-files) and start over. Before you do, go to `<path-to-game>\Silent Hill 2\data\` and make a backup of your `Folder 01` folder (your save files). After you reinstall everything, you can put that `Folder 01` folder back in  `<path-to-game>\Silent Hill 2\data\` so you don't lose your save files.

**Comment by donodonodono** [comment]
it worked! thank you for helping. it turns out i never even had enhanced edition ever really installed, only partly. the mistake i made was putting the sh2e files over the original files, which made it kinda fucky. surprised it even worked in the first place...anyways, again, thanks.
