### ISSUE TITLE
Invisible phone and more

### ISSUE THREAD

**Issue by SuperContra6** [elishacloud/Silent-Hill-2-Enhancements#364]
Hi.
Thanks for your hard work. A few comments and one question:

1. At one of the locations in the town there is an invisible phone (only a sign is visible and it has collision). Maybe, you can fix it:

![sh2pc 2021-01-13 19-41-57-73](https://user-images.githubusercontent.com/47208273/104553899-7e377900-564c-11eb-9ee7-741e9b0b8e81.jpg)
![sh2pc 2021-01-13 19-42-08-16](https://user-images.githubusercontent.com/47208273/104553905-7f68a600-564c-11eb-8f01-10ae4df7dd6d.jpg)

2. A miss on one of the maps of Image Enhancement Pack:

![sh2pc 2021-01-13 19-43-26-74](https://user-images.githubusercontent.com/47208273/104553942-8abbd180-564c-11eb-8140-436ec1a630bc.jpg)

3. What tools you are used for replacing textures in *.map files?

**Comment by Polymega** [comment]
Hi SuperContra6,

Thanks for the notes.

1. Good catch. This is something I think not many other people have ever noticed. I have a list of geometry edits I plan/hope to do for the game sometime in the future. I'll add this to the list. I can't promise I can fix it, but I'll certainly look into it when the time comes.

2. That's intentional. Once you get both maps, James will fold the Wood Side map over and on top of the Blue Creek map. Zooming out of the map to see the whole thing makes things clearer here.

3. You can use what's called the SH Texture Explorer, but we've since learned that it does bad things to the alpha channels of texture files, and can introduce further compression/artifacts to the textures themselves. As such, we on the team edit textures within .map files "by hand" (through hex editing).

**Comment by SuperContra6** [comment]
> 1. Good catch. This is something I think not many other people have ever noticed. I have a list of geometry edits I plan/hope to do for the game sometime in the future. I'll add this to the list. I can't promise I can fix it, but I'll certainly look into it when the time comes.

Okay. I'm sure you can do it.

> 2. That's intentional. Once you get both maps, James will fold the Wood Side map over and on top of the Blue Creek map. Zooming out of the map to see the whole thing will make better sense.

You did not understand me. Let's zoom in:

![1](https://user-images.githubusercontent.com/47208273/104612440-4144a400-5697-11eb-988b-f7d7b1da7d91.jpg)

The letter "A" is outside the bounds of the map "Wood Side Apartments". See:

![2](https://user-images.githubusercontent.com/47208273/104612470-49044880-5697-11eb-8a49-85ffbc126d98.jpg)

You need like this:

![3](https://user-images.githubusercontent.com/47208273/104612496-50c3ed00-5697-11eb-9ed1-ff5b19253a3d.jpg)

P.S. The "1F" map has the same problem.

> 3. You can use what's called the SH Texture Explorer, but we've since learned that it does bad things to the alpha channels of texture files, and can introduce further compression/artifacts to the textures themselves. As such, we on the team edit textures within .map files "by hand" (through hex editing).

Thank you for information.

**Comment by Polymega** [comment]
> The letter "A" is outside the bounds of the map "Wood Side Apartments". See:

I see. I'll fix that up then. There is a future planned update for the Image Enhancement Pack and I can include it there. Thanks.

**Comment by SuperContra6** [comment]
> 3. You can use what's called the SH Texture Explorer, but we've since learned that it does bad things to the alpha channels of texture files, and can introduce further compression/artifacts to the textures themselves.

However, there is some benefit from the incorrect operation of SH Texture Explorer: the grass looks better in a way:

BEFORE:
![1](https://user-images.githubusercontent.com/47208273/104711145-0a6f9c00-5732-11eb-9781-761aa3f25d63.jpg)
![2](https://user-images.githubusercontent.com/47208273/104711153-0c395f80-5732-11eb-8168-928d0a4f35fa.jpg)

AFTER:
![3](https://user-images.githubusercontent.com/47208273/104711209-1b201200-5732-11eb-9c43-0c08a2c2f12d.jpg)
![4](https://user-images.githubusercontent.com/47208273/104711216-1c513f00-5732-11eb-87bf-0862933171c4.jpg)

Is not?

**Comment by Polymega** [comment]
What you see in your "after" photos is black, "crusty" lines along the alpha edges. We can see this better using the beginning 2D trees. Notice the black, crusty edges on the 2D trees, which is caused by the SH Texture Explorer:

![image](https://user-images.githubusercontent.com/27395260/104765733-583ad300-5737-11eb-89ec-9b2eebaee179.png)

How do we fix this? We blur the edges of the texture while keeping the alpha channel sharp:

![tree alpha](https://i.imgur.com/1tjPyKt.gif)

If we do this and import the data through hex editing (bypassing the SH Texture Explorer), then there are no issues.

Here is what happens if we import this same texture + alpha channel using the SH Texture Explorer:

![image](https://user-images.githubusercontent.com/27395260/104765903-aa7bf400-5737-11eb-8213-924505fa2ce6.png)

Notice that the alpha channel has removed all the blurring we have applied to the tree texture. Because of this, there is now nothing but black color right past the pixels of the tree texture that the alpha channel uses. This is where the black, crusty lines then come from.

And as previously mentioned, the SH Texture Explorer also adds further compression/artifacts to re-imported textures, which is something we don't want. This is the other reason we do not use it.

**Comment by Polymega** [comment]
These issues have since been fixed.
