### ISSUE TITLE
black screen freeze

### ISSUE THREAD

**Issue by speccie223** [elishacloud/Silent-Hill-2-Enhancements#365]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5825153/d3d8.log)
when i open the game its just a black screen and then it says program is not responding
i could play the game before but it doesnt work anymore i dont know if im missing some files or what

**Comment by Polymega** [comment]
Thanks for the log file. Look at your log file, I can't immediately see anything that could be the issue. 

- The files/folders in your game's directory seem to be in place. (Although that extra `SILENT HILL 2` folder inside your `Silent Hill 2` folder isn't needed. Maybe try removing that from the game's directory?)
- You are not using XInput Plus or DSOAL, so those are ruled out as being the cause of your issue. 
- Nothing seems off/wrong in your INI settings.

Some questions I can think of:

1. Do you remember what files/packages you updated before this issue happened?
2. Do you have any compatibility settings enabled for the game? Right click `sh2pc.exe`, select **Properties**, then click the **Compatibility** tab. Ensure everything in their is unchecked/disabled.

**Comment by speccie223** [comment]
i didnt update anything i just followed the steps played once then it stopped working 
i tried everything you said but still does not work

**Comment by AeroWidescreen** [comment]
@Polymega Would this not be another problem with `SingleCoreAffinity`? According to the log he uploaded, his game freezes when attempting to do that. You're more experienced with solving issues here than I am; it's an honest question.

@speccie223 It wouldn't hurt to disable `SingleCoreAffinity` in the **d3d8.ini** file and see if it that gets you anywhere. Keep in mind that you have to use only one core or you're going to run into many issues, so don't get too excited and start playing the game if it does work.

**Comment by elishacloud** [comment]
> Would this not be another problem with `SingleCoreAffinity`? According to the log he uploaded, his game freezes when attempting to do that. You're more experienced with solving issues here than I am; it's an honest question.

No, it is unlikely that this is caused by `SingleCoreAffinity`.  The `SingleCoreAffinity` task is running on a separate thread by itself.  Even if the thread froze it would have no effect on the games functionality, other than that the game would still be running on multiple cores.

It is common for this to be the last line because this is the last things that sh2e module does during the initialization phase.  There are a few other things that log, for example the disk space is logged when you try and load or save a game.  But since this is one of the last initialization lines in the debug log, it is common for this line to to be the last line in the log if the game hangs.

I have recently [added several other logs](/elishacloud/Silent-Hill-2-Enhancements/commit/7e8590168e7e07eae93256554c9ab06f3e025dd9) to the debug log to help isolate where freezing like this comes from.  For example, I found out that if the sound initialization fails then the game will freeze.  In a recent check-in I added logs to log these types of failures in hopes to help us discover what is happening with these types of issues.

Here is the update with additional logs:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5825397/d3d8.zip)

**Comment by Polymega** [comment]
Thanks Elisha. @speccie223, please download the package Elisha provided (above) and replace the files in the game's directory with these new ones.

Then, launch the game. If it still hangs, please then upload a new copy of your `d3d8.log` file here.

**Comment by AeroWidescreen** [comment]
@elishacloud Ah, thanks for the explanation. What you've said makes perfect sense and I'll keep this in mind in the future. I've edited my post to not cause further confusion.

**Comment by speccie223** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5826136/d3d8.log)
still doesnt work when i added files

**Comment by Polymega** [comment]
Temporarily name `sh2pc.exe` to something else such as `sh2pc_ee.exe` and see if that launches the game for you.

**Comment by elishacloud** [comment]
@speccie223, I noticed you had this installed to: "C:\Users\caspe\OneDrive\Desktop\SH2\Silent Hill 2\"

This is a OneDrive folder.  I wonder if OneDrive is causing an issue.  Try moving the game to a different folder that is not under OneDrive.

Also, here is a full debug build.  This has lots of extra logging that may help see where the game is getting stuck:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5827176/d3d8.zip)

**Comment by Polymega** [comment]
No response so I'll close this out. Feel free to re-open this ticket for further troubleshooting.
