### ISSUE TITLE
Silent Hill 2 Taking Longer Than It Should To Launch

### ISSUE THREAD

**Issue by Endgame22** [elishacloud/Silent-Hill-2-Enhancements#368]
Hello, my game takes a minute or more to launch and I'm not sure why. My hardware is more than good enough. Ryzen 3700x, 2070 Super GPU, 32gb RAM. 
Here is the d3d8.ini file. Thanks.

**Comment by Polymega** [comment]
Hi there, 

I edited your post to remove the INI string. Could you please upload a copy of your `d3d8.log` file? (Upload it as a file in your response.) Your log file will also include the INI settings you originally posted.

**Comment by Endgame22** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5846797/d3d8.log)

**Comment by Polymega** [comment]
Perfect, thanks. Everything looks to be in order with the log file. There's two things that immediately come to mind with what might be taking the game a while to launch.

Please try these things one at a time (try one first, before doing the other):

- Open the `d3d8.ini` file and set `d3d8to9 = 0`.

If the game still takes a while to launch set `d3d8to9 = 1` then:

- Temporarily remove the following files from the game's directory:
   - `dsoal-aldrv.dll`, `dsound.dll`

**Comment by Endgame22** [comment]
Ah, the first suggestion worked. Thanks!

**Comment by Polymega** [comment]
Glad we pin-pointed it! As for why d3d8to9 is making the game take a long while to launch I'm not sure, as this is not a common issue reported to us. But perhaps it's something that can be looked into at a future time.

_Do note that disabling `d3d8to9` will also disable all the features found under the `[SHADERS]` header within the `d3d8.ini` file._

**Comment by Endgame22** [comment]
I see. Odd. I added the audio enhancements, so maybe I'll see if that solution works too. I'll enable d3d8to9 again and try. Also I see in game options it only shows 7.1 audio and theres no other options like stereo. Is this normal? Will I get good audio even without surround setup?

**Comment by Endgame22** [comment]
So removing those audio files in the folder while enabling d3d8to9 also works, and now audio option is only stereo which makes sense. Other than more 3D sound space, does removing those files lessen quality? Thanks again

**Comment by Polymega** [comment]
In regards to the audio: When SH2 released back in the Windows XP days, applications (such as SH2 PC) were allowed to change your audio output device. But from Windows Vista and onwards applications can no longer do this (it must be manually changed by the user themselves through Windows' Sound Control Panel). Because of that, we've locked the ability to change this through SH2 PC as it doesn't actually change anything.

When using DSOAL (`dsoal-aldrv.dll` & `dsound.dll`) to restore 3D positional audio for the game, SH2 PC may detect your audio output as 7.1 surround (as DSOAL is "spoofing" this to restore positional audio).

You can open the `alsoft.ini` file to adjust settings for DSOAL to see if the game will launch faster for you. DSOAL is created and maintained by a third party, and I'm largely unfamiliar with how its INI settings affects things. [But you can read up on it some here](https://github.com/kcat/openal-soft/blob/master/alsoftrc.sample) if you'd like to play around with its settings.

----------------------------------

> Other than more 3D sound space, does removing those files lessen quality?

No. So long as you've download the Audio Enhancement Pack, DSOAL doesn't affect the quality of the Audio Enhancement Pack files. DSOAL just presents any audio its given with 3D positional effects.

I did forget to mention that if you want to remove DSOAL from the game, you should also remove `alsoft.ini` (that's the settings file for DSOAL).

> So removing those audio files in the folder while enabling d3d8to9 also works

It's interesting that _either_ disabling d3d8to9 _or_ removing DSOAL fixes the issue of the game taking a significantly long time to launch for you. This makes it a bit trickier to know for sure which one is the real culprit. (I would assume, DSOAL though.)

**Comment by Endgame22** [comment]
I'll make matters even weirder for you, putting everything back to the way it was it all works fine now! I installed all of this last night and tested it then as well. Perhaps the PC just needed a restart to make game work?

**Comment by Polymega** [comment]
> Perhaps the PC just needed a restart to make game work?

I know the first thing people in IT ask to those who call about a computer problem is, "Did you restart the computer?" ... Looks like the old adage still works! 🤣

**Comment by Endgame22** [comment]
Lol sorry for the trouble! Thank you for your help, and if I do run into issues again I'll try those suggestions you first made

**Comment by Polymega** [comment]
No problem. Glad it ultimately worked out to where you can still use all the files/packages. I'll close this ticket out.
