### ISSUE TITLE
Advanced Options Save Confirm Bug

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#370]
@belek666 
I've found a small bug with the Advanced Options menu and wanted to ask if this is something you could look into? This issue is not critical, so if you wouldn't mind helping, please review this at your leisure:

https://youtu.be/UIOLbo_42XM

I noticed when the "Change the settings?" box appears within the Advanced Options screen, it will make the text description at the very bottom either disappear or show the wrong text string. It will also either disable or incorrectly apply the "3D effect" on certain text choices (refer to the images below).

- This appears to be a vanilla PC bug
- This happens with any language selected
- This happens with all three executables
- This does not happen on any of the other Option screens (only Advanced Options screen)

--------------------------------

Not sure if it's related to the bug, but I've noticed that if "Noise Effect" is highlighted when the pop-up box appears, it no longer has the 3D effect. If "Shadows" or "Fog" was highlighted when the pop-up box appears, then it incorrectly highlights "Advanced Filters" while the pop-up box appears (this can also be seen in the video linked above). 

Examples:

![Screenshot 2021-01-27 16-39-34](https://user-images.githubusercontent.com/27395260/106058162-e2335600-60be-11eb-8786-75d295314a81.png)
![Screenshot 2021-01-27 16-39-44](https://user-images.githubusercontent.com/27395260/106058165-e3648300-60be-11eb-914a-bdcdd853e1b0.png)
![Screenshot 2021-01-27 16-40-00](https://user-images.githubusercontent.com/27395260/106058170-e52e4680-60be-11eb-8c47-259b38bb0fc7.png)
![Screenshot 2021-01-27 16-39-50](https://user-images.githubusercontent.com/27395260/106058172-e65f7380-60be-11eb-98f5-3acc8fa704de.png)

**Comment by nipkownix** [comment]
Had a look at this. Apparently, the text descriptions at the bottom of the screen are incorrect because the confirmation prompt isn't just an overlay sitting on top of the options, but instead a "replacement". When the prompt is showing, the options that should still be below it are removed. Here's what it looks like when I make the prompt invisible:

![image](https://user-images.githubusercontent.com/33870163/154966708-223a84ca-2f93-43b7-8dea-5d128d943322.png)

You mentioned the prompt in the advanced options screen is the only one doing this, so I imagine the other ones are not removing the options, just hiding them below the prompt.
