### ISSUE TITLE
PS2 CGI preservation

### ISSUE THREAD

**Issue by levonnn** [elishacloud/Silent-Hill-2-Enhancements#373]
Are there any plans to add 4:3 authentic PS2 videos as an option? Without extra filters (sharpening etc) and cropping. Just de-interlaced and re-encoded for 4:3 resolution, with no extra filtering, with correct black bars on top and bottom, that match black bars in engine cutscenes if played in 4:3? Left as is for those who prefer purist experience.

**Comment by Polymega** [comment]
Hello,

Sorry, there are no plans to offer multiple versions/packages of the FMVs at this time.

**Comment by levonnn** [comment]
Oh well. I think it's part of the legacy and worth preserving. The definitive vanilla experience. I hope it won't be overlooked, at least in the future.

**Comment by Polymega** [comment]
It's a long read, but I'd kindly ask you to read a recent interview we had to get a better understanding of our goals and intent with the project: https://www.silenthillmemories.net/sh2/enhanced_edition_en.htm#interview

**Comment by levonnn** [comment]
> **Elisha:** Yes. One of my goals is to try to help the community preserve older games.

I'm with Elisha here.
In the end, I don't see how it harms the project or your goals. You created a massive .ini with stuff that can be enabled and disabled, adjusted to particular preferences. If you have a single vision for it, why bother then? Just lock it up as you see fit. I don't think it's the question of pleasing every last fan out there. There are just things that are worth keeping, because they're integral parts of Silent Hill 2 experience. For example, like original 4:3 aspect and low resolution. And there's luxury in having it on PC platform, because it can be extensively customized. You already offer your improvements in chunks, so anyone can install or not install parts of it. I, for example, don't use hi-res 2D art, because I prefer vanilla low-res grungy look of the game, which helps conceal low poly models, uneven facial animations and low-res textures of the game.

I'm negative towards additions like fridge cord, because I believe that when something is released to the world, it's imperfections is part of the legacy (with exception of outright broken products), part of public consciousness, part of gaming history. So some mods, even if intention is good, are too intrusive and should be optional.

**Comment by Polymega** [comment]
I don't know what to say then. Sorry. We try to be very accommodating with what can be toggled, as you said, but there's also things that are limited for one reason or another. For a large package such as the FMVs, we don't want to manage/edit/maintain multiple versions of it, for a few reasons.

If I were to deinterlace the PS2 videos and do nothing else to them as you suggested, someone else will say that's not authentic anymore since the fps is no longer 59.97i. For us, it's accepting that we can't please everyone, but trying to find the solution that pleases the majority. And for our project, the majority of people who use it do so for a better HD experience of the game.

**Comment by Badore90** [comment]
> Are there any plans to add 4:3 authentic PS2 videos as an option? Without extra filters (sharpening etc) and cropping. Just de-interlaced and re-encoded for 4:3 resolution, with no extra filtering, with correct black bars on top and bottom, that match black bars in engine cutscenes if played in 4:3? Left as is for those who prefer purist experience.

Anyway most of what you're requesting (4:3 videos as original with correct bars) is already settable with option 3 of _FMVWidescreenEnhancementPackCompatibility_ 

Toggling some options (4 or 5) you can have a perfect 4:3 experience (either in gameplay, cut-scenes and FMVs) keeping all the EE improvements. 
I use to play it on a 4:3 CRT monitor sometimes (I made a separate d3d8.ini with 4:3 settings, so i just have to switch the ini file when connecting to a 4:3 screen).

**Comment by snigelpasta** [comment]
> I don't know what to say then. Sorry. We try to be very accommodating with what can be toggled, as you said, but there's also things that are limited for one reason or another. For a large package such as the FMVs, we don't want to manage/edit/maintain multiple versions of it, for a few reasons.
> 
> If I were to deinterlace the PS2 videos and do nothing else to them as you suggested, someone else will say that's not authentic anymore since the fps is no longer 59.97i. For us, it's accepting that we can't please everyone, but trying to find the solution that pleases the majority. And for our project, the majority of people who use it do so for a better HD experience of the game.

Is it not feasible to have one 4:3 cutscene pack that can be scaled according to how you set the .ini? So the information in the original cutscenes is always there but the video can be stretched so the top and bottom is cropped?

I also think it's preposterous to cut off a big chunk of Takayoshi Satos work in a way that cannot be reversed (within the project.)

I also agree the idea with the fridge cord is terrible. For all we know the developers could have done this on purpose, but even if it wasn't, if the goal of the project is to preserve the original game then it's none of your business to reinvent it.

**Comment by Polymega** [comment]
> I think it's preposterous to cut off a big chunk of Takayoshi Satos work in a way that cannot be reversed

All we've did is remove the videos' built-in letterboxing. I wouldn't consider that a part of Mr. Sato's work.

> if the goal of the project is to preserve the original game then it's none of your business to reinvent it.

It's never stated on the site or in that interview that the project is about 1:1 preserving the game. You're focusing on one line said by Elisha and ignoring the rest of the what was said and the project's general mission. Just remove the file if a power cord is such a terrible thing for you. hp190.map

**Comment by TommvinHuwaltzky** [comment]
the "issue" with the power-cord I can understand (thanks Poly for giving the file-name btw :P), but the videos ARE perfectly preserved. you don't HAVE to crop them. that comes across as arbitrary whining.
and "low resolution" is an "integral part"? nonsense. don't you think that if the PS2-hardware would have been more powerful that the game wouldn't have had a higher resolution? what do you think people that played the vanilla-PC-version back then did?
they played it at a higher res than 480p. was that not integral to the spirit of Team Silent?
why do you think they made the PC-version of Silent Hill 3 run at 60fps? because it's better. they didn't care for an "extra-cinematic" experience (since cinematic is 24fps, not 30). they just COULD, because PCs are more powerful. so they did. they'd have done it if the PS2 had been more powerful.
think before you post, just saying....

**Comment by Badore90** [comment]
> the "issue" with the power-cord I can understand (thanks Poly for giving the file-name btw :P), but the videos ARE perfectly preserved. you don't HAVE to crop them. that comes across as arbitrary whining.
> and "low resolution" is an "integral part"? nonsense. don't you think that if the PS2-hardware would have been more powerful that the game wouldn't have had a higher resolution? why do you think all the remasters on console have higher resolutions? what do you think people that played the vanilla PC-version back then did? they played it at a higher res than 480p. was that not integral to the spirit of Team Silent?
> why do you think they made the PC-version of Silent Hill 3 run at 60fps? because it's better. they didn't care for an "extra-cinematic" experience (since cinematic is 24fps, not 30). they just COULD, because PCs are more powerful. so they did. they'd have done it on the console if the PS2 had been more powerful.
> by your logic the per-pixel-lighting should NOT have been in the PC-version of part two, nor in any version of part three. because it's "high/er-res".
> think before you post, just saying....

I didn't knew Silent Hill 3 runs at 60fps on PC, interesting, I only played it on Ps2.

Anyway, considering any hw source connected to the correct type of  monitor,  FMVs on EE look similar to Xbox. 
On Ps2 they're actually clearer, since they have the best/original compression and above all, because they run at 60fps.

Really, SH2 FMVs played from ps2 connected to a good CRT TV with scart-rgb cable, are crystal clear (i.e. the beginning bathroom scene, where there's no fog or other effects that dirty the picture). So making the EE FMVs less polished won't raise the fidelity with the original version, but it's true the opposite.

Obviously if you connect the Ps2 to a digital tv you'll see a dirty mess... That's not the correct way to judge it.

@ **levonnn** Imho you've done well making your report. Each of us has a different sensitivity, you can notice something I can't and viceversa.

Indeed it's good to never do such jobs alone (for example, when correcting the italian translation Bruno and I brutally corrected each other a lot of times... To have a opposition is fundamental for checking if a choice is a good one or not).

About the fridge cord, I think it is not a so bad choice.
Mybe there could be some meaning about Maria seeing in the dark firstly? But then they added the light on the fridge, so I don't think that adding the power cord would ruin any meaning (also other domestic appliances  in the game have cords, lights in corridors, aren't supposed to be self-lighted, just normal electric lamps on "normal" condominiums).

That said i understand your point, and it's a good thing having the possibility to remove it.

There's only one change that I disagree with on this EE so far. But being it an ongoing project there's always hope for some modifications... But it isn't related to FMVs, I think they're good as they are. Sure at 60fps they would be even better.

**Comment by AeroWidescreen** [comment]
> About the fridge cord, I think it is not a so bad choice.
> Maybe there could be some meaning about Maria seeing in the dark firstly? But then they added the light on the fridge, so I don't think that adding the power cord would ruin any meaning (also other domestic appliances in the game have cords, lights in corridors, aren't supposed to be self-lighted, just normal electric lamps on "normal" condominiums).

And it can be argued that in a world like SIlent Hill, where impossible spaces, teleporting doors, and other supernatural phenomenon are normal occurrences, a power cord is not necessary to explain why a refrigerator is lit in an empty hospital filled with monsters.

But, as you mentioned, it's not inconsistent with what's already been established, there's evidence that it may have been an oversight by the developers, and (as far as I know) it doesn't conflict with any lore or destroys the meaning behind the scene. This is generally why I have no strong feelings for or against the power cord. 

Personally, I would remove it just so I don't have to read another complaint about how we ruined the SH2 experience. As if the existence of this power cord, among other minor changes, are the equivalent to what George Lucas did to the original Star Wars trilogy. Pyramid Head shot first, and CGI Walter Sullivan can be seen lurking in the background.

**Comment by Polymega** [comment]
That's correct. It's never been established in the lore that Alessa can telepathically power appliances.

> Personally, I would remove it just so I don't have to read another complaint about how we ruined the SH2 experience.

It wouldn't matter, as I intend on making the observation deck's 2D trees 3D, the balcony handrail in hotel room 312 3D, and add geometry to the incomplete window in Blue Creek room 203. People will say I'm ruining SH2 with that, as well.

I've went into someone's stream where they complained for 10+ minutes (it was so long I started to time it) about me adding a light bulb and support wires to a lamp shade. They said "I have mental issues" because I have the audacity to change things. 

My rant here is not towards anyone in this thread. Most people are supportive and even kind towards the project. But it only takes a few awful people to make me feel like a terrible person. I've had to delete some YouTube comments because they were that bad. I haven't read or responded to any YouTube comments on our videos in months because of those few people who go out of there way to be spiteful. Those things stick with you, and I'm only human.

I've been involved in some form or fashion with nearly every fix/feature for the game, but let's ignore that, as I apparently don't know anything about the game and just want to spit on SH2. I've spent literally _hundreds_ of unpaid hours on this project as I just want to ruin the game for everyone.

![image](https://user-images.githubusercontent.com/27395260/107839346-4752a100-6d79-11eb-86d6-994937bb8d23.png)

**Comment by AeroWidescreen** [comment]
I still think an installer would be the best solution, where specific files or settings won't be used or included based on what people select.

### Enhanced Audio
 -PS2 Source Quality Files
 -DSOAL Surround Sound
 
 ### Enhanced Images
 -AI Upscaled & Remastered Images
 -Widescreen Menu Backgrounds
 -HD Fonts
 -HD Cursor
 
### Enhanced Effects
-SMAA
-Color Correction
-PS2 Noise Filter
-PS2 Fog
-Soft Shadows

### Enhanced 3D Modeling
etc.

But hey, I know it's easier said than done.

**Comment by TommvinHuwaltzky** [comment]
> I've went into someone's stream where they complained for 10+ minutes (it was so long I started to time it) about me adding a light bulb and support wires to a lamp shade. They said I have "mental issues" because I have the audacity to change things.

yeah, I've watched that stream.
as much as I like that guy, he can be a bitter asshole sometimes. well, a lot of the time... -.-


some of the changes are a bit polarizing, but you can't ask the devs on any little detail (esp. after all these years) if it's ok to change them or not.
so imo a good solution to this would actualy be to have ppl decide via an installer or to give the exact name of the file/s that's been altered.

**Comment by Polymega** [comment]
An installer is on the wish list for us. If it happens, there's a chance it'll be one of the last things done. Mostly because we're still changing packages as we go along (like the recent removal of ReShade or changing IndirectSound for DSOAL).

However, for my to-do list, I've had planned to make an Excel sheet or something cataloging all the changes I've made to the .map files. I plan to sit down and work on this once I get all the remaining edits I need to do done.

> the Silent-Hill-Series (and I mean the ACTUAL games, parts 1 through 4) always were works of passion, and so is your Enhanced Edition.

That's a very sweet thing for you to say. Thank you.

**Comment by Badore90** [comment]
> And it can be argued that in a world like SIlent Hill, where impossible spaces, teleporting doors, and other supernatural phenomenon are normal occurrences, a power cord is not necessary to explain why a refrigerator is lit in an empty hospital filled with monsters.
> 
> But, as you mentioned, it's not inconsistent with what's already been established, there's evidence that it may have been an oversight by the developers, and (as far as I know) it doesn't conflict with any lore or destroys the meaning behind the scene. This is generally why I have no strong feelings for or against the power cord.

Yes. We know it's a "metaphoric/spiritual" world let's say, so anything can happen. But at the same time what happens in James mind (or in the other world...) has memories of the actual world as a base. It is not a completely fantasy world with floating things and strange characters like i.e. Psychonauts, it is based on the actual world (in a quite detailed way also), so lamp cord or not there's no so much difference, because that's a strange situation considering the location and the point of the game where it happens (it is already strange to have that fridge there, strangely difficult to open, with that strange ring inside, so even if it lighted without a cord, things wouldn't be much weirder).

In other cases, where the setting has mostly a normal decor, it is good to correct those shortcomings, like the lamp holders and other missing things that have been corrected.

But again some people could have always seen those absences as intended subliminal clues for making the most observant players noticing that nothing was right...

Not a easy task :D

**Comment by snigelpasta** [comment]
> > I think it's preposterous to cut off a big chunk of Takayoshi Satos work in a way that cannot be reversed
> 
> All we've did is remove the videos' built-in letterboxing. I wouldn't consider that a part of Mr. Sato's work.
> 
> > if the goal of the project is to preserve the original game then it's none of your business to reinvent it.
> 
> It's never stated on the site or in that interview that the project is about 1:1 preserving the game. You're focusing on one line said by Elisha and ignoring the rest of the what was said and the project's general mission. Just remove the file if a power cord is such a terrible thing for you. hp190.map

Okay, thanks for clearing things up, and thanks for the file name.
And sorry if I came off rude.
