### ISSUE TITLE
Noise on black bars in 4:3 mode.

### ISSUE THREAD

**Issue by levonnn** [elishacloud/Silent-Hill-2-Enhancements#374]
I noticed there's noise during CGI cutscenes on black bars if it's enabled and played in 4:3 resolution (I played in 640x480). But during engine cutscenes, black bars on top and bottom are completely black. So for consistency noise should be present or not in both cases. I remember noise was over black bars on PS2, so maybe it's worth keeping or make it optional.

**Comment by levonnn** [comment]
I checked PS2 version and there's no noise on the bars during CGI, but engine cutscenes have noise on them. Looks like Enhanced Edition has it in reverse. :)

**Comment by Polymega** [comment]
> I checked PS2 version and there's no noise on the bars during CGI, but engine cutscenes have noise on them. Looks like Enhanced Edition has it in reverse. :)

Yeah, there doesn't seem to be a consistent setup with the noise filter and letterbox layering for the FMVs/in-game cutscenes on various platforms. 

For the original FMVs, the letterboxing is part of ("baked in") to the video files themselves. And the PS2/Xbox version appear to completely disable the dynamic noise filter while the FMVs play. That's why you don't see noise on top of the bars for FMVs. The PC version keeps the noise filter playing on top of FMVs (if enabled).

Putting aside the issue of the noise grain sitting on top of the letterboxing, the question that would come from this is: Which is better? A consistent noise grain between FMV/in-game cutscene/normal gameplay (PC)? Or disabling the grain during FMVs (PS2/Xbox)? My vote is likely for the former.

For 4:3 users, a possible idea is to call/insert the dynamically made letterboxes (what the game uses for in-game cutscenes) for the FMVs, so these black bars will sit on top of the noise filter/FMVs.

**Comment by levonnn** [comment]
> Putting aside the issue of the noise grain sitting on top of the letterboxing, the question that would come from this is: Which is better? A consistent noise grain between FMV/in-game cutscene/normal gameplay (PC)? Or disabling the grain during FMVs (PS2/Xbox)? My vote is likely for the former.

I frankly never understood why grain was on top of black bars during engine cutscenes. Is it an oversight? Is it intended? I kinda feel it's not up to me, rather does it serve any artistic purpose or it's just a mistake? If it adds something to the experience, we should probably keep it the way it was on PS2 (remove it during FMVs, keep it during engine cutscenes). If it doesn't, then I'd rather have some consistency: if the noise is kept, then it should be present in both FMVs and ingame, if not, then remove from both.

> For 4:3 users, a possible idea is to call/insert the dynamically made letterboxes (what the game uses for in-game cutscenes) for the FMVs, so these black bars will sit on top of the noise filter/FMVs.

Looks like a good solution. If technically viable.

**Comment by elishacloud** [comment]
This issue has been fixed in the latest update.  The noise filter will only cover the FMV not the pillarboxes.

Here is the update:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6588165/d3d8.zip)
