### ISSUE TITLE
game freezing/crashing at same point each time

### ISSUE THREAD

**Issue by megawizards** [elishacloud/Silent-Hill-2-Enhancements#377]
hello! i am new to using the enhanced edition (i installed it last week) and after finally playing it today - after everything running smoothly - i have encountered the game crashing at the exact same part as i am running down a street, just a few minutes after the cemetery scene with angela (i believe it is before it's intended to load into a new area). i have tried a few troubleshoots but i am not the best at getting down the nitty gritty when it comes to discovering the root of an issue with this. i will attach the log and screenshot where i encounter the crash. 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5921902/d3d8.log)
![Screenshot (49)](https://user-images.githubusercontent.com/78510600/106816992-394ba480-6644-11eb-88ad-71179f456742.png)

**Comment by Polymega** [comment]
Hi @megawizards,

This is the first time we've heard a report on such an issue. Since you've installed the game over a week ago, you've probably already done this, but the first thing I'd recommend is restarting your computer. Sometimes a simple restart is all it takes.

Because it's crashing at the same point I think you're right that the game isn't loading the next town chunk properly. I'm not sure why that might be. To be sure: Did you place all the files from the various enhancements packages within the `sh2e` folder and **not** the `data` folder? (The `data` folder should be left untouched.)

Looking at your log file, I see some extra files in the game's directory that shouldn't be there. This may be causing the problem. [You want your directory tree to look like this.](http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree) Try removing the following files/folders from the game's directory:

```
\dxsetup\
Autorun.exe
autorun.inf
data1.cab
data1.hdr
data2.cab
data3.cab
data4.cab
kernel.ex_
layout.bin
Setup.bmp
Setup.ini
setup.inx
```

Also, it looks like you're missing two files that are a part of [the SH2 Enhancements module](http://enhanced.townofsilenthill.com/SH2/install.htm#installSH2Enhancements): The `d3d8.ini` and `d3d8.res` file. Try re-downloading the SH2 Enhancements module. 

If all else fails, a fresh re-install of everything might fix the issue. The directory tree I linked above shows you what files should be installed with the base (vanilla) game, and what additional files will be added when downloading the other packages.

@elishacloud 
He's using the latest build and this line is still present:
`7416 17:14:12.151 Environment variable __COMPAT_LAYER = "640X480 Installer"`

Just so I know in the future, would such lines still be shown in the log if `CheckCompatibilityMode` is enabled?

**Comment by Polymega** [comment]
Also, I just noticed you have the INI file for DSOAL (`alsoft.ini`) but not the DSOAL files themselves (`dsoal-aldrv.dll` and `dsound.dll`). Including what I mentioned about some of the SH2 Enhancements modules being missing, it looks like various files were removed and foreign files have been added to the game's directory. This might be the cause of the stability issues.

**Comment by elishacloud** [comment]
> @elishacloud
> He's using the latest build and this line is still present:
> `7416 17:14:12.151 Environment variable __COMPAT_LAYER = "640X480 Installer"`
> 
> Just so I know in the future, would such lines still be shown in the log if `CheckCompatibilityMode` is enabled?

Yeah, the new `CheckCompatibilityMode` option cannot remove all compatibility options.  However, in this case it will just relaunch the game as admin preventing the compatibility options from taking effect.  As you can see from the screenshot, he is not actually running in "640X480".

I think there may be something wrong with his install.  Maybe there are some missing files?

**Comment by megawizards** [comment]
thank you for the responses! i think i had a lot of confusion with the emulator i had to download for the game, where some files had the same name and i may have left files where they shouldn't be? i'm thinking a fresh install of both the emulator and enhanced edition will give me a clean slate, possibly.

**Comment by Polymega** [comment]
I'd probably recommend doing a fresh install. Once you install the base game, check the directory tree I linked to make sure you only have those files installed, before proceeding to download all the other packages on our site. (Note some files for the base game aren't created until you launch the game for the first time; these specific files are mentioned as such on that directory tree).

And to clear up terminology: Our project is for the PC version of Silent Hill 2. The PC version is a native application to Windows, so it's not using an emulator. You _can_ play the PS2 version of Silent Hill 2 through a PS2 emulator such as PCSX2, but our project and the version of SH2 it works with is not an emulator.

**Comment by megawizards** [comment]
thank you very much! would it work if i did use the ps2 emulator, or would i have to use the physical pc version?

**Comment by Polymega** [comment]
No, our project only works with the PC version ([either version seen at the bottom of this page](https://www.silenthillmemories.net/sh2/versions_en.htm)). 

You definitely have a copy of the PC version (going off your log files and that you've gotten the game to run in the first place), so I'd still recommend re-installing everything, and making sure all the files are accounted for as what's seen in [the directory tree](http://enhanced.townofsilenthill.com/SH2/install.htm#directoryTree).

**Comment by megawizards** [comment]
i've uninstalled everything and will do a fresh install of everything and be more thorough going through steps! thanks for the help and dedication.

**Comment by Polymega** [comment]
No problem and good luck! One of the final-final things we'd like to do is make an installer for all our project files (once everything is more-or-less set in stone on our end). Until then, you'll have to extract all the packages one-by-one. 😵 

But first we'd _reeeeaaallllyyy_ like [GOG](https://www.gog.com) to just release SH2 & 3 PC digitally, same as they've done with SH4. It would make our lives easier, as we don't know what extra files are added to SH2 PC when people download it from the internet.

**Comment by megawizards** [comment]
the issue certainly seems to be coming from the game install, so that would solve so many issues. your enhanced edition, though, is incredible so i hope i can get it working to jump back into it!

**Comment by megawizards** [comment]
just a quick update, the full uninstall/reinstall worked and i was able to get past the part i was originally crashing at! thanks again for you assistance.

**Comment by Polymega** [comment]
Huzzah! Glad to hear it. 🥳
