### ISSUE TITLE
Music is often looping

### ISSUE THREAD

**Issue by Salammbo09** [elishacloud/Silent-Hill-2-Enhancements#378]
I've never played Silent Hill 2 before, thanks for all that has been done on this enhanced version. I had a great time on it!

Unfortunately I had this music problem that makes an endless loop. It sometimes made the game freeze (I think it does, I had to force the game stop when i tried to reload the game or anything that could have relaunched the music). The game didn't freeze that much but this music problem happened everytime i played.

Well i expect a problem with my CPU or Windows 10. I tried to change the single core affinity option several times but it didn't change anything.

This is my file [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5922391/d3d8.log)

Also I played the game in French. I'm sorry that I can't devote time to development because the translation is sometimes quite bad even in the menus, and it's full of mistakes. I would have liked to help.

**Comment by Polymega** [comment]
Hello, 

Sorry you're having troubles with the audio looping. That is typically because the game is running on multiple CPU cores. But looking at your log file, everything seems to be in order.

> Well i expect a problem with my CPU or Windows 10. I tried to change the single core affinity option several times but it didn't change anything.

Yeah, that was the first thing I was going to suggest to do.

I'd at least set `SingleCoreAffinity` back to a value of `2` or `3` then. This will use a different CPU core on your computer, in case the first core has too many processes already running on it (which could bog down the game).

--------------------

I noticed the game is using your Intel HD Graphics as your graphics processor. I Google searched your motherboard (ASUSTeK COMPUTER INC. K501LX) and it looks like that line of laptop usually features a dedicated Nvidia graphics card? If so, [try setting SH2 PC to run on your Nvidia card instead](https://www.techadvisor.co.uk/how-to/pc-components/how-set-default-graphics-card-3612668/). The bump in graphics processing may help with ensuring the game runs smoothly (to decrease the chance of audio desyncing).

--------------------

You can also try temporarily removing the DSOAL files from the game's directory (`alsoft.ini`, `dsoal-aldrv.dll`, and `dsound.dll`) to see if that fixes the issue.

--------------------

I also saw these lines in your log file, which I've never seen before:

```
52476 23:58:03.219 Redirecting IDirect3DDevice9::Reset(this = 16DD96A0, pPresentationParameters = 0019FD2C) ...
52476 23:58:03.224 Destroyed runtime environment on runtime 16DD9D20.
52476 23:58:03.341 Recreated runtime environment on runtime 16DD9D20.
```

I think these lines might relate to `d3d8to9`. You can try setting `d3d8to9 = 0` to see if that fixes the audio problem.

**Comment by elishacloud** [comment]
> I also saw these lines in your log file, which I've never seen before:
> 
> ```
> 52476 23:58:03.219 Redirecting IDirect3DDevice9::Reset(this = 16DD96A0, pPresentationParameters = 0019FD2C) ...
> 52476 23:58:03.224 Destroyed runtime environment on runtime 16DD9D20.
> 52476 23:58:03.341 Recreated runtime environment on runtime 16DD9D20.
> ```
> 
> I think these lines might relate to `d3d8to9`. You can try setting `d3d8to9 = 0` to see if that fixes the audio problem.

These are new logs added from the shader code.  This basically just means that the the game reset the display.  This will happen if you alt+tab out and then run some application that shows a UAC window.  It is normal and probably not related to the sound issue.

The sound issue is a multi-threading issue with the actual game code.  We added `SingleCoreAffinity` which can avoid the issue in most cases.  However, if the drive is running too slowly or too fast the threads could still get out of sync.  The threading issues were supposed to be fixed in v1.1 of Silent Hill 2, but v1.1 still has issues.

@Salammbo09, there are a few things you can try:
1. You can try using different CPUs.  Just set `SingleCoreAffinity` to different values and see if another CPU maybe has less issues here.
2. You can try disabling the `SingleCoreAffinityTimer`.  Just add `SingleCoreAffinityTimer` to the ini file and set it to `0`.
3. Try disabling your antivirus and/or other security products.  Sometimes security products will change the speed at which the audio files are accessed and cause the threads to get out of sync.
4. Try using release build 1850 instead of 1860, just in case the new changes to `SingleCoreAffinityTimer` are causing this issue.  Note: make sure to remove `SingleCoreAffinityTimer` from the ini file if you do this.

Let us know if any of these solutions helped or not.

**Comment by Salammbo09** [comment]
Thanks for the answers. Just to let you know I've read you and I'll tell you the next I'll try to play the game.

**Comment by Polymega** [comment]
No follow-up so I'll close this ticket out. Feel free to re-open for further troubleshooting.
