### ISSUE TITLE
Consistent save/load BG images for each campaign

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#379]
This fixes an issue where, if you select "load game" two or more times in a row while in Maria's campaign, the save background image will change from her face to James' face until you go back to "save game" to reset the cycle.

nop the following instruction: `0044B40F - mov al,[0093C0B6]`

And add the following code:
If `00932174 byte (main menu event index) == 0x07` set [`ChapterID`](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Common.cpp#L262-L267) to `0x00` (one write, no constant iteration)

This code ensures only James' face is shown when selecting "load game" from the main menu. I believe 00932174 would be a new address for the project.

```ini
; Ensures the correct background image for the save/load screen is always shown for each campaign. (0|1)
FixSaveBGImage = 1
```

Thank you to Bigmanjapan for researching/finding the instruction. Thank you to Aero_ for ensuring it's safe to nop. Thank you Elisha for implementation.

**Comment by Bigmanjapan** [comment]
sh2pc.exe+1BB225B (01FB225B) byte

This address mimics the ChapterID address' values. It holds a value of 0x00 when James scenario is active and a value of 0x01 when Maria's scenario is active. 

But it also sets the value back to 0x00 upon returning to main menu after beating Maria's scenario. ChapterID address doesn't do that and that causes Load menu to show Maria's face for the first time it's entered (since the ChapterID still holds a value of 0x01, Maria's value).

Disable the first variable check like it was proposed before (the 0093C0B6 one) and replace ChapterID (01DBC00C) for 01FB225B in the instructions that drive textures' loading process for Save/Load menus. 

I did a brief testing with these two instructions and the main menu issue was fixed.

0044B41B - 80 3D 0CC0DB01 01 - cmp byte ptr [01DBC00C],01
0044E931 - 80 3D 0CC0DB01 01 - cmp byte ptr [01DBC00C],01

**Comment by Bigmanjapan** [comment]
Edit: This information is only useful if you want to fix the issue by hex-editing the executable directly, I don't propose it to be the main solution for this issue.

sh2pc.exe+1BB225B (01FB225B) byte

This address mimics the ChapterID address' values. It holds a value of 0x00 when James scenario is active and a value of 0x01 when Maria's scenario is active.

But it also sets the value back to 0x00 upon returning to main menu after beating Maria's scenario. ChapterID address doesn't do that and that causes Load menu to show Maria's face for the first time it's entered (since the ChapterID still holds a value of 0x01, Maria's value).

Disable the first variable check like it was proposed before (the 0093C0B6 one) and replace ChapterID (01DBC00C) for 01FB225B in the instructions that drive textures' loading process for Save/Load menus.

I did a brief testing and altering address at this instruction fixes the issue.

0044B41B - 80 3D 0CC0DB01 01 - cmp byte ptr [01DBC00C],01

The edits to the executable to fix the issue are:

At 0004B40F - 0xA0B6C09300 to 0x9090909090
At 0004B41D - 0x0CC0DB01 to 0x5B22FB01

**Comment by Bigmanjapan** [comment]
This information is only useful if you want to fix the issue by hex-editing the executable directly, I don't propose it to be the main solution for this issue.

sh2pc.exe+1BB225B (01FB225B) byte

This address mimics the ChapterID address' values. It holds a value of 0x00 when James scenario is active and a value of 0x01 when Maria's scenario is active.

But it also sets the value back to 0x00 upon returning to main menu after beating Maria's scenario. ChapterID address doesn't do that and that causes Load menu to show Maria's face for the first time it's entered (since the ChapterID still holds a value of 0x01, Maria's value).

Disable the first variable check like it was proposed before (the 0093C0B6 one) and replace ChapterID (01DBC00C) for 01FB225B in the instructions that drive textures' loading process for Save/Load menus.

I did a brief testing and altering address at this instruction fixes the issue.

0044B41B - 80 3D 0CC0DB01 01 - cmp byte ptr [01DBC00C],01

The edits to the executable to fix the issue are:

At 0004B40F - 0xA0B6C09300 to 0x9090909090
At 0004B41D - 0x0CC0DB01 to 0x5B22FB01

**Comment by AeroWidescreen** [comment]
So you found a different variable to use, huh? Nice. Appears to be working fine. 

@elishacloud In summary, this is everything that needs to be done:

```
// Prevents James' save background from appearing during the Maria scenario
0044B419 nop
0044B419 nop
```
`0044B41B cmp byte ptr [01FB225B],01 // Prevents Maria's save background from appearing after returning to the main menu`

**Comment by AeroWidescreen** [comment]
So you found a different variable to use, huh? Nice. Appears to be working fine. 

@elishacloud In summary, this is everything that needs to be done. I've written them in both assembly format and hexadecimal format for your convenience.

```
Assembly:
// Prevents James' save background from appearing during the Maria scenario
0044B419 nop
0044B41A nop

Hexadecimal:
// Prevents James' save background from appearing during the Maria scenario
0044B419 9090
```

```
Assembly:
// Prevents Maria's save background from appearing after returning to the main menu
0044B41B cmp byte ptr [01FB225B],01

Hexadecimal:
// Prevents Maria's save background from appearing after returning to the main menu
0044B41D 01FB225B

```

**Comment by elishacloud** [comment]
I tried implementing this, but ran into some issues finding the correct address for `01FB225B` on binary v1.1 and the Directors Cut.   Any idea what this address should be for binary v1.1 and the Directors Cut?

BTW: I think I got it working on binary v1.0.  Test build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5985994/d3d8.zip)

**Comment by AeroWidescreen** [comment]
@elishacloud Unfortunately this memory address is only accessed through a registry pointer, and the source of this pointer is unreliable, so you'll have to acquire it like this:

```
NA v1.0
Byte Pattern ( ? ? ? ? F3 AB B8 ? ? ? ? A3 ? ? ? ? BA 1F 00 00 00 ) = 00538059
00538059 Offset: +125B = 01FB225B
```

Searching for that byte pattern should lead you directly to the pointer for the other executables. Then you apply the offset and you'll have the address.

**Comment by elishacloud** [comment]
> so you'll have to acquire it like this:
> 
> ```
> NA v1.0
> Byte Pattern ( ? ? ? ? F3 AB B8 ? ? ? ? A3 ? ? ? ? BA 1F 00 00 00 ) = 00538059
> 00538059 Offset: +125B = 01FB225B
> ```

This is _exactly_ what I was doing in the build I gave you, except that `00538059` should be `00538060`.  Anyways, I didn't think I changed anything and it seems to be working now.  Not sure what I was doing wrong before.

Here is a test build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5986568/d3d8.zip)

BTW: Here are the addresses I am using for each version:
```txt
v1.0
Found memory address: 0044B419 + 4 --> 01FB225B
v1.1
Found memory address: 0044B5B9 + 4 --> 01FB5E5B
vDC
Found memory address: 0044B5B9 + 4 --> 01FB4E5B
```

**Comment by AeroWidescreen** [comment]
> This is _exactly_ what I was doing in the build I gave you

That's funny, at least I know I'm doing something right. 

> Anyways, I didn't think I changed anything and it seems to be working now. Not sure what I was doing wrong before.

Well, I got good news and bad news. Good news: you implemented everything correctly, working across all versions of the game. The bad news is that the memory address that @Bigmanjapan gave us doesn't appear to be reliable. For example: entering any room in Wood Side Apartments changes the value from a 0 to 1, indicating that we're in the Maria scenario when we're not. Perhaps this is what you were having trouble with?

I'll try to find another address we can use tomorrow, assuming BMJ doesn't respond by then. Otherwise, you'll have to go with John's original suggestion.

**Comment by AeroWidescreen** [comment]
@elishacloud Nope, couldn't find anything. Just follow John's original post at the top and that should take care of it.

**Comment by elishacloud** [comment]
Ok, I re-implemented it based on @Polymega's initial comments.  Take a look at it now.

Test build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6016297/d3d8.zip)

**Comment by Polymega** [comment]
The code to nop seems to be fine, but the second part isn't working.

When returning to the main menu, the chapter ID isn't changing back to 0x00.

**Comment by elishacloud** [comment]
Oops.  Looks like a copy paste issue.  Try this build.

Test build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6016815/d3d8.zip)

**Comment by Polymega** [comment]
Nice. All's working well across all binaries. Thanks, Elisha!

**Comment by Polymega** [comment]
@elishacloud 
We found a little quirk with this fix. A small change is needed. Thanks to Aero_ for looking into this.

Instead of nop'ing `0044B40F - mov al,[0093C0B6]`, we need to nop `0044B419 - jnl 0044B438` instead.

For my own curiosity, would all that needs to be changed is the following [on line 28](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/SaveBGImage.cpp#L28)?

`-0x5` to `+0x5`?

Thank you!

**Comment by elishacloud** [comment]
> For my own curiosity, would all that needs to be changed is the following [on line 28](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/SaveBGImage.cpp#L28)?

Changing that line will result in the correct address.  However, since we are now NOP'ing a larger amount of data we also need to change [line 38](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/b8a385c69747b91cc1aa4ac67e052a6066240096/Patches/SaveBGImage.cpp#L38).  We need to tell it that we are NOP'ing more than 5 bytes.

Try this update and see if it works:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8467089/d3d8.zip)

**Comment by Polymega** [comment]
Thanks for the briefer on that. It's definitely changed something but it's not behaving right. We're now seeing Maria's face as the save background image at all times when we should only see it while playing her campaign.

**Comment by elishacloud** [comment]
It is possible that I NOP'ed to many bytes.  I was a little bit unclear about how many bytes to NOP.  I NOP'ed address `0044B419` through address `0044B424`, 11 bytes.

Try this one, this one just NOP's that one line:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8467277/d3d8.zip)

**Comment by Polymega** [comment]
Thanks Elisha, all is good now.

> Try this one, this one just NOP's that one line

This should be fine. That's how Aero_ and I tested this originally (by nop'ing just that one line).
