### ISSUE TITLE
Audio stutter/desync in FMVs.

### ISSUE THREAD

**Issue by Pinkaminks** [elishacloud/Silent-Hill-2-Enhancements#380]
Just installed the EE to test it before streaming it for some friends, and every time an FMV plays every ~4-5 seconds there will be a few frames of freezing and 1-2 seconds of the audio being completely cut out before resuming, now desynced, and will continue to do this for the entire duration, getting worse and worse.

Here is my log.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/5929693/d3d8.log)

I have disabled d3d8to9, removed dsound.dll and dsoal-aldrv.dll, and even tried a suggested edit of device.fix regarding an issue specifically for nvidia cards.

I have a GeForce RTX 2060 Super, a Ryzen 5 3600X, and 16 gigs of ram.

EDIT: When I went to go record a short clip to show exactly what happens, the game now becomes unplayably slow and stuttery whenever OBS is open. I don't have any clue exactly why this might be, but when both are open and I look in my Performance tab in task manager, the '3D' graph for my GPU spikes up to ~50%, whereas normally it hovers around 7%.

**Comment by Polymega** [comment]
Hi there, 

Try remove ReShade and see if that helps. About two updates ago we integrated our own shaders to remove the external need for ReShade. A big reason this was done is because we've had consistent tickets of people experience launch/performance issues with it (even affecting more than capable graphics cards).

Remove these files from the game's directory:

```
\reshade-shaders\
d3d9.dll
d3d9.log

```

**Comment by Pinkaminks** [comment]
Removing those 2 files seemed to help, but not completely fix the issue, it still stutters and gets slightly desynced, just at a less frequent rate. (3 stutters in the SH2 E3 FMV for example, compared to something like 10+ before)

If you got any other ideas id of course like to remove them entirely if possible, but if worse comes to worst, I can survive with minimal stutters.

However, the OBS issue is still prevalent, and would be a much bigger roadblock, for me at least.

**Comment by Polymega** [comment]
The is a long shot, but did you try restarting your PC? Perhaps there was another instance of SH2 PC running in the background? Right now, the game only runs stable on a single core and it uses 100% of that core, so if there's two instances running then both instance will be fighting for 100% use of the same core.

**Comment by Pinkaminks** [comment]
I did try that, but decided to try again. For whatever reason, now it stutters just as much as before, despite still not having the reshade files in the folder. I even tried adding them back just to see what would happen and its the same. 
I was aware of the 1 core thing from years ago when I last tried to play, but mentioning that gave me the idea to set OBS to not use the same core as the game, but that didn't do anything. I had a brief moment where it was running smoothly, with OBS open, after I set it to realtime priority in task manager, but i've been unable to replicate this.

**Comment by elishacloud** [comment]
You could also try restricting OBS from using the same core that Silent Hill 2 is using.  If you have hyper-threading on your CPU then you will want to make sure that both the cores that could be used by Silent Hill 2 are not used by OBS.

Try this:
1. Setting `SingleCoreAffinity` to `3`.  This will tell Silent Hill 2 to use only the 3rd core (CPU 2, since cores start counting at 0).
2. Open Task Manager and make sure that the OBS process is not using the 3rd core (CPU 2).  You can do this on the "Details" tab of Task Manager and right-clicking on the OBS process selecting the "Processor affinity" item.
3. If you have hyper-threading on your CPU then make sure that the OBS process is not using the 4th core (CPU 3).

**Comment by Pinkaminks** [comment]
Looks like we posted at the same time, hence the redundancy, but I did try it again since I didn't consider hyper-threading, and no variation of removing cores on OBS or swapping cores on SH2 changes anything. I'm suspecting its something on my GPUs end, but iv'e no idea what it could be.

**Comment by AeroWidescreen** [comment]
What resolution are you playing in? 50% sounds high, but maybe not if your desktop is running in native 4K or you're pushing multiple monitors.

Have you tried running the game without any mods? Because if you still have performance issues when using an original install, then that probably means it's an issue with your setup. Just don't forget to limit your game to one core if you decide to try this.

**Comment by Pinkaminks** [comment]
My monitor is 2560x1440, which the game is running at, and I only have the one. I'm reinstalling right now. I'll edit as soon as i've tested it.

**Comment by Polymega** [comment]
> No issues with a fresh vanilla install, reinstalled EE and the stutter is still there

Try this for me: Leave all your files now as-is but go to `\Silent Hill 2\sh2e\` and rename the `movie` folder to anything else. This will prevent the game from using the new FMVs and will instead use the original videos.

Do the videos still stutter for you? I'm curious if this issue is specific to the FMVs or something else with the project files. (And to confirm: The stuttering is only happening with the FMVs, yes?)

**Comment by Pinkaminks** [comment]
To confirm; no issues with gameplay, its solely the FMVs. I've been testing it with the movies menu, but even the opening bathroom FMV has the stuttering. 
Renaming the movies folder had no effect. Moved the folder entirely just to be safe.

However, I have found the culprit of the OBS issue. If the d3d8to9 setting is disabled in the ini, it causes the massive slowdown whenever the game and OBS are both open. If it's set to 1 it works perfectly fine.  No change to FMV stuttering regardless of setting.

**Comment by Pinkaminks** [comment]
Since OBS is working now I was able to get some recordings of the issue. 

The SH2 E3 Trailer movie.   https://www.youtube.com/watch?v=1lhilasjlbc&feature=youtu.be
The opening bathroom FMV.   https://www.youtube.com/watch?v=Yyf8XOrHJIk&feature=youtu.be

OBS makes the stuttering worse to a noticeable degree, but it's not particularly playable without recording anyway. For example, while the OBS clip of the bathroom FMV above has 3 long looping stutters, and a few stutters that are only a few frames long, without OBS there is a single long looping stutter and 1 stutter that only lasts for a few frames. 

On top of this, the gameplay seems to now be affected, freezing at random points if i'm moving. https://www.youtube.com/watch?v=2MHliGY_CUQ&feature=youtu.be

These freezes last until I let go of whatever key i'm holding to move. Happens identically regardless of OBS or not. Haven't tested it with a controller, and plan on restarting my PC to test as well, but I feel like it's worth noting beforehand anyway.

**Comment by Polymega** [comment]
Oh wow, those freezes are pretty frequent and severe. I'm sad to say I have no clue what might be causing this. :-/ All your hardware is more than enough to handle the game. 

My only guess is that it's related to hyperthreading as Elisha suggested, or perhaps there's some other piece of software running in the background causing the hiccups. Maybe there's a driver issue with one of the hardware, but I wouldn't even know what driver(s) to update to test/check.

**Comment by AeroWidescreen** [comment]
> My only guess is that it's related to hyperthreading 

I too am using a Zen 2 processor (3700x) with SMT enabled, but I obviously have none of these issues. Where we differ the most is the GPU. Are you aware if anyone has tried this with an RTX card before? I doubt it matters, but you never know?

> Maybe there's a driver issue with one of the hardware, but I wouldn't even know what driver(s) to update to test/check.

Yeah, and asking him to reinstall Windows as a blanket solution isn't exactly a reasonable request either. This is something he'd have to troubleshoot on his own.

**Comment by Pinkaminks** [comment]
I haven't met anyone who's specifically tried to play and stream SH2EE with an RTX card, no. Also, yeah, if you're processor has no issues, mine shouldn't, Ryzen 5 3600x has better single core benchmarks than ryzen 7 3700x and it's not had any issues up till now, and I haven't had it all that long (like 2 years max). I haven't overclocked anything, so maybe that'd help, but i'd rather not do it just for this.

I updated my drivers and made sure nothing running that used any relevant amount of CPU was set to not use the hyperthreaded cores SH2EE was running on and it removes most of the stutter, though a bit still remains. I had an issue with OBS and audio but figured that out. (seems like the win10 function that allows you to route audio to different devices doesn't really work to change SH2's audio on the fly and you just have to do it in reverse)

I'll have to deal with it as is since there's not much else I can try. Not sure if I should leave this open or not as a 'just in case' thing, i'll leave that up to ya'll.

**Comment by DonQuinto** [comment]
I think you can now resolve this issue: try to replace binkw32.dll with a more recent version. If it works, then problem solved 🙃
