### ISSUE TITLE
Having troubles with text files.

### ISSUE THREAD

**Issue by ApolloEM** [elishacloud/Silent-Hill-2-Enhancements#386]
Greetings! I was playing around with the sh2 text files today and I decided to do a complete Romanian translation. Now, I did install the SH2 resource editor, and I did edit 2 of the files, those being: common.msg_e.mes and item_msg_e.mes.
![Screenshot_5](https://user-images.githubusercontent.com/79145993/108634203-32fd5b00-7481-11eb-9234-db59b6a6c0d1.png)
![Screenshot_6](https://user-images.githubusercontent.com/79145993/108634216-427ca400-7481-11eb-90f7-f6901e07a451.png)
only a small portions of the text from common.msg works, and none of the text from item_msg work. Is there anything I can do fix this, because I'd really like to make a full Romanian translation of this game. Thank you in advance!

**Comment by Polymega** [comment]
Hi ApolloEM,

There's some older threads around here that go into detail about making new translation packs, along with making them compatible with the HD fonts our project uses. 

To start: It is recommended to no longer use the SH Resource Editor. A newer, better, more robust text editor has since been made known as [SH2MSGConvert](https://gitlab.com/sh2msgconvert/sh2msgconvert). I strongly recommend you use this software for editing message files.

In regards to editing the message files, check out and read over these other threads first. They may help you with your Romanian translation project:

- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/144
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/234
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/328

I think what might be going on is that you're using specialized characters that are not supported by the game. This is just a guess, though.

**Comment by ApolloEM** [comment]
I see, thank you very much for this info! I have made sure to not use any special characters in my translation because it would've been more of a hassle than it would really be worth. I'll make sure to see if SH2MSGConvert works better.
