### ISSUE TITLE
Sound Issue 

### ISSUE THREAD

**Issue by MerpyDerp** [elishacloud/Silent-Hill-2-Enhancements#392]
i cant explain what im hearing cause i dont know what the sound its making is called, if i had to put it to works its the sound u hear when when listening to low quality music like bzzzzz lol, well anyways this issue only occurs when the flashlight is turnned on and i dont get why it wasnt happening before so it just started when i played the game again after a while

**Comment by MerpyDerp** [comment]
Oh just to add it only happens when im playing while streaming on discord

**Comment by Polymega** [comment]
Hearing audio feedback interference only when James' light is on doesn't make sense. Since this is only happening when you're streaming, are you also using a mic in your stream? Do you have the hotkey to toggle James' flashlight ("L" by default) also being used to something related to your microphone in Discord?

I don't think this is an issue with the game/our project.
