### ISSUE TITLE
"CatacombsMeatRoomFix" force seeks required files in sh2e/ folder

### ISSUE THREAD

**Issue by Psycho-A** [elishacloud/Silent-Hill-2-Enhancements#393]
I'm used to create "lite" builds of SH2: EE for myself, where all EE files goes back to data\ folder by replacing original content - and it works fine except one issue: "CatacombsMeatRoomFix" param is forcing to search 'ps189.map' and 'ps193.map' files in 'sh2e\bg\ps\' instead of data\ even if "UseCustomModFolder" is set to 0. Looks like some shortcoming. I think using "sh2e" override should be set globally, with keeping fallback to read missing files in data no matter of various bugfixes...

**Comment by Psycho-A** [comment]
UPD. Trying to move required files into data/ dir makes this fix applied incompletely.

Files in sh2e/ folder:
https://fastpic.ru/view/114/2021/0309/_efc24f36b39697272857b2dd654aa70b.jpg.html

Files in data/ folder:
https://fastpic.ru/view/114/2021/0309/_b3d9393c596bc469ed543b43ace8194e.jpg.html

**Comment by Polymega** [comment]
The purpose for this check is because this fix requires **both** modified .map files and modified memory addresses. If you use one without the other, then the visuals will not look correct (as you found out). That's the purpose of this "safety" check.

However... the visuals of this room are messed up to begin with, so having our `CatacombsMeatRoomFix` adjust memory addresses _without_ the modified .map files really can't do any more harm than what's inherently done to this room. 

I can request Elisha remove this "safety" check altogether because, as seen in your photos above this post, it's not any worse than how these vanilla rooms already look, and this would also allow you to place the modified files in the data\ folder instead of the sh2e\ folder.

**Comment by elishacloud** [comment]
This will be fixed in the next update.
