### ISSUE TITLE
FIX FOUND: Loading a Quick Save inside the Cemetery creates odd environmental effects for that area

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#4]
@Bigmanjapan , I'm hoping with your deduction skills in [determining the address line(s) that caused issues for the rowboat animation](https://github.com/elishacloud/dxwrapper/issues/9#issuecomment-374322883) bug that maybe you can determine what the cause is here as well? 

If you load a Quick Save file that's inside the cemetery the environment looks weird for the cemetery. If you leave the area and come back it fixes itself. This only happens if you load the game from within the cemetery: 

https://youtu.be/Und9vwU1NtU

**Edit:** Forgot to mention this also occurs with the vanilla PC version (no mods/fixes being used).

**Comment by Bigmanjapan** [comment]
This issue is due to early locations having separate colour palettes addresses, probably because they were modelled as test room in the begginning of development.

Saving / loading process assignes wrong values to loading zone, cover-up fog and location's textures colours palettes. If you freeze the values while being outside of the cemetery, the issue will not occur. The addresses should be unfrozen of course once a players's past the cemetery.

https://youtu.be/tOWG0pcpyl0

[PC_SH2_colour_palettes.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/2042359/PC_SH2_colour_palettes.zip)

@AeroWidescreen

**Comment by Polymega** [comment]
Excellent work once again, Bigmanjapan! Many thanks

**Comment by AeroWidescreen** [comment]
@Bigmanjapan @Polymega  Had same extra time tonight, so I took a quick look. I thought this was going to be more of a hassle but maybe not.  Download the cheat table and tell me if it works.

Enable the script before loading any saved data.
[Download](https://mega.nz/#!ROJHlSZa!KBmM8AMjbOs8p1i520qvMe4FN03Z8rcdA6SuoIdCQrU)

**Comment by Bigmanjapan** [comment]
Is it supposed to be active only at the cemetery / near cemetery or all the time? 
Works fine for the cemetery, breaks stuff in other locations: 

![toilet](https://user-images.githubusercontent.com/31383389/40826504-fecf2158-65a4-11e8-8d67-adb8cf958a58.png)

**Comment by Polymega** [comment]
Echoing Bigmanjapan's statement: Fixed the Quick Load bug in the cemetery but glitches up the beginning bathroom and observation deck area. I have **not** done a full play test with the fix in effect. 

![image](https://user-images.githubusercontent.com/27395260/40843533-491c1d68-657f-11e8-90ce-48018a895575.png)

**Comment by AeroWidescreen** [comment]
Well that's embarrassing. I checked different save points and locations, but never bothered to check the intro of the game.

> Is it supposed to be active only at the cemetery / near cemetery or all the time?

It's suppose to activate under certain lighting conditions. I'll try again later.

**Comment by AeroWidescreen** [comment]
> Link is broken?

Fixed. I had to re-upload  the cheat table last night and forgot to update the link before I went to sleep.

> I also think it somehow tied towards that white fade-in that happens before cutscene with Angela since it's a single instance of such white fade-in in the whole game?

I don't think there's any correlation, but I never gave it much thought. Good point. I'm almost certain the fade-in is a regular transition overlay recolored to white/gray. You can usually change the color of those type of things. The speed is affected by FastTransitions as well.

**Comment by Polymega** [comment]
This looks to be the ticket so far, Aero! The beginning area looks a-okay now. I'll do a full play test and randomly quick save/quick load spots throughout the game to be sure. Really great work here, thank you.

**Comment by Bigmanjapan** [comment]
New script seems to work with no issues. 

>I don't know what this value is actually for

More speculation here. Maybe 0001000A, 0001000B, 0001000C, 0001000D, 0001000E etc values are indicators of a texture skinning zone of the loaded location on which James stands?

Because this looks oddly like a texture zoning of some sorts (brightness go wrong if you load inside this zone with unloaded textures (0001000E zone)): https://youtu.be/8QUQWyuHhFQ

Either way, if your script tricks game engine into thinking that James stands on the other zones which have right brightness values assigned to them, then it's all good.

> Then, after exiting the bowling alley, it becomes "dawn time."

Have you noticed that there are multiple James / Maria models' texture sets for each of the daytime state? I always wondered why devs had to make multiple texture sets instead of adjusting models' colors via game engine means. Maybe they run into some limitation we ran into in the flashlight thread.

**Comment by AeroWidescreen** [comment]
@elishacloud
### Cemetery Lighting Fix

If the value in ecx = 0001000E, then write 0001000D to ecx. This will prevent the game saving the wrong lighting values in this area, which would normally corrupt the fog. 

XXXXXXXX = code cave

```
0047C31C jmp XXXXXXXX
XXXXXXXX cmp ecx,0001000E
XXXXXXXX je // jumps to mov ecx,0001000D
XXXXXXXX mov [00942ED0],ecx
XXXXXXXX cmp ebp,02
XXXXXXXX jmp 0047C322

XXXXXXXX mov ecx,0001000D // jump goes here
XXXXXXXX mov [00942ED0],ecx
XXXXXXXX cmp ebp,02
XXXXXXXX jmp 0047C322
```

**Comment by elishacloud** [comment]
Thanks @AeroWidescreen!

**Comment by elishacloud** [comment]
Fixed. Closing issue.
