### ISSUE TITLE
100% Single Core Constant on i5-9400 - expected?

### ISSUE THREAD

**Issue by DaveACG** [elishacloud/Silent-Hill-2-Enhancements#403]
Have installed all the latest versions of the enhancement pack and its support files, but on my i5-9400 I find that on one core (which I understand it should only be using), it's a locked 100% at all times regardless of action in-game, which is leading to stuttering, even when playing at 30fps. The core is usually at 3.9->4ghz. Switching cores does not help.

GPU usage (GTX 1660) is barely cracking 30% at 4K so it's not that. Is this just expected behavior with the pack and I need better single core performance?

**Comment by Polymega** [comment]
Hi there,

Your processor is totally fine for the game/project. SH2 PC has an inherent issue of only running stable on a single core and, whichever core it uses, it uses 100% of that core at all times. We're pretty sure this has to do with buggy audio middleware the PC devs had to use.

We have it on our to-do list to hopefully fix this. If all goes to plan, the game will only spin the core when it needs to (instead of running it non-stop), and also hopefully have it run smoothly using multiple cores instead of just one.

**Comment by DaveACG** [comment]
Understood, thanks for the reply.
