### ISSUE TITLE
FMVs

### ISSUE THREAD

**Issue by TommvinHuwaltzky** [elishacloud/Silent-Hill-2-Enhancements#407]
So this has probably been discussed before (if so, point me to it), but can you go a bit in depth why the FMVs can't be run at 60FPS? Since you're already using the original PS2-assets. Is it because you would have to up the whole game's frame-rate, which causes a lot of additional problems? Unlikely, since the PS2-game is also running at 30 as a whole, yet the FMVs are 60.
Just curious, hope you can enlighten me (:

**Comment by Polymega** [comment]
Two reasons:

1. The PC version simply doesn't play them right at 60 fps. The videos stutter very, very badly. It's likely the game is hard-coded to only play them at 30fps. That would need to be looked into and resolved.
2. We'd need to create 60 fps versions of the FMVs, as there doesn't exist a 60p (59.97p) fps version of them (PS2 is 29.97i). This would be done using AI interpolation to "fill in the blanks" between frames. We'd need to find one that produces results we're happy with it and we haven't looked into this any because the first bullet point would need to be resolved first.

**Comment by TommvinHuwaltzky** [comment]
> there doesn't exist a 60p (59.94p) fps version of them (PS2 is 29.97i)
Oh I see. Wasn't aware of that. So how is it done on the PS2-hardware? Through interlacing/interpolating? Sorry, I'm a bit ignorant on how stuff like that works.
I play Nier Automata with the interpolated-FMV-pack, and it looks pretty good, not just sped up. Is it the same idea?

**Comment by Polymega** [comment]
Sure, this is a rather basic/simple explanation, and I'm likely messing up some of the details:

Interlaced footage has two different points in time contained within each frame; the even lines are of one point, the odd lines are of another point. This can also be referred to as the fields of the frame. When viewed on a CRT television it gives the _temporal resolution_ of being 60 fps because of how CRT are designed; CRTs render the fields of the footage horizontally, from left-to-right, starting with the odd lines then the even lines (or vice versa; can't remember), going from top-to-bottom.

Because of how CRTs handle this, you don't really see any interlacing on them and instead gives the illusion of 60 full frames per second (the temporal resolution). More simply put: Interlacing was made to save on bandwidth during the hey-day of broadcast television because you could still give the _temporal resolution_ of 60 fps without any interlacing artifacts due to how CRTs display video. It was a win-win... until modern televisions came into existence.

Modern displays do not render images the same as CRTs; modern displays render the entire frame of a video in one pass. So when viewing interlaced footage on modern displays, you'll see the classic "saw tooth" effects.

![image](https://user-images.githubusercontent.com/27395260/112878160-989ec180-9095-11eb-858c-1dee3266afa1.png)

To fix this, you need to deinterlace the footage. [There are different ways to deinterlace](https://en.wikipedia.org/wiki/Deinterlacing#Deinterlacing_methods), all with their pros and cons. The method we chose to do is a "blend" deinterlacing, where we combine and average the two different fields per frame to create one full frame. But by combining/averaging the fields of two different points in time to create one full frame, we're changing the video from 60 half (interlaced) frames per second to 30 full (progressive) frames per second.

But with our new, full (progressive) frames, we can then feed these frames into an AI algorithm to create new frames to "fill in the blanks" between these frames. By doing this, we double the amount of frames which bumps the videos from 30 to 60 full frames per second. If/when we reach that point, our project will be the only version of SH2 that offers 60 **full** frames per second videos.

These two videos are a friendly introduction into interlacing/frame rate:
- https://www.youtube.com/watch?v=5eu_KjKsnpM
- https://www.youtube.com/watch?v=DyqjTZHRdRs

**Comment by TommvinHuwaltzky** [comment]
Hm... Some of it I kinda knew/figured, some of it I didn't. Still learning, also with the terminology. Hafta watch a looooot more Digital Foundry I guess :P

And hey man, thanks again for taking the time ("Issue" can be closed as well I guess)!

**Comment by Polymega** [comment]
> Oh yeah, and I don't remember, but does it also not work correctly on PCSX2? If not, any idea why?

Yes and no. The PS2 videos are interlaced (29.97i) and, assuming you're playing PCSX2 on a modern display, you'll see the interlacing artifacts. 

However, PCSX2 has built-in deinterlacers. The best deinterlacer they offer for SH2's FMVs is "blend," which merges the fields to make a full frame. But by using PCSX2's "blend" deinterlacer, you're then viewing the videos at 30 full frames per second... the same as what are project currently offers. :)

> Hafta watch a looooot more Digital Foundry I guess :P

Those videos I linked above are great introductions into these topics.

> And hey man, thanks again for taking the time ("Issue" can be closed as well I guess)!

Sure thing. Cheers
