### ISSUE TITLE
Sound issue

### ISSUE THREAD

**Issue by Snakebites754** [elishacloud/Silent-Hill-2-Enhancements#408]
I have an issue where no sound effects are playing. The only sound effect I can find that is playing properly is the sound that plays when you hit "continue game" in the main menu. All other sounds (like the hit sound or footsteps) do not play at all.

**Comment by Polymega** [comment]
Make sure the SFX volume level is turned up in the game's Options menu.

**Comment by Snakebites754** [comment]
It's on full volume, trust me I've checked that and the troubleshooting on the Enhanced Edition site.

**Comment by Polymega** [comment]
Try temporarily removing the `dsound.dll` and `dsoal-aldrv.dll` files from the game's directory. Is sound then restored for you?

Can you also upload a copy of your `d3d8.log` file?

**Comment by Snakebites754** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6230077/d3d8.log)
Moving the dsound and dsoal files out of the game did not work.

**Comment by Polymega** [comment]
Look at your log, you are missing your `data\` folder, which is critical/needed. Additionally, there are a bunch of other files/folders that aren't a part of our project that might be causing conflicts/issues.

I'd recommend starting over and ensuring only the base game and our project files are in the game's directory. [This is what you want your directory to look like when all's said and done.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree)

**Comment by Snakebites754** [comment]
When I downloaded the game, there was no data folder. I attached a picture of what the directory looks like (The dsound and dsoal are still removed).
Everything works fine, except the sound effects.
![SH2](https://user-images.githubusercontent.com/47196096/113021944-b75e9000-9149-11eb-9e8f-f87889cf0603.PNG)
![SH2 2](https://user-images.githubusercontent.com/47196096/113021958-ba598080-9149-11eb-992e-08184204a5ff.PNG)

**Comment by Polymega** [comment]
[You need the `data\` folder.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#what-is-the-purpose-of-the-sh2e-folder)

Looking at your screenshots, you downloaded the installation files for the game. So you would need to run setup.exe and [follow the installation instructions](http://enhanced.townofsilenthill.com/SH2/install.htm#installGame) to install the game **to its own directory**. If you don't have a disc drive, you'll need to virtually mount the disc images.

Ultimately, you'll either need to reinstall everything and ensure only the needed files are in the game's directory, or find another source for SH2 PC.

**Comment by Snakebites754** [comment]
No, from how it is the sh2pc.exe file runs exactly how it's supposed to. 
When I downloaded it, it installed of the discs and became these files. There was no data folder and I don't know why. I installed off of disc 1, did everything the EE site said to. I don't know why I'm missing the data folder.
![Discs](https://user-images.githubusercontent.com/47196096/113029915-a5cdb600-9152-11eb-9689-39aa501c8ddd.PNG)

**Comment by matt8928** [comment]
It looks like you have only copied the files of the installation discs

Mount the discs, then right click on the drive with CD1 and choose run/install or whatever

**Comment by umbrellacorp53** [comment]
> No, from how it is the sh2pc.exe file runs exactly how it's supposed to.
> When I downloaded it, it installed of the discs and became these files. There was no data folder and I don't know why. I installed off of disc 1, did everything the EE site said to. I don't know why I'm missing the data folder.
> ![Discs](https://user-images.githubusercontent.com/47196096/113029915-a5cdb600-9152-11eb-9689-39aa501c8ddd.PNG)

This does not mean that anything was installed. Let's explain this from the beginning. 

**History/backstory:** Back when this game was released, it came on discs. You'd pop the disc in your drive, and a little window would pop up asking if you wanted to run "setup.exe" from the disc. The installer would run as the files were copied to your computer in the install directory. Midway through it would ask you to put disc 2 in the drive, and then eventually disc 3. After installing it would ask you to put disc 1 back in the drive in order to play. The reason why it had 3 discs is because the game was too big to fit on one disc. So, disc 1 is the "play" disc, and disc 2 and 3 were all the game's data. Also, requiring a disc in the drive was how they ensured you actually owned the game back then.

**Now:** In 2021, things are very different, but SH2 has yet to be re-released. So, all of the copies that are in circulation are ripped from the original discs. They're "disc images". In order to interact with these disc images, you need to "mount" them in a "virtual drive". Windows 10 has this feature built in now. So, what you're looking at in your last screenshopt isn't "files", it's virtual drives, containing virtual discs. (I.e. your computer is pretending it has a disc drive with a disc in it). 

This is only step one of installing the game. Once you have the disc mounted in the virtual drive, you have to actually run "setup.exe" from the virtual drive. You do not copy these files onto your computer, you run the setup file directly from the virtual drive. You cannot skip this step or do this any differently, because the installer is designed to work from discs. As the installer runs, it will ask you to "Please insert disc 2". You do this by "unmounting" disc 1, from virtual drive (F:), and mounting disc 2 into virtual drive (F:). This will trick your computer into thinking you opened up a disc drive and swapped out the discs. (Side note: You should not have all 3 discs mounted at once in different virtual drives like you have it now. This is unnecessary and can make the process more confusing.)

**Summary of steps:** 
1. Mount disc 1, double click it, run setup.exe.
2. Follow setup instructions until it asks for disc 2 ("Please insert disc 2").
3. Unmount disc 1 from virtual drive (F:), mount disc 2 into virtual drive (F:), and hit continue. 
4. When it asks for disc 3, unmount disc 2, then mount disc 3, and continue.
5. Follow any other install directions.

**Final note:** Wherever you downloaded the game from they added a "Crack" folder to the disc image. This is/was how people play the game without a disc in the drive, or in our case, mounted virtually. I believe that you do not need to use this anymore and can instead proceed with installing SH2:EE into the Silent Hill 2 install directory (wherever you chose to install it). I believe that the Enhanced Edition comes with a sh2pc.exe that no longer asks for a disc.

Hopefully this clears things up. If you don't have the patience to read the whole thing for the history lesson then just follow the 5 steps.
