### ISSUE TITLE
Framerate issues

### ISSUE THREAD

**Issue by Arthandas** [elishacloud/Silent-Hill-2-Enhancements#410]
My framerate dips below 30 fps, which results is very noticeable stuttering. I tested it in the cemetery area at the beginning of the game. It's easy to force the drops by running around between the tombstones. I'm using default ini settings at 1440p with i5-7500 and rtx 2060. Do I need better hardware or is it just an engine thing? :)

I tried to record it but bandicam tanks the framerate below 15 fps.

**Comment by Polymega** [comment]
We're aware of the choppiness and hope that if/when we can make the game run stable on multiple cores that it might also indirectly fix some of the stuttering. 

You can read about it some on this thread: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/282

**Comment by Arthandas** [comment]
I already read through it :)
At first I thought it's something to do with the refresh rate but the choppiness is there even with G-sync enabled.

I did some testing out of curiosity and it seems the cemetery is very heavy on resources for some reason. Depending on where you stand and even though the rendered image is mostly the same the framerate can go as low as 25 fps or as high as 70+.

Disabling the single core affinity completely fixes the issue and basically triples the framerate to 120+ (which I think is the limit).

What exactly is the problem with letting the game run on multiple cores? How about enabling only two cores?

**Comment by Polymega** [comment]
We spoke with the lead programmer of SH2 PC a while back and, according to him, they had to ship the game using a beta build of the audio middleware they needed, as the final build wasn't ready by the time Konami required them to wrap things up. 

Being beta, it had issues processing the audio using multiple cores. So if you were to run the game on multiple cores, the audio will eventually either start to skip infinitely on a one second loop, or stop playing altogether. Then, soon after, the game will ultimately crash.

I believe it's due to some sort of memory overflow with the audio part.

**Comment by Arthandas** [comment]
I understand, thanks for your answers and let's hope a fix is possible.

**Comment by TommvinHuwaltzky** [comment]
has apparently been a problem ever since the [XBox-conversion](https://youtu.be/nna2yt1c9gI?t=666)... :-o
