### ISSUE TITLE
Map in Angela's room (room 109 in Blue Creek Apartments)

### ISSUE THREAD

**Issue by Arthandas** [elishacloud/Silent-Hill-2-Enhancements#414]
When examined, the game displays the default message as if James examined one of many paintings hanging in the apartments.
How about changing it to something more appropriate like:

"A map of the United States.
There's nothing of particular
interest about it."
<img width="1280" alt="Map" src="https://user-images.githubusercontent.com/41027064/113760281-55d48d80-9716-11eb-9fae-748a67a6802e.png">

**Comment by Polymega** [comment]
Sure, this'll be included in the next update.

![Screenshot 2021-04-07 17-07-07](https://user-images.githubusercontent.com/27395260/113934407-b53ca700-97c3-11eb-957a-a8466b775cea.png)

**Comment by Arthandas** [comment]
Awesome :)
I have one more related suggestion: could you make it so that the text displayed after examination can be closed/scrolled only with the examine/action button instead of every single button including analog stick?
Currently if you move along a wall/shelf/any other piece of environment and spam the action button to see if anything can be examined, the text will appear only for a split second because it's instantly cancelled by the movement action. Basically, it means you need to make a full stop before examining anything or you'll skip the text.

**Comment by Polymega** [comment]
This is handled on a per-message basis and is something we won't change. This was deliberately coded by the devs so that some text strings require you to press a button to exit, while others don't.

Info:
- https://gitlab.com/sh2msgconvert/sh2msgconvert/-/blob/master/ControlCodes.md#separatora-altered
- https://gitlab.com/sh2msgconvert/sh2msgconvert/-/blob/master/ControlCodes.md#separatorb-displayed

**Comment by Arthandas** [comment]
So it's the same on PS2?

**Comment by Polymega** [comment]
Yes, this is normal behavior for all versions of the game.
