### ISSUE TITLE
Enhanced Edition Black screen on startup

### ISSUE THREAD

**Issue by ReservoirDog24** [elishacloud/Silent-Hill-2-Enhancements#415]
Dear Team.

I installed the game and i downloaded all the files in the installation guide. However, I only manage to get a black screen after launching the game. I tried several fixes but nothing seems to work:

- I tried following the instructions on the troubleshooting page of the website.
- I downloaded a hotfix from one of your pages (https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v1.8.1900.0).
- I tried to change the single core affinity
- I tried to set `CheckCompatibilityMode = 0` and i inserted this line: `SingleCoreAffinityTimer = 0`
- I tried to run the game on Compatibility mode for Windows XP

I would also like to add that when I open the Task Manager to close the application, it results that the program uses up to 30% of the CPU and it results as "Not Working". That much use is normal ?

Thanks in advance.

This is my log:
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6271048/d3d8.log)

**Comment by Polymega** [comment]
Hello,

Looking at your log file, it seems you are missing the `data\` folder, which the game needs in order to launch/play. Here's some more info about that folder: http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#what-is-the-purpose-of-the-sh2e-folder

This is a directory tree of what your game's folder should look like after installing everything. _(Note that some of the files listed would not be created for you until after you successfully launch the game for the first time, which is mentioned in that list):_ http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree

Besides that, everything else seems fine in your log file. But without the `data\` folder, the game will not run. I would recommend reinstalling the vanilla game to ensure you have the `data\` folder after its installation.

Once you do this, you should **not** have to do these things anymore:

> - I tried to set CheckCompatibilityMode = 0 and i inserted this line: SingleCoreAffinityTimer = 0
> - I tried to run the game on Compatibility mode for Windows XP

**Comment by ReservoirDog24** [comment]
OMG thank you. When I installed the game I changed the directory, but forgot to create one for the game, so the files went all over the place. I though I got all of the but I forgot to relocate the data folder.

Thanks again, i played a couple of minutes and it runs perfectly.

**Comment by Polymega** [comment]
Great! Glad to hear this was an easy fix.

And to be sure: You should set `CheckCompatibilityMode = 1` in the `d3d8.ini` file. 

You are probably also safe to delete the `SingleCoreAffinityTimer = 0` line from the `d3d8.ini` file as well, so that way it will be handled as default like before.

**Comment by ReservoirDog24** [comment]
Yes, I alredy did that.

Thanks again, this is my first time playing the game and the EE looks fantastic. I guess you can close the issue now.

**Comment by Polymega** [comment]
Have a great time with the game!
