### ISSUE TITLE
Low framerate/audio desync when meeting Angela in the apartment

### ISSUE THREAD

**Issue by joel94543** [elishacloud/Silent-Hill-2-Enhancements#43]
I followed the installation guide from the site and am not using WineD3D. The framerate drops during the cutscene with Angela after the FMV in the apartment and the audio gets delayed about a second. Outside of that the game runs slightly choppy when running through the streets.

**Comment by Polymega** [comment]
The framerate drops during cutscenes may be a PC spec issue. [Try one of the following](http://enhanced.townofsilenthill.com/SH2/#troubleshooting): 


Issue | OS | GPU | Recommendation
-- | -- | -- | --
The game runs slow in general. | Any | Any | Tone down the value (intensity) for IncreaseNoiseFilterRes = in the d3d8.ini file if you increased it beyond 512.
The game runs slow in general. | Any | Any | Disable your anti-aliasing solution, if you are using any.
The game runs slow in general. | Any | Any | Remove the ReShade & Filters files, if you are using them.
The game runs slow in general. | Any | Any | Remove the WineD3D For Windows files, if you are using them.

[For running in the streets](http://enhanced.townofsilenthill.com/SH2/#troubleshooting): 

Issue | OS | GPU | Recommendation
-- | -- | -- | --
The game runs slow during outside segments in the game. | Any | Any | Tone down the values (intensity) of the Fog Fix settings in the `d3d8.ini` file or set `Nemesis2000FogFix = to 0`.

**Comment by Polymega** [comment]
Also, if you are running this game at 60 FPS you will also experience these issues. The game wasn't designed to run at this framerate and I experience similar problems when played at 60 FPS. Perhaps if/when we can get this game to run on multiple CPU cores that will alleviate the issue at higher framerates.

**Comment by joel94543** [comment]
I'm running it at 30. Disabling Reshade seems to have fixed it.

**Comment by Polymega** [comment]
The two main benefits of using ReShade are: It _slightly_ adjusts color and level balances to be more on par with the PCSX2 version. These adjustments are extremely subtle and you won't loose anything (in terms of experience) with having this gone. 

The other thing it does is add anti-aliasing to the game. However, you can still achieve anti-aliasing through your GPU's control panel, if you prefer, so that way you don't need to use ReShade. I'm not sure who makes your card (AMD, Nvidia, etc.) but check out its AA options for specific games within its control panel and adjust from there. Just be careful: Certain anti-aliasing options can be _very_ processor heavy for your PC.

**Comment by joel94543** [comment]
I tried turning off AA in the Nvidia control panel before disabling reshade, but it didn't help. The differences are slight enough though.
