### ISSUE TITLE
1440x1080 support

### ISSUE THREAD

**Issue by greppim** [elishacloud/Silent-Hill-2-Enhancements#433]
I can't run the game with this custom resolution while disabling the widescreen fixes, which aren't necessary due to the fact it's a 4:3 resolution.

**Comment by elishacloud** [comment]
Yes, that is correct.  If you disable the widescreen fixes then the game only works with the game's native resolution list.  1440x1080 is not natively supported by the game so you need to enable the widescreen fixes to support this resolution.

The natively supported resolutions are:
 * 320x240
 * 640x480
 * 800x600
 * 1024x768
 * 1280x1024
 * 1600x1200

If you are using any resolution besides these ones then you need to enable the widescreen fixes.

**Comment by AeroWidescreen** [comment]
It's a reasonable misconception that the "widescreen fix" is only for those playing in widescreen. You can (and should) use it for any aspect ratio, because it provides benefits beyond just widescreen support, such as the ability to use custom resolutions.

And  keep in mind that if you didn't [add your custom resolution to your OS](https://www.nvidia.com/en-us/drivers/custom-resolutions/), it may not work unless windowed mode is used.
