### ISSUE TITLE
Black screen before first Pyramid Head boss fight. (Blue Creek Apartments)

### ISSUE THREAD

**Issue by stephvgo** [elishacloud/Silent-Hill-2-Enhancements#440]
Hello,
So I'm playing the Director's Cut edition with the EE enhancements. When I enter the stairway using the Apartment Stairway Key (right before the first boss fight with Pyramid Head), I get a black screen. I can hear the door close once I open it, and the music for the boss fight. However, I only see a black screen. I can't press Esc to leave either, I have to shut down the process via Task Manager. I tried switching CPUs to my Nvidia instead of the integrated CPU (both in Task Manager and in Nvidia Control Panel), however the game doesn't seem to pick it up and I get the same error.
Here are my logs. Thank you in advance! [d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6724155/d3d8.log)

**Comment by Polymega** [comment]
Hi stephvgo,

Sorry you're having issues. This particular problem has never been reported to us before, so it might be tricky to troubleshoot. Since it always seems to freeze in the same room/cutscene, I'm led to believe some of the core game files might have been downloaded incorrectly or tampered with, which is resulting in this issue. 

Some things I can think to try:

- In your log file, I see you're running the game with your integrated graphics processor (Intel IGP). Try running the game using your discrete Nvidia card instead. [Here is how you can change this.](https://www.techadvisor.com/how-to/pc-components/how-set-default-graphics-card-3612668/)
- Open the `d3d8.ini` file, find `UseCustomModFolder` and disable it (change it to `UseCustomModFolder = 0`).
  - This will disable all of our modified game files. This test will see if our modified game files are causing the freeze or not. If this does not fix the problem, you can re-enable `UseCustomModFolder`.

----------------------

- Temporarily remove `d3d8.dll` from game's directory by placing it in a different folder:
  - This will disable our project completely and you will be playing the vanilla game. Launch the game and load back into your save file right before this room/boss fight. Does the issue still happen?

If the issue still happens when testing the vanilla version of the game, my recommendation would be to find a new download of the game (if you originally obtained the game online). MyAbandonWare has a copy of the game, including a version that already has all of the game files extracted for you. I've never downloaded it, but I've heard from many people it is a legitimate download.

In any case, if you decide to do this, **make a backup of your save files first** by going to `<path-to-game>\save\` and making a backup of your `Folder 01` folder. After re-downloading the game, you can place your `Folder 01` folder back in the `<path-to-game>\save\` directory (you can make a `save` folder if one doesn't already exist).

Hope this helps some.

**Comment by stephvgo** [comment]
Thank you very much! So I set the` UseCustomModFolder` value to zero and this solved the issue. I may have messed up somewhere when installing the EE. Thank you so much for the prompt response!

**Comment by Polymega** [comment]
> So I set the `UseCustomModFolder` value to zero and this solved the issue.

Interesting. Here's something you can try then. Delete the following folders:

```
<path-to-game>\sh2e\bg\
<path-to-game>\sh2e\bg2\
<path-to-game>\sh2e\etc\message\
```

Then re-download the [Enhanced Edition Essential Files](http://enhanced.townofsilenthill.com/SH2/install.htm#installEssentialFiles). Replace any files/folders, if prompted.

**Comment by stephvgo** [comment]
So far everything looks good! I found the underlying issue, actually. Turns out my `sound` folder was not within the `sh2e` folder. That would explain why my audio would loop in certain areas. Super thankful for your help!!

**Comment by Polymega** [comment]
Great!

> That would explain why my audio would loop in certain areas.

Elisha and I have been talking behind the scenes about this. If the stars align and all goes well, we hope to fully correct this bug sometime in the near future.
