### ISSUE TITLE
I have an issue when I enter a door the screen turns black kicks me out of the game.

### ISSUE THREAD

**Issue by ninstil** [elishacloud/Silent-Hill-2-Enhancements#442]
After the eddie fight in the catacombs i enter the door to exit the room and all of a sudden the screen turns black and kicks me out. what do i do ?

**Comment by Polymega** [comment]
Does the happen every time you exit that particular door?

Please attach your `d3d8.log` file.

**Comment by ninstil** [comment]
yes and I cant progress.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6773842/d3d8.log)

**Comment by Polymega** [comment]
Thanks for the log file. The only thing unusual I see is that you're running the game from `sh2pc.exe.bak.exe` instead of `sh2pc.exe`. Try running the game through `sh2pc.exe` to see if that fixes it.

Beyond that, it's very rare to receive reports of the game consistently crashing at a particular point, and every time someone reports this it crashes at a different spot for them. I don't believe this is caused by our project, but instead is likely caused by a bad game file(s).

I would recommend temporarily removing the `sh2e` folder from the game's directory to see if that fixes it. If it does fix it, that may mean some files might have become corrupted when downloading the project files.

If the issue still happens, I'd recommend re-installing the base (vanilla) game. If you do this, be sure to make a backup of your save files first located at `<path-to-game>\save\Folder 01\`

**Comment by ninstil** [comment]
I took the sh2e files out and it worked thanks so much if I have more issues ill come here if I need more help.

**Comment by Polymega** [comment]
Progress! That tells me either one of the enhancement packages wasn't extracted to the right folder or perhaps some of the files became corrupter when downloading or extracting them.

The `sh2e` folder should look like this:
http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree

You can also try re-downloading the enhancement packages, testing them one-by-one, to see if that fixes it. I would start with the Enhanced Edition Essential Files:
http://enhanced.townofsilenthill.com/SH2/install.htm#installEssentialFiles

**Comment by Polymega** [comment]
No response so I'll close out this ticket. Feel free to re-open for further troubleshooting,
