### ISSUE TITLE
missing image files

### ISSUE THREAD

**Issue by loficious** [elishacloud/Silent-Hill-2-Enhancements#448]
hello, so basically when i started playing SH2, the game runs decently, but 1 problem is that after getting the map, the map doesn't seem to show up, it also happens in the inventory where it doesn't show a photo of mary or any item you get, even the clock hands in the puzzle don't show up either, including the vault puzzle & the coin puzzle too. although i did the instructions right, there might be some mistake i made.

**Comment by Polymega** [comment]
Hi there, 
Please upload a copy of your `d3d8.log` file.

**Comment by loficious** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6921342/d3d8.log)

**Comment by Polymega** [comment]
Thanks. Looking at your log, nothing seems out of the ordinary. The only tests/suggestions I can think of are:

- Move the entire game contents to a different folder. Perhaps the `™` in the `Silent.Hill.2.Directors.Cut.PC.Game(djDEVASTATE™)` folder name is messing with things.
- Ensure the contents within the `sh2e` folder are correct. [It should look something like this.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree)

If all else fails, set `UsePS2LowResTextures  = 1` in the `d3d8.ini` file. This will disable the upscaled full screen images and use the default ones, so that way you can at least see the original textures.

**Comment by Polymega** [comment]
No response so I'll close out this ticket. Feel free to re-open for further troubleshooting.
