### ISSUE TITLE
Angela Cutscene slowdown

### ISSUE THREAD

**Issue by TheBear18AnimationStudios** [elishacloud/Silent-Hill-2-Enhancements#452]
Having trouble getting the game to avoid slowdown during a cutscene, which affects the sound timing being off, as when I reach the cutscene of her with the knife at the mirror, the in game gameplay slows down hard, causing the dialogue to play before the characters have even opened their mouth, anything that can be done?

**Comment by Polymega** [comment]
Please upload a copy of your `d3d8.log` file.

**Comment by TheBear18AnimationStudios** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7101386/d3d8.log)

Here is my copy, sorry about the late response, I had no trouble with any other cutscenes up to this point, but I'm worried it could happen w/later cutscenes

**Comment by Polymega** [comment]
Thanks. Did you by chance downloaded a pre-made package of all our project files? I ask because there's a lot of files in your game's directory that shouldn't be in there; whether it's old files/packages we no longer use or files that shouldn't be in there to begin with. We recommend you download the packages from our site only.

Remove the following from the game's directory:

```
reshade-shaders/
d3d8.dat
d3d8.zip.modupdater
d3d9.dll
d3d9.log
device.7z
dsound.ini
dsound.log
ReShade.ini
ReShade_sh2pc.ini
_README.txt
```

[Your directory should look more like this.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#directoryTree)

If you still experience slowdown you can play the game in windowed mode, set the game's resolution to something smaller and see if that helps.

I would also recommend moving the entire game folder to a cleaner directory. There's a chance the "™" in that game folder could be messing things up. I'd recommend something simple like `C:\Users\arodr\Downloads\KONAMI\Silent Hill 2\`

**Comment by TheBear18AnimationStudios** [comment]
Well, I got a copy of SH2 from a friend a long time ago initially like 7 years ago or something

any of the packages have been from your site only & selected replace when asked

I'll try to clean it out asap & get back if it slows down again

**Comment by TheBear18AnimationStudios** [comment]
Oh geez the TM in the folder was the problem, game works really well now, thank you so much for the help!

**Comment by Polymega** [comment]
Great! I'll close this ticket then. Feel free to re-open it if need be.
