### ISSUE TITLE
Slowdown and stutter in a single area of the map

### ISSUE THREAD

**Issue by Zhnigo** [elishacloud/Silent-Hill-2-Enhancements#454]
Good day, and first of all, thanks for your work!

My issue is as follows: I'm encountering noticeable slowdown and stuttering when wandering the area circled on the map, after clearing the hospital. This is the only ingame area with perfomance issues for me in the entire game so far.

Running the last version of sh2e, win10, on a 2080ti, with no other fixes.
![image](https://user-images.githubusercontent.com/20024669/130715068-6af2d1c2-9cd4-4ddb-b00e-94f89805b39c.png)

**Comment by Polymega** [comment]
Hi there,

It's hard to say what might be causing this. Is the slowdown/stuttering constant in this area? Or does it happen just occasionally while here?

If I were to guess, since the game runs on a single processor core and always maxes out the core (always runs at 100% usage), it might be creating bottleneck situations for whenever the game needs to load new data in.

There may be new things being loaded into the game around that area and this code is fighting for an opening to execute in a thread that's always staying maxed out.

We have it on our to-do list to properly fix the game to run on multiple processor cores. If we fix this, it should help reduce stuttering/performance concerns.
