### ISSUE TITLE
An assortment of very minor bugs

### ISSUE THREAD

**Issue by Zhnigo** [elishacloud/Silent-Hill-2-Enhancements#457]
Good day! First of all, I want to say a huge thank you to everyone involved in this project, for helping me relive one of my adolescence defining games.

The following is a list of small mostly visual bugs that I've encountered after playing and replaying the game. They're all very minor, but since SH2E already has fixes for many extremely minor issues, I will post them for you to decide whether any of them are worth fixing.

1. 
Where: twisting hallway in the prison, after breaking your way out of the bottom of the well. 
What: On both ends of the hallway, the walls and water behind the bars have a visible hard cutoff
![20210825054444_1](https://user-images.githubusercontent.com/20024669/130889537-782dc924-0c48-4d32-b822-b314cdf3f8f9.jpg)
![20210825054517_2](https://user-images.githubusercontent.com/20024669/130889548-015ba635-9734-4150-abc0-2607b0031226.jpg)

2.
Where: Prison, office near the entrance
What: The writing on the blackboard is mirrored
![20210825060635_1](https://user-images.githubusercontent.com/20024669/130889638-c67cb83e-f70b-4b0c-8c70-50dfacbe5f8b.jpg)
![20210825060644_1](https://user-images.githubusercontent.com/20024669/130889628-feca892d-1647-4206-bdd2-38384a089d87.jpg)

3.
Where: Prison cafeteria, Eddie cutscene
What: At the end of the cutscene, as Eddie leaves through the door, his model can be seen frozen for several moments as the door closes behind him.
https://files.catbox.moe/79bcpv.webm

4.
Where: Labyrinth, after meeting Maria, before the innocent prisoner puzzle.
What: On the Labyrinth map, there's a small horizontal gap on one of the segments.
![image](https://user-images.githubusercontent.com/20024669/130889987-aedd6927-0ba6-477c-8401-59aa435cce8d.png)

5.
Where: Lakeview Hotel, when first visiting the staircase leading to the 3rd floor.
What: As the player checks the locked shutters and turns around to leave, Mary's voice can be heard saying "James". However, with quick transitions enabled, the voice is cut off halfway.
https://files.catbox.moe/aquged.webm

6.
Where: Right after leaving Blue Creek Apartments 
What: The texture on one of the doors is flipped
![20210825131200_1](https://user-images.githubusercontent.com/20024669/130891586-48b85a27-1ffd-4e4b-8afe-67981391536c.jpg)
![20210825131209_1](https://user-images.githubusercontent.com/20024669/130891632-bce90b5b-00ee-42f7-a010-f2b842a36da2.jpg)

7.
Where: Right before arriving at the final boss
What: There's a unnatural flat grey colored rectangle around the staircase where it intersects with the floor of the boss room
![image](https://user-images.githubusercontent.com/20024669/130891799-e3cb3a45-125c-40b1-8db5-1fba1354e364.png)

8.
Where: Everywhere
What: Loading the game clear file from the pause menu during gameplay softlocks the game.

9.
Where: Everywhere
What: If movement controls are set to Run, and James starts running from a standing position, the footstep sound from the second step he takes will play three times in a rapid succession.
https://files.catbox.moe/92yzrf.webm

**Comment by Polymega** [comment]
Hi @Zhnigo,

Thanks for all these notes! I should be able to answer most/all of them:

1. If/when we have a level editor for the game I plan to address this. I will add a black fade gradient to give the illusion the hallway continues onwards into darkness.

![untitled-4](https://user-images.githubusercontent.com/27395260/53214345-3f444880-361a-11e9-8f60-f328a4d4c4dc.gif)

2. There are quite a few instances of UVs for textures being flipped/reversed. So many that I'm not sure it's worth me going in and trying to fix them all. I'll make a note of this but I cannot promise I'll flip this sign back over.
3. Yes, this has also bothered me for many years. I've recently fixed this and it'll be included in our next project update. It was as simple as ever-so-slightly changing the final camera's position at the end of its sweep to hide the fact his model freezes at the end.
4. This gap is due to an alignment issue made by the game itself. It's like this on all versions of the game. We'll probably consider this a non-issue and leave it as it is.
5. I don't think we can do anything about this if you're using `FastTransitions`. It's an unfortunate side effect of faster, more convenient transition speeds.
6. There are quite a few instances of flipped UVs throughout the town's stores/businesses. So many that I'm not going to bother addressing them. If we planned on upscaling the environment textures I would worry more about this, but since we're not, I'm going to have to leave this issues as they lie.
7. Yes, this little quark has bugged my OCD for years as well. So much so that I asked Bigmanjapan about it. The way this room works/loads is different and more complicated than other rooms. So much so, that it's safer that we don't touch this. It's not as easy as darkening a part of the texture file; it has to do with how the game considers that piece of metal as part of the top-most floor (where the fog fade has influence).
8. [We have this fixed and will be a part of the next update.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/47)
9. I'm not 100% certain, but this might be normal behavior across all versions of the game. Either way, I don't think it's something we'll worry about at this time.

Thanks for all the notes!

**Comment by Zhnigo** [comment]
Thanks for the thorough reply!

**Comment by Polymega** [comment]
I believe all points have been responded to. Some of these things have either already been addressed/fixed or are on my to-do list when Phillip finishes the level editor. I'll close this ticket out but thanks again for your notes!
