### ISSUE TITLE
Shutter bug/Lag skips  

### ISSUE THREAD

**Issue by TDJZER0** [elishacloud/Silent-Hill-2-Enhancements#460]
Hi, Great upgrade to an mazing game I am loving it  :) Little issue I have came across so I have a Ryzen 2700 and The 3060 12Gb ampere card when I turn on metrics overlay which is part of the NVidia GeForce experience, Use the Xbox overlay or have Discord or anything open to be exact while Playing silent hill 2 with your mod the game starts to shutter and lag hard like no stop even minimize then go back in does not fix it , I have tried to set the core to different settings and no luck at all fixing the issue, I am using Windows 11 Final Build and yes it works very well for this game minus that tiny issue,  just wondering would you know what is going on I have also tuned off gsync and any other settings in the NVidia control panel and still happens, If need i can record the issue and post it for you let me know much Thanks :)

**Comment by Polymega** [comment]
Currently the game will only run stable on a single core of your processor and it always--at all times--uses 100% of that core, which can make the game bottleneck itself. We hope to fix this at some point in the future. In the meantime, if other applications are using the same core that SH2 PC is using it might bog down the game since the game is now not only fighting itself for processing requests on this core, but other applications as well.

I know you already mentioned trying this, [but I'd recommend trying additional cores to run the game on](http://enhanced.townofsilenthill.com/SH2/config.htm#SingleCoreAffinity), if you haven't already exhausted all your options here.

[Here are some other general troubleshooting tips for lag/stuttering.](http://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#the-game-runs-slow-in-general) Perhaps something there might help.

Lastly, none of us on the team are using Windows 11 yet so there's a chance it might have something to do with the new operating system. If that is the case, it'd be hard for us to test/troubleshoot for that.

**Comment by Polymega** [comment]
We've just released an update that includes a custom, built-from-scratch streaming audio engine which has noticeably reduced the frequency and severity of stuttering/hitching experienced throughout the game. Please update the project when you're able. Also, do note that you may still experience some stutters as you play. In these situations, it would be caused by things such as the game engine loading in external assets (like town chunks) as you play.
