### ISSUE TITLE
Typographical error in Brookhaven Hospital lobby

### ISSUE THREAD

**Issue by ChuckyIO** [elishacloud/Silent-Hill-2-Enhancements#474]
Blackboard next to lobby entrance is written "infomation", missing an **r**.

https://i.ibb.co/P13c5DV/pic.jpg

**Comment by Polymega** [comment]
I've dedicated an entire stream in finding how many instances of "infomation" I could find, along with other funny "Engrish" typos. 😁  Turns out "infomation" appears in several places, especially in the hotel. Anyway, I have this fixed for the Hospital entrance sign:

![Screenshot 2021-11-05 15-34-44](https://user-images.githubusercontent.com/27395260/140568451-27f8b896-025e-4c8d-8a6f-e5d559b5a2cc.png)

I'm not going to bother with the other "infomation" typos elsewhere. I wanted to fix this one in particular though because of how prominent it is and being located right at the start of the Hospital (and above the crucial map). ...it's hard to take a Hospital serious/reputably if they can't spell information correctly on their front entrance sign, y'know?

Anyway, this will be part of the next project update.

**Comment by ChuckyIO** [comment]
Stream link? so I don't post redundant submissions in future.

**Comment by Polymega** [comment]
Sure. They're VODs now and they've been up for a while. Not sure how long they'll stay up:

Part 1: https://www.twitch.tv/videos/1144682136
Part 2: https://www.twitch.tv/videos/1166503620
