### ISSUE TITLE
Won't launch

### ISSUE THREAD

**Issue by shizz2** [elishacloud/Silent-Hill-2-Enhancements#480]
![silent hill 2](https://user-images.githubusercontent.com/95317880/144135031-5a446f9a-8e0e-4459-a7ab-c66ab33235d8.jpg)
Is this fan mod meant for Windows 10? Eveytime I try to start it I just get this screen and it hangs no matter how long I wait.

**Comment by Polymega** [comment]
Please upload a copy of your d3d8.log file.

**Comment by shizz2** [comment]
> Please upload a copy of your d3d8.log file.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/7634597/d3d8.log)

**Comment by Polymega** [comment]
I'm not totally sure what the issue is. One weird thing I found in your log file is that you don't have the config file for the SH2 Enhancements module. This would be the d3d8.ini file. This shouldn't have any effect on why the game is hanging on launch, but you can re-download this package here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest

If you temporarily remove d3d8.dll from the game's directory (which essentially makes the game run in vanilla) will the game then launch for you?

Others things I could suggest is restarting your PC and, if you downloaded the game from the internet, either re-download the package or download it from another source. Perhaps there are core files missing within the \data\ folder which is hanging the game?

**Comment by shizz2** [comment]
>If you temporarily remove d3d8.dll from the game's directory (which essentially makes the game run in vanilla) will the game then launch for you?
yes

**Comment by shizz2** [comment]
It should work with the European Directors Cut right?

**Comment by Polymega** [comment]
Yes, it works with both the North American and European (Director's Cut) versions and our project works with Windows 7 and up.

Place the d3d8.dll file back in the game's directory. Open d3d8.ini and set `d3d8to9 = 0`. Save changes and launch the game. Does it run for you then?

Remember: Since, for some reason, you didn't have a d3d8.ini file to begin with, you'll need to re-download the SH2 Enhancements module in the link I provided earlier.

**Comment by shizz2** [comment]
Redownloaded from the link and changed ini but still the same problem.

**Comment by Polymega** [comment]
>> If you temporarily remove d3d8.dll from the game's directory (which essentially makes the game run in vanilla) will the game then launch for you?
>
>yes

I'm not sure what's going on. Elisha might be able to lend some suggestions, but he's currently taking a break from things. I can only think to recommend disabling certain features within the SH2 Enhancements module (found in `d3d8.ini`) and see if disabling something specific will then let you launch the game.

**Comment by shizz2** [comment]
Disabled everything possible in the .ini and again, still hangs upon launch, I'll try using different disc versions and such tomorrow.

**Comment by shizz2** [comment]
Tried 2 precongifured/prebaked versions of the Enchanted Edition but even by those 2 I get the same thing, I'm going to stick with the normal version, unless someone somehow ever find a fix.
