### ISSUE TITLE
Question about performace

### ISSUE THREAD

**Issue by JFuninvited** [elishacloud/Silent-Hill-2-Enhancements#486]
Is there any plan to fix the cpu thread at 100%? already mentioned [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/153) 

It is a problem only when the game is runing on old hardware.

**Comment by Polymega** [comment]
This is caused by bad handling of the audio by the game. Because of this issue, the game also only runs stable on a single core and, whatever core it runs on, the game utilizes 100% of its resources at all times. This happens even on the latest hardware.

This is a known issue (it's been a problem since the release of the game back in 2003) and is one of our biggest "to do" things still on our list.

We've taken a break from the project but hope to be back soon. [You can keep track of this issue by following this ticket.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/423) As such, I'll close out this ticket. Please follow progress on the other ticket.
