### ISSUE TITLE
[new feature request] ability to edit the preferred texture filter mode

### ISSUE THREAD

**Issue by Riccardoman** [elishacloud/Silent-Hill-2-Enhancements#497]
Let me first thank you for your outstanding work

Would you kindly include an option in the config to give the ability to choose anisotropic/linear/nearest filter?

Silent Hill 2 has the same issues as every other old title, on a modern LCD monitor the textures are washed out, and the nearest neighbor would give things a better contrast/definition imo

**Comment by elishacloud** [comment]
Thanks for the request.  I would like to understand this request a bit more to help figure out the best way to implement this.

Here is a list of the texture filters available:  https://docs.microsoft.com/en-us/windows/win32/direct3d9/d3dtexturefiltertype

Which texture filter do you want to use?  What are you trying to accomplish by changing the filter?

**Comment by Polymega** [comment]
SH2 already uses a point filter, from what I remember. Point filtering I would assume is the same or behaves incredibly close to nearest neighbor filtering. 

If you remember Elisha, we tried changing the texture filtering globally and it had a noticeable, negative impact on the foliage/vegetation textures in the game. It created a black, "crusty" outline along the alpha edges of the leaves.

I can't remember if we opted to make all texture filtering point, or somehow isolated the vegetation textures and applied point to them only.

**Comment by elishacloud** [comment]
> Silent Hill 2 has the same issues as every other old title, on a modern LCD monitor the textures are washed out, and the nearest neighbor would give things a better contrast/definition imo

Just for fun I created a build that uses nearest neighbor (D3DTEXF_POINT) filtering.  I don't think it looks as good.  But you can check it out and if you like it we can create an option to allow it to be enabled.

Testing build with nearest neighbor filtering enabled: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8484665/d3d8.zip)

**Comment by elishacloud** [comment]
> SH2 already uses a point filter, from what I remember. Point filtering I would assume is the same or behaves incredibly close to nearest neighbor filtering.

Yes, SH2 does use a combination of point and linear filtering.  In the build posted in the comment above I have set all the filtering to point.

> If you remember Elisha, we tried changing the texture filtering globally and it had a noticeable, negative impact on the foliage/vegetation textures in the game. It created a black, "crusty" outline along the alpha edges of the leaves.

Yes, I have been thinking about this because we enabled anisotropic filtering only for some of the textures and I don't think it is very noticeable.  It would be nice to change this so that we could enable it on all textures except the ones like the foliage/vegetation that have issues.

I created a build that forces anisotropic filtering for all textures: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8484893/d3d8.zip)

You can see that anisotropic filtering does help in some of the texturing.  See screenshot below (click on it to see the detail).

![Screenshot 2022-04-13 14-32-53](https://user-images.githubusercontent.com/25625456/163277542-bc1f8643-8ab6-47db-8133-fc03c2b0e4e8.png)

**Comment by Riccardoman** [comment]
Thank you for your openness
By neighbor filter I intend this https://love2d.org/w/images/8/8f/ComparisonFilters.png 
By now I set many early 3d games to have this type of textures filter and so far I've only noticed much better color fidelity especially on alpha textures. If you look at this comparison https://abload.de/img/coverzpook.png you can notice colored borders that don't belong to the original unfiltered image

As soon as I can I'll test it out and will let you know!

**Comment by Riccardoman** [comment]
Yes Elishacloud, but what I've noticed lately using source ports, in quake for example, is that anisotropic isn't necessarily bound o the filter applied to a surface, as antialiasing doesn't necessarily touch exclusively geometric borders (ssaa). It can be applied 16x of anisotropic without touching how the textures are filtered

**Comment by Riccardoman** [comment]
> Yes, I have been thinking about this because we enabled anisotropic filtering only for some of the textures and I don't think it is very noticeable. It would be nice to change this so that we could enable it on all textures except the ones like the foliage/vegetation that have issues.

Probably the culprit is a poor alpha implementation Thad doesn't follow the borders properly

**Comment by Polymega** [comment]
> You can see that anisotropic filtering does help in some of the texturing. See screenshot below (click on it to see the detail).

Ohhhh yeah. I remember now. See those mysterious black specks around the leaves of the tree? That was the other thing it introduced.

> Probably the culprit is a poor alpha implementation Thad doesn't follow the borders properly

Yes, this is a big part of the problem. It's also why MSAA is a kind of a nightmare. Textures were made/arranged in UV space with no anti-aliasing in mind. Which I guess makes sense given the era this game was made.

**Comment by elishacloud** [comment]
> in vkquake

Keep in mind that vkquake created a whole new engine for the game to run under.  There are a lot of things they can do the we cannot do since we are not creating a new engine but just "wrapping" the existing engine and adding some updates.  We are limited by the design of the current engine.

> a combo of 16x aniso+8xsupersampling+nearest neighbor filter the game looks very crisp and detailed all the lines

In Direct3D when you set a texture onto a mesh you can chose only one filter, either anisotropic or point (nearest neighbor).

> suggest you try just for a moment to understand what I mean

Yes, I understand you want a crisp looking game.  I think part of the issue is with the textures themselves.  The textures in Doom lend themselves to this type of visual look.  I sent you the build that uses nearest neighbor so you can see the "raw" or pixelized textures.

BTW: I understand what you want since I am a retro gamer and use things like the [RetroTINK 5 Pro](https://www.retrotink.com/product-page/5x-pro) to make sure that I can get perfect sharp pixels from my SNES, Sega Genesis and my other retro gaming systems.

> Probably the culprit is a poor alpha implementation Thad doesn't follow the borders properly

Correct.  The game has bad use of the alpha channel.

**Comment by Riccardoman** [comment]
elishacloud you're right, I forgot what render SH2 uses
Also I took a quick screen for foliage comparison
![Screenshot (1458)](https://user-images.githubusercontent.com/74624503/163386062-5209bf11-73d7-4e44-8585-7e8be71e73ca.jpg)
![Screenshot (1459)](https://user-images.githubusercontent.com/74624503/163386070-98aa454f-3c5c-4b4e-9394-53d21f0f8004.jpg)
And it's not too bad, I think that making it an editable option in the ini would not deter too much from the original experience. The more the options for the user the better!
Although I've noticed that the washed out textures fit nicely with the game depressing atmosphere, surprisingly. Like a dream the images are vague and unclear

**Comment by Riccardoman** [comment]
Ouch no nevermind, the issue doesn't concern only the foliage textures 
![Screenshot (1460)](https://user-images.githubusercontent.com/74624503/163387523-16a8b0ac-b823-439d-9be2-57ff67c96f2b.jpg)

**Comment by Riccardoman** [comment]
A question unrelated to this topic: is there a way to disable/skip the first 2 intro logos (the konami and the partnership ones)?

**Comment by elishacloud** [comment]
> Ohhhh yeah. I remember now. See those mysterious black specks around the leaves of the tree? That was the other thing it introduced.

Yeah, I want to be able to exclude out certain textures somehow so that they can remain as they are, like the trees and foliage.  I believe other textures can be improved by changing the filter type.

> I think that making it an editable option in the ini would not deter too much from the original experience. The more the options for the user the better!

I think having another option is good also.  I do kind of like the look that you get from most of the textures when using nearest neighbor or point filtering.

> Ouch no nevermind, the issue doesn't concern only the foliage textures

If I can exclude some textures I could exclude the foliage and the urinals.

**Comment by elishacloud** [comment]
> A question unrelated to this topic: is there a way to disable/skip the first 2 intro logos (the konami and the partnership ones)?

Yes, if you press the space bar during the 2 intro logos it will skip to the next one immediately.

**Comment by Riccardoman** [comment]
I mean skipping them altogether with a command line. I searched in the data folder to delete them but I suppose they are still images?

**Comment by Polymega** [comment]
There's currently no way to skip them altogether. They don't last long, especially if you press space on them.

**Comment by IlDucci** [comment]
> If you remember Elisha, we tried changing the texture filtering globally and it had a noticeable, negative impact on the foliage/vegetation textures in the game. It created a black, "crusty" outline along the alpha edges of the leaves.

Hello, alpha bleeding, old friend... I guess that if you wanted to change the texture filtering, you also need to double check every single texture with transparency to see if you need to bleed the colors over the RGB space (XNormal's PSD plugins seem to do the trick) and reencode them to DXT5 minimum (DXT1 does black out these details).
