### ISSUE TITLE
[feature request] alt+tab: free mouse for others apps

### ISSUE THREAD

**Issue by legluondunet** [elishacloud/Silent-Hill-2-Enhancements#516]
Hello,
on Linux when I alt+tab to use another software during gaming, the mouse cursor is stuck in SH2 game and is not free for others software.
Is this the same behavior on Windows?

**Comment by Gemini-Loboto3** [comment]
Basically yeah, the game requires exclusive access to the mouse because the game was originally planned as an exclusive fullscreen app, but you can still tab out and the mouse should be released. It can be glitchy and sometimes the mouse is not released for other apps. There is a way to disable it by changing the exclusivity flag in DirectInput when it creates the mouse device, but it will make the game misbehave with the way the game cursor moves in some sections.

**Comment by legluondunet** [comment]
in dosbox, if you press ctrl+F10, cursor is free for others apps and is totally inactive in Dosbox.

**Comment by elishacloud** [comment]
Good idea.  BTW: I know in Windows you can free the mouse by pressing the Windows key.

**Comment by Polymega** [comment]
I might be missing something to this, but this is already achievable by Alt + Tabbing?

**Comment by elishacloud** [comment]
Unfortunately, sometimes when you alt+tab it will not release the mouse and there is no mouse visible on the Windows desktop.  Also, this seems to be the case in Linux all the time, see [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/516#issue-1236685180).

**Comment by Gemini-Loboto3** [comment]
That's the behavior coming from DirectInput when you associate a mouse with exclusive access to the window. Sometimes the game won't release the mouse even during debugging, which is rather annoying because the input from it is locked as well and you can only debug via keyboard. Not 100% sure if that could be changed to toggle mouse exclusivity whenever the game loses or regains focus.

**Comment by elishacloud** [comment]
> Sometimes the game won't release the mouse even during debugging

Yes, I have seen this also.  Would be nice to fix that also!

**Comment by mercury501** [comment]
Hi all! 
@legluondunet could you please test this build to see if it changes anything on linux?
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10501487/d3d8.zip)

**Comment by legluondunet** [comment]
alt+tab on Linux using @mercury501 dll, cursor mouse is still captured and active in SI2.

**Comment by mercury501** [comment]
Dang, thanks for testing!

**Comment by Void48** [comment]
any chance you could try giving this issue another look and maybe try another fix before the new big update? @mercury501 🙏

**Comment by mercury501** [comment]
> any chance you could try giving this issue another look and maybe try another _possible_ fix before the new big update? @mercury501 🙏

I'll try if I find the time, but no promises. In the mean time, every time I alt-tabbed and the mouse wouldn't work a tap of the right mouse button made it work again, could you test if it works for you?

**Comment by Void48** [comment]
> > any chance you could try giving this issue another look and maybe try another _possible_ fix before the new big update? @mercury501 🙏
> 
> I'll try if I find the time, but no promises. In the mean time, every time I alt-tabbed and the mouse wouldn't work a tap of the right mouse button made it work again, could you test if it works for you?

I'm not home right now so can't really test anything. Could you try what mercury said? @legluondunet
