### ISSUE TITLE
Game crashes after entering second gate

### ISSUE THREAD

**Issue by Xandumas** [elishacloud/Silent-Hill-2-Enhancements#530]
I wanted to replay the game again (played EE both on my desktop and my old laptop) and I try to play now and the game crashes without fail after going through the second gate in the beginning of the game (more specifically, in the graveyard after you meet Angela and you go through THAT gate to go to town). Can provide a video if needed, tried updating the game's files, haven't reinstalled yet but saving that option for later as I remember installing the game was kind of a pain.

**Comment by Polymega** [comment]
Does the crash happen consistently on _both_ your desktop and laptop? Did you recently re-download the game files from somewhere? Can you attach a copy of your `d3d8.log` found in the game's directory?

Typically these types of reports/crashes are caused by a bad installation of the base game. So my initial suggestion would be to download/install the base game again, then apply the project files on top like normal.

**Comment by Xandumas** [comment]
> Does the crash happen consistently on _both_ your desktop and laptop? Did you recently re-download the game files from somewhere? Can you attach a copy of your `d3d8.log` found in the game's directory?
> 
> Typically these types of reports/crashes are caused by a bad installation of the base game. So my initial suggestion would be to download/install the base game again, then apply the project files on top like normal.

Hello! Sorry about the late response, life has been very crazy recently and I haven't had much free time as of late. To answer your questions

I've sold my laptop awhile ago, I was just referencing that to pinpoint that I haven't had much issues with this project in the past on this device and another. Yes it consistently crashes on my desktop. I updated a couple files from the site but other than that I didn't re-install the game at all. Also sorry about not linking my d8 log! I didn't see that sticky until a day later lol
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8905821/d3d8.log)


My hypothesis is that there's an invalid texture somewhere that crashes the game, however I can be completely wrong on that. Let me know what you think.

**Comment by TheMachineAmbassador** [comment]
> Hello! Sorry about the late response, life has been very crazy recently and I haven't had much free time as of late. To answer your questions

Hi [Xandumas](https://github.com/Xandumas), no worries as you said this is life. I know it sounds cliche but life is full of surprises, i hope the reason of your responding the question a bit late is because something good things happened in your life :) but good thing is we're always here unless we encounter some problems as you had, you can ask us anything and anytime you want about the game :).

About you're problem i've checked log file and only issue i saw is you're dll file loads reshade that we don't use anymore, i don't think it may cause crash but can you try with new build i send you below. Also you may want to change you're directory name (Games (T)) to something else sometimes special characters and spaces might cause issue. If these steps didn't solve your issue, unfortunately you might need to download game again.

[release](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8792305/d3d8.zip)

Also @Polymega i was thinking can we do for this game something like repair tool or something like that ? I think it would be cool but i don't know is that cause some copyright issue.

**Comment by Xandumas** [comment]
> > Hello! Sorry about the late response, life has been very crazy recently and I haven't had much free time as of late. To answer your questions
> 
> Hi [Xandumas](https://github.com/Xandumas), no worries as you said this is life. I know it sounds cliche but life is full of surprises, i hope the reason of your responding the question a bit late is because something good things happened in your life :) but good thing is we're always here unless we encounter some problems as you had, you can ask us anything and anytime you want about the game :).
> 
> About you're problem i've checked log file and only issue i saw is you're dll file loads reshade that we don't use anymore, i don't think it may cause crash but can you try with new build i send you below. Also you may want to change you're directory name (Games (T)) to something else sometimes special characters and spaces might cause issue. If these steps didn't solve your issue, unfortunately you might need to download game again.
> 
> [release](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8792305/d3d8.zip)
> 
> Also @Polymega i was thinking can we do for this game something like repair tool or something like that ? I think it would be cool but i don't know is that cause some copyright issue.

Hey TheMachineAmbassador! I want to start off saying thank you so much for being patient with me, unfortunately what I meant is a lot of stress, however overall I am doing good and it means the world to me that you guys are very kind and patient with not only me but other people on here, and for that I'm very grateful :) (though one good news that has happened recently is I got my Steam Deck! :D) 

I installed that d3 release you gave me and renamed the folder the game is in and voila! I can get past the second gate now without issues! I believe what you said about the outdated reshades is the culprit, I can't think of anything else it could be. Regardless, thank you for the help and if I encounter anything else I'll let you guys know :) And once again, thank you for being very kind <3

**Comment by TheMachineAmbassador** [comment]
I'm so glad to hear that worked 😍 I hope you don't get lost in Silent Hill streets 😀

> I believe what you said about the outdated reshades is the culprit, I can't think of anything else it could be. Regardless, thank you for the help and if I encounter anything else I'll let you guys know :) And once again, thank you for being very kind <3

Yep, i guess team added much better options than given by reshades. Also with the new build that i send you, you can play game with our new sound engine that makes the game run on multicore systems perfectly. 

> Regardless, thank you for the help and if I encounter anything else I'll let you guys know :) 

Anytime, i hope you don't encounter issues while playing :))) but if you encounter, please send us, we'll appreciate.

**Comment by TheMachineAmbassador** [comment]
I'm so glad to hear that worked 😍 I hope you don't get lost in Silent Hill streets 😀

> I believe what you said about the outdated reshades is the culprit, I can't think of anything else it could be. Regardless, thank you for the help and if I encounter anything else I'll let you guys know :) And once again, thank you for being very kind <3

Yep, i guess team added much better options than given by reshades. Also with the new build that i send you, you can play game with our new sound engine that makes the game run on multicore systems perfectly. 

> Regardless, thank you for the help and if I encounter anything else I'll let you guys know :) 

Anytime, i hope you don't encounter issues while playing :))) but if you encounter, please send us, we'll appreciate.
