### ISSUE TITLE
Crash after picking up the memo

### ISSUE THREAD

**Issue by GallowPeacer** [elishacloud/Silent-Hill-2-Enhancements#534]
Hello, so apparently at the very beginning of the game after interacting with the first monster, I went to the Saul St located at the bottom left of the map, where there's a white van, there was a memo and a save point inside, the game crashed after I just interacted with the memo... I restarted the game and redid the same thing again by going to the van, but the crash didn't occur, I don't know how... My PC is excellent and I use a dedicated GPU.
![sh 2 b](https://user-images.githubusercontent.com/107673660/174270236-28584d92-b79a-44a7-a911-c45155bc6189.png)
![sh2 a](https://user-images.githubusercontent.com/107673660/174270265-296cf791-0b46-4a5c-9033-98d73d9c1674.png)

**Comment by Polymega** [comment]
We believe the reason for these seemingly random (but consistent) freezes and crashes might be due to a Windows update conflicting with how our project hooks itself into the game and/or Windows files. We've just released a new build that uses an entirely new hooking method which should fix the issues you were experiencing. 

You can grab this update to the SH2 Enhancements Module by either running the Setup Tool in Maintenance Mode and checking for updates:

![image](https://user-images.githubusercontent.com/27395260/198746434-162feecb-9967-44c7-b0f4-8093408054e5.png)

[Or by manually downloading here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest) (We recommend updating through the Setup Tool if you installed the project using this tool, otherwise the tool will not know you have updated this package.)

-----------

If you don't mind, please let us know if you still experience this issue upon updating. We'll close the ticket after a little while if we don't hear back. Thanks
