### ISSUE TITLE
Purple screen?

### ISSUE THREAD

**Issue by GallowPeacer** [elishacloud/Silent-Hill-2-Enhancements#535]
At the beginning of the game, after getting close to the Wood Side Apartments, I tried opening up an inventory after I picked the first aid kit in Lucy Jade Restaurant, the screen just froze in purple? (with background sound) I don't know what just happened, but after clicking everything on my keyboard, the game turned back to normal.
![sh2 mmm](https://user-images.githubusercontent.com/107673660/174279615-8f983ad4-d113-4dcb-9bba-7408c6060833.png)

**Comment by Polymega** [comment]
Please attach a copy of your `d3d8.log` file.

**Comment by GallowPeacer** [comment]
> 

Here's the file
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8927693/d3d8.log)
;

**Comment by Polymega** [comment]
Thanks. Let's start very simple. Try moving the contents of the game folder to a new location. For example, move the contents found in:

`D:\Games\silent hill 2\Silent.Hill.2.Director.Cut\Silent.Hill.2.Director.Cut`

to

`D:\Games\Silent Hill 2`

Does this improve/fix things?

**Comment by GallowPeacer** [comment]
> 

I will try, thanks for the help.

**Comment by Polymega** [comment]
PS - Where did you obtain the base (vanilla) PC game from?

**Comment by GallowPeacer** [comment]
> PS - Where did you obtain the base (vanilla) PC game from?

I downloaded it from some random website (cracked game).
If that's the case, then I guess that's why I'm having problems with the game such as massive lag in the streets even though I'm having a really expensive PC and a dedicated GPU. 
If I'm guessing right, you'll send me the link of a trusted website like what I've read in the other issue; https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/536#issuecomment-1159198470
And that's what I'm going to do so if I'm right.
Thanks for your help!

**Comment by Polymega** [comment]
> If I'm guessing right, you'll send me the link of a trusted website like what I've read in the other issue

Yep. :) I'd certainly start with that route first.

> I'm having problems with the game such as massive lag in the streets even though I'm having a really expensive PC and a dedicated GPU.

You shouldn't have _massive_ lag while in the streets, but you might experience some random stutters/hitching while you play due to the game having to run on a single core. [This is explained more here.](https://youtu.be/CmoMZw-UXqM?t=43)

Our next project will mitigate this issue to allow the game to run stable on multiple processor cores. This should reduce the amount of stutters you experience while playing (though you still might experience some due to issues unrelated to audio handling).

You can try out an early build of this version by downloading the package below. This would [replace **Step 3**](http://enhanced.townofsilenthill.com/SH2/install.htm#installSH2Enhancements) on the project site: https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8744858/d3d8.zip
