### ISSUE TITLE
Voice.afs doesn't need complete sound replacement in fact...

### ISSUE THREAD

**Issue by Psycho-A** [elishacloud/Silent-Hill-2-Enhancements#55]
I looked into the voice.afs file version from audio Enhancement Pack, and found that all files have been replaced to uncompressed wavs from PS2 version. Then I made a kind of comparing by audio definitions: frequency range and balance, volume level, duration (all files were also listened individually). I found that most of 44.1 or 48 kHz ADX files are not so bad and almost identical to ones that inserted as WAVs from PS2 (at least I couldn't find any hearable differences), and doesn't seems to require for excess 1,5 Gbs of arhvie's growing. PS2 stored their sound assets mostly in SVAG container with Sony ADPCM format which is almost the same as CRI ADPCM (ADX) and uses 4 to 1 compression. The problem of SH2PC version isn't audio format itself, but just crappy encoding with overloaded volume, killing dynamic range and frequency range caused by lowering sample rate to 22 or 24 kHz. I don't know what did they do with them, but the rest of 44 and 48 kHz files are mostly encoded just fine.

I made list of files quality of that is **objectively** worse than PC ones:
- 1fwb_rain.adx
- boilers.adx
- clock_4.adx
- dust_ju_6.adx
- forest_wind.adx
- g_start.adx
- game_over.adx
- gero_ed.adx
- go_to_ura_1.adx
- go_to_ura_2.adx
- goki_jet.adx
- harigane.adx
- hotel_d1_cl.adx
- inai.adx
- ind_ev_mv.adx
- lakeside.adx
- mar_end_roll.adx
- silen.adx
- suiteki.adx
- surprise_01.adx
- surprise_02.adx
- surprise_03.adx
- surprise_07.adx
- tv_noiz_1.adx

And these only might be replaced in kind of "light" version of audio enhancement pack keeping voice.afs size inside of 500 mb limit...

**Comment by Polymega** [comment]
Hi @Psycho-A , 

Keeping most (if not all?) the dialog files as WAV is probably the best solution to enhance these particular files. Despite our best efforts, when converted back to ADX, many of the dialog files had degradation issues introduced to them (more on that below). This comes from Elisha, our lead programmer, spending months trying to encode the PS2 WAV files back to ADX without any issues... it simply couldn't be done with some of the tracks. 

For many tracks, when converted to ADX, whenever the sound would transition into silence you'd hear a robotic "glitch-like" effect during the transition. Also, for some tracks, there was a somewhat ear-piercing tone that would play during the silent parts. [That annoying tone is something that is introduced to tracks that are compressed with ADX. ](http://www.firebrandx.com/sh2completesoundtrack.html)

I don't have my list on-hand (and I don't know if I can readily find it easily) but there were quite a few dialog tracks with these types of issues. With many of them surely being the same as what you listed above. 

It seems to depend on what audio card and/or headphones you use. For example: I could hear these issues clear-as-day on my home PC. But, using the same headphones at work, I could barely hear these problems at all. Other people weren't able to hear the issues, either. But Nisto, one of our residential audiophiles, could also hear the problems. It seems to depend on what equipment you're using. 

Anyway, as you've also found, there are issues when converting the tracks back to ADX. But to play things safe, we kept as many of the dialog tracks as WAV as possible. It's the most fool-proof method of ensuring we didn't overlook any other audio oddities in other tracks we may've considered to be fine otherwise. 

Conserving file size is always a plus and a good, necessary practice to do when working in the games industry. But for this particular project, I'd say the emphasis is placed more on quality than reduce file size quantities, if having to choose between the two. Because that was the main issue with the PC version to begin with: [Reduced/compressed files for many, many things to meet the demands of Konami to put it all on three CDs. ](https://github.com/elishacloud/dxwrapper/issues/6#issuecomment-392883381)

**Comment by Psycho-A** [comment]
@Polymega 
No, I didn't meant to convert the PS2 files from my list back to ADX - they might be inserted as WAVs, but the rest of PC assets would be untouched as they already encoded to ADX pretty good. I compared them by a frequency spectrograms with PS2 ones, and even this way I couldn't find any significant differences like additional noise. Moreover, files surprise_*.adx recorded for PC better than PS2 when they are mono against stereo.

**Comment by elishacloud** [comment]
Closing.  We have no plans to change the 'voice.afs' file in this way.
