### ISSUE TITLE
Potential issue with the quality of enhanced audio?

### ISSUE THREAD

**Issue by BabaYouFar** [elishacloud/Silent-Hill-2-Enhancements#585]
Hi, I found a video comparing audio on an emulated game vs enhanced edition, and the emulated version sounds better? 
The video: https://www.youtube.com/watch?v=EDLzr29fNv4

It's as if the audio is cleaner and has better surround sound.

**Comment by Polymega** [comment]
This is due to post-processing filters/effects applied to the audio. Audio for this project was losslessly taken from the PS2 version, however, the post-processing handling of the audio will vary between different hardware/software running the game. In this instance, going off what the video says, PCSX2's [SPU2-X](https://wiki.pcsx2.net/SPU2-X) audio plugin, which was made specifically for that platform, might be what's nicely altering the sound further. 

Perhaps in the future I could see what Gemini thinks about creating an audio processing filter for our use, but no matter what, the way audio is handled in the PS2 version [is fundamentally different than other versions](https://enhanced.townofsilenthill.com/SH2/compare.htm#sound), so it will never 100% match up.  But at this time, there are no plans to revisit the audio for this project.

**Comment by BabaYouFar** [comment]
That's very interesting. I didn't know how different the audio could still be beyond asset quality. Thanks for the explanation!

Does that mean that the emulated audio itself is inaccurate to how it sounded on real hardware?

**Comment by Polymega** [comment]
> Does that mean that the emulated audio itself is inaccurate to how it sounded on real hardware?

I haven't done a direct comparison between the audio of a real PS2 console and PCSX2, but I would imagine they're very similar in sound presentation. PCSX2 has been in development for a long time and has made great strides in compatibility/performance.

And, according to that Wiki page, SPU2-X is "the latest, most supported, and best sound plugin [for PCSX2]."

I do believe there are still some bugs with certain BGM tracks when played through PCSX2. The most notable being a few tracks don't start/stop at the right spots. But besides that, it's audio presentation is really good for the game.
