### ISSUE TITLE
Various small issues

### ISSUE THREAD

**Issue by 8sm32K4D1K5f3E** [elishacloud/Silent-Hill-2-Enhancements#597]
Just posting these so they're known, didn't see them in any of the open or closed issues.

Invisible stop sign, has collision and you can see the shadow of it (Look at the outline on the wall there) but no actual visible model.
![stopsign](https://user-images.githubusercontent.com/97014490/189457116-fcdf3206-ed3b-4e12-afc1-3bc9a0c1c036.jpg)

There's various inconsistencies between the large (overview) map and the small (individual sides of the map) maps. Example below.
![Inconsistentmap](https://user-images.githubusercontent.com/97014490/189457115-04c5fb04-dc2f-40e9-b2c9-61c66c1db6ee.jpg)

This save icon gets placed at the wrong location on the map.
![wrongmap](https://user-images.githubusercontent.com/97014490/189457118-d39cf9a2-0395-45c8-b4c3-0b6977289736.jpg)

**Comment by Polymega** [comment]
Hi there,

Thanks for your notes.

1. Invisible stop sign

That's interesting, as another person [found an invisible phone booth.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/364) We have someone working on a level editor for us. Once that's in a working state, I will look into adding the stop sign back. Thanks for catching that.

2. South Vale vs. South Vale West maps

These differences were intentionally made for all versions of the game. The zoomed out, "overview" map of South Vale has less details in it vs. the zoomed in South Vale West map. 

3. Slightly misplaced icons on maps

We're at the mercy of ~~how~~ where the game programmed to position these icons on the maps. The misplaced save icon at Jack's Inn can be seen on all versions. There are several other instances of slightly misplaced icons on other maps, similar to this. Although I suppose for this particular instance, maybe the devs didn't want to cover up the words "Jack's Inn" on the map? No clue...

**Comment by Polymega** [comment]
1. Invisible stop sign

I'm not in the process of using the level editor to make adjustments. This one is a bit weird. On PS2, there is no stop sign and there is no collision here, however the shadow of the sign's face plate can still be seen like on the PC version:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/73dc62fc-95a1-48a4-8930-ee69ce7a54b4)

Here's where things get tricky:

**If I add the geometry for the stop sign in**
- It will not cast a shadow. This is because we don't have the tools to readily edit shadow (.kg2) files. I think it would look really weird to have it there but not cast a shadow.

**If I instead remove the collision for the stop sign**
- It will look/behave just like the PS2 version then. Meaning, that shadow of the sign's face plate can still be seen at specific angles. While we don't have the means to adjust shadow files (.kg2), we do have the means to adjust collision files (.cld). 

I think the latter approach would be better for this situation.

**Comment by Polymega** [comment]
Team member @bigmanjapan is not concerned with such limitations and has provided us with a fix to _both_ remove that unneeded collision _and_ remove the shadow casted on the sign's face plate. So this will be completely resolved in our next update.

Thanks, BMJ!
