### ISSUE TITLE
Improper lighting in Bowl-O-Rama during the Completely Dark Town part

### ISSUE THREAD

**Issue by DeejGuy** [elishacloud/Silent-Hill-2-Enhancements#603]
Hi, this exactly an issue preventing me from playing the game. But it does seem to be a bug that I wanted to report. During the town roaming part right after the hospital where the town is dark, if you go into Bowl-O-Rama and then into the main room with the bowling lanes, the lighting seems to react strangely to whether the flashlight is on or off. I'm not sure which if the two ways of lighting the room is the correct one, but it seems like the room is lit wrong while the flashlight is off, and fixes itself while the flashlight is on.
![Screenshot 2022-09-17 19-59-32](https://user-images.githubusercontent.com/113809867/190881387-6e59dfac-41c7-4115-a4fd-2a1a1aeea4d7.png)
![Screenshot 2022-09-17 19-59-47](https://user-images.githubusercontent.com/113809867/190881389-01ad17e2-ba38-4b37-bf68-a776e8a2a9f7.png)
![20220917200049_1](https://user-images.githubusercontent.com/113809867/190881396-8334e7d1-a26c-4ccf-8ac1-0b174ddf3423.jpg)
![20220917200113_1](https://user-images.githubusercontent.com/113809867/190881401-9537f2b4-7a6b-49e4-b3de-6d7091431c92.jpg)
![20220917200051_1](https://user-images.githubusercontent.com/113809867/190881423-e2205969-884f-4064-944b-e58bb5808756.jpg)
![20220917200116_1](https://user-images.githubusercontent.com/113809867/190881402-a4f7e76d-6cec-4dda-9a86-b2a4b926993f.jpg)
-images.githubusercontent.com/113809867/190881397-137ca0e4-844b-4cfd-870f-b08936a70d6e.jpg)
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9592881/d3d8.log)

**Comment by DeejGuy** [comment]
OK, seems like the same lighting stuff happens the first time you enter the bowl-o-rama as well. Also just checked the ps2 version of the game using pcs2 1.6.0 and the same lighting shift happens.  Guess that's how it's supposed to work. My bad.

**Comment by Polymega** [comment]
No worries. I believe what you were describing is that the environment becomes darker when the flashlight is turned on? If so, that is correct behavior. This was the developer's way of simulating how our eyes behave in dark areas.

When you're in a dimly lit area, your pupils will contract to let more light in order to see better in the dark. When this happens, you're able to see things a bit better in the dimly lit area.

In real life, if you turn on a light then turn it back off you'll notice that this area is now much darker. This is because your pupils constrict (become smaller) when the light was turned on. Now, with the light turned back off and your pupils constricted, less light is going into your eyeballs, making the room appear darker.

This is what the game is trying to mimic. When the flashlight is turned on, the areas outside of the light's reach become darker, as James' eyes have become constricted. When the flashlight is turned off, over the course of several seconds, the room will become _slightly_ brighter.
