### ISSUE TITLE
Adding analog turning to mouse

### ISSUE THREAD

**Issue by mercury501** [elishacloud/Silent-Hill-2-Enhancements#608]
As noted in https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/356 and https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/390, there's been people who'd like to control sh2 with keyboard and mouse, like in sh3.

I've been experimenting on this branch [here](https://github.com/mercury501/Silent-Hill-2-Enhancements/tree/Input-Test), there's not much, most of the work has revolved around static and dynamic analysis. 

My most important findings so far, I'll use absolute addresses:

The function that reads input from keyboard and joystick is at `0x52E4C0`, and if you go with something like cheat engine and look in the region of `0x1FB7F18`, each input has it's byte, and they're set in the function I cited.

If no keyboard movement key is pressed, and controller X or Y axis have values (`0x52EA25`) it sets a flag at `0x01fB806A` which is some kind of "Analog Flag", if it's set it uses the controller values to move.

This flag is checked and the turning values are used in various functions called at the `0x54F2CB` function pointer, where it calls a function based on the Animation Index of James.

I've tried hooking the input function and feeding various values to the animation index, controller values and such but to no avail.

If someone has some clue as to how to put these puzzle pieces together, that'd be great. 

Don't hesitate to ask for more info!

**Comment by Polymega** [comment]
@Gemini-Loboto3 
Any interest or thoughts on this one?

**Comment by Polymega** [comment]
What about the possibility of injecting into DInput's left joystick function for joypads? With this approach, you'd be emulating the left joystick via mouse movement. The joystick can do analog and cannot be remapped by the game (left joystick is always movement for a joypad).

**Comment by mercury501** [comment]
I'll try and reverse engineer some more, took a break from it to not get burned out!

From my RE'd functions, I think I should be able to do something, but I'd need a mid-function hook and I've never done one before. 
This is the function I'm talking about, at `0x52E4C0`, find it [here](https://gist.github.com/mercury501/a919b1b4630c1e303443806122c0740d).
My theory is to branch out as soon as it reads controller input, and populate input ram according to the latest mouse and keyboard data, basically treating every input as controller input. I'll try and do that and report back!

**Comment by mercury501** [comment]
Quick update, I managed to inject values in the game by hooking the function that retrieves controller axis data and James finally turns, it'll need more work tho. Basically my idea is to convert keyboard walking and turning inputs into controller analog ones, because the game uses either one or the other.

After a POC it needs quite a lot of testing with people familiar with the game imo, input is very important.

To accept/cancel with mouse buttons should be easy, I have the groundwork to inject button presses, I should only read which button is mapped to ok/cancel.

**Comment by Polymega** [comment]
This is _awesome_!! I can't thank you enough for looking into this. The progress you're sharing sounds so good. :grin: 

> After a POC it needs quite a lot of testing with people familiar with the game imo, input is very important.

You know I am happy to help here, and I can recruit others to help with testing as well, same as we did when testing the new audio engine. :+1:

**Comment by mercury501** [comment]
Sharing my progress:
I'm able to turn James using the mouse, only for now I'm having 2 states, slow and fast turn, I'll look into how to implement some kind of curve to translate relative mouse input data to joystick analog data.
Here's a test build (only works with 1.0)
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9688047/d3d8.zip)

I put some little temporary things in the debug overlay, it was useful while testing and debugging things!

You can aim and shoot with mouse buttons, and it detects which button you've mapped to do so. I still have to debug tho, as it doesn't work with arrow keys for example, but I think it's a good place to start!

**Comment by Polymega** [comment]
Simply amazing... Even something as simple as pressing left click to skip the intro screens... Never thought I'd see the day where I could do this! And this test finally made me switch from arrow keys for movement to WASD... that was a nice feeling ☺️ 

Anyway, I played around with it and I was grinning the whole time. 😁 Can't believe this is becoming a thing! 

I know this is very early on, but I have a few notes for the future from playing around with it just now:

--------------------

You may want to put a condition where mouse movement is disabled while text prompts are shown. There are different text prompts in the game. Some require you to press the Action button to proceed while others will go away if you simply move the character. The latter text prompts can instantly disappear upon triggering them due to slight mouse movement.

I tested this with SH3 PC and it looks like they disable mouse movement during texture prompts as well to avoid this very issue. We can find the appropriate address to know when a text prompt is shown later, no problem.

---------------------

Whenever I Alt + Tabbed out of the game James would start spinning in circles on his own. I was pretty sure the mouse wasn't moving when I did this, but I'm not sure.

Either way, we may want to set mouse movement to 0 whenever the game window loses focus. This could help prevent James spinning infinitely when Alt + Tabbing out.

----------------------

SH3 PC has a mouse for the pause screen. SH2 PC doesn't have this but, as a type of compensation, it might be cool to detect whenever the mouse is moved forward/back then cycle up on the pause menu selection up/down. [009326B4 (Pause menu button index) byte](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Common.cpp#L46)

----------------------

I used a wireless mouse for testing. When I turned off the mouse's power and turned it back on mouse input no longer worked. Just a heads up on that.

**Comment by mercury501** [comment]
Here's a new build, it should fix the following:

- Ballerina James when Alt+Tabbed
- Ignoring input when text is shown

The address I found is sh2pc.exe+54CC58, I don't exaxtly understand yet what it represents, but I'm using it for now.

I'm still looking into:

- Pause menu navigation
- Avoid button input sticking

Cheers!

**Comment by Polymega** [comment]
> Here's a new build, it should fix the following:

Thanks for adding these in! I hope I didn't distract you too much with those notes; they were written with the intent of being later-on things to look into. 😅 

> The address I found is sh2pc.exe+54CC58, I don't exaxtly understand yet what it represents, but I'm using it for now.

I will try and do a full playthrough soon while monitoring this address. I'll let you know if it should be totally safe or not to use!

Thank you!

**Comment by mercury501** [comment]
No worries, it's good to focus on some other things from time to time!

If you're gonna have a playthrough you could watch also this other address `sh2pc.exe+54CC6C`, as it changes when there's text as well.

**Comment by Polymega** [comment]
`sh2pc.exe+54CC58`
The address you're currently using. I assume you're doing something like if `0094CC58 == 255` enable mouse movement? If so, this is safe to do. The value for this address actually changes a lot for all sorts of different things, not just on text prompts, but it always goes back to `255` during regular gameplay, which makes it safe to use, I believe.

`sh2pc.exe+54CC6C`
This one is not safe to use. It's "default" value constantly changes depending on which room/area you are in.

**Comment by mercury501** [comment]
Yeah, that's precisely the condition, thank you!

**Comment by PunishedFiddle** [comment]
Cool! I've beat SH1&2EE using SH3 style KB+M a month ago, so It'd be good to have a native mouse support for SH2EE. I also remapped a free view button to my mouse's side-button and It felt nice.

**Comment by mercury501** [comment]
Thank you!
Here's another build, with the "ignore when text is up" function and pause menu navigation:
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9693331/d3d8.zip)

I'll have to look into button sticking now, besides maybe a better "analog" support. How does it feel to control james? I've never used kbm even in sh3, so I don't have a feel for it!

**Comment by Polymega** [comment]
Awesome! A few more notes, if you don't mind:

-------------

You may want to add an additional condition check:

If [EventIndexAddr](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Patches.h#L211) == 5 (map) || 6 (inventory) || 7 (options)
- Disable mouse click functions (left click -> Action Input, right click -> Cancel Input)

To explain:

![image](https://user-images.githubusercontent.com/27395260/193475000-2b91fa6b-f46f-42b1-82c6-5d770b48ff5f.png)

On the map screen, you can use the mouse cursor to click the purple arrows to cycle between maps. However, with this fix, left click also registers as an Action input, so when you a purple arrow it will override this click and zoom in on the map instead. Disabling the fix on this menu should prevent this issue.

![image](https://user-images.githubusercontent.com/27395260/193474966-ef771ece-dc00-4263-9d78-8e1d6d54c16b.png)

On the inventory screen, you can use the mouse to click the << and >> icons to move the item carousel. A similar issue happens here where when you click <</>> it will simultaneously cycle _and_ select an item instead of just cycling. Disabling the mouse click functions on this menu should also prevent this issue.

I included `7 (options)` menu in the conditional check since this screen already functions correctly with the mouse. Excluding it would just help prevent any redundancy issues with mouse functionalities.

-------------

Menu navigation for the pause menu is a bit too delayed/sluggish. Can this be "snappier"?

---------------

### Special Consideration: Memos Screen
On the note of pause menu navigation with the mouse, could such a thing also be implemented to the Memos Screen, where mouse movement will cycle through the memos and left/right click work here? ([EventIndexAddr](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Patches.h#L211) == 8 (memo list))

Additionally, SH2 PC has a special rule in place:
Keyboard arrow keys are _always_ used for menu navigation. So, for example, if you change movement to WASD you can navigate the menus using WASD but _you can also_ navigate using the arrow keys. The arrow keys are hard-coded to always be used for menu navigation, no matter what.

...except they forgot to do this for the Memos List. So, for example again, if you set movement to WASD then only WASD will work on the Memos List screen. To be honest, I think Creature Labs totally forgot the Memos List exists, as it doesn't even have a mouse cursor for navigation.

With that said, can some special love and attention be put towards the Memos List to do the following?

- Mouse movement can cycle through the memos on the Memos Screen.
- Right click on the main Memos Screen will exit this screen.
- Arrow up/down keys can also navigate the memos within the Memos Screen.

------------------

> besides maybe a better "analog" support. How does it feel to control james? I've never used kbm even in sh3, so I don't have a feel for it!

It's feeling great so far!! It can feel a little "weird" using a mouse for movement at first, but after a while you get used to it. I'll also say I missed KB+M controls from SH3 PC upon returning to SH2 PC. It's nice to have the essentials such as turning, examining, cancelling, etc on your mouse; it's a liberating feeling once you get a hang of it. 😊 

As you said, maybe some better analog detection for his turning would be nice, but it's really coming along great!!

**Comment by mercury501** [comment]
So I implemented your suggestions, I restored the Enter key as well in the memo screens, as I think in general it acts as "ok" in all other menues, right?

I reduced the "debounce" from 300ms to 150, let me know if it needs adjusting!

Your analysis is always spot on and appreciated!

Here's a new build:
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9693621/d3d8.zip)

**Comment by Polymega** [comment]
> I restored the Enter key as well in the memo screens, as I think in general it acts as "ok" in all other menues, right?

My man!! That's something I didn't notice. Great catch! 👍 The Memos Screen is now shares the same "rules" as all the other menus. This consistency is wonderful. Thank you again!

> I reduced the "debounce" for pause and memo vertical navigation from 300ms to 150, let me know if it needs adjusting!

Could we bump this down to something like... 50ms? 

Also, another adjustment for the pause menu I'd like to throw by you:

The pause screen will vertically cycle over from top -> bottom or bottom -> top when going through the choices, which is great. However, this feels "weird" on the _horizontal_ cycling for the "Are you sure you want to exit?" Yes/No selection.

Can we add the following?

If Pause Menu is active
- If ` 009326B0 (exit to main menu choice) == 0 (yes)`
   - Prevent mouse movement left from cycling choice
- Else If ` 009326B0 (exit to main menu choice) == 1 (no)`
   - Prevent mouse movement right from cycling choice

^ The idea is if "Yes" is selected, left mouse movement won't cycle the choice to "No" (which is on the right), and vice versa. As otherwise, this feels "weird."

**Comment by mercury501** [comment]
I agree, feels better now.
here's a new test build:
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9695808/d3d8.zip)
