### ISSUE TITLE
Game crashing within 2 minutes of entering Prison

### ISSUE THREAD

**Issue by nosulragal** [elishacloud/Silent-Hill-2-Enhancements#614]
After I proceed down the ramp beneath the Historical Society and pass the door into the prison, within 2 minutes the game will CTD. Nothing prompts this. I could be standing still and the game still crashes. It's repeatable, always within the same amount of time. I search Google and this github and could find nothing about this specific issue, so I apologize if this has been covered elsewhere. 

I have already set d3d8to9 = 0 and AutoUpdateModule = 0 as I saw those were commonly performed tasks at the start of bug testing. The game still crashes.

Here is my crash log (I hope I included this right, I've never used github before.)

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9741033/d3d8.log)

**Comment by Polymega** [comment]
Hello,
Where did you acquire the base/vanilla game from? This might correlate with the issue you're having.
Thanks

**Comment by nosulragal** [comment]
I acquired the fully extracted version from [here](https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download) and put it in its own folder.

I acquired the SHEE executable from [here](https://enhanced.townofsilenthill.com/SH2/install.htm) and installed it to the same folder I extracted the game to.

When the crashing issue first happened and I was searching for solutions, I found [this](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v2.0.2006.0) version, downloaded the new files and installed them into the same directory. Still crashes.

I have not yet performed the solution found in [this](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/591) thread, but I am unsure how it would matter because the steps given are literally the steps I followed to install the game in the first place.

**Comment by Polymega** [comment]
Can you download the build found in this thread and see if the crash persists?
https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/599#issuecomment-1266087700

**Comment by nosulragal** [comment]
Well, it doesn't seem to be crashing within 2 minutes yet, so that's a big fix! Thank you so much. Looking at the other thread, it's something to do with the shadows, I guess? It's strange how the rest of the game ran perfectly aside from some audio stutters but it would just CTD only when entering the prison, but, whatever. I'll play it some more later and if the problem crops up again I'll let you know.

Thank you so much for your attention and your assistance!

**Comment by Polymega** [comment]
Great! Hopefully that fixes the problem. The shadow thing is an unrelated issue. The build you're using now has the project hooking its code into the game in a different way. This new way was harder to set up, but should prove safer/more stable for use.

**Comment by Polymega** [comment]
We believe the reason for these seemingly random (but consistent) freezes and crashes might be due to a Windows update conflicting with how our project hooks itself into the game and/or Windows files. We've just released a new build that uses an entirely new hooking method which should fix the issues you were experiencing. 

You can grab this update to the SH2 Enhancements Module by either running the Setup Tool in Maintenance Mode and checking for updates:

![image](https://user-images.githubusercontent.com/27395260/198746434-162feecb-9967-44c7-b0f4-8093408054e5.png)

[Or by manually downloading here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest) (We recommend updating through the Setup Tool if you installed the project using this tool, otherwise the tool will not know you have updated this package.)

-----------

If you don't mind, please let us know if you still experience this issue upon updating. We'll close the ticket after a little while if we don't hear back. Thanks
