### ISSUE TITLE
[Issue with FMV Pack] Flashback cutscene clips out at the end

### ISSUE THREAD

**Issue by IlDucci** [elishacloud/Silent-Hill-2-Enhancements#615]
I was recording all the game's cutscenes when I realized that flash.bik's audio noises out at the end of the video. Some people might not notice it because there's also music playing over, but the clipping can be heard even by playing the .bik video file.

Solution should be simple: find out if the audio is getting cut before when it should and add a tiny fade effect at the end.

**Comment by Polymega** [comment]
The waveform fades out correctly:

![image](https://user-images.githubusercontent.com/27395260/195215599-c6e22722-1f23-45d3-9377-78f15e7185ea.png)

Its length is 4.853 seconds. 

Opening the video, its length is 4.20 seconds:

![image](https://user-images.githubusercontent.com/27395260/195215902-615fad30-daa3-4042-85c9-982dd2071a9d.png)

When previewing this video through RAD Tools Bink player, the audio gets stopped short because the video is shorter than the audio length. However, in the game, the audio is timed different for this video and _I don't understand why._

If I make the audio 4.20 seconds long to fix this, the audio stops well _before_ the video ends when watching it through the game. When previewed through the Bink player, everything is timed correctly. This video with the original 4.853 second audio length gets cut off when viewed **both** in the game and through the Bink player. I really don't understand what's going on here.

Anyway, I made the audio end at 4.545 seconds, which is longer than the video itself, but looks to be timed just right when viewed through the game. It'll still click/pop if viewed through the Bink player.

I don't claim to understand why this is. Maybe the game is speeding up the framerate of this particular FMV just a bit? Or maybe it's just good ole fashioned jank with the game. I dunno... But here it is if you want to play with it. I'll also include this as part of a new FMV Pack update. Thanks, IlDucci.

@MarioTainaka
[flash.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9760395/flash.zip)

**Comment by MarioTainaka** [comment]
> The waveform fades out correctly:
> 
> ![image](https://user-images.githubusercontent.com/27395260/195215599-c6e22722-1f23-45d3-9377-78f15e7185ea.png)
> 
> Its length is 4.853 seconds.
> 
> Opening the video, its length is 4.20 seconds:
> 
> ![image](https://user-images.githubusercontent.com/27395260/195215902-615fad30-daa3-4042-85c9-982dd2071a9d.png)
> 
> When previewing this video through RAD Tools Bink player, the audio gets stopped short because the video is shorter than the audio length. However, in the game, the audio is timed different for this video and _I don't understand why._
> 
> If I make the audio 4.20 seconds long to fix this, the audio stops well _before_ the video ends when watching it through the game. When previewed through the Bink player, everything is timed correctly. This video with the original 4.853 second audio length gets cut off when viewed **both** in the game and through the Bink player. I really don't understand what's going on here.
> 
> Anyway, I made the audio end at 4.545 seconds, which is longer than the video itself, but looks to be timed just right when viewed through the game. It'll still click/pop at the end if viewed through the Bink player.
> 
> I don't claim to understand why this is. Maybe the game is speeding up the framerate of this particular FMV just a bit? Or maybe it's just good ole fashioned jank with the game. I dunno... But here it is if you want to play with it. I'll also include this as part of a new FMV Pack update. Thanks, IlDucci.
> 
> @MarioTainaka [flash.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9760395/flash.zip)

Sorry for the late response. I might look into fixing this myself cuz I did notice it a couple of times. I think this happens because the game kinda...sorta... speeds up the videos very slightly even though they're running at 30FPS

**Comment by MarioTainaka** [comment]
> The waveform fades out correctly:
> 
> ![image](https://user-images.githubusercontent.com/27395260/195215599-c6e22722-1f23-45d3-9377-78f15e7185ea.png)
> 
> Its length is 4.853 seconds.
> 
> Opening the video, its length is 4.20 seconds:
> 
> ![image](https://user-images.githubusercontent.com/27395260/195215902-615fad30-daa3-4042-85c9-982dd2071a9d.png)
> 
> When previewing this video through RAD Tools Bink player, the audio gets stopped short because the video is shorter than the audio length. However, in the game, the audio is timed different for this video and _I don't understand why._
> 
> If I make the audio 4.20 seconds long to fix this, the audio stops well _before_ the video ends when watching it through the game. When previewed through the Bink player, everything is timed correctly. This video with the original 4.853 second audio length gets cut off when viewed **both** in the game and through the Bink player. I really don't understand what's going on here.
> 
> Anyway, I made the audio end at 4.545 seconds, which is longer than the video itself, but looks to be timed just right when viewed through the game. It'll still click/pop at the end if viewed through the Bink player.
> 
> I don't claim to understand why this is. Maybe the game is speeding up the framerate of this particular FMV just a bit? Or maybe it's just good ole fashioned jank with the game. I dunno... But here it is if you want to play with it. I'll also include this as part of a new FMV Pack update. Thanks, IlDucci.
> 
> @MarioTainaka [flash.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9760395/flash.zip)


Yeah so this sounds alot better. It still clips a teeny tiny bit but you won't notice unless you're wearing studio headphones.
