### ISSUE TITLE
Download failed: The connection with the server was reset - Loop

### ISSUE THREAD

**Issue by DarlingDash** [elishacloud/Silent-Hill-2-Enhancements#616]
![SH2EEsetup tmp_z1EmJVi45g](https://user-images.githubusercontent.com/115605315/195244349-be194149-96cc-4f20-a407-883a400e166e.png)
 This error just repeats, can't seem to find a consistent failing pack but most commonly its happened with the xinput pack and the other ones eventually.

**Comment by Polymega** [comment]
I'm trying to get to the bottom of this. Can you please try again now? I've changed additional CDN settings which I'm hoping mitigates this issue. Thanks.

**Comment by Polymega** [comment]
If you download this link directly, does it work? You might need to Right Click > Save As to download it:
https://files.townofsilenthill.com/SH2EE/packages/SH2EE_XInputPlus_4.15.2.zip

**Comment by Polymega** [comment]
> Edit: i edited the url to https://files.townofsilenthill.com/SH2EE/packages/SH2EE_FMV_Enhancement_Pack_1.5.3.zip and it downloaded that as well. So i guess i could download it all this way, just would have to find the exact zip names and where to extract them

Great. That was going to be the next thing I was going to ask you to try (a large download). I'm still unsure what's happening but, in the meantime, here are direct download links:

- You can obtain the latest SH2E module [from this GitHub page](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases)
- https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Enhanced_EXE_NA_v1.0.zip
- https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Essential_Files_1.2.4.zip
- https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Image_Enhancement_Pack_1.1.1.zip
- https://files.townofsilenthill.com/SH2EE/packages/SH2EE_FMV_Enhancement_Pack_1.5.3.zip
- https://files.townofsilenthill.com/SH2EE/packages/SH2EE_Audio_Enhancement_Pack_2.0.4.zip
- https://files.townofsilenthill.com/SH2EE/packages/SH2EE_DSOAL_1.31a.02.zip
- https://files.townofsilenthill.com/SH2EE/packages/SH2EE_XInputPlus_4.15.2.zip

Since the Setup Tool is giving you trouble, you won't be able to use it to check/know when any package is being updated. I'm hoping we can have you run the Setup Tool without issue in the future so you can use the tool to your advantage.

**Comment by Polymega** [comment]
PS - Please let me know if you run into any issues or not directly downloading these packages once you've downloaded them all.

**Comment by Polymega** [comment]
@DarlingDash 
I'd like to ask for your help testing for a solution to the issue you were having. None of us on the team are experiencing this issue, so we cannot test for a solution ourselves. Therefore, it is very important for us to have someone like you test. Your help with this can ensure others in the future will hopefully never run into the same problem.

If you don't mind, please download this test build of our Setup Tool: [SH2EEsetup_TESTBUILD.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9780900/SH2EEsetup_TESTBUILD.zip)

### Before you run the test build
A few important notes:

- This is a WIP (work in progress) build, so certain functionalities might not work right. _The only thing we're worried about with you using this test build is whether or not you can successfully download all the packages in one go._
- The installation process might not finish at all using this build, as only the new method of downloading the packages is implemented. Things might get stuck once the last file is downloaded. Again though, we're only worried about if you are able to successfully download **all** of the packages in a single go.

With these important notes in mind:

** **You should NOT use this installer on your actual Silent Hill 2 game folder!** **
Run the installer and have the files downloaded to a temporary, throw-away folder. Because this is a WIP test build, it should not be used to replace any actual files in the game folder.

So with all of that said, may we ask you to download the test build linked above, run it, download the packages to a temporary/throw-away folder, and let us know if you were able to successfully download **all** of the packages in a single attempt?

Thank you very much for your time and help here.

**Comment by DarlingDash** [comment]
I am glad to help, excuse me for the late reply i was at work.
![NVIDIA_Share_VnFxvj7Jdj](https://user-images.githubusercontent.com/115605315/195738713-54e5f35f-e914-4e5e-a1fa-36e77d168f64.png)
https://streamable.com/5df6r2
The files seem to still not be able to download. I get this message running with and without admin privilege. I also attached a streamable link showing what happens when i go through with downloading the files if that helps. Let me know if i could try anything else.

**Comment by Polymega** [comment]
Thank you for your help with testing. I'll tag @nipkownix, whose the creator of the Setup Tool, so he can respond directly with any future posts/testing.

**Comment by nipkownix** [comment]
Thanks for testing, @DarlingDash. Could you please test this new build?
[SH2EEsetup-ght.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9786855/SH2EEsetup-ght.zip)

**Comment by DarlingDash** [comment]
Happy to report that indeed successfully install all the way through. Nice!
![image](https://user-images.githubusercontent.com/115605315/195956865-36fd23fe-7da9-4c98-866d-b2fb4f2b8edb.png)

**Comment by nipkownix** [comment]
@Polymega Welp, that last build was using GitHub's servers to distribute the files, which confirms our host/CDN is the issue here :/

**Comment by Polymega** [comment]
@DarlingDash 
I'm sorry to ask for your help again, but may I ask you to try the following build for what should hopefully be the final test?
[SH2EEsetup_1.1.0.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9795691/SH2EEsetup_1.1.0.zip)

**Comment by DarlingDash** [comment]
No problem, Glad to help. First thing is when extracting the zip and opening the setup.exe it says its outdated and it generates two more setup files and deleted the extracted one i think? Anyway after updating it and going through with it were back at square one with the connection reset. 
![zfHNo3wpd6](https://user-images.githubusercontent.com/115605315/196062589-4eb022a4-11ae-463c-8789-d7fd4ed12e26.png)
![firefox_wTB7C6wqTk](https://user-images.githubusercontent.com/115605315/196062591-8d22a44b-6179-40cd-885b-3cad508e936b.png)
![NVIDIA_Share_F0aKaOatzk](https://user-images.githubusercontent.com/115605315/196062592-d297380a-eefa-446c-bd55-94e135e10894.png)

**Comment by Polymega** [comment]
Thank you so much again for testing. As for the outdated warning/message: That was a mistake on my end when sending you that new build. That can be ignored for these testing purposes. The main thing was whether or not you got the server reset message upon attempting to install, which you did. Okay, that helps confirm some things on my end. Thanks!

**Comment by CLPSAW** [comment]
Hi everyone, I was very excited about this easier-to-install setup tool, but sadly, I experienced the same "download failed" error mentioned above. I was able to bypass this by unchecking the box for Enhanced FMV and Audio packs, which are the largest in file size. Surely I can install those manually, as I used to in the past when I tried the Enhanced project, but I'm reporting this so you guys can perfect this awesome tool that most certainly makes it more accessible to many other players, going through each process manually was a real pain. Thanks for the attention.

**Comment by Polymega** [comment]
We appreciate you letting us know! We're in the process of getting this sorted out. In a nutshell: It looks like the hosting provider used for the project (for both the site and the download packages) has fairly strict timeouts in place for long, continued server connections (such as when trying to download all the project files through the Setup Tool). 

Since the project is on a shared hosting plan, we do not have access to change/increase the length before timeout on the server. I'm looking into alternate providers for file sharing. I want a file sharing provider that doesn't have any sort of bandwidth cap per month, that provides stable/fast connections, and allows for direct linking.

In the meantime, you can run the test build of the Setup Tool nipkow provided above ([found here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/616#issuecomment-1279029840)) to download any outstanding packages. Sorry for the issues.

**Comment by CLPSAW** [comment]
Thanks for replying. I am already far into the game :) I simply combined the Setup Tool and manual downloads of the FMV and Audio packs, everything is working fine and, since it's been a while since the last time I played SH2, specially with the Enhancements, I gotta say, everything is looking awesome! Much higher quality and NO obvious bugs so far, unlike previous builds with audio issues or letterboxing issues on the map, etc. It all looks so hi-res and perfect!

On a side note, I could simply google this before asking, but you guys are the experts: is there anything similar but for SH3?
Much appreciated, and, as I'm sure I already said this once in another account, keeping one of the best games ever made alive after all these years and making it even better, it's something I wish I could thank you enough, but THANK YOU!

**Comment by Polymega** [comment]
Great; glad you got it sorted out. If you don't mind, in the next day or three, I might ask you to retry the Setup Tool to see if it downloads everything. (I'd ask @DarlingDash to help with this, but we've made him test so many times already!) 

I'm in the process of switching the site over to a dedicated hosting plan (I'll get an entire server all to myself), and I'm thinking/hoping that'll fix the timeout issue. I'll have SSH access to the server, so if the issue still happens, I should be able to increase the length before timeout to remedy the problem.

Anyway, I'm speaking ahead of myself here. But, if you don't mind, I'd like to ask your help with testing in the coming days.

> On a side note, I could simply google this before asking, but you guys are the experts: is there anything similar but for SH3?

We've haven't looked into SH3 PC but there exists patches for the game. Steam006, who is apart of our team on this project, has made a lot of improvements on his own for the game. [You can find more info here.](https://www.pcgamingwiki.com/wiki/Silent_Hill_3#Essential_improvements)

> Much appreciated, and, as I'm sure I already said this once in another account, keeping one of the best games ever made alive after all these years and making it even better, it's something I wish I could thank you enough, but THANK YOU!

From all of us: Thank you! ❤️

**Comment by CLPSAW** [comment]
Sure, I'd be glad to help, I just hope I don't miss the request.
I installed all 5 SIlent Hill games today, after finding a video about this new easier Setup Tool method, I decided to try SH2 once more, to see if all major bugs were fixed and hoping this would be a good reason to replay the franchise after so many years. SH3 is probably the only one I missed some endings in the past, but why play SH3 when I can start from the SH2? :)
SH1 is the only one I did everything over and over, with awesome graphics on the emulator, so starting from the second game is a good plan, especially with how good it is looking now!

One question, when I do get to test the thing for you, the process will be to download it to a random location so I don't mess my current installation?
Again, thank you dearly for the support and I'll be looking into that SH3 link you sent here.

**Comment by Touisni** [comment]
Hello guys I stumbled unto the same issue and it still prevails even in the test build, I've downloaded the files manually I'm wondering how can I install them manually too

**Comment by CLPSAW** [comment]
Yeah, I'm sorry, I placed them there but I made a mistake when I was explaining here. The data folder contains a movies folder but you can clearly see how smaller the total file size is there.
I'm making sure to check for updates here often. SH2 is perfect so far, with very minot visual bugs and 2 weird collision problmes that may or not have been in the original game, I can't recall, if I had a place to send screenshots, I'd love to report bugs, if you guys do care about solving each one.

**Comment by Polymega** [comment]
> I'm making sure to check for updates here often

I'm hoping the move over to a dedicated server will ultimately fix this error with the Setup Tool. Time will tell once the migration is complete.

> SH2 is perfect so far, with very minor visual bugs and 2 weird collision problems that may or not have been in the original game, I can't recall, if I had a place to send screenshots, I'd love to report bugs, if you guys do care about solving each one.

If it's super minor nit-picks with visuals and collision we probably won't address them. 

For example: Shadow logic/behavior is kind of weird with this game. It can look glitchy in some spots, but that's actually accurate/correct shadow behavior. 

There are also numerous instances of Z-fighting with geometry, as Team Silent liked to overlay polygons with transparent textures _just above_ other polygons.

Collision in the game can also be weird. Especially in the apartments whenever a Lying Figure or Mannequin is inside one of the apartment's very tiny closet spaces. If done right, you can make them teleport all over the place.

**Comment by AndrewsSlaveck** [comment]
Hi everyone,
I was hoping to find some help in here. I'm having this exact same issue with the new download tool. 
I read this entire post to see if I had something to do, but it seems to me that this is a known issue.

If there's any update on this would you guys mind to reply with any info?

Thanks in advance guys.
By the way. This project is a masterpiece. Thanks for everything you guys are doing in this awesome work.

**Comment by mircoCampanella** [comment]
Hi guys,
it might be a solution to upload zip files to github, 
because I'm trying to manually download zip files from
https://files.townofsilenthill.com/SH2EE/packages
and I can't get over 100 kb/s with google chrome

**Comment by Polymega** [comment]
We're currently migrating the project site/files over to a dedicated server to help with the load of new users due to the recent SH announcements. As this migration is currently underway, there will be slowdown during this server transfer. Please be patient with us.

Check our Twitter page for server updates when they happen:
https://twitter.com/WhereAllBegins/status/1583624623752871936

**Comment by Guapotoni** [comment]
So, I may have found a fix. When the error message pops up that the connection has crashed etc. instead of hitting retry hit "Next" instead of "Retry" for some reason the download bar isnt working because as soon as I hit "Next' the game completely installed and ran. I also made sure it worked so I walked around the restroom and made a temp save, quit the game, reloaded the game and voilà ran perfectly. Hope this saves someone from wasting anytime on not playing this magnum opus.

**Comment by Polymega** [comment]
@DarlingDash @CLPSAW 
May I ask a big favor? Can you try the installer again **as soon as possible** and let me know if it times out for you or not? Also, can you let me know the average speed of the download? (Just watch it for 30-60 seconds at the start to get a base download speed.)

You can grab the Setup Tool here, if you need it again:
https://enhanced.townofsilenthill.com/SH2/install.htm#usingEE

Install the project to a temporary, throw-away folder for testing purposes.

Thanks

**Comment by Polymega** [comment]
Server migration is done and distribution for the project's file packages has been changed to a more stable solution.

I am going to close this ticket out . For sake of management/consolidation, if you run into any troubles still with the Setup Tool, [please report them here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/647).
