### ISSUE TITLE
IM DUMB WITH PCS

### ISSUE THREAD

**Issue by OGMrSmack** [elishacloud/Silent-Hill-2-Enhancements#617]
can someone please help me figure out how to run Silent hill 2 ehanced version with the sh2eesetup.exe file or whatever?

**Comment by Polymega** [comment]
You would download the "Fully Extracted Version" of SH2 PC from this site: https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download

Extract its contents to a folder [then follow Step 2 on our project site](https://enhanced.townofsilenthill.com/SH2/install.htm#usingEE) to install the Enhanced Edition project.

**Comment by OGMrSmack** [comment]
do i need the disc?

**Comment by Polymega** [comment]
No, you do not. If you download the base (vanilla) PC game from the site I linked, you can then skip Step 1 on our project site and go straight to Step 2. Just follow the instructions on our site.

**Comment by OGMrSmack** [comment]
When i did this before i couldnt figure out how to run the launcher properly. Any tips for a newbie?

**Comment by Polymega** [comment]
All that should need to be done is double-clicking `SH2EEsetup.exe` to make it run. Follow its instructions to install the Enhanced Edition project. You'll need to download the base (vanilla) game first.

**Comment by OGMrSmack** [comment]
the base vanilla game is that the iso verion or am i dumb

**Comment by Polymega** [comment]
> You would download the "Fully Extracted Version" of SH2 PC from this site: https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download

Download then extract its contents. You will need to be familiar with unzipping packages.

**Comment by OGMrSmack** [comment]
oh boy im not familiar with computers at all

**Comment by Polymega** [comment]
> You would download the "Fully Extracted Version" of SH2 PC from this site: https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download

Downloading the "Fully Extracted Version" version will download a `Silent-Hill-2-Restless-Dreams_Win_EN_Fully-Extracted-Version.zip` file. Once download, you will right click this file and select "Extract All..." Extract the contents of this download to a folder of your choice.

This will extract all of the contents found within that .zip for a folder of your choosing. The files it will extract are all the files for the base (vanilla) version of Silent Hill 2 PC. You need these files for both the game to work in general and in order to use our project.

 Then, [proceed with Step 2 and follow its instructions on the project site.](https://enhanced.townofsilenthill.com/SH2/install.htm#usingEE)

Unfortunately, I would not be able to assist you much further than this.

**Comment by OGMrSmack** [comment]
thank you im just new to pc transfer from console never really use a pc and well now im a toddler

**Comment by Polymega** [comment]
No worries. Hope I helped you some!
