### ISSUE TITLE
Loud repeated beeping, followed by crash upon entering elevator in alternate Hospital

### ISSUE THREAD

**Issue by dlav97** [elishacloud/Silent-Hill-2-Enhancements#621]
Just got to the alternate Hospital on the 3rd floor. Whenever I open my map or inventory, a loud repeated beeping occurs. Also, whenever I enter the elevator, the game freezes. I have had 0 issues up until this point. Thank you for your time. I have included my d3d8.log file

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9815511/d3d8.log)

**Comment by Polymega** [comment]
Can you try this build of the project and let us know if you still experience these issues?
https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9701091/d3d8.zip

**Comment by Guapotoni** [comment]
btw this fixes it!!!
had the same issue

**Comment by Polymega** [comment]
We believe the reason for these seemingly random (but consistent) freezes and crashes might be due to a Windows update conflicting with how our project hooks itself into the game and/or Windows files. We've just released a new build that uses an entirely new hooking method which should fix the issues you were experiencing. 

You can grab this update to the SH2 Enhancements Module by either running the Setup Tool in Maintenance Mode and checking for updates:

![image](https://user-images.githubusercontent.com/27395260/198746434-162feecb-9967-44c7-b0f4-8093408054e5.png)

[Or by manually downloading here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest) (We recommend updating through the Setup Tool if you installed the project using this tool, otherwise the tool will not know you have updated this package.)

-----------

If you don't mind, please let us know if you still experience this issue upon updating. We'll close the ticket after a little while if we don't hear back. Thanks
