### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by Icaunic** [elishacloud/Silent-Hill-2-Enhancements#625]
Is the setup supposed to be downloading at 93-112kb/s or are there currently problems? I can't imagine this is supposed to be so?

**Comment by Polymega** [comment]
We're currently migrating the project site/files over to a dedicated server to help with the load of new users due to the recent SH announcements. As this migration is currently underway, there will be slowdown during this server transfer. Please be patient with us.

I just spoke with the hosting provider and I'm hoping the migration will be complete by sometime tomorrow.

**Comment by Icaunic** [comment]
really appreciate you thanks!
