### ISSUE TITLE
Fallo

### ISSUE THREAD

**Issue by Ceretesaurio** [elishacloud/Silent-Hill-2-Enhancements#629]
Al pasar del apartamento Wood Side al Blue Creek, el juego se queda bloqueado.
El programa no descargar y tengo fibra óptica de 300Mb/s. 
Alguna solución?

**Comment by Polymega** [comment]
If the game consistently gets stuck or freezes at the same point, try using this build of the project. Let us know if this fixes the issue: https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9701091/d3d8.zip

**Comment by Ceretesaurio** [comment]
Cómo implemento ésto porque yo no entiendo... a la hora de quedarse bloqueado tengo que reiniciar el equipo completo, no puedo cerrarlo tampoco.
________________________________
De: Polymega ***@***.***>
Enviado: sábado, 22 de octubre de 2022 18:49
Para: elishacloud/Silent-Hill-2-Enhancements ***@***.***>
Cc: Ceretesaurio ***@***.***>; Author ***@***.***>
Asunto: Re: [elishacloud/Silent-Hill-2-Enhancements] Fallo (Issue #629)


If the game consistently gets stuck or freezes at the same point, try using this build of the project. Let us know if this fixes the issue: https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9701091/d3d8.zip

**Comment by Ceretesaurio** [comment]
> Si el juego se atasca constantemente o se congela en el mismo punto, intente usar esta versión del proyecto. Háganos saber si esto soluciona el problema: https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9701091/d3d8.zip

He copiado esos ficheros, el juego avanza, hasta donde he probado (ya que llevo en directo desde el inicio de esta madrugada) ha fallado ahí, el sonido fallaba en la habitación de la caja fuerte (el puzzle) justo al cruzar la puerta para bajar de planta, se volvía a congelar antes de usar esos dos ficheros, ahora parece que funciona. Hay algún fallo o algo más adelante en el juego? el menú de configuración lo tengo en la opción Default, no he tocado nada, tengo el juego en compatibilidad con windows 7 (instalado en un 10) mi equipo es bastante potente Ryzen 7, 16gb de ram 3333mhz y una 3060 RTX de 12gb no debería haber problemas de rendimiento no?

**Comment by Polymega** [comment]
These reports of the game consistently crashing/freezing at a seemingly random point have just started happening. We haven't changed anything on our end with the project to make this happen. We're not sure, but we think it might be caused by a Windows update breaking something.

With the test build I sent you, our lead programmer has overhauled how our project hooks into the Windows files it needs. This change will officially be included with our next project update.

In the meantime, I'm glad to hear it's resolved your issues.

Oh, one thing though:

> el menú de configuración lo tengo en la opción Default, no he tocado nada, tengo el juego en compatibilidad con windows 7 (instalado en un 10

We recommend you disable any compatibility modes for `sh2pc.exe`. Simply run `sh2pc.exe` without any compatibility settings enabled.

**Comment by Polymega** [comment]
We have officially released the build you tested and confirmed was working for you.

You can grab this update to the SH2 Enhancements Module by either running the Setup Tool in Maintenance Mode and checking for updates:

![image](https://user-images.githubusercontent.com/27395260/198746434-162feecb-9967-44c7-b0f4-8093408054e5.png)

[Or by manually downloading here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest) (We recommend updating through the Setup Tool if you installed the project using this tool, otherwise the tool will not know you have updated this package.)

-----------

If you don't mind, please let us know if you still experience this issue upon updating. We'll close the ticket after a little while if we don't hear back. Thanks
