### ISSUE TITLE
1080p 4:3?

### ISSUE THREAD

**Issue by Seranim1** [elishacloud/Silent-Hill-2-Enhancements#634]
Hey, I wanted to ask if there is a way to play the game in 1080p while still using the original 4:3 aspect ratio? so 1440by1080. There is no ingame option for it

**Comment by elishacloud** [comment]
Yes, that is possible.

First you need to disable the "Show all resolutions in Options menu"

![image](https://user-images.githubusercontent.com/25625456/197400935-9af96aa3-d65b-4e00-ace8-7bf53c4d4972.png)

Then add the following items to the d3d8.ini file:

```ini
ResX = 1440
ResY = 1080
```

You may also need to manually hide your Start Menu bar because the game does not hide it in this mode.
