### ISSUE TITLE
Can't use Chinese language pack on SH2EE, the game will be messed up

### ISSUE THREAD

**Issue by MCSeekeri** [elishacloud/Silent-Hill-2-Enhancements#643]
Hi, I'm a player from China and I'm having some unexpected problems when I try to install the language pack on SH2EE.
This language pack is made by enthusiasts, and in their release page they claim that the language pack supports SH2EE, and the installation method is to replace the files in the `data` folder, but when I do that the game is still in English. If I replace the contents of the `sh2e` folder, the game will look like this.
![That's bad.](https://user-images.githubusercontent.com/20928094/198262488-bd9390e5-21b0-4375-b0dc-48362ef0c585.png)

I have tested two different versions of Silent Hill, one from your Github issue. the other from Rutracker, which I loaded and installed with Alcohol 120%.
I don't really know how to make language packs, so I'm attaching screenshots and files from the original author.
![From Douban](https://img1.doubanio.com/view/note/l/public/p54207538.webp)
![image](https://user-images.githubusercontent.com/20928094/198276264-0ec2325e-50a7-4f6c-b0e3-7e10c1c26d1c.png)
[Original author](https://www.douban.com/note/690960765)
Actually, the original author released a version with SH2EE and his language pack, which he said he had gotten your permission for. But for some reason, I can't run that version, ironically.
I'm attaching the original author's file here because the service used by the original author may be difficult for you to use, so I've put it [here](https://pan.mcseekeri.top/%E8%B5%84%E6%BA%90/SH2_zh_CN_Patch_v1.01.7z).

Incidentally, I see that you are currently experiencing server bandwidth shortages, why not use software such as [OneDrive-Vercel-Index](https://github.com/spencerwooo/onedrive-vercel-index)? That way the installer can also be downloaded through a fixed link.
If you can't upload to OneDrive due to copyright issues, `archive.org` is also a good option.

Since English is not my native language, I have used machine translation, so please be sure to point out if there is something difficult to understand

**Comment by Polymega** [comment]
> and the installation method is to replace the files in the data folder, but when I do that the game is still in English. If I replace the contents of the sh2e folder, the game will look like this.

It sounds like the installation method for the Chinese language pack precedes our project. We recommend never placing any modified files in the `data` folder. You should only placed modified files in the `sh2e` folder, as this ensures you never overwrite/replace original game files.

> I have tested two different versions of Silent Hill, one from your Github issue. the other from Rutracker, which I loaded and installed with Alcohol 120%.

We also don't recommend you use an installation of the base (vanilla) game from Rutracker. [Russian-packed versions of the game break compatibility with our project.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/623#issuecomment-1286308666)

> I don't really know how to make language packs, so I'm attaching screenshots and files from the original author.

The reason the main menu looks like this is because things must match. So, for the main menu screen, there are two textures at play:

- start00.tex - This is the background image with the SH2:EE logo in black
- start01.tex - This is the texture that contains all of the menu choices (Load, Continue, New Game, etc.)

Any time in the game where two or more textures are using together (such as the clock in the apartments which uses a second texture for the movable clock needles) their native resolutions must be scaled together.

So for your issue above on the main menu, start00.tex has been upscaled 4x its native resolution. But the Chinese translation for start01.tex is still at 1x (original) native resolution. In order for start01.tex to display correctly, its resolution must be enlarge 4x (or start00.tex must be reduced by 4x).

> [Original author](https://www.douban.com/note/690960765)
Actually, the original author released a version with SH2EE and his language pack, which he said he had gotten your permission for. But for some reason, I can't run that version, ironically.
I'm attaching the original author's file here because the service used by the original author may be difficult for you to use, so I've put it [here](https://pan.mcseekeri.top/%E8%B5%84%E6%BA%90/SH2_zh_CN_Patch_v1.01.7z).

I am currently working behind the scenes with the original author (Toni @lakeviewhotel) to make his Chinese language pack compatible with our project. This also means an HD Chinese font and HD main menu will be included.

If everything goes to plan, we will then host his Chinese language pack on our project site and it will be a simple case of download a ZIP file and extracting its contents to the main game folder.

> Incidentally, I see that you are currently experiencing server bandwidth shortages, why not use software such as [OneDrive-Vercel-Index](https://github.com/spencerwooo/onedrive-vercel-index)? That way the installer can also be downloaded through a fixed link.
If you can't upload to OneDrive due to copyright issues, archive.org is also a good option.

Thank you for the suggestion. It's a little more complicated than that. I just need our hosting provider to stop dragging us through the mud and allow me access back to my server files. Without access, I'm currently at a standstill with things. This has been one of the most unprofessional experiences I've had with a company in recent memory.

**Comment by MCSeekeri** [comment]
Ok, thanks for the reply, it's good to know that you guys are working with the Chinese producer, because he hasn't made any movement on the release page for a while and I thought he gave up on compatibility with SH2EE.
So, do I modify a few files to make the game work, or am I better off waiting for the Chinese package to be released?
Also the language pack page on the website seems to be inaccessible ......
Again, by the way, the version of Rutracker I downloaded is not the one that has been modified twice, but the original CD image, so I think it should be compatible.

I wish you all the best in solving the server problem soon!

**Comment by Polymega** [comment]
> Ok, thanks for the reply, it's good to know that you guys are working with the Chinese producer, because he hasn't made any movement on the release page for a while and I thought he gave up on compatibility with SH2EE.

toni seemed excited about the prospect of finally having an HD Chinese font sheet for the game. Hopefully he makes good progress on this and I will be there to help him and field any questions he may have.

> So, do I modify a few files to make the game work, or am I better off waiting for the Chinese package to be released?

There's a few ways you can go about this. Let's try either of these methods:

### Method 1
- Make sure none of the files in the `data` folder were overwritten/replaced.
- Download toni's current Chinese language pack.
- Then install the Image Enhancement pack. I don't know if toni's Chinese language pack also modified texture files, but by doing this, it will replace any Chinese texture files which should fix any incompatibilities.

^ I believe this should allow for the use of the Image Enhancement Pack images while also using a Chinese font without the full screen images breaking.

### Method 2
- Make sure none of the files in the `data` folder were overwritten/replaced.
- Fully delete the `sh2e\pic\` and `sh2e\font\` folders. This will delete all of the upscaled full screen textures and original HD font sheet.
- Then install toni's current Chinese language pack.

^ I believe this should remove the Image Enhancement Pack images (which will using the original/vanilla textures) while also using a Chinese font without the full screen images breaking.

> Also the language pack page on the website seems to be inaccessible ......

This was a mistake. I accidentally included that link on one page early. It shouldn't be there at the moment. I'd remove the link, but I have no access to my server files (this is the main problem I'm currently having with my hosting provider).

**Comment by MCSeekeri** [comment]
The first method failed as expected.
But the second method surprisingly works, only the settings page is messed up ......
I'll try the patch for the director's cut with toni instead.

**Comment by MCSeekeri** [comment]
The first method failed as expected.
But the second method surprisingly works, only the settings page is messed up ......
I'll try the patch for the director's cut with toni instead.

**Comment by MCSeekeri** [comment]
After changing the patch, the game is in Japanese, and the settings page is still garbled ......
So sad

**Comment by Polymega** [comment]
It might be best to reach out to toni and see if he can troubleshoot.

**Comment by MCSeekeri** [comment]
> It might be best to reach out to toni and see if he can troubleshoot.

Ahh……I don't have an account for the site where he posted the page, and I don't know how to contact him.
I'll go to his Github Repo and submit an issue.

**Comment by MCSeekeri** [comment]
I found the version of SH2EE that renders Chinese properly, and it seems to be an older version.
The key here is sh2pc.exe, older versions of sh2pc.exe do not seem to have the problem of rendering Chinese as Japanese.

The file is attached [here](https://pan.mcseekeri.top/%E8%B5%84%E6%BA%90/Silent%20Hill%202.exe) and may be helpful to you in solving this problem.
```
SHA1
FAA11CC156F54CCC52866336D4B95515CD3B276D
SHA256
482FC4AC2EC062264D4E537E6E084FD0FEBCAAE308B009E5954899FFB5460D64
```
Also, I'm glad to see you guys solved the slow download problem!
