### ISSUE TITLE
Crash during first Pyramid Head fight

### ISSUE THREAD

**Issue by jayceedeeo** [elishacloud/Silent-Hill-2-Enhancements#645]
During the first pyramid head fight, about halfway through, the music starts stuttering. The game will then crash whenever the music stops playing (whether that be dying, leaving through the bottom door, or once it has fully faded out after leaving thru the top door). Restarting the game, my computer, or muting the music didn't fix this.

**Comment by Polymega** [comment]
We believe the reason for these seemingly random (but consistent) freezes and crashes might be due to a Windows update conflicting with how our project hooks itself into the game and/or Windows files. We've just released a new build that uses an entirely new hooking method which should fix the issues you were experiencing. 

You can grab this update to the SH2 Enhancements Module by either running the Setup Tool in Maintenance Mode and checking for updates:

![image](https://user-images.githubusercontent.com/27395260/198746434-162feecb-9967-44c7-b0f4-8093408054e5.png)

[Or by manually downloading here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest) (We recommend updating through the Setup Tool if you installed the project using this tool, otherwise the tool will not know you have updated this package.)

-----------

If you don't mind, please let us know if you still experience this issue upon updating. We'll close the ticket after a little while if we don't hear back. Thanks

**Comment by jayceedeeo** [comment]
This fixed the problem! Thank you for your help!
