### ISSUE TITLE
Game crashes after leaving Heaven's Night and Passing the Truck

### ISSUE THREAD

**Issue by Mikeand1ke** [elishacloud/Silent-Hill-2-Enhancements#661]
Note I've tried so many different fixes I've seen throughout Github and nothing worked so far. Hopefully someone can help me here because this is odd

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9905185/d3d8.log)

**Comment by Polymega** [comment]
This will sound a bit off in and of itself, but in the main game folder rename `sh2e` to `lang` then launch the game. Does it still crash here?

**Comment by Mikeand1ke** [comment]
> 

Nope that didn't work

**Comment by Polymega** [comment]
Okay, you can rename that back to `sh2e`. At this time, we're not totally sure what is causing this issue. As you mentioned, there has been an influx of other tickets relating to the same thing (although the crashes/freezes seemingly happen at different spots).

The packages that are grabbed/downloaded by users haven't been updated since our last project update back at the beginning of July. And, back when this update was released, there were no issues like this...

**Comment by Mikeand1ke** [comment]
> 

Yeah it's just weird cause it wasn't crashing at all and now it's just constantly on that one part. Hopefully a solution is found!

**Comment by elishacloud** [comment]
Ok, I created an update that I hope can fix some of these issues.  Can you try this update?

Here is the update.  Unzip this into the Silent Hill 2 game folder overwriting the existing file: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9905745/d3d8.zip)

**Comment by Mikeand1ke** [comment]
> 

Still didn't work for me, legit replaced the file and still nothing

**Comment by Polymega** [comment]
Please update our project to the latest version(s) and see if that resolves the issue.

Closing ticket. Feel free to re-open if you'd like further assistance.
