### ISSUE TITLE
Translation Pack Discussion - Polish

### ISSUE THREAD

**Issue by destroytheardor** [elishacloud/Silent-Hill-2-Enhancements#663]
Hi!
I'm attaching Polish files in *.mes format. I've also included old translated in-game maps and Game Over screen - I was unable to upscale them on my own, so you can ditch them all together. I'd like to update some of these files in a later date if that won't be an issue. 
[Silent Hill 2 Enhanced Edition Polish language files](https://drive.google.com/file/d/1SHCIYLbGomsrbreBEoF_RDAdYBMYcTTZ/view?usp=share_link)

**Comment by Polymega** [comment]
Hi @destroytheardor,

Thanks for reaching out. Are you the creator of this translation? We'd love to work with you to include the Polish language pack as a download on our project site then! 

A lot has changed over the years with our project, which indirectly changes how we're handling translation packs. So I'd need to work with you to make sure those changes are updated/reflected for the Polish language. Are you open to working with me soon to make such changes?

Let me know and I can give you a list of resources to get started. But to start, [are you familiar with the SH2MSGConvert tool?](https://github.com/loadwordteam/SH2MSGConvert) This is a modern tool to change text strings in the game, and what we strongly recommend using to edit the message files.

> I've also included old translated in-game maps and Game Over screen - I was unable to upscale them on my own, so you can ditch them all together.

Sounds good. Any translation pack offered on our site will be for text only (along with a translated main menu). Looking at the package you sent, it looks like the one I helped Belek666 with in the past? I see the .ai file for the font sheet and an HD main menu (start01.tex).

**Comment by destroytheardor** [comment]
Hello @Polymega,
Yes – I created this translation a couple of years ago with Belek666 and some other guys. I was planning to refresh it a little in the near future to fix a few minor misspellings and compensate for ditching of translated maps. I'll be glad to work with you on bringing it into Enhanced Edition. 

SH2MSGConvert tool is new for me, but I'll try it out. It should be easy enough.

**Comment by Polymega** [comment]
> SH2MSGConvert tool is new for me, but I'll try it out. It should be easy enough.

It's very easy to pick up and there's plenty of documentation on their GitHub page for it. It's significantly better to use than the SH Resource Editor tool. 

Alright, so let's talk some more about translations. To start, we have written a comprehensive guide on translating to other languages for SH2 PC. In this guide, we also go over the SH2MSGConvert tool in certain areas: https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#

^ You don't have to read through all of this since you've already done most of the work, but there are several things we need to check off from this document:

-------------

### 4:3 Boundary Restrictions
[Have you kept translations within a 4:3 boundary?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.bgoye4s4iq8a) All of your translation tests should be done while playing the game in a 4:3 aspect ratio, to be sure.

-------------

### Fixing incorrectly colored text strings
A few lines in the game, such as "I'll wait at BAR Neely's" and "The door what wakes in darkness, opening into nightmares," should be blue, not white. [Have these colors been fixed?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.1d337z371evw)

-------------

### Recoloring save file names/prompts
Nearly all of the save location names have their colors changed for the save menu, to make their coloring more consistent. [Have you changed the colors to be compliant?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.ndiyy5lr2js)

- You can [download and use this file](https://igotaletter.com/temp/sh2pc/TranslationGuide/SH2PC_Translation-Guide_Save-Load-Screen-Color-References.txt) as a reference for how to update the colors of these strings in the `m_card_x_msg_*.mes` file. (Use with the SH2MSGConvert tool.)

----------

### Save screen character limitations
There are character limitations for a few strings in the pause menu. [Are you within these character limitations?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.fns41fbpz7b8)

-----------

### 2D/3D control string changes
Certain strings found within the Control Options menu can change, depending on whether Directional (2D) or Rotational (3D) control type is selected. [Have these strings been translated correctly?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.r53nwexuz3m2)

--------------

### Replace another language besides English
You should replace another language besides English (so, changing the "e" in `*_e.mes` to either "f", "g", "i", or "s".). [This is because the English language _**does not**_ use subtitles for a few spots.](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.405in8lvfet3)

- If you change which language the Polish pack replaces, make sure you update the language string in `options_msg_*.mes` accordingly. For example, if you are now replacing the German language (`options_msg_g.mes`), you'd change "Polszczyzna" _back_ to "English" and instead change "Deutsche" to "Polszczyzna", if that makes sense.

-------------

### HD font sheet
I see I helped you make the Polish HD font sheet in the past. We have made some updates/changes to how HD font sheets are handles (thanks to Belek666's help). I will take care of this part for you.

------------

### Packaging the Polish translation pack for use with the project
I will also handle this for you closer to the end.

------------

There's a lot to go over here, I know, but hopefully I broke it up into manageable pieces. If you have any questions, please let me know.

Thanks!

**Comment by Polymega** [comment]
No immediate rush for this! Take your time and I'll be here to help as I'm able. 👍

**Comment by justtoask** [comment]
@destroytheardor Did you test it?

**Comment by destroytheardor** [comment]
@justtoask I'm in 2/3 of the work right now. I can't spend as much time on this as I'd like to. It should be ready in a couple of days.

**Comment by Polymega** [comment]
Hi destroytheardor,
Wanted to check in and see how the edits for the Polish translation pack are going? If I can assist you in any way, let me know.
Thanks

**Comment by justtoask** [comment]
@destroytheardor Are you still active?

**Comment by destroytheardor** [comment]
@Polymega @justtoask Hey! I'm so sorry! First I've been abroad and then got overwhelmed by work, so I couldn't finish that translation. I only had time to correct all the files, but I still need to check markers and run some tests. I still need to finish my current project at work, so I won't get to SH2 before Friday.

**Comment by Polymega** [comment]
Thanks for getting back with us! Whenever you're ready, [please refer to this post](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/663#issuecomment-1300477009) for a checklist of items that may need attention for submission.

**Comment by Polymega** [comment]
I went in a tidied up the Polish font sheet. You can grab it below. Save out the image below as `font000.png` and place it in the `\sh2e\font\` folder. I'd possibly recommend removing any other versions of `font000` in this folder.

![SH2 PC - HD Fonts 10 rows - POLISH](https://user-images.githubusercontent.com/27395260/220793045-608753b4-41eb-4e3c-a4cd-3d096573da7d.png)

Then, make sure you are using a newer build when testing. [You can grab one of the latest project builds here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10798848/d3d8.zip)

**Comment by destroytheardor** [comment]
Wow, it looks stunning! Thank you!

**Comment by Polymega** [comment]
Happy to do so! We look forward to including the Polish pack on the project/site in the future!

**Comment by Polymega** [comment]
I've made some alterations to my native, working fontsheet file. With the uptick in interest of people wanting to make translation packs, these changes will make creating future fontsheets easier for me.

Anyway, this means I also made some alterations to the Polish fontsheet. Please use the fontsheet below for your work/submission: [SH2 PC - HD Fonts 10 rows - POLISH](https://user-images.githubusercontent.com/27395260/221448857-68ec79a5-587d-422e-ab67-e1dcf9506c0d.png)

**Comment by justtoask** [comment]
@destroytheardor It seems that this takes a really long time, could I try to help you?

**Comment by destroytheardor** [comment]
I know... I'm just working in two editorial offices at once and I have plenty of work related trips lately. I hope to jump in any day now, because I need to finish this before RE4R release week.

**Comment by justtoask** [comment]
@destroytheardor You sure you don't want me to help you?

**Comment by justtoask** [comment]
If you're still working on it, please reconsider the translated textures, since from what I've seen most other translation packs include them.

**Comment by destroytheardor** [comment]
Hello! Yes, I'm still *planning* to finish this. I've been trying to understand how to edit textures EE, but this is beyond my comprehension. 😑

**Comment by Polymega** [comment]
Unfortunately, there's no convenient tool out there yet that can handle, let alone edit the HD textures. I had to manually extra the body data of each `.tex` file (via hex editing) and place them in an appropriate `.dds` file with the correct header data.

It was a slow and somewhat grueling process. I don't really have any research notes on the matter, but I do have this Excel spreadsheet that catalogs all the images I worked on: https://docs.google.com/spreadsheets/d/1ENUcCJmnyXV2VJqx5LJMSoETpHOwlSHv8ANBvvv758s/edit#gid=0

However, for translation packs hosted on our project site, we're only hosting the translated `.mes` files and a translated main menu `start01*.tex`. So for inclusion of a translation pack on our project site, you wouldn't need worry about the fullscreen images.

**Comment by justtoask** [comment]
@destroytheardor If you're Still doing the textures I found some tools online, one of which allows for replacing textures.
https://www.silenthillmemories.net/sh2/modding_en.htm

**Comment by justtoask** [comment]
@destroytheardor How's the progress on the translation?

**Comment by xfc11** [comment]
Hello @Polymega! I already started a new translation project, but have a problem with making Polish characters visible in the game. I edited the table file, but after replacing e.g., š with ą, it's š that is still shown in the subtitles. Is there something that I'm doing wrong?

**Comment by Polymega** [comment]
> Hello @Polymega! I already started a new translation project, but have a problem with making Polish characters visible in the game. I edited the table file, but after replacing e.g. š with ą, it's š that is still shown in the subtitles. Is there something that I'm doing wrong?

Hi there! I'll ping @IlDucci on this as he might know what's going on. But to start with troubleshooting: [Are you using the custom, modified font sheet for the Polish language as part of your tests?](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/663#issuecomment-1441031432)

**Comment by IlDucci** [comment]
> Hello @Polymega! I already started a new translation project, but have a problem with making Polish characters visible in the game. I edited the table file, but after replacing e.g. š with ą, it's š that is still shown in the subtitles. Is there something that I'm doing wrong?

I think that, at first glance, yes, the custom font texture+bin file are not installed.

**Comment by destroytheardor** [comment]
@IlDucci Hey. You can use my translated files if you want. There's also a TXT-MES converter in the ZIP (text files in message folder are not converted to mes). I'm too busy with my work to finish the project at the moment. Feel free to use whatever you want.
[Silent Hill 2 Enhanced Edition PL.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13301701/Silent.Hill.2.Enhanced.Edition.PL.zip)

**Comment by IlDucci** [comment]
> @IlDucci Hey. You can use my translated files if you want. There's also a TXT-MES converter in the ZIP (text files in message folder are not converted to mes). I'm too busy with my work to finish the project at the moment. Feel free to use whatever you want. [Silent Hill 2 Enhanced Edition PL.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13301701/Silent.Hill.2.Enhanced.Edition.PL.zip)

That quote will probably be more useful to @xfc11 .

**Comment by Gabstom** [comment]
Hey!
I'm updated Polish map texture (1024) to upscale version from Enhanced Edition (4096)
I removed the original text and matched the font to the original.

[SH2.Mapy.HD.PL.zip](https://drive.google.com/file/d/1bXt0rAMhtGIcpVNK-L_Vwvhg2pTQ8oDx)

![1](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/117903500/2659e334-1cf0-43e4-ac78-f2f95ba26c4c)

![2](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/117903500/da930e6e-0ca6-4e32-925f-e86ac351d582)

**Comment by destroytheardor** [comment]
Hello again! I've been a bit overwhelmed lately, but I'm back on project - mostly thanks to Gabstom who made an awesome job upscaling *.tex files. I'm working on text files right now, and I'll a full package including Gabstom's textures as soon as I'm done.

**Comment by destroytheardor** [comment]
Ok, so... I think I've done the main part. I've fixed colors and checked the save screen character limit. I'm using the current SH2EE build and files, but seems like I missed something - Polish fonts still aren't displayed correctly in a few places - on the Pause screen, in the Inventory  and on some notes screens (notes read from Memo menu seem to work fine). Any ideas...?
@Polymega @justtoask 

**Screens:**
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/117284021/2dcd51ad-6d17-4ff2-b9d9-a3a38c390cf9)
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/117284021/227ea8fa-fd4c-427d-a8f5-106af16eddb6)
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/117284021/d8ed9405-798e-4763-b536-14f2b3a59777)

**Polish files + textures:**
https://1drv.ms/u/s!AoPqsCGJi0SzktwgfZpTM94nMBvmGg?e=p1EklR

**Comment by IlDucci** [comment]
> Ok, so... I think I've done the main part. I've fixed colors and checked the save screen character limit. I'm using the current SH2EE build and files, but seems like I missed something - Polish fonts still aren't displayed correctly in a few places - on the Pause screen, in the Inventory and on some notes screens (notes read from Memo menu seem to work fine). Any ideas...?

The latter two cases seem to be a case where the TXT file is in the wrong encoding, as it should not be outputting two characters per character.

For the PAUSE menu, if we are talking about the resource\r_menu_*.res files, remember that those files must be in ANSI/ASCII and that any Polish characters must be written with the characters that were replaced by the new Polish font.

**Comment by destroytheardor** [comment]
@IlDucci Yes! That was it! Thank you so much! I'll double-check everything and do some more testing. I'll make a contribution soon :)

**Comment by destroytheardor** [comment]
Alright, files are ready (I hope). Here's the link - https://1drv.ms/u/s!AoPqsCGJi0SzktwhPF-kF70YRx-epA?e=PDJjZ6
All text and texture files should be translated and double-checked. Polish does overwrite English in this version.
@Polymega

**Comment by Polymega** [comment]
Great work here, destroytheardor!

A couple questions for you:

For language packs hosted on our site, [we only include translated .mes files and a translated main menu.](https://enhanced.townofsilenthill.com/SH2/languagepacks.htm) If we offer this language pack as a download, are you okay with only having translated .mes files and main menu?

[We'd ask you to overwrite another Latin language besides English.](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit?pli=1#heading=h.15qhgoiz74zz) This is mostly because the English language doesn't translate _every_ string. In particular, this relates to the UFO ending ([see here](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit?pli=1#heading=h.405in8lvfet3)). Are you okay to have the Polish language pack overwrite another language instead? If so, I can tell you how to do this. It's very easy.

If you change it to replace another language, we would include a file the auto-launches the game with the Polish language already selected, so don't worry about that.

**Comment by destroytheardor** [comment]
@Polymega Alright, I made a new package without textures (except Main Menu). Polish now overwrites German, I made necessary adjustments in option_msg_g.mes and r_menu_g.mes. I also changed floor naming in appropriate files (2F in Poland is 1st floor etc. so we changed naming in *.mes files and on map textures; now it's reverted to English naming). I've double-checked everything and all seems to be fine. 

It's a bit of a shame that @Gabstom's work won't be included, but we spoke, and he's fine with this. As we understand, it is connected to updates of Enhanced Edition that might overwrite Polish textures with new English ones, so it might cause inconsistencies, so we're fine with this. 

However, it would be nice to maybe at least add a link to the Polish textures in the description of the language pack? Of course, if that's not a problem. I'll upload textures to my cloud drive and to the grajpopolsku.pl website (it's the biggest community of fan translators in PL).

It would be nice if one day someone could find a way to make textures work like language specific *.mes files, but that might be really tough, if possible at all.

[Silent Hill 2 EE PL (German to Polish).zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13873488/Silent.Hill.2.EE.PL.German.to.Polish.zip)

**Comment by Polymega** [comment]
Thank you so much, destroytheardor! Please give me a few days to look over the language pack. I'll do some checks and tests for the pack in the near future to help make sure everything is in order. 

> However, it would be nice to maybe at least add a link to the Polish textures in the description of the language pack? Of course, if that's not a problem.

Yeah, that would be fine! Just send me a link to the grajpopolsku.pl download once you get it established. 

Also, can you please send me a list of everyone's names who was involved in the creation of this language pack? Additionally, if you'd like, please also include a link to be associated with each person's name (such as if you want to include a website or contact link for each person).

**Comment by IlDucci** [comment]
Don't forget reason number two for picking a language to replace: the change in size of the "Put in Shelf" action in the Inventory menu, when looking at the shelf next to the Hotel elevator.

**Comment by destroytheardor** [comment]
@Polymega No rush, take your time. Just please take a closer look at Save Menu, as I'm pretty sure I've messed it up... ;)

The list of involved is rather short:

**belek666** - https://enhanced.townofsilenthill.com/SH2/credit.htm#Belek666 original fonts, additional tools, editing *.exe, technical stuff in general... and PS2 port; 
**xychu** - original widescreen patch for PC, testing... and Xbox port;
**Gabstom** - upscaled textures for Enhanced Edition [Gabstom](https://github.com/Gabstom)
and myself - **destroytheardor** - translation, texture editing, being a helpdesk guy for users, keeping an eye on the whole project in general... and PC version.

I could add a long list of special thanks tho, including a **big thank you to you** - for new Polish fonts and beautiful start01g.tex ;)

@IlDucci  Yeah, but it's not an issue - I figured it out like a decade ago ;)
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/117284021/8fc5b2f2-bcd8-4b24-92b7-6e7ad8bb0bf2)

**Comment by Polymega** [comment]
> @IlDucci Yeah, but it's not an issue - I figured it out like a decade ago ;)

A nice side effect of replacing the German language is it also makes this text string fit a lot nicer within the box:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/2ac274c3-76d0-4c5d-ab30-424f8203a212)

@destroytheardor 
Great work to you and everyone else involved with this effort! And than you for sending me a list of names/links of those who worked on this. A couple of notes and requests for you:

--------------------

For the file structure, please do the following:

- Rename the `sh2e` folder to `lang`
- Remove the following files from the package: `font000.tga`, `SH2 PC - HD Font (Polish).ai`
- Include the following file and place it in the **main directory**: [language.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13893904/language.zip)

---------------------

Is it possible to make the text strings on the right column shorter?

![Screenshot 2024-01-09 18-44-58](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/69c65843-7ba4-44d8-a2ce-c988a6863057)

-------------------

Can you make this text string **under 11 characters?** This is due to a bug with the game. [See here.](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit?pli=1#heading=h.2c7v1phm075w) You can make it say something simple like "Folder".

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/1d8d6593-1065-418c-8ab9-01f81f34efc7)

--------------

This save file name is actually used in three different locations: The beginning bathroom, the motorhome, and BAR Neelys. I'd advise changing the name of this save location. (For example: If someone saves in the beginning bathroom, they'll be confused why it says "Kamper") 

For the English version, we made the save file name "Bathroom/Motorhome/Bar". It's not the most elegant solution, but it covers all situations.

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/9bad396d-099a-4152-ac86-9e7409a0e6fc)

-----------------

Thanks!

**Comment by destroytheardor** [comment]
@IlDucci Thank you for kind words and for the tips. Here's the fixed *.zip:

[Silent Hill 2 Silent Hill 2 EE PL (German to Polish v2).zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13894211/Silent.Hill.2.Silent.Hill.2.EE.PL.German.to.Polish.v2.zip)

**Comment by Polymega** [comment]
Thanks! I noticed an alignment issue with the SH2:EE logo on the main menu (`start01*.tex`). I've went in and fixed that. You can find the final, packaged file here for your own records:

[SH2EE_LangPack_Polish.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13921373/SH2EE_LangPack_Polish.zip)

Are there any other adjustments/changes needed to be made? If not, I will work on getting this included on our website soon then.

Thanks!

**Comment by destroytheardor** [comment]
@Polymega Thank you! I think we're all set. I'll give you a link to Polish textures pack whenever folks at Graj po polsku upload it on their servers. :)

**Comment by Polymega** [comment]
Awesome!! I just made the announcement for it here: https://twitter.com/WhereAllBegins/status/1746241286460293154

Thank you all again so much!

**Comment by destroytheardor** [comment]
@Polymega Polish language pack with translated textures has been added to the download section of Graj po polsku. I'd be more than happy if you could add the link to the pack description on EE's page.

https://grajpopolsku.pl/download/silent-hill-2-ee/

The pack contains full list of files - *.tex, *.mes and etc. I made some alterations to text files to better fit them with translated textures, so users need to overwrite everything. 

Graj po polsku is there only trustworthy web portal offering fan translations in Poland. They have high and professional standards, and don't allow to publish language packs ripped from official releases. There's no scammy ads on the page, everything is free and made by fan translators. Servers are trustworthy and been there for long years.

**Comment by Polymega** [comment]
No problem--I've included this link on the Language Pack page: https://enhanced.townofsilenthill.com/SH2/languagepacks.htm

**Comment by justtoask** [comment]
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/72657053/24a7a96f-6f88-4490-863f-5ed99091513b)
Hey, I've noticed that the language called is called "polszczyzna", but it should just be "Polski". Could you change that?



> and don't allow to publish language packs ripped from official releases

you're telling that like it's a good thing, which it would usually be if it wasn't for the fact that most digital releases don't include the official Polish translations of the games lol.
