### ISSUE TITLE
Correct / most recommended version of the game to use. Also should both official patches from Konami be used or not after game install?

### ISSUE THREAD

**Issue by rfpm** [elishacloud/Silent-Hill-2-Enhancements#668]
Hey guys, I'm just posting this as an issue as I don't see any up to date information regarding the version of the game to install and I don't see any information at all regarding if the official two patches from Konami should be used or not before installing the Enhanced Edition?

Maybe I'm crazy but I have both the North American and European PC versions of Silent Hill 2 and have the option to install one or the other, even though you mention it can be used with both do you recommend one over the other? I have both and can't choose which to install. Your executable is based on the North American from what I gather online, right?

------------

The first official patch is "sh2patch.exe". From what I gather online this is meant for the North American version of the game and is meant to be patch v1.1 for fixing sound looping issues (unsuccessfully). Is it recommended to install this or not before installing the Enhanced Edition? If not then why so? I see in the past you had mentioned that "In the future, we plan to change this on our site to v1.1. Using Konami's official patch tool on an untouched v1.0, it will "officially" remove the DRM found within v1.0. (But doesn't fix the sound looping issues.)" Was this ever changed on your site since then?

The second patch is "sh2_gfx" and contains a new "device.fix" file meant to be dragged and dropped into the SH2 root folder. "This update is used to address missing text and/or missing videos on nVIDIA GeForce FX cards. Mobile chipsets are not included.". As above, is it recommended to install this or not before installing the Enhanced Edition? If not then why so? 

Thanks for all the hard work guys, massively appreciated and I love this project and team so much.

**Comment by AeroWidescreen** [comment]
The original North American version is what we primarily use for testing. That's your safest bet. No patch is needed. My understanding is that no version is specified because it ultimately shouldn't matter at all. Any differences should be overwritten by the Enhanced Edition.

> "This update is used to address missing text and/or missing videos on nVIDIA GeForce FX cards. Mobile chipsets are not included.". 

Again, all of this is included in the Enhanced Edition. NVIDIA graphics cards are fully supported. It really shouldn't matter.

**Comment by AeroWidescreen** [comment]
> I hadn't seen much talk of the official "sh2_gfx" patch so I wasn't sure either, I actually don't have a clue what it's attempting to fix or if it was even able to fix anything.

All I know is that despite this game having the NVIDIA logo on its splash screen, their cards have numerous visual glitches in this game that we had to solve with the Enhanced Edition. The irony is that AMD was "the way it's meant to be played" if you were playing the original PC port.

> Also thanks so much for the work you've contributed to the project and other projects around Github, etc. I've seen you around a lot and really appreciate everything you've done for all these older games.

I really appreciate that! I'm going to close this now since it sounds like your issue has been resolved.
