### ISSUE TITLE
Game crashes when entering the door before the "Maria laying on the prison bed" scene

### ISSUE THREAD

**Issue by Asteredia** [elishacloud/Silent-Hill-2-Enhancements#677]
I tried to re-start my pc and open the game several times but it keeps chrashing whenever i open the door before that scene. Please Help

**Comment by Polymega** [comment]
Please attach a copy of your `d3d8.log` file.

**Comment by Asteredia** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10049557/d3d8.log)

**Comment by Asteredia** [comment]
Please answer the problem, I still do not know the problem is and it keeps crashing again here's the _d3d8.log file_ 

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10096431/d3d8.log)

**Comment by Polymega** [comment]
_Temporarily_ remove the `d3d8.dll` file from the game's directory. This will essentially have you playing the vanilla version of SH2 PC. Launch the game and test the crash spot. Does it continue to crash?

**Comment by Asteredia** [comment]
The problem is solved right now, thank you

**Comment by Polymega** [comment]
What I was having you test by doing that is to see whether or not the crash is happening due to the base (vanilla) game, or something in our project files. If you temporarily removed the `d3d8.dll` file and it resolved the crash, that tells us it has something to do with our project files.

You'll want to keep using our project, as vanilla SH2 PC is quite unstable and its sound will eventually begin to stutter/stop playing and ultimately crash your game.

You can place the `d3d8.dll` file back into the game's directory. Next, _temporarily_ rename the `sh2e` folder found in this directory to anything else (such as `sh2e_temp`). Does the game still crash when you do this?
