### ISSUE TITLE
[Feature Support] Anisotropic filtering

### ISSUE THREAD

**Issue by NineKain** [elishacloud/Silent-Hill-2-Enhancements#695]
Makes textures look nicer for almost no performance loss

**Comment by elishacloud** [comment]
Yes, I added anisotropic filtering to Silent Hill 2 in a previous check-in.  It does make many textures look better.  However, there are a good number of the textures throughout the game that have transparent edges and this causes ugly lines to be seen in these textures.  We tried to find a way to filter out the textures with transparent borders, but that was deemed as not feasible.  So at this point there is no way for us to add anisotropic filtering without also adding ugly artifacts to the screen.

**Comment by TommvinHuwaltzky** [comment]
So I'm guessing forcing it driver-level has the same down-sides?

**Comment by Polymega** [comment]
At least for Nvidia, I don't believe forcing it at a driver-level works, strangely enough.

**Comment by elishacloud** [comment]
Yeah, same issue at the driver-level.

Also, the same issue happens with edge-anti-aliasing, but on Nvidia there is a transparent option that fixes the issue for anti-aliasing.  But it only works for Nvidia.  However, with anisotropic filtering there is no such option.  It's too bad because there is quite a bit of improvement with anisotropic filtering.

**Comment by Polymega** [comment]
Here's an example of what AF was doing:

![image](https://user-images.githubusercontent.com/27395260/213066696-b8abbcfa-1b67-405e-92d1-106beca80b0c.png)
![image](https://user-images.githubusercontent.com/27395260/213066713-53ec2580-0656-48af-9ca9-b4d69fbbe12d.png)
