### ISSUE TITLE
ADX Audio\AFS Audio Archive isn't being Redirected with the latest public build

### ISSUE THREAD

**Issue by MarioTainaka** [elishacloud/Silent-Hill-2-Enhancements#696]
Just made another topic to keep everything neat. With the latest build available on the website ADX and AFS Audio isn't being redirected but Sddata.bin is. Attached are Reloaded II file monitor logs which show what gets loaded or redirected in the first two areas of the game.
[Latest dll logs.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10442105/Latest.dll.logs.txt)
[Public Website dll logs.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10442106/Public.Website.dll.logs.txt)

**Comment by Polymega** [comment]
This issue was found out a little while back and has been fixed for the next update. It was an overlooked element when we revised how our project hooks itself in the game.

See here for more info: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/686#issuecomment-1372734156

I'll close this ticket. Thanks for checking it out though!
