### ISSUE TITLE
Latin language pack

### ISSUE THREAD

**Issue by alchemillahospital** [elishacloud/Silent-Hill-2-Enhancements#712]
I have been working on a Latin translation of SH2 for my YT channels and was wondering how, when that gets done, I might submit to here as well. 

https://www.youtube.com/channel/UC3KmJNh3VaEHHCUQFhxGgcQ
https://www.youtube.com/@AlchemillaHospital1
SilentHillCommunity.com

![la1](https://user-images.githubusercontent.com/49393896/219959532-7c0f1b0f-804b-40af-817d-fdeb612168dd.jpg)

**Comment by Polymega** [comment]
Hi Amy,

Cool project! Once you get everything translated, there will be a few additional steps needed to get the translation pack compliant with our project. The main things being:

------------------

A high definition main menu will need to be translated to Latin. I can do this for you. I would just need the following translated:

```
LOAD
CONTINUE
NEW GAME
OPTIONS
MOVIES
EXIT
ACTION LEVEL
RIDDLE LEVEL
HARD
NORMAL
EASY
BEGINNER
Main Scenario: LETTER FROM SILENT HEAVEN
Sub Scenario: BORN FROM A WISH
```

-------------------

You will need to translate a language _other than_ English. There are two main reasons for this:

1. English is used in various regions around the world (as a second language or otherwise).
2. The non-English language files in the game utilize _additional_ subtitles that are not used by the English language files.

If you have originally replaced the English files, you can change this by renaming all of your translated files from `*_e.mes` to either `*_f.mes`, `*_g.mes`, `*_i.mes`, or `*_s.mes`.

**Note:** If you change which language the Latin pack replaces, make sure you update the language string in `options_msg_*.mes` accordingly. For example, if you are now replacing the German language (`options_msg_g.mes`), you'd change "Latīnum" back to "English" and instead change "Deutsch" to "Latīnum", if that makes sense.

---------------------

You will also need to be considerate of certain character length limitations on certain text strings (if the character length is too long, it will corrupt parts of the text). Certain text strings were incorrectly colored in the game, which would need to be addressed. You will need to overhaul the colors the text strings use while in the Save Screen.

[All of this is detailed in this document.](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#) Please give it a read, as it goes over all required information. This document also provides general tips/advice for translating the game along with information on using [SH2MGSConvert](https://github.com/loadwordteam/SH2MSGConvert).

If you are still using that old SH Resource Editor to adjust text, I strongly, _strongly,_ _**strongly**_ recommend moving over to SH2MSGConvert. It makes everything so much better and it's less prone to bugs/in-game text display issues.

**Comment by NoUserNameForYou** [comment]
Studeo linguae Latinae et propositus tuas mihi placet!
