### ISSUE TITLE
ISSUE: SFX for the "basement dweller" of Brookhaven Hospital does not repeat

### ISSUE THREAD

**Issue by HyperCynical** [elishacloud/Silent-Hill-2-Enhancements#721]
Hey guys, first time poster, wanted to try and help if I can. Testing the newest update, I noticed there is an issue with the basement dweller monster that usually has a high pitched, screeching noise play every few seconds after you've descended towards the basement in the Nightmare. Unfortunately, it seems that the trigger only plays the sound once now and does not repeat. Not sure if it is due to the audio changes or a change in scripting though.

The sound will play again if you exit and re-enter, but it still only ever plays once.

**Comment by Polymega** [comment]
Hi there,
This audio looping infinitely was a bug in the PS2 version that Team Silent themselves fixed later on for the Xbox version. It is only supposed to play once, and it's scripted in a way where there's a chance it won't play when you enter this area. (The chance reset each time you reload the stairway area.)

**Comment by HyperCynical** [comment]
Oh wow! I was definitely not aware of this. It's quite interesting because I played through the game six times now and found it actually rarely would even play in the first place, or it would play but in a way that seemed somewhat inconsequential to what was intended. I'm not saying they didn't change this intentionally for the xbox version, but maybe that was an unintentional bug from changing something else? 

I obviously might be wrong, but considering both the original AND Director's Cut versions for PS2 do this, I can't imagine the Xbox version for some reason being the definitive version on this SFX issue. Sounds more like the Xbox version had an issue with the sound looping as well.

**Comment by HyperCynical** [comment]
This is coming from a guy who has played this game too many times to count and owns literally every single iteration of it from platform derivatives to region variations. So it's not like I'm coming from not having played these games before. I'm pretty sure even the HD collection had this sound effect repeating, whereas this version does not. 

Anything that could confirm the intention was a single play of the sound would be great, but I have no idea why you feel the xbox version "not repeating" would be the definitive version? You can't physically see the "creature" creating the sound. So of course, it would need to repeat to intrigue the person playing. Otherwise it's a random noise that may have or may have not meant anything at all. Clearly that's not the intention with the basement. It's supposed to imbue a sense of foreboding as well as a sense of wonderment for the potential creature on the other side of that cage.

This is just a fundamental misunderstanding of the intention of the sound effect I feel.

**Comment by Polymega** [comment]
> I obviously might be wrong, but considering both the original AND Director's Cut versions for PS2 do this, I can't imagine the Xbox version for some reason being the definitive version on this SFX issue.

I believe the reason this is still present in the PS2 DC version is simply because it was already there in the PS2 version. Digging in the files, there is evidence of Born From a Wish in the original PS2 build.

> Anything that could confirm the intention was a single play of the sound would be great, but I have no idea why you feel the xbox version "not repeating" would be the definitive version?

I don't have hard proof for this specifically, but the dev team fixed various issues present in the PS2 version when they ported the game over (but the Xbox version also made its own issues from the port). 

For example, James' eyes glow abnormally bright in the PS2 version due to a bad vertex shader. They fixed this on Xbox. 

When Angela opens the door at the end of her cutscene in the "flesh room," you can see the movable piston floating in thin air behind the door (depending on the timing of when this cutscene initiated). The dev team added a solid black box behind this door to hide the piston for the Xbox version.

They fixed various typos present in the PS2 version's text. A typo I remember off the top of my head is one of the books Maria reads in the mansion for her BFaW campaign.

The "pig squeal" sound in the Hospital's basement basement loops on repeat infinitely. There's no deviation to the sound's volume or timing in between plays. It _sounds_ like an error. I'm led to believe this was an intentional change as it is now random if a) it plays at all while in this staircase area, b) the timing of when it plays, and c) the volume of how loud it plays. It's now a random audio event like many other secret audio events in the game.

Anyway, those issues I mentioned above? They're not fixed in the PS2 DC version, either. Why is that? There is evidence of BFaW in the files of the original PS2 version. I'm led to believe BFaW was near-done but they didn't have time to ship it with the original PS2 release. Soon after, they got it done and ready for ~~a possible~~ the inevitable PS2 DC release and _then_ ported everything over to Xbox. During _this_ porting to Xbox is when they also went in and fixed things. So any original bugs are still present in PS2 DC for this reason.

> This is coming from a guy who has played this game too many times to count and owns literally every single iteration of it from platform derivatives to region variations. So it's not like I'm coming from not having played these games before.

Yeah, same here. About a year or two ago I finally found a new/sealed Korean version to finish my quest with this. Took me 8 years to find this copy new and arrange a shipping plan... 😩

**Comment by HyperCynical** [comment]
That's incredible!! I have still got that Korean version on my wishlist, was close to getting it on eBay once but man is it hard to find any copies being sold. Congrats!!

And this was really interesting to read, I actually remember now the "random" sound events seeming new as I was so used to the PS2 version. There are at least two or three specific sound effects that I didn't recognize and figured you guys must've fixed something there. It also makes more sense now as to why the basement squeal seems to sometimes exist and sometimes not. 

Thanks for the clarification! Looks like I'll have to play through the Xbox version again, it has been quite a few years. As a kid I definitely didn't notice so many subtle differences between the two consoles.
