### ISSUE TITLE
No search mode movement with RS

### ISSUE THREAD

**Issue by Berzel1us** [elishacloud/Silent-Hill-2-Enhancements#722]
Previously you were able to move the camera in the search mode with the right stick. It seems that it's not possible anymore. Also wanted to remap the dpad por changing weapons and it doesn't seem to work anymore.
![Screenshot 2023-02-24 183417](https://user-images.githubusercontent.com/59519669/221325470-2cca7d7c-782f-44d4-90df-ae7404f829c1.png)

**Comment by Polymega** [comment]
If you changed/upgraded from XInput Plus to Xidi with this new update, you'll need to change **Controller type for search cam movement** to "DirectInput". You can uncheck/disable the **Restore D-pad movement** to assign inputs to the D-pad in the game.

**Comment by Berzel1us** [comment]
This worked fine, thank you. Unfortunately I won't be able to move in the menu by disabling the option "restore d-pad".

**Comment by Polymega** [comment]
> Unfortunately I won't be able to move in the menu by disabling the option "restore d-pad".

Yes, that's correct. The D-pad will no longer be used for movement purposes (character or menu navigation).

> edit: I tried to disable "restore d-pad" and I wasn't able to map my controller keys in the for the d-pad.

Huh... So I just did several tests with both XInput and DirectInput controllers, with and without the use of Xidi, and with and without the use of our project and it looks like SH2 PC does not allow game functions to be assigned to the D-pad of controllers. I could've sworn this was possible but maybe I've been misremembering that this whole time? 

But good news! We can fix this with the use of Xidi. So, make sure you upgraded/installed to Xidi. Then, find `Xidi.ini` in the game's directory and open it with a text editor. Replace the **entire** contents of this file with the following code:

```ini
[Mapper]
Type			= ModifiedStandardGamepad

[CustomMapper:ModifiedStandardGamepad]

; Imports all of the element mappers from StandardGamepad.
; This line is allowed to appear anywhere in the section, including between or after the element mappers below.
Template		= StandardGamepad

; These changes are applied on top of the template.
ButtonA			= Button(2)
ButtonB			= Button(3)
ButtonX			= Button(1)
DpadUp			= Button(13)
DpadDown		= Button(14)
DpadLeft		= Button(15)
DpadRight		= Button(16)
```

A few notes: 
- **Restore D-pad movement** will still need to be disabled. 
- Xidi will, of course, need to be installed in order to use this.
- This will only work with XInput controllers, _not_ DirectInput controllers.

We will probably be pushing out an update to Xidi in the near future, and I will include the INI changes shared above as part of that package update.

**Comment by Berzel1us** [comment]
This definitely worked. And thank you for opening that issue. It'd be a great improvement. Great work with the project. (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧
