### ISSUE TITLE
the game crashes

### ISSUE THREAD

**Issue by SONIC0798** [elishacloud/Silent-Hill-2-Enhancements#747]
Hello, I have a problem when pressing the ESC key, the game crashes. How to solve this problem.

**Comment by Blunderless** [comment]
i don't have an answer for this, but i want it to be known that for the record, i can't pause without it crashing either, and it was working fine before that update.

i'm 100% certain they and i are not the only people with problems regarding this update.

**Comment by SONIC0798** [comment]
Yes , I still have a game stalled with a riddle with a clock I can 't get out

**Comment by SONIC0798** [comment]
another bug.
if you press ESC, the game crashes and the sound remains in the headphones. Only restarting the device helps.

**Comment by Polymega** [comment]
We will need you to perform tests to help us understand what is causing this issue.

Please attach your `d3d8.log` file. Open the Config Tool (`SH2EEconfig.exe`) and start disabling features, launching the game in between disabling things, to see if a certain feature is causing the issues for you.

I'd recommend disabling _everything_ on one of the tabs (pages) in the Config Tool, then launching the game. If the issue becomes resolved, then re-enable everything on that page and start disabling features one-by-one until you hone in on what specific thing is causing the problem.

**Comment by elishacloud** [comment]
@SONIC0798, we are not experiencing the same issue as you are so we need your help to fix the issues.  As @Polymega mentioned, attaching your log file will help us troubleshoot the issue.  Also, if the issue is caused by a specific feature then knowing which feature caused the issue will help us isolate the issue and fix the issue.

Can you try disabling some of the newer features to see if the issue is in one of these features?  If you figure out which feature has the issue please let us know so we can fix it.

Here are some suggestions for features to try turning off:
* **Display Tab:** Set Framerate to `30 FPS`
* **Input Tab:** Disable the following settings:
* * `Assign multiple functions to the same input`
* * `Enhance mouse input`
* * `Enable mouse weapon swap`

**Comment by SONIC0798** [comment]
Hi, sorry for the late response.
I tried to disable all the functions, but the game still crashes when you press ESC and it also crashes when you enter the inventory in the notes menu.

Here is the file:
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10948144/d3d8.log)

**Comment by elishacloud** [comment]
We just fixed an issue that I think is the same as this.  Can you try with this build here:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10945113/d3d8.zip)

**Comment by SONIC0798** [comment]
yes, thanks, everything is working fine now.
