### ISSUE TITLE
[Request] Auto-hide mouse cursor

### ISSUE THREAD

**Issue by 60d74** [elishacloud/Silent-Hill-2-Enhancements#750]
Add hiding the mouse cursor in menus when using the controller

**Comment by nasovic** [comment]
Second this. Would be nice if possible.

**Comment by mercury501** [comment]
Thank you for your interest!
So your issue got me thinking, and together with the help of a few other team members, particularly @Polymega and @Murugo, we managed to implement an auto-hide cursor feature. But actually, we made more than that!

Quick changelog:
- the cursor now auto hides after approximately 3 seconds
- the cursor is now available in the pause menu, and memo list, with a behaviour similar to the vanilla save game screen

Here's a dev build if you're curious, just drag and drop these 2 files in your sh2 folder, make a backup of d3d8.ini since your EE settings are stored there:
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11298948/d3d8.zip)

We're still not done, so no ETA yet but shouldn't be too long.

Cheers!

**Comment by mikeoxmaull** [comment]
> Thank you for your interest!
> 
> So your issue got me thinking, and together with the help of a few other team members, particularly @Polymega and @Murugo, we managed to implement an auto-hide cursor feature. But actually, we made more than that!
> 
> 
> 
> Quick changelog:
> 
> - the cursor now auto hides after approximately 3 seconds
> 
> - the cursor is now available in the pause menu, and memo list, with a behaviour similar to the vanilla save game screen
> 
> 
> 
> Here's a dev build if you're curious, just drag and drop these 2 files in your sh2 folder, make a backup of d3d8.ini since your EE settings are stored there:
> 
> [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11298948/d3d8.zip)
> 
> 
> 
> We're still not done, so no ETA yet but shouldn't be too long.
> 
> 
> 
> Cheers!

tysm, this works great, now the cursor is out of the way, appearing in the middle of the screen
