### ISSUE TITLE
Shadows clipping before going behind an object. 

### ISSUE THREAD

**Issue by zmarotrix** [elishacloud/Silent-Hill-2-Enhancements#771]
Maybe I didn't do a great job with the description of the issue, but I took a video to show it off. I'll update here if I see it anywhere else. 

https://www.youtube.com/watch?v=mGBAaj2LTKo

**Comment by Polymega** [comment]
This is "correct" behavior, for all intents and purposes. If the Xbox/PS2 versions rendered at a higher fidelity you'd also be able to easily see this behavior there, too. 

You won't see it on PCSX2 when playing SH2 in high resolutions because, with PCSX2, the higher the rendering resolution the sharper the soft shadows become (at 4K the shadows are practically razor sharp). 

With our project, we retain the same softness for the shadows, regardless of resolution. By doing this, you see those "haloed" edges for shadows. If I have time I can maybe illustrate why it does this. Playing at unusual resolutions/aspect ratios can make the effect more pronounced, though.

**Comment by elishacloud** [comment]
@zmarotrix, if you don't like soft shadows you can disable it.  Then you won't see that issue.

**Comment by Polymega** [comment]
Here it is on PS2 for a frame of reference:

![image](https://user-images.githubusercontent.com/27395260/230816863-27a9609b-74d5-4332-ac36-d99bad5c0dd0.png)

**Comment by TommvinHuwaltzky** [comment]
Weird, that looks like SSAO-artefacting...

Btw, it will prolly _never_ be possible to have the actual models casting shadows, like they did with the HD-collection (at least for SH3 if I remember correctly), right? Since as it works now, it's an invisible, simplified model the shadow is projected from, like they often did with PS2-games. SotC did it too.
