### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by Edziomama** [elishacloud/Silent-Hill-2-Enhancements#772]
Hi! When I tried to install sh2ee my antivirus blocked the installation telling me a Trojan had been detected. Can someone explain to me what's going on?

**Comment by Polymega** [comment]
Hi there,

The Setup Tool (`SH2EEsetup.exe`) might be erroneously flagged as malware by your antivirus (AV) software (also known as a "false positive"). Create an exception through your AV software to download and run the Setup Tool. For your safety, the Setup Tool should only ever be downloaded by you from this website. Do not download the Setup Tool from another source—this is a safe practice for using the Internet in general.

We submit each update of the Setup Tool to Windows Defender and Avast antivirus software for analysis and clearance. However, there are many AV software on the market which might still flag the tool as a false positive, since the tool is not submitted to all AV vendors. For added peace of mind, you can submit the Setup Tool to the AV vendor you use to have them analyze and clear the tool. (Most AV vendors have an option to submit files for analysis on their website.)

Here is the source code for our tool: https://github.com/nipkownix/SH2EE-web-installer
