### ISSUE TITLE
it says that there isnt any game

### ISSUE THREAD

**Issue by ivandragoy** [elishacloud/Silent-Hill-2-Enhancements#783]
i installed silent hill 2 directors cut on internet archive and i used pcsx2 for playing and it works well. i wanted tu updete the game to the enhanced version but when i select the folder where i entered the game it says that there isnt.
sorry for the english i dont spoke it very well, thanks

**Comment by Polymega** [comment]
Hello,

> i installed silent hill 2 directors cut on internet archive and i used pcsx2 for playing and it works well.

Our project is for the _PC version_ of Silent Hill 2. What you are using is the _PS2 version_ of Silent Hill 2 being emulated on your computer through PCSX2.

You will need to download the PC version of Silent Hill 2 in order to use our project. You can find a copy of the PC version here: https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download

Download the "fully extracted" version.
