### ISSUE TITLE
error 0xc00007b

### ISSUE THREAD

**Issue by nizar787** [elishacloud/Silent-Hill-2-Enhancements#792]

**Comment by elishacloud** [comment]
That error means that some required component is missing.  Usually that is a Microsoft Runtime.

Here are a few possible fixes and work arounds:

1. Install the Microsoft VC runtime x86 from [here](https://www.microsoft.com/en-us/download/details.aspx?id=52685).  Make sure you use the x86 and not the x64, since this is a 32bit game.
2. Try renaming or removing dsound.dll and dinput.dll.
