### ISSUE TITLE
Sound Skipping

### ISSUE THREAD

**Issue by Jaycaspian** [elishacloud/Silent-Hill-2-Enhancements#803]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11837861/d3d8.log)
I have an issue where the sound intermittently cuts out/skips. It seems to happen predominately in cutscenes, but it can happen in normal gameplay as well. Sometimes it's only for a half second to a second, at other times (usually during cutscenes) it will last upwards of 2-3 seconds.

I've tried restarting the system, as well as toggling pretty much every sound option in the launcher and none of them help. I also tried running on DirectX 8, but still no dice.

Let me know if I can provide any further information.

Any help would be appreciated.

**Comment by Polymega** [comment]
Hello,

Can you please attach a copy of your `d3d8.log` file?

**Comment by Jaycaspian** [comment]
> Hello,
> 
> Can you please attach a copy of your `d3d8.log` file?

Thanks for your response!

I've attached it to the original post.

**Comment by Polymega** [comment]
Thanks. Quickly looking over your log file, everything seems to be fine. _Typically_, whenever the sound skips it's due to other processes running on your PC that might be fighting for bandwidth on a processor thread at that moment. Do you have any heavy programs up and running while you play? Maybe OBS running or a ton of tabs opens in your web browser? This is often a hard issue to troubleshoot as it's usually caused by specific reasons unique for that PC.

**Comment by Jaycaspian** [comment]
Yeah, I understand it can be difficult.

After restarting the system I was running without anything open. I could try trimming processes further to a bare minimum, if you think that could help.

**Comment by elishacloud** [comment]
Usually skipping comes from not enough power (CPU or GPU).  I recommend setting levels lower until you find the issue.  Example: lower the FPS to 30, reduce the video resolution disable, disable shaders, etc.

**Comment by Jaycaspian** [comment]
It turns out this may be a cabling issue. I tried to play on the same system using a different display and I couldn't reproduce the problem. I'll close this for now.

Greatly appreciate the assistance.
