### ISSUE TITLE
Cant open sh2pc.exe

### ISSUE THREAD

**Issue by hoikl** [elishacloud/Silent-Hill-2-Enhancements#807]
After installing the enhanced edition, it launches and runs fine if I select to run after closing installer. The problem is when I close the game I'm unable to run the game again through the exe file as it's trying to open with the notes app.
![Screenshot (1)](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/138256794/da9e2500-e7b6-4b84-98ce-54fb8b580614)

**Comment by Polymega** [comment]
This is because you have hidden known file extensions. So the `sh2pc.exe` you're seeing is most likely `sh2pc.exe.bak.exe`, which wouldn't be right. The `sh2pc` you see in there is actually `sh2pc.exe`.

First, show known file extensions on your machine. Follow these steps: https://www.wikihow.tech/Show-File-Extensions-on-Windows

Then, re-check that one file. It should just be `sh2pc.exe.bak`. This is a backup of the game's original executable (EXE). You'll want to run the game using the `sh2pc.exe` you see in there once you show known file extensions.
