### ISSUE TITLE
Silent Hill 2 Black Screen upon startup

### ISSUE THREAD

**Issue by LordEmrys** [elishacloud/Silent-Hill-2-Enhancements#814]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12030213/d3d8.log)

Hi! When I start my sh2pc.exe, be it administrator or not, I simply get a black screen on start up and nothing else. I have attached the d3d8.log file but I don't think it shows me where exactly the problem lies. I don't get any error messages or codes. Let me know if you need anything more than that

**Comment by Polymega** [comment]
Hi there,

I'm not sure what the cause is, but I see you're using a very old, outdated version of the project. I recommend downloading our project's [Setup Tool](https://enhanced.townofsilenthill.com/SH2/install.htm#usingEE) and reinstalling, if desired.

Doing this will update all files for all enhancement packages that make up our project.

-------------

You can also directly download an update _for just_ the SH2 Enhancements module here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases

Just note you would _not_ be downloading updates for all the other enhancement packages.

**Comment by LordEmrys** [comment]
> Hi there,

Hey it works! Thanks a lot!
