### ISSUE TITLE
I'm having trouble setting up a controller

### ISSUE THREAD

**Issue by matheusvb3** [elishacloud/Silent-Hill-2-Enhancements#824]
I went to play the game with my friend and we had trouble mapping the run command in our controller. In the controller settings screen, we put the cursor in the action we wanted to map (run/guard), then we had to press Enter on the keyboard but as soon as we let go of Enter it would automatically map that action to "button 7" in the controller. We tried pressing all buttons but none worked.

[2023-07-27-21-10-45.webm](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/94158d56-3852-4eeb-9f0e-e758fc60570d)

I'm confused as to what we're doing wrong.

Edit: oh yeah I'm using Linux too...

**Comment by Polymega** [comment]
I'm unsure if Xidi works and behaves with Linux...

You can try XInput Plus to see if that yields any better results with Linux:
https://files.townofsilenthill.com/SH2EE/legacy/SH2EE_XInputPlus_4.15.2.zip

**Comment by matheusvb3** [comment]
I'll try and I'll let you know if I can make it work.  Thanks.

**Comment by matheusvb3** [comment]
Sorry for the silence. It's not a problem with the game or Xidi, it's actually a problem with Wine. It happens with other games too (but not native Linux applications). 😟 I've reached out for help on their forum but I haven't received a response yet.

Also, if it wouldn't be too much trouble, I was a little curious if it'd be possible to give the controller settings screen more descriptive names like "right trigger/left shoulder button/cross/triangle/Start/Select" instead of "button 1, 2, 3..." I figure since the heavy work has already been laid out for the save screen filesize fix it wouldn't be too complicated.

I'll close this issue since it's not related to the project.

**Comment by Polymega** [comment]
> Also, if it wouldn't be too much trouble, I was a little curious if it'd be possible to give the controller settings screen more descriptive names like "right trigger/left shoulder button/cross/triangle/Start/Select" instead of "button 1, 2, 3..." I figure since the heavy work has already been laid out for the save screen filesize fix it wouldn't be too complicated.

I've given this a lot of thought in the past and believe it might be deceptively complicated. Here were my various thoughts on the matter:

- We'd have to monitor/detect what controller is plugged in prior to launching the game and run it through a list of vendors to know if it's Xbox, PlayStation, or something else.
   - Is there a repo of known controller types for us to use?
      - If not, how do we feasibly collect this data?
   - What about future controllers that may release? 
      - How long should/would we update the controller list for?
   - What about generic controllers that are detected as generic but use Xbox-style button names? How could we know/handle that?
- Xidi works by spoofing the game into always think there's a controller connected to the game. If Xidi "wraps" itself around the actual controller, how does this work for detecting the correct controller type to display the correct button prompts?
   - Xidi also allows you to swap out an Xinput controller with a totally different one. How do we handle that if the swapped controller uses different button names?
- The game's font sheet doesn't include all button symbols for controllers like Xbox and PlayStation. How do we add/include the button symbols then? Is that even possible?
   - If, instead of symbols, do we type out the button names? So instead of "△" it would show "Triangle". 
      - We'd then have to worry about translation efforts, including those for Fan Translation Packs.

I personally think it's too much of a headache/too messy to tackle. _However..._ I did think of a compromise, of sorts, to this issue:

Within the Configuration Tool we have a new option under the **Input** category called something like, "Button prompts." This would be a dropdown list with the following options:

- Generic (aka default)
- Xbox
- PlayStation
- Nintendo

You select which controller type you'll be using from this list and the text strings can update accordingly. Here would be the cons for such an approach:

- Limited selection of controller types to choose from
- You must re-open the Config Tool and change this selection if changing controllers prior to launching the game
- Still cannot use symbols, so things like "△" it would have to be typed out as "Triangle"
- Likely no translation support, so for all languages it would say "Triangle," for example
- Cannot update button prompt names if controller is switched out mid-game

And of course, the pros:

- Much more feasible to possibly do

**Comment by matheusvb3** [comment]
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/5ef63ca7-334c-400a-ade5-445fbec5f6d2)
> Within the Configuration Tool we have a new option under the Input category called something like, "Button prompts." 

I think that would be ideal! I imagine very, very few people (I would risk saying no one, even) would be bothered that their controller is an Xbox model (ABXY) but the game is using PlayStation terminology (triangle, square etc) or vice-versa. It's important to keep in mind that only the face buttons have inconsistent naming across brands, so everything else (d-pad, Start, Select, triggers, bumpers/shoulder buttons and sticks) using human-readable terminology would be of _great_ benefit to people configuring their controllers.

In any case, if you decide against having a selector for prompt naming in the config tool (to decrease complexity perhaps), you can just use the official terminology and call them "face button up, face button left" etc.

> Likely no translation support, so for all languages it would say "Triangle," for example

I see, maybe that wouldn't be too inconvenient because when you're mapping your controller you're actually pressing the button you want to assign to that respective action, so even if I didn't speak an ounce of English and went to map "flashlight" to the right trigger, for example, I would know what button I should press to do that in gameplay since, evidently, I just assigned that button myself.

Also I don't think not being able to use symbols for the face buttons is an important issue since the rest of the buttons would still have their English names. Moreover, the controller config screen has a very strict 4:3 aspect ratio that leaves very little room for the button names, so shortened terminology like LT/RT/LB/RB/D-pad up etc would have to do. I'm not sure if it'd even be worth translating the initials of each button for each language if there was a way to translate these strings (I myself have never seen a game use translated initials of buttons for my native language).
