### ISSUE TITLE
60fps mode not working correctly.

### ISSUE THREAD

**Issue by Beep402** [elishacloud/Silent-Hill-2-Enhancements#840]
Hello I'm trying to run the game at 60fps but the mode is acting weird for me.

Once the game loads it runs at 60 in the bathroom area. Once I leave that area however, the game drops to 30fps and remains locked there except for static shots like grabbing the map out of the car. There was also a brief spike where it went back up to 60 while running down the hill to the cemetery but then it went right back to 30fps. The inventory Menu also runs at 30fps. 

PC Build:
AMD Ryzen 5 3600X 6-Core Processor
Ryzen 5700XT
16GB of RAM
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12588645/d3d8.log)

**Comment by AeroWidescreen** [comment]
This sounds like an issue with v-sync reducing the game to 30fps when 60fps can't be achieved, but your system should be more than adequate, so I'm not exactly sure what the problem is. Unless someone has a better idea, you could reducing your resolution for 2560x1440 to 1280x720 to see if that makes any difference. Also, make sure you don't have any kind of v-sync forced through your AMD drivers.

**Comment by Polymega** [comment]
This DLL is hooking into the game:

```
C:\Program Files (x86)\Steam\gameoverlayrenderer.dll
```

If Aero_'s suggestion doesn't help, try seeing if the Steam overlay is causing any issues.

**Comment by Beep402** [comment]
Hello I know its been a while since I posted this but I wanted to update this issue.

Turning off steamoverlay did not fix the issue. I also have no extra settings configured in my AMD driver software.

I created a video to show the issue in action and have linked it below:
https://www.youtube.com/watch?v=kgR5sxSscpw

Thank you for taking the time to look into this.
