### ISSUE TITLE
Possbile camera Off-set verticality issue or not really?

### ISSUE THREAD

**Issue by Pocokk** [elishacloud/Silent-Hill-2-Enhancements#848]
Hey there!

I've stumped upon a video that collects the various game versions that is available for the whole Silent Hill franchise and when I reached the PS2 version of Silent Hill 2, I noticed a segment that I'm not sure is present here, but might be the case:

[At 24:30](https://www.youtube.com/watch?t=1470&v=II_AU_uptDE&feature=youtu.be), the person in the video mentions about off-set problems on the vertical axis. I don't remember this being noticeable or even an outright issue for the PC port, perhaps you guys already fixed/adjusted it in early updates, can't tell. Please have a look! (also the later part of that video is interesting as well)

Thank you.

**Comment by MarioTainaka** [comment]
> Hey there!
> 
> I've stumped upon a video that collects the various game versions that is available for the whole Silent Hill franchise and when I reached the PS2 version of Silent Hill 2, I noticed a segment that I'm not sure is present here, but might be the case:
> 
> [At 24:30](https://www.youtube.com/watch?t=1470&v=II_AU_uptDE&feature=youtu.be), the person in the video mentions about off-set problems on the vertical axis. I don't remember this being noticeable or even an outright issue for the PC port, perhaps you guys already fixed/adjusted it in early updates, can't tell. Please have a look! (also the later part of that video is interesting as well)
> 
> Thank you.

on the PC version you won't ever have this issue because  of signals being digital nowadays. On PS2 this issue.. well it isn't exactly an issue. But it happens because CRT's handled overscan  insanely well and consoles took at advantage of this to basically run at a lower resolution to increase performance. The edges of the screen would most of the time be hidden by the big bezels CRT's had back then
