### ISSUE TITLE
Possible fix for the freezes and crashes.

### ISSUE THREAD

**Issue by Storm3000** [elishacloud/Silent-Hill-2-Enhancements#85]
Hi!

Some people are having problems to play the game correctly. In some systems, when entering the game it only appears a black screen instead the intro logo, in other cases the game freezes randomly. This issues seems to be related to the code on the multilanguage sh2pc.exe file, and in some way to the single core affinity option, the admin rights and the Windows version (being more frequently these issues on Windows 7).

By the moment, the only way to avoid these issues is using the english sh2pc.exe file. This way you can enable the single core affinity option on the d3d8.ini file and the game will work fine. However, the english .exe version has some minor missing texts (not a big deal, really) if you play the game in other language than english.

**Comment by Polymega** [comment]
We're not sure what was changed/modified in the binary for the "no CD" multilanguage .exe, as we weren't the ones who created this modified executable. There may be a chance that whoever created this custom .exe also applied additional edits we aren't aware of which are causing freezes/crashes. 

Do you own the physical copy/discs for the European version of the game? If you do, I would try using the original (CD check) executable of the Director's Cut version by placing the disc in your computer and seeing if the untouched European .exe also experiences freezes and crashes.

**Comment by Storm3000** [comment]
No, I don't have the physical discs. I just have an old copy of the European version, but it won't work with the original .exe. :(

Anyway, I'll use the english .exe. It's working fine and just have some missing texts in other languages on the Main Menu and Pause Menu only.

**Comment by Storm3000** [comment]
@Polymega I'm not sure where to ask this, but I'm a little confused about the d3d8 file. I downloaded the latest version on the Silent Hill 2 Enhanced Edition website (the elishacloud's file), but the first time I play the game, a window ask me if I want to update the d3d8.ini file. I don't know why. It is the same file than d3d8 from AeroWidescreen website? Am I doing something wrong?

**Comment by Polymega** [comment]
You may periodically receive an **Updates available dialog box** upon game launch. If you see this box that means there is an important update for SH2 Enhancements. Choose how the updater will handle your d3d8.ini file then click **Download and install updates now**. If you have modified any settings in the d3d8.ini file you may want to choose **Don't replace INI files** during the update to avoid having your customizations reset. **But note that an update may add new modifiable settings within the INI file you would not receive if you choose to not replace the INI files.**

**If you installed Silent Hill 2 to an admin-protected directory** such as `\Program Files\` you will need to run the game as Administrator during the mod's update process in order for SH2 Enhancements to succesfully update and replace its files. Otherwise, the mod will say it successfully updated files but actually hasn't. If you installed Silent Hill 2 to a local user directory, such as `\My Documents\`, SH2 Enhancements will update and replace its files without issue. You can always go to (SH2 Enhancements' website)[https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases] and manually download the latest version of the mod and replace your files that way.

**Comment by Polymega** [comment]
You can run the mod updater when launching the game and that should get you squared away, just in case the latest version wasn't manually downloaded.

> It is the same file than d3d8 from AeroWidescreen website?

No, they are different. You will only use Elisha's download package (that contains its own d3d8.dll file).

**Comment by Storm3000** [comment]
Thank you. :)

I think it's fine then. I was in doubt because it seems the window showed the AeroWidescreen web site, and I wasn't sure from where came the .ini file.

**Comment by Polymega** [comment]
> I was in doubt because it seems the window showed the AeroWidescreen web site

Oooh. The reason for that is the mod updater module (the notification that tells you when an update is available) is made by ThirteenAG. So a link to his site is included in the module even when other projects use it (to give him credit).

**Comment by Polymega** [comment]
@Storm3000 

[The newest release of the project](https://www.youtube.com/watch?v=377H3K9jAGA) allows you to change the language in the North American executable. After downloading all necessary update files, try using the North American .exe (and change it to your desired language) and see if you still have running issues with this .exe.

**Comment by Polymega** [comment]
@Storm3000 
Elisha has made some behind-the-scenes improvements with how the project handles custom files. [Would you mind downloading the latest build of the project](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3133197/d3d8.zip) and playing the game with the European (Director's Cut) executable to see if the crashes still persist?

**Comment by elishacloud** [comment]
Closing as this is specific to the DC version of the game and we are moving to the NA version.
