### ISSUE TITLE
I can't find SH2 Camera Editor

### ISSUE THREAD

**Issue by setsukanaomi** [elishacloud/Silent-Hill-2-Enhancements#851]
Hi, how you doing? The Camera Editor no longer exists? The link http://etc.townofsilenthill.com/sh2pc_camera_editor/ doesn't exists anymore ;-;

**Comment by Polymega** [comment]
I removed the page/download because it requires a user to have Cheat Engine on their PC. There should be some level of familiarity with Cheat Engine before downloading it, and I didn't feel comfortable keeping the tool up due to that requirement of the end user.

If you do use Cheat Engine, you can grab the Cheat Table for this tool here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/351#issuecomment-728266241

**Comment by setsukanaomi** [comment]
Thank you so much, sorry for the old related issue! Hope u keep up with the good work. <3
