### ISSUE TITLE
Reshade 5.9.2 crashes the game (at least for me) when any effects are activated

### ISSUE THREAD

**Issue by kaaona** [elishacloud/Silent-Hill-2-Enhancements#852]
You know, by ticking the box near it. Instant ctd. I tried it with enabling dx9 in the config files, and the reshade install was dx9 too. I also wanted to disable that and use crosire's wrapper but the game already has a d3d8.dll.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12779238/d3d8.log)

**Comment by elishacloud** [comment]
This project already includes crosire's wrapper.  To use ReShade you need to disable all shaders in this project first.  Then copy the d3d9.dll file from ReShade into Silent Hill 2 folder.  Make sure you are not using the dxgi.dll file.  I have not tested with the latest ReShade, there could be bugs in the latest ReShade, but we used to work with the older ones.

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/25625456/9c8953e3-1e4c-4d3d-8f8f-523838063344)

**Comment by kaaona** [comment]
Ohhhh so, the brightness selector is facilitated by a shader?

By the way two more things, in dx8 SGSSAA is possible, which is amazing. Do you know any AA compatibility bits for dx9 that enables that kind of super sampling?

And I tried downsampling through gedosato in dx9 in lue of SGSSAA (it starts by only showing a quarter of the game on the screen, but an alt tab fixes that) but it causes a crash whenever you hit escape to open the menu, (I guess you didn't think anybody would try 10k resolution when you made the menu? Or is it some other thing causing that?) I didn't get any crashes other than by hitting esc though.

**Comment by kaaona** [comment]
Should I close this issue and open a new one for downsampling crashes? I'm new to github. Also I guess the AA bits question doesn't belong in issues?

**Comment by elishacloud** [comment]
> the brightness selector is facilitated by a shader?

Silent Hill 2 uses gamma controls for the brightness selector.  However, in Direct3D9 gamma controls only work in fullscreen exclusive mode.  So instead we converted them to shaders so that they work in windowed mode.

> By the way two more things, in dx8 SGSSAA is possible, which is amazing. Do you know any AA compatibility bits for dx9 that enables that kind of super sampling?

I wanted to create an SSAA feature for Silent Hill 2.  That is one of the better ways to do AA.  However, it is also the most GPU intensive way.  Edge AA (MSAA) is much easier for the GPU.  I am not sure how you enabled SGSSAA or how to do the equivalent in dx9.

> Should I close this issue and open a new one for downsampling crashes? I'm new to github. Also I guess the AA bits question doesn't belong in issues?

The crash is probably related to the fact that we take a snapshot of the game window when you press ESC to enter the menu.  In this case I suspect that one of the textures is not large enough to store the snapshot data, or something like that.  You can open a new issue on that and close this issue.
