### ISSUE TITLE
Alignment Issue with Config Tool

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#861]
From the latest Actions build (https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/128bd37be7418d0228353684401fb2883ae15c3e), there's an alignment issue with the Config Tool that I don't believe was there before.

Notice the missing border line (see red arrow) and overlapping text in some of the other screen grabs.

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/29b39fb4-d837-4ff1-b1ec-0760669d2230)
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/a4ac28aa-2ae4-4884-90b8-a93850570848)
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/3cbef4f6-4cb7-4367-ae50-86deeb3b5a27)

**Comment by elishacloud** [comment]
This is just an issue with the Workflow version.  You can see from this screenshot that the normal release version is working fine in the latest check-in.  This is just an issue with the Workflow, and has nothing to do with any check-in.

This seems related to compiling this for Windows 10 vs. Windows XP.  The Workflow can only compile this for Windows 10 not XP.

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/25625456/111379a2-b200-49ac-9c3c-1ce0d0fdf508)

I will try and fix this so that the Workflow tool can be more useful.

**Comment by elishacloud** [comment]
Fixed.  I found a couple other issues with the Launcher size that is exposed by this issue.  If you use this fixed version and then go back and use another Launcher you may see issues with the old Launcher.
