### ISSUE TITLE
reduce gunshot and enemy scream volume levels?

### ISSUE THREAD

**Issue by bmw216** [elishacloud/Silent-Hill-2-Enhancements#868]
is it possible to reduce gunshot and enemy scream volume levels?

**Comment by matheusvb3** [comment]
When the game was ported to PC, the way the shotgun hit sounds work was changed, perhaps unintentionally. In SH2/SH3, each pellet of the shotgun bullet gets ray-traced. This is easier to see in SH3, where each pellet creates sparks when it hits a wall. In the PS2 version of SH2 (as well as all versions of SH3), the volume level stays the same regardless of the amount of pellets that hit the enemy. In the PC version, however, the volume of the enemies change depending on how many pellets hit them. This can be seen by making it so that only one pellet hits the enemy, where they sound much quieter. Personally this "quirk" never bothered me because I _love_ games where shotguns sound punchy and heavy, but this could very well be a porting glitch and it does indeed get _extremely_ loud depending on your PC volume level.

This is what killing the ritual monster with a rifle sounds like:

https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/f3a9131d-7f20-492d-9afb-1eef8799a50a



This is what killing him with the shotgun sounds like (listen to both videos with max volume to better hear the difference):

https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/98937378/a337b0bb-a769-4a28-a8ef-1a3bf3d2888d


Notice how the audio mixer slider always goes to the yellow zone.

@Polymega, can you test this in the PS2 and Xbox versions? I don't have a save in the prison to try this.

**Comment by bmw216** [comment]
wtf, i didnt know u could shoot the ritual monster.

the sound levels on pc is horrendous. its too loud.

**Comment by matheusvb3** [comment]
> the gun and monster screams are too loud.

Do you mean all guns or just the shotgun? The pistol and rifle have the correct volume level on PC I'm pretty sure, it's the same as on the PS2, it's only the shotgun that is incredibly loud

**Comment by bmw216** [comment]
@matheusvb3 all guns

**Comment by Polymega** [comment]
We provide tools to modify any of the game's sound files here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/tree/master/AudioScripts

Closing ticket. Feel free to re-open if you'd like further assistance.
