### ISSUE TITLE
Pyramid Heads can slide across the ground when attacking

### ISSUE THREAD

**Issue by matheusvb3** [elishacloud/Silent-Hill-2-Enhancements#872]
During the boss fight with the two Pyramid Heads, they can slide across the ground while attacking, either with the spear thrust attack or the one where they swing it sideways multiple times. This is specially noticeable in hard action because of their much higher movement speed, but it happens in other difficulties as well (I've only tested normal, but I imagine it happens in easy and beginner). It also happens in the PS2 version. It does _not_ happen in any of the three other times he appears holding the spear in the game (hospital chase and two rooms in the labyrinth, tested on PC).

This can also happen with their flinching animation, which from what I can tell happens randomly but has a much higher chance of happening when their health is almost down to zero. 

You can see a video of me fighting them on hard [here](https://files.catbox.moe/hqq06p.mp4). I only put clips where you can clearly see his feet sliding across the ground. It does _not_ happen every time he attacks, sometimes he correctly stands still while performing those animations (only rotating to try to hit you with the spear if you're running away).

I'm not 100% sure if this was really an oversight, perhaps the problem could be the animations being bad because they didn't have enough time and they wanted to make the PH boss harder in which case the correct solution would be to make better animations for them (I think it's very likely this is an oversight though). Well, SH2 is already a very easy game, even on hard action, so I'm not sure fixing this would really make that much of a difference...

Also, in the video you can see there are seams in the rug on the floor there, this is caused by turning off the high resolution textures option in the menu. It happens in every room in the game, no matter how insignificant, from beginning to end. It's specially noticeable in the labyrinth and Lakeview hotel where it looks _really_ bad. I had never seen it before because I never turn off that option but by chance I did because I was recording this playthrough with OBS. Is this a known issue with the PC port or is this just on my end? Turning that option off also caused some other issues with lighting but they are much less frequent than the white seams that appear everywhere.

**Comment by Polymega** [comment]
For that sliding movement, I'm unsure if that's happening code-side through the main binary or is a quirk with their animation files. And unfortunately, the `.anm` (animation) files are still an overall mystery format. I believe some research has been done on the format, but it's no where near far along to create any sort of editor for the animation files. Sad to say, it will probably just have to stay that way.

> Also, in the video you can see there are seams in the rug on the floor there, this is caused by turning off the high resolution textures option in the menu. It happens in every room in the game, no matter how insignificant, from beginning to end. [...] Is this a known issue with the PC port or is this just on my end?

It's not "technically" an issue per se... there's some code in the game that reduces any texture format by a certain percent for the low res graphics mode. This was surely done to help terrible, awful GPUs of the late 90's/early 2000's. When these textures get reduced by such an amount, it obviously looses a lot of detail and the image will become "blurry" when it becomes enlarged to fill the mesh surfaces. 

The white lines are caused by the incredibly strict UV placement on any given texture file. The devs placed UV borders _on the absolute, pixel-perfect edge_ for many parts within any given texture file. So, any deviance in texture size (particularly when reduced) will create a lot of "bleeding". Those white lines you see are the white, empty space in many textures files that is now "bleeding" into the space of whatever UV was placed next to its border.

This exact scenario is why we can't implement multi sample anti-aliasing; because MSAA samples pixel information _outside_ of UV boundaries, leading to a similar issue (which can/will happen _no matter_ the texture size so long as the UVs are right along the edges of textures as they were done for this game).

I hope that made sense!

_Random example of a texture in the game:_

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/3b3205fb-fdbf-4387-aac7-e4385a19a9ce)

**Comment by matheusvb3** [comment]
I'm not familiar with how SH2 works internally, but I believe it's not caused a thing from their animation files because when you encounter him outside the boss room he doesn't do the sliding movement, yet he uses the same animations. It's hard to even say if that was intentional or not because he doesn't always slide when attacking or flinching (though it seems to happen more often than not, around 70%-60% of the time). The only way to know for certain would be to check how he was programmed to function in boss form, the assembly intructions could help deduce what were the intentions of the developers, but I really have no idea to go about accomplishing this...

>I hope that made sense!

Perfectly understood! You know, I always thought placing the UV coordinates as close as possible to the edge the of the textures was the correct way to do it so as to not let texture information go to waste.
