### ISSUE TITLE
Not working on Steam Deck (Only Director's Cut is launching)

### ISSUE THREAD

**Issue by borduere** [elishacloud/Silent-Hill-2-Enhancements#892]
I have installed SH2E on my windows machine. There everything worked fine and opening the SH2PC.exe will open the enhanced version.

After copying the full folder (both game and enhancements) on my Steam Deck, opening the SH2PC.exe always opens the Director's Cut version. After looking at the D8 log, I saw that it is not logging anything because the enhanced version does not get opened. I tried with the most recent proton and 7.0.6

**Comment by Polymega** [comment]
Hi there,

Unfortunately, no one on our team owns a Steam Deck to help with this. We have a dedicated thread for people who own the Deck to help troubleshoot with each other [found here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/505#issuecomment-1892827846) (which I see you also already found!). Since you found the main thread, I'll close this ticket out.
