### ISSUE TITLE
Maria's hair not transparent in a cutscene

### ISSUE THREAD

**Issue by metatronicsauce** [elishacloud/Silent-Hill-2-Enhancements#91]
Sorry in advance if this isn't the right place for this.

In the Labyrinth when we find dead Maria, the area around her hair is white, instead of being transparent.
![untitled](https://user-images.githubusercontent.com/16717983/53285328-af7ec700-370b-11e9-9ec0-b52ae1621d3b.png)

Is there anything that can be done to fix this? does anyone know why this happens? It's always bothered me and nobody else seems to talk about it, but it's always happened to me on the PC version.

**Comment by Polymega** [comment]
Hi @metatronicsauce ,

At the moment, the PC version does not cast shadows upon dynamic (movable objects such as James, items, NPCs, and enemies). Because dynamic objects currently don't receive shadows, if they have any transparency in their texture and are in front of a static object (such as the bed in your image above) that is receiving a shadow, you'll get the issue you've mentioned. 

[This has also been posted here.](https://github.com/ThirteenAG/WidescreenFixesPack/issues/409#issue-293750781)

We've been experimenting with restoring the ability for dynamic objects to receive shadows again on the PC version. You can see results of this testing below. This fix is a fairly involved one, that literally affects all areas of the game, so it will very likely be some time until it's released. We want to make sure  everything is working correctly, first. 

![image](https://user-images.githubusercontent.com/31383389/49656583-4c688700-fa70-11e8-8a12-9b8ac69f3196.png)
![image](https://user-images.githubusercontent.com/31383389/49656591-4f637780-fa70-11e8-941a-3603e2fd50e7.png)
![image](https://user-images.githubusercontent.com/31383389/49656596-538f9500-fa70-11e8-9f23-3da3d5c2c925.png)
