### ISSUE TITLE
Suggestions and Observations

### ISSUE THREAD

**Issue by GlitchyReal** [elishacloud/Silent-Hill-2-Enhancements#916]
Went through SH2 again and wanted to share some observations with the latest public build. I'm sure most (if not all) of these issues are known to you guys or else they're on my end to which I hope you can help me address them.

- Right analog stick L2 View Mode isn't working. Is this an issue with Xidi? Similarly, the boat mini-game seems to be running on Easy mode even during Action Hard. Has this always been the case? (I rarely play on Action Hard.)
- The outdoor town at night (after Brookhaven) lags HARD. Seems to be worse around multiple monsters. I'm using the 60fps adjustment. Sometimes monsters taking damage seem to teleport between frames.
- Checking on Ernest after his first conversation in the BfaW sub-scenario, Maria's animations and sound of knocking and turning the handle are out of sync. ("Ernest are you there? No. I guess not.")
- In the board overlapping puzzle in BfaW, the tile graphics don't overlap perfectly. Are they meant to?
- Is it possible to utilize a higher quality model for the shadows?
- In the "Lost Memories" memo in BfaW, there is a typo: "The grave become an open field." Should be "became."
- Blood doesn't seem to disappear with distance and renders through/over the fog. Is this addressable? (Observed in BfaW.)
- At the top of the stairs outside Ernest's study, Maria says it's blocked by a "wall" when it's actually bars and stacked junk. (Nitpicking here.)
- Is it possible to make geometrical additions such as the refrigerator cord a toggle in the Configuration Tool?

Also, if you need more testing, I'm up for another round :)

**Comment by Polymega** [comment]
> Right analog stick L2 View Mode isn't working. Is this an issue with Xidi? Similarly, the boat mini-game seems to be running on Easy mode even during Action Hard. Has this always been the case? (I rarely play on Action Hard.)

It should be working. You can try changing the controller type for search cam movement in the Config Tool. All Action difficulties behave the same for the rowboat section, as keyboards couldn't do Hard rowboat.

> The outdoor town at night (after Brookhaven) lags HARD. Seems to be worse around multiple monsters. I'm using the 60fps adjustment. Sometimes monsters taking damage seem to teleport between frames.

Yes, we've determined its due to the shadows in this area. If you temporarily disable shadows, it fixes the lag. Team member @pmttavara is working on a tool to help us address the shadow lag for the upcoming project update.

> Checking on Ernest after his first conversation in the BfaW sub-scenario, Maria's animations and sound of knocking and turning the handle are out of sync. ("Ernest are you there? No. I guess not.")

I might look into this, but no promises. There's a good amount of examples of bad audio syncing throughout the game, so I'm not sure if it's worth fixing just for this one.

> In the board overlapping puzzle in BfaW, the tile graphics don't overlap perfectly. Are they meant to?

Team member @AeroWidescreen looked into this a few years back and found a fix would be rather complicated to pull off. Instead of each board having its own address for placement, they all share the same function and untangling the code to account for every possible position/rotation of the boards would be intense.

> Is it possible to utilize a higher quality model for the shadows?

Unfortunately not.

> In the "Lost Memories" memo in BfaW, there is a typo: "The grave become an open field." Should be "became."

I'll look into this, thank you.

> Blood doesn't seem to disappear with distance and renders through/over the fog. Is this addressable? (Observed in BfaW.)

Layered transparencies are very finicky with this game. I've learned this the hard way while working on level edits. I'm not sure if it's something we'll look into at this time.

> At the top of the stairs outside Ernest's study, Maria says it's blocked by a "wall" when it's actually bars and stacked junk. (Nitpicking here.)

I'll look into this, thanks.

> Is it possible to make geometrical additions such as the refrigerator cord a toggle in the Configuration Tool?

Geometry edits to environments aren't done code-side, but file-side (.map files). And all .map edits are included in one, download package. There are a lot of edits coming down the pipeline, and it isn't feasible to make countless package variations or toggleable options for even a fraction of them.

Also, that fridge cord is a badge of honor. A long time ago I received a death threat over it. As a result, I'll be adding in another fridge cord down the line.

Thanks

**Comment by GlitchyReal** [comment]
Thanks for the response! I hope these kinds of queries are more helpful than annoying.

re: Fridge cord, holy shit that’s not something to hand out death threats over. I’m curious where you’d add a second one, but in any case I respect it.

**Comment by GlitchyReal** [comment]
A few quick ones:

- Reinstate a delay to hold on black during ‘New Game’ tone for better effect/mood instead of proceeding immediately to FMV.
- The minimap. Was this ever found in the PC files? If so, can it be reapplied? If not, would a facsimile be made?
- (New content) Konami Code or NG+ for BfaW to play as Mary over Maria? Neat but too much/difficult?
