### ISSUE TITLE
DInput controllers don't work until you lose and re-focus game window

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#919]
XInput controllers seem to be fine. For DInput controllers, when you launch the game, the controller won't work. If you Alt + Tab (lose game focus) then go back into the game, the DInput controller proceeds to work like normal.

[This is not a problem on the current public release build](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/tag/v2.1.2070.0), so the change happened sometime after that. 

I tried testing the workflow binaries, going all the way back to the last non-expired one ([seen here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6884655470)), and the problem is still there. So this issue happened sometime before that build, but after the latest public build.

**Comment by elishacloud** [comment]
I think this issue was caused by this commit:  https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/4e9f68987e20c39391f5210098f670b602694295

Here is a fix without that change to see if the issue still exists: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/14552062/d3d8.zip)

**Comment by elishacloud** [comment]
I removed that code for now.  But it is not really a fix.  This brings back an old issue where if you Alt+Tab out of the game and the fight-click to get back into the game window then the mouse buttons don't respond.  I will need to find a better fix for that issue.
