### ISSUE TITLE
How to move the camera on PC?

### ISSUE THREAD

**Issue by gerooo909** [elishacloud/Silent-Hill-2-Enhancements#922]
I want to play with keyboard only, and you totally can do it but i cant move the camera like you would with the right stick on ps2, silent hill 3 pc port does allow you to move the camera but silent hill 2 is missing those inputs in the button config menu, does anyone know solution for this?

**Comment by Polymega** [comment]
By default, with our project, you'd use the mouse to move the camera after activating search view. If you want to also control the search camera with the keyboard only (no mouse), you can open `SH2EEconfig.exe`, navigate to **Input > Mouse** and disable "Enhance mouse input". 

By disabling this, you'll be able to use your movement keys on the keyboard to control the search camera. Just note that you must totally stop moving James in order to control the camera.
